load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")
load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//voxeloo/...": "",
    },
)

py_binary(
    name = "clang_format",
    srcs = ["clang_format.py"],
    main = "clang_format.py",
    deps = [requirement("clang-format")],
)
