// BIBLE_QUESTS_MAIN — generated by
// scripts/harthmere/convert-bible-catalog-to-typed.cjs from the retired
// HARTHMERE_QUEST_CATALOG_JSON, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest and step ids are derived from array index
// (bible_quest_ids.ts), so appending is free and reordering is a migration.
// bible_quest_ids.test.ts fails on any reorder.

import type { BibleQuestDef } from "@/shared/harthmere/bible/bible_quest_schema";

// ANNOTATION PLACEMENT — deliberate, and the two alternatives were tried.
//
// Annotating the DECLARATION gives every element the contextual type
// BibleQuestDef, so tsc checks each row against one known target.
//
//   * `Object.freeze([...])` with no element context infers a UNION of 13
//     anonymous shapes. Every optional `rewards.reputation` key then appears
//     as `number | undefined` and the module DOES NOT COMPILE. Verified.
//   * `Object.freeze([...] as const)` compiles, but builds a 13-element tuple
//     of deeply-nested literal types before checking assignability. Measured
//     between 13.3 s and 18.2 s against 13.0-15.4 s for this form — i.e.
//     within run-to-run noise on the machine used, so no speed claim is made
//     for it either way. This form is preferred for being the one that states
//     the intended type once, at the top, where a reader looks for it.
const QUESTS: BibleQuestDef[] = [
  {
    "id": "bellbound_q01_cracks_in_bridge",
    "code": "Q1",
    "title": "Cracks in the Bridge",
    "category": "main",
    "arc": "main",
    "giverName": "Reeve Caldus Merrow",
    "hidden": false,
    "district": "Old Bridge",
    "authoredWaypoint": [
      476,
      0,
      -212
    ],
    "estimatedMinutes": 35,
    "contentType": "Solo investigation",
    "repeatability": "once",
    "phase": "main",
    "premise": "The bridge cracks in a bell-shaped pattern after a tremor, and Caldus needs a clear-headed outsider to inspect it.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "giver",
      "giverId": "reeve_caldus_merrow"
    },
    "gate": {
      "levelBand": {
        "min": 5,
        "max": 10
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q01_cracks_in_bridge_obj_01",
        "label": "Speak with Caldus at Reeve Hall",
        "type": "talk",
        "targetId": "speak_with_caldus_at_reeve_hall",
        "targetName": "Speak with Caldus at Reeve Hall",
        "district": "Old Bridge",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q01_cracks_in_bridge_obj_02",
        "label": "Inspect the bridge crack pattern",
        "type": "inspect",
        "targetId": "inspect_the_bridge_crack_pattern",
        "targetName": "Inspect the bridge crack pattern",
        "district": "Old Bridge",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q01_cracks_in_bridge_obj_03",
        "label": "Ask Master Garrik Fen about frequency damage",
        "type": "choice",
        "targetId": "ask_master_garrik_fen_about_frequency_damage",
        "targetName": "Ask Master Garrik Fen about frequency damage",
        "district": "Old Bridge",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q01_cracks_in_bridge_obj_04",
        "label": "Report the bell-shaped pattern to Father Aldren",
        "type": "choice",
        "targetId": "report_the_bell_shaped_pattern_to_father_aldren",
        "targetName": "Report the bell-shaped pattern to Father Aldren",
        "district": "Old Bridge",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 250,
      "silver": 50,
      "items": [
        "bridgewalkers_eye_passive"
      ],
      "titles": [],
      "reputation": {
        "Merchant Compact": 100
      },
      "unlocks": [
        "significant_cracks_highlighted"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "50 silver, Bridgewalker’s Eye, Caldus/Merchant Compact reputation +100."
    },
    "dialogue": {
      "offer": "Reeve Caldus: \"I appreciate you coming. I would normally entrust this to the Watch, but Sergeant Holt's hands are full with the gate, and I want someone with a clear head. The bridge has cracks. Not the usual kind. Not the kind that come from frost or wagons. Walk it. Stand at the middle. Tell me if you feel anything strange. And please — say nothing to the market about it. I will not have a panic over a fashionable shape in stone.\"",
      "active": "The parchment Caldus gave you traces a bell-shaped fracture across the bridge stones. Walk the bridge to the centre, then take Caldus's question to Master Garrik Fen at the carpenter's yard. Garrik will not come to the bridge himself, so you carry the question to him.",
      "ready": "Garrik did not laugh. He read the shape and named it — a frequency pattern, the kind a great bell makes in stone when it is struck very close. He wants Father Aldren told. Caldus deserves the same answer, in his own house, before market opens.",
      "complete": "Caldus: \"Bridgewalker's Eye, then. A coin and a habit. Keep what you saw between the three of us until I know what to do with it. And — thank you. I would not have wanted anyone else to stand at that disc tonight.\"",
      "fail": "Caldus: \"Then leave it for now. Walk back to the Hall when your boots are dry, and we will start again. The bridge is not going anywhere, gods willing.\""
    }
  },
  {
    "id": "bellbound_q02_whispers_at_well",
    "code": "Q2",
    "title": "Whispers at the Well",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Old Well / Underways",
    "authoredWaypoint": [
      484,
      0,
      -151
    ],
    "estimatedMinutes": 30,
    "contentType": "Solo investigation",
    "repeatability": "once",
    "phase": "main",
    "premise": "Aldren sends the player to listen at the sealed Old Well after children report a voice asking for a bell.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q01_cracks_in_bridge",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 5,
        "max": 10
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q02_whispers_at_well_obj_01",
        "label": "Speak with Father Aldren",
        "type": "talk",
        "targetId": "speak_with_father_aldren",
        "targetName": "Speak with Father Aldren",
        "district": "Old Well / Underways",
        "authoredWaypoint": [
          484,
          0,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_whispers_at_well_obj_02",
        "label": "Listen at the Old Well without answering",
        "type": "inspect",
        "targetId": "listen_at_the_old_well_without_answering",
        "targetName": "Listen at the Old Well without answering",
        "district": "Old Well / Underways",
        "authoredWaypoint": [
          484,
          0,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_whispers_at_well_obj_03",
        "label": "Record the well voice and persistent Heard the Well flag",
        "type": "choice",
        "targetId": "record_the_well_voice_and_persistent_heard_the_well_flag",
        "targetName": "Record the well voice and persistent Heard the Well flag",
        "district": "Old Well / Underways",
        "authoredWaypoint": [
          484,
          0,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_whispers_at_well_obj_04",
        "label": "Return to Aldren",
        "type": "choice",
        "targetId": "return_to_aldren",
        "targetName": "Return to Aldren",
        "district": "Old Well / Underways",
        "authoredWaypoint": [
          484,
          0,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 300,
      "silver": 75,
      "items": [
        "heard_the_well_persistent_buff"
      ],
      "titles": [],
      "reputation": {
        "Chapel Circle": 100
      },
      "unlocks": [
        "heard_the_well_flag"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "75 silver, Heard the Well persistent buff, Chapel reputation +100."
    },
    "dialogue": {
      "offer": "Father Aldren, paler than usual: \"Yes. I have seen this pattern. I have prayed about this pattern. Saint Verena has not, so far, granted me clarity. Three days ago two children from the Mudden Ward went to the Old Well on a dare. The boy — Tam — came back trembling. He said the well had asked him to bring it a bell. I want you to go and listen. Bring no metal, no bell, no chime, no charm. And do not answer the well.\"",
      "active": "The Old Well sits behind the market boundary, sealed in iron. Aldren was very clear: listen, do not speak. Whatever you hear belongs to him before it belongs to the town.",
      "ready": "Aldren is waiting on the chapel office step. He has not moved since you left. Tell him what the well said — exactly, if you can — and he will tell you whether you are to keep walking down this road or to forget what you heard.",
      "complete": "Aldren reads your face. \"You will rest tonight. Come back in the morning, and I will have a decision, and you will tell me whether to give it to you. Saint Verena keep you. Saint Verena keep us both.\"",
      "fail": "Aldren: \"Then we wait. The well is not going anywhere. Find me when you have the heart for it. I will be in the office, pretending to read.\""
    }
  },
  {
    "id": "bellbound_q02_5_rat_girl_knows",
    "code": "Q2.5",
    "title": "The Rat-Girl Knows",
    "category": "main",
    "arc": "main",
    "giverName": "Nessa Crowe",
    "hidden": false,
    "district": "Mudden Ward",
    "authoredWaypoint": [
      416,
      0,
      -158
    ],
    "estimatedMinutes": 20,
    "contentType": "Optional social investigation",
    "repeatability": "once",
    "phase": "main",
    "premise": "If the player heard the Nessa branch at the well, Nessa admits she heard the same voice as a child.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q02_whispers_at_well",
      "giverId": "nessa_crowe"
    },
    "gate": {
      "levelBand": {
        "min": 5,
        "max": 10
      },
      "timeOfDay": [
        "dusk",
        "night"
      ],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q02_5_rat_girl_knows_obj_01",
        "label": "Trigger Nessa branch from the well voice",
        "type": "talk",
        "targetId": "trigger_nessa_branch_from_the_well_voice",
        "targetName": "Trigger Nessa branch from the well voice",
        "district": "Mudden Ward",
        "authoredWaypoint": [
          416,
          0,
          -158
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_5_rat_girl_knows_obj_02",
        "label": "Speak privately with Nessa",
        "type": "inspect",
        "targetId": "speak_privately_with_nessa",
        "targetName": "Speak privately with Nessa",
        "district": "Mudden Ward",
        "authoredWaypoint": [
          416,
          0,
          -158
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_5_rat_girl_knows_obj_03",
        "label": "Receive the truth of her childhood fall",
        "type": "choice",
        "targetId": "receive_the_truth_of_her_childhood_fall",
        "targetName": "Receive the truth of her childhood fall",
        "district": "Mudden Ward",
        "authoredWaypoint": [
          416,
          0,
          -158
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q02_5_rat_girl_knows_obj_04",
        "label": "Accept or refuse the Rat-Girl’s Token",
        "type": "choice",
        "targetId": "accept_or_refuse_the_rat_girl_s_token",
        "targetName": "Accept or refuse the Rat-Girl’s Token",
        "district": "Mudden Ward",
        "authoredWaypoint": [
          416,
          0,
          -158
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 200,
      "silver": 0,
      "items": [
        "rat_girls_token"
      ],
      "titles": [],
      "reputation": {
        "Mudden Kin": 50
      },
      "unlocks": [],
      "permanentBuffs": [
        "undead_damage_bonus_minor",
        "fear_resistance_minor"
      ],
      "variable": false,
      "previewText": "Rat-Girl’s Token, Mudden Kin +50, undead/fear utility bonus."
    },
    "dialogue": {
      "offer": "Nessa Crowe stiffens when you describe the woman's voice. Then her shoulders drop and she sits. \"Fine. Fine. I was nine. There was a drought, the well was lower, my brother dared me. I dropped in. While I was down there, in the dark, I heard a woman's voice. She told me her name. And she told me what was beneath the chapel.\"",
      "active": "Nessa is telling you a thing she has not told anyone in fifteen years. Stay with her. Do not look away. The Ward is loud outside her door and she is trying not to be.",
      "ready": "Nessa folds your hand around a small bronze charm. \"This was my brother's. He is dead now. Keep it on you. If she is speaking again, then we are all about to find out I wasn't lying.\"",
      "complete": "The Rat-Girl's Token is warm against your palm. Nessa wipes her face on her sleeve and stands up like she did not just tell you the centre of her life. \"Go. And if Aldren asks — tell him I sent my regards. He'll know what that means.\"",
      "fail": "Nessa shakes her head and turns to her work. \"Then it stays between me and the dark. Come back when you are ready to hear it properly, or don't.\""
    }
  },
  {
    "id": "bellbound_q03_dreams_of_drowning",
    "code": "Q3",
    "title": "Dreams of Drowning",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Temple Green",
    "authoredWaypoint": [
      480,
      0,
      -137
    ],
    "estimatedMinutes": 40,
    "contentType": "Social investigation",
    "repeatability": "once",
    "phase": "main",
    "premise": "Aldren asks the player to quietly ask seven townspeople if they have been sleeping well.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q02_whispers_at_well",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 5,
        "max": 10
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q03_dreams_of_drowning_obj_01",
        "label": "Ask Elowen about river dreams",
        "type": "talk",
        "targetId": "ask_elowen_about_river_dreams",
        "targetName": "Ask Elowen about river dreams",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q03_dreams_of_drowning_obj_02",
        "label": "Ask Mara about black water at the market",
        "type": "inspect",
        "targetId": "ask_mara_about_black_water_at_the_market",
        "targetName": "Ask Mara about black water at the market",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q03_dreams_of_drowning_obj_03",
        "label": "Ask Tovin about the river flowing wrong",
        "type": "choice",
        "targetId": "ask_tovin_about_the_river_flowing_wrong",
        "targetName": "Ask Tovin about the river flowing wrong",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q03_dreams_of_drowning_obj_04",
        "label": "Ask Brother Vance about Halene and the buried bell",
        "type": "choice",
        "targetId": "ask_brother_vance_about_halene_and_the_buried_bell",
        "targetName": "Ask Brother Vance about Halene and the buried bell",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 400,
      "silver": 100,
      "items": [
        "dreams_of_the_bell_codex"
      ],
      "titles": [],
      "reputation": {
        "Chapel Circle": 200
      },
      "unlocks": [
        "aldren_trust_unlocked"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "100 silver, Chapel +200, Aldren trust, Dreams of the Bell codex."
    },
    "dialogue": {
      "offer": "Aldren looks slightly more rested, and slightly more frightened. \"I have been hiding a truth from myself for nearly three years. I need you to talk to seven people and ask each one a simple thing: have you been sleeping well? If they say no, ask what they have been dreaming. Bring me back what you hear. Everyone in town knows my face. They do not yet know yours.\"",
      "active": "Seven names on Aldren's parchment: Elowen, Mara, Tovin, Old Jory, Ysabet, the child Lina Reed, and Brother Vance in the cottage on chapel grounds. Vance is the last name for a reason — go gentle, and go in any order.",
      "ready": "You have seven dreams in your head and they fit together like the staves of a barrel. Bell under water, woman in the river, horses that will not lie down, an old man who knows Halene rang the bell herself. Aldren is in the chapel. Tell him.",
      "complete": "Aldren sits on the chapel floor — not on a bench — and you hear him say: \"She rang the bell. Of course she did. She had to be sure. I have spent two years angry at the wrong people.\" He owes you an explanation. He owes you several. First, he owes you a key.",
      "fail": "Aldren: \"Then bring me the ones you spoke to, and we will fill the rest tomorrow. Better an honest few than a tidy seven. The dreams are not going anywhere either.\""
    }
  },
  {
    "id": "bellbound_q04_sisters_letters",
    "code": "Q4",
    "title": "The Sister’s Letters",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Temple Green",
    "authoredWaypoint": [
      480,
      0,
      -137
    ],
    "estimatedMinutes": 35,
    "contentType": "Lore reading puzzle",
    "repeatability": "once",
    "phase": "main",
    "premise": "Aldren opens Mother Halene’s letters and the player learns the bell was buried under the altar.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q03_dreams_of_drowning",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 5,
        "max": 10
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q04_sisters_letters_obj_01",
        "label": "Enter the chapel archive",
        "type": "talk",
        "targetId": "enter_the_chapel_archive",
        "targetName": "Enter the chapel archive",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q04_sisters_letters_obj_02",
        "label": "Read Halene’s letters in sequence",
        "type": "inspect",
        "targetId": "read_halene_s_letters_in_sequence",
        "targetName": "Read Halene’s letters in sequence",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q04_sisters_letters_obj_03",
        "label": "Identify the bell pit under the altar",
        "type": "choice",
        "targetId": "identify_the_bell_pit_under_the_altar",
        "targetName": "Identify the bell pit under the altar",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q04_sisters_letters_obj_04",
        "label": "Take the bell fragment to Osric Vale",
        "type": "choice",
        "targetId": "take_the_bell_fragment_to_osric_vale",
        "targetName": "Take the bell fragment to Osric Vale",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 450,
      "silver": 150,
      "items": [
        "halene_letters_codex",
        "bell_fragment_quest_item"
      ],
      "titles": [],
      "reputation": {
        "Chapel Circle": 200
      },
      "unlocks": [
        "black_anvil_referral"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "150 silver, Halene Letters codex, Bell-Fragment quest item, Chapel +200."
    },
    "dialogue": {
      "offer": "Aldren unlocks an iron-bound cabinet and lifts out a bundle of letters tied with blue ribbon. \"Mother Halene wrote to herself. I read the first three after she died and stopped. I should not have stopped. I am asking you to read the rest with me. Three of us in the room, in case one of us cannot bear it. Sit.\"",
      "active": "Nine letters in Halene's hand, ordered by date. Aldren reads first, then Brother Vance when he arrives. You read the third yourself. Take them in order — the rhythm of them matters as much as the words.",
      "ready": "The last letter is the day before Halene's death. \"I am going to ring it again. Properly this time. With both hands, with intention.\" Aldren has been crying quietly. Vance has not — Vance is smiling, the awful peaceful smile of confirmed suspicion.",
      "complete": "Aldren stands. \"There is a door in the chapel cellar. I have known it was there. I have prayed it would stay shut. I am going to ask you to help me open it. But first — take this to Master Vale at the Black Anvil.\" He hands you a bronze fragment. \"He has been waiting longer than he has admitted to be asked.\"",
      "fail": "Aldren closes the cabinet and ties the ribbon back as carefully as Halene would have. \"Then we read the rest another day. The letters have waited three years. They will wait another evening.\""
    }
  },
  {
    "id": "bellbound_q05_beneath_the_stones",
    "code": "Q5",
    "title": "Beneath the Stones",
    "category": "main",
    "arc": "main",
    "giverName": "Master Osric Vale",
    "hidden": false,
    "district": "Craftsman Row",
    "authoredWaypoint": [
      530,
      0,
      -232
    ],
    "estimatedMinutes": 45,
    "contentType": "Crafting + combat hybrid",
    "repeatability": "once",
    "phase": "main",
    "premise": "Osric forges a quest-bound Bellbinder handbell and the forge is attacked by Compact-paid men.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q04_sisters_letters",
      "giverId": "master_osric_vale"
    },
    "gate": {
      "levelBand": {
        "min": 7,
        "max": 12
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q05_beneath_the_stones_obj_01",
        "label": "Show Osric the bell fragment",
        "type": "talk",
        "targetId": "show_osric_the_bell_fragment",
        "targetName": "Show Osric the bell fragment",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q05_beneath_the_stones_obj_02",
        "label": "Smelt the meteoric trace and cast the handbell",
        "type": "combat",
        "targetId": "smelt_the_meteoric_trace_and_cast_the_handbell",
        "targetName": "Smelt the meteoric trace and cast the handbell",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresCombatValidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q05_beneath_the_stones_obj_03",
        "label": "Defend the forge from attackers",
        "type": "choice",
        "targetId": "defend_the_forge_from_attackers",
        "targetName": "Defend the forge from attackers",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q05_beneath_the_stones_obj_04",
        "label": "Claim the Bellbinder’s Voice",
        "type": "choice",
        "targetId": "claim_the_bellbinder_s_voice",
        "targetName": "Claim the Bellbinder’s Voice",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 600,
      "silver": 200,
      "items": [
        "bellbinders_voice_handbell",
        "forge_apprentice_brand_cosmetic"
      ],
      "titles": [],
      "reputation": {
        "Town Watch": 100,
        "Merchant Compact": -100
      },
      "unlocks": [
        "bell_bronze_ingot_recipe"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "200 silver, Bellbinder’s Voice, Bell-Bronze Ingot recipe, Forge-Apprentice Brand, Watch +100, Compact -100."
    },
    "dialogue": {
      "offer": "Master Osric Vale looks at the fragment, then at you, then at the fragment again. \"Close the door.\" He locks it himself. \"My grandfather made this bell. The buried one. I have known about it since I was eleven and never been asked. If Aldren means to open the chapel cellar, you will need a key. The key is a bell. We are going to forge one. Tonight. You and I. Get the bellows.\"",
      "active": "Four steps to a Bellbinder's handbell: smelt the sky-stone, match the alloy, strike the form on rhythm, tune the rim against Osric's fork. Osric coaches. Luth stays close. The door stays locked.",
      "ready": "The bell glows faintly on the anvil. As Osric lifts it toward you the door rattles — someone testing the lock. Three masked figures come through the side window, well-equipped and coordinated. Not bandits. Hold the bell. Hold the forge.",
      "complete": "One of them, dying, says only: \"The Compact… knows… the bell… should stay… buried…\" Osric: \"Merchant Compact. Someone in the Compact wants what is beneath this town to stay there. Go to the chapel. Take the bell. Tell Aldren what happened here. I have my own people to warn.\" The Bellbinder's Voice is yours.",
      "fail": "Osric pulls the bell back and sets it under the anvil cloth. \"Then we finish another night, before someone else finishes us. Go home. Lock your door. Come back when your hands stop shaking.\""
    }
  },
  {
    "id": "bellbound_q06_hidden_door",
    "code": "Q6",
    "title": "The Hidden Door",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Chapel Undercroft",
    "authoredWaypoint": [
      480,
      -6,
      -137
    ],
    "estimatedMinutes": 40,
    "contentType": "Combat + investigation",
    "repeatability": "once",
    "phase": "main",
    "premise": "The player opens the bricked chapel cellar door and the first Underways breach begins.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q05_beneath_the_stones",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 7,
        "max": 12
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q06_hidden_door_obj_01",
        "label": "Break open the brick wall",
        "type": "talk",
        "targetId": "break_open_the_brick_wall",
        "targetName": "Break open the brick wall",
        "district": "Chapel Undercroft",
        "authoredWaypoint": [
          480,
          -6,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q06_hidden_door_obj_02",
        "label": "Ring Bellbinder’s Voice at the bronze plate",
        "type": "combat",
        "targetId": "ring_bellbinder_s_voice_at_the_bronze_plate",
        "targetName": "Ring Bellbinder’s Voice at the bronze plate",
        "district": "Chapel Undercroft",
        "authoredWaypoint": [
          480,
          -6,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresCombatValidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q06_hidden_door_obj_03",
        "label": "Fight the crypt-breach enemies",
        "type": "choice",
        "targetId": "fight_the_crypt_breach_enemies",
        "targetName": "Fight the crypt-breach enemies",
        "district": "Chapel Undercroft",
        "authoredWaypoint": [
          480,
          -6,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q06_hidden_door_obj_04",
        "label": "Secure undercroft access",
        "type": "choice",
        "targetId": "secure_undercroft_access",
        "targetName": "Secure undercroft access",
        "district": "Chapel Undercroft",
        "authoredWaypoint": [
          480,
          -6,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 700,
      "silver": 250,
      "items": [
        "cellar_dust_cloak_cosmetic",
        "bellbinders_antechamber_lore"
      ],
      "titles": [],
      "reputation": {
        "Chapel Circle": 300
      },
      "unlocks": [
        "chapel_undercroft_access",
        "underways_first_ring_access"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "250 silver, Bellbinder’s Antechamber lore, Chapel +300, Cellar-Dust Cloak, permanent undercroft access."
    },
    "dialogue": {
      "offer": "Aldren locks the chapel doors before descending. Brother Vance insists on coming. \"Behind this brick is a door. I have never seen the door. I have only the floor plan. We are going to open the brick. Vance — sit there, please. Do not stand up unless I ask you to.\"",
      "active": "Swing the pick. The brick gives in pieces. Behind it: an iron door with no keyhole — only a bronze plate at chest height, a circle the size of the Bellbinder's Voice. Aldren watches you, not the door.",
      "ready": "The door grinds open. Cold air sighs out, older than the chapel, older than the town. Mineral, and underneath, dried blood. Eight columns ahead of you. Behind the smaller iron door at the far end, something has begun to move.",
      "complete": "Aldren stops at the top of the spiral stair. \"I cannot go further with you. I am needed in the town. I will keep the door open. I will pray.\" He looks smaller than he did at the start of the week. Map the first hall. Come back. Plan the next descent.",
      "fail": "Aldren pulls the iron door half-shut behind you. \"Then we rest. The undercroft is not going anywhere, gods grant. Come tomorrow, when the chapel bell — what we have left of it — has rung the dawn.\""
    }
  },
  {
    "id": "bellbound_q07_bellward_halls",
    "code": "Q7",
    "title": "The Bellward Halls",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Bellward Halls",
    "authoredWaypoint": [
      486,
      -14,
      -151
    ],
    "estimatedMinutes": 60,
    "contentType": "Solo dungeon",
    "repeatability": "once",
    "phase": "main",
    "premise": "The player enters the first Underways ring alone and clears the Bellward Halls.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q06_hidden_door",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 8,
        "max": 13
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q07_bellward_halls_obj_01",
        "label": "Navigate the circular Bellward Halls",
        "type": "talk",
        "targetId": "navigate_the_circular_bellward_halls",
        "targetName": "Navigate the circular Bellward Halls",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q07_bellward_halls_obj_02",
        "label": "Read six Bellward prayer chambers",
        "type": "inspect",
        "targetId": "read_six_bellward_prayer_chambers",
        "targetName": "Read six Bellward prayer chambers",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q07_bellward_halls_obj_03",
        "label": "Defeat or release the First Choir Crone",
        "type": "choice",
        "targetId": "defeat_or_release_the_first_choir_crone",
        "targetName": "Defeat or release the First Choir Crone",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q07_bellward_halls_obj_04",
        "label": "Attune to the first bellward ring",
        "type": "choice",
        "targetId": "attune_to_the_first_bellward_ring",
        "targetName": "Attune to the first bellward ring",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 900,
      "silver": 400,
      "items": [
        "first_choir_achievement",
        "crones_veil_or_gray_hood"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "six_bellward_lore_entries",
        "bell_attunement_plus_1"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "400 silver, six Bellward lore entries, First Choir achievement, cosmetic choice, Bell-attunement +1."
    },
    "dialogue": {
      "offer": "Aldren, at the top of the spiral: \"The first ring of the Underways is yours to walk alone. I will not send a party into a hall that has not been heard for nine hundred years. Map it. Read the chambers. Come back to me with what was carved there.\"",
      "active": "Six prayer chambers ring the central pillar — Aevith, Karag-Drath, Vyrenia, Murvath, Sylenne, Korruthax. One altar in each. Read every inscription. The voices you hear between the chambers are not threats; they are curious. Walk slowly.",
      "ready": "Three figures wait at the central pillar — a crone in chapel robes, an old man in stonemason leathers, a youth in apprentice gray. All dead three hundred years. They stop singing when you approach. The crone speaks first: \"Why are you in our hall?\"",
      "complete": "The crone, after the last note: \"Then go down. We could not finish the binding. We tried. We failed. We left a tomb half-built. If you can finish what we could not, ring the True Bell. If you cannot — please — kill us all the way through, before you go.\"",
      "fail": "The Bellward Halls go quiet around you and you can hear your own breath again. Surface. Find Aldren. The hall will be the same when you return — that is the whole problem with it."
    }
  },
  {
    "id": "bellbound_q08_voices_in_stone",
    "code": "Q8",
    "title": "Voices in the Stone",
    "category": "main",
    "arc": "main",
    "giverName": "Auto Trigger",
    "hidden": true,
    "district": "Old Harth Tomb",
    "authoredWaypoint": [
      490,
      -26,
      -155
    ],
    "estimatedMinutes": 30,
    "contentType": "Lore + choice",
    "repeatability": "once",
    "phase": "main",
    "premise": "Old Harth’s Memory Stone presents the three final paths: Rebind, Slay, or Wake.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q07_bellward_halls"
    },
    "gate": {
      "levelBand": {
        "min": 8,
        "max": 13
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q08_voices_in_stone_obj_01",
        "label": "Descend to Old Harth’s Antechamber",
        "type": "talk",
        "targetId": "descend_to_old_harth_s_antechamber",
        "targetName": "Descend to Old Harth’s Antechamber",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q08_voices_in_stone_obj_02",
        "label": "Touch the Memory Stone",
        "type": "inspect",
        "targetId": "touch_the_memory_stone",
        "targetName": "Touch the Memory Stone",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q08_voices_in_stone_obj_03",
        "label": "Hear Old Harth’s confession",
        "type": "choice",
        "targetId": "hear_old_harth_s_confession",
        "targetName": "Hear Old Harth’s confession",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q08_voices_in_stone_obj_04",
        "label": "Record the provisional path choice",
        "type": "choice",
        "targetId": "record_the_provisional_path_choice",
        "targetName": "Record the provisional path choice",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 1000,
      "silver": 500,
      "items": [
        "harths_memory_pin"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "bellbinder_confession_lore",
        "provisional_path_choice"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "500 silver, Bellbinder’s Confession lore, provisional path flag, Harth’s Memory pin."
    },
    "dialogue": {
      "offer": "The hidden stair only appears after the First Choir is dealt with. It spirals down into a small octagonal room. A stone sarcophagus sits in the centre — HARTH OF AEVITHSFORD, BELLBINDER, LAST. Above it, suspended on four iron chains, hangs the Memory Stone. Touch it.",
      "active": "Old Harth's voice fills the chamber. Do not interrupt it. He has been waiting nine hundred years to say this and the stone will only hold it a few more tellings. Listen to all of it before you decide anything.",
      "ready": "Harth: \"Choose well. Choose with your friends. Choose for the town. And if you choose to wake her — tell her, please, that Harth thought she was beautiful. I never told her. I should have.\" The Memory Stone goes dark. You have three threads now. Pick one when you are ready, and you may change it up until you reach the chamber.",
      "complete": "Rebind. Slay. Wake. The choice is yours to set, and yours to revise, until the Last Ringing. Talk to the town. They will have opinions. Aldren most of all. Caldus more than you would guess. Nessa more honestly than any of them.",
      "fail": "Leave the antechamber for now. The Memory Stone will hold Harth's voice a little longer. Come back when your head is clear. He will still be waiting."
    }
  },
  {
    "id": "bellbound_q09_veins_of_wyrm",
    "code": "Q9",
    "title": "The Veins of the Wyrm",
    "category": "main",
    "arc": "main",
    "giverName": "Auto Trigger",
    "hidden": true,
    "district": "Bellward Halls",
    "authoredWaypoint": [
      486,
      -14,
      -151
    ],
    "estimatedMinutes": 75,
    "contentType": "Group dungeon",
    "repeatability": "once",
    "phase": "main",
    "premise": "The second Underways ring exposes Thaedryn’s leaking essence and Vyrahel’s first appearance.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q08_voices_in_stone"
    },
    "gate": {
      "levelBand": {
        "min": 9,
        "max": 14
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q09_veins_of_wyrm_obj_01",
        "label": "Form or scale the group dungeon",
        "type": "talk",
        "targetId": "form_or_scale_the_group_dungeon",
        "targetName": "Form or scale the group dungeon",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q09_veins_of_wyrm_obj_02",
        "label": "Clear three vein halls",
        "type": "inspect",
        "targetId": "clear_three_vein_halls",
        "targetName": "Clear three vein halls",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q09_veins_of_wyrm_obj_03",
        "label": "Defeat Vyrahel non-lethally or lethally",
        "type": "choice",
        "targetId": "defeat_vyrahel_non_lethally_or_lethally",
        "targetName": "Defeat Vyrahel non-lethally or lethally",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q09_veins_of_wyrm_obj_04",
        "label": "Record group contribution and path consequence",
        "type": "choice",
        "targetId": "record_group_contribution_and_path_consequence",
        "targetName": "Record group contribution and path consequence",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 1300,
      "silver": 750,
      "items": [
        "vein_keepers_scale"
      ],
      "titles": [],
      "reputation": {
        "All Factions": 50
      },
      "unlocks": [
        "vyrahel_spared_town_npc_if_nonlethal"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "750 silver, Vein-Keeper’s Scale, faction-wide reputation bonus, Vyrahel town state if spared."
    },
    "dialogue": {
      "offer": "The veins of the dragon leak amber-gold along the carved channels. You need a party now. The second ring is not a hall a single torch can read. Gather three to five, and descend together — Aldren will not be coming.",
      "active": "Three halls in spiralling sequence: the Pulse Hall, the Echo Hall, the Spine Hall. Mind what the echo throws back at you. The walls of the third hall are her ribs. Keep the party together.",
      "ready": "At the end of the Spine Hall, a small wyrmling waits — eight feet, no more. She speaks before she fights. \"Mother sleeps. You smell like bell. You smell like the cold-bell-people. Are you here to ring her? Don't ring her. She's tired.\" Choose your words. They land harder than your blade will.",
      "complete": "Vyrahel goes down — or yields, if you held back. A passage opens to Harth's true tomb, deeper still. The party can rest at the threshold. The dragon's breathing is louder now than the river above.",
      "fail": "Withdraw to the chapel undercroft. The party can reform. The veins will still glow tomorrow; Vyrahel will still patrol them. She has not slept in centuries. She can wait."
    }
  },
  {
    "id": "bellbound_q10_bellbinders_tomb",
    "code": "Q10",
    "title": "The Bellbinder’s Tomb",
    "category": "main",
    "arc": "main",
    "giverName": "Auto Trigger",
    "hidden": true,
    "district": "Old Harth Tomb",
    "authoredWaypoint": [
      490,
      -26,
      -155
    ],
    "estimatedMinutes": 60,
    "contentType": "Group dungeon",
    "repeatability": "once",
    "phase": "main",
    "premise": "The player opens Old Harth’s true tomb, claims the regalia, and obtains the Founder’s Seal.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q09_veins_of_wyrm"
    },
    "gate": {
      "levelBand": {
        "min": 9,
        "max": 14
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q10_bellbinders_tomb_obj_01",
        "label": "Solve the four-bell group ritual",
        "type": "talk",
        "targetId": "solve_the_four_bell_group_ritual",
        "targetName": "Solve the four-bell group ritual",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q10_bellbinders_tomb_obj_02",
        "label": "Collect six Bellbinder regalia pieces",
        "type": "inspect",
        "targetId": "collect_six_bellbinder_regalia_pieces",
        "targetName": "Collect six Bellbinder regalia pieces",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q10_bellbinders_tomb_obj_03",
        "label": "Defeat tomb guardians",
        "type": "choice",
        "targetId": "defeat_tomb_guardians",
        "targetName": "Defeat tomb guardians",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q10_bellbinders_tomb_obj_04",
        "label": "Claim the Founder’s Seal",
        "type": "choice",
        "targetId": "claim_the_founder_s_seal",
        "targetName": "Claim the Founder’s Seal",
        "district": "Old Harth Tomb",
        "authoredWaypoint": [
          490,
          -26,
          -155
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 1600,
      "silver": 1000,
      "items": [
        "six_bellbinder_regalia",
        "bellbinder_robe_cosmetic",
        "founders_seal"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "tomb_keepers_boon",
        "last_apprentice_laid_to_rest_achievement"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "1000 silver, six Bellbinder Regalia pieces, Tomb-Keeper’s Boon, Bellbinder robe, Last Apprentice achievement."
    },
    "dialogue": {
      "offer": "Old Harth's true tomb is sealed with a bronze clapper-mechanism. The four positions around it want four bells, rung in sequence. Coordinate. If you ring it wrong, the door will hold its grudge.",
      "active": "A single hostile spirit waits inside — Kelvin Voss, Harth's first apprentice, dead nine hundred years guarding this room. He will speak first. Tell him your chosen path and he will fight you on its terms.",
      "ready": "Kelvin falls. Six pieces of Bellbinder regalia rest on six plinths — stole, hammer, tuning fork, handbell, chain, ring. Distribute them across your party as the paths require, or carry them all on one back. The Founder's Seal lies in Harth's hand.",
      "complete": "The undercroft is open behind you when you climb out. Aldren is waiting. Caldus is waiting. Word has spread, somehow, that someone is below. The market is quieter than it should be. The tower's wooden clapper rings the hour with the wrong sound.",
      "fail": "Kelvin holds his post; the regalia stays on its plinths. Heal up. Regroup. He has been waiting nine hundred years — he will wait another evening for the argument to resume."
    }
  },
  {
    "id": "bellbound_q11_last_ringing",
    "code": "Q11",
    "title": "The Last Ringing",
    "category": "main",
    "arc": "main",
    "giverName": "Father Aldren",
    "hidden": false,
    "district": "Bellward Halls",
    "authoredWaypoint": [
      486,
      -14,
      -151
    ],
    "estimatedMinutes": 45,
    "contentType": "Race-against-time group quest",
    "repeatability": "once",
    "phase": "main",
    "premise": "The player confirms the final path and keeps the Bellward Chamber from collapsing before the boss fight.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q10_bellbinders_tomb",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 10,
        "max": 15
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q11_last_ringing_obj_01",
        "label": "Confirm Rebind, Slay, or Wake path",
        "type": "talk",
        "targetId": "confirm_rebind_slay_or_wake_path",
        "targetName": "Confirm Rebind, Slay, or Wake path",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q11_last_ringing_obj_02",
        "label": "Coordinate bell ringing and chamber mechanics",
        "type": "inspect",
        "targetId": "coordinate_bell_ringing_and_chamber_mechanics",
        "targetName": "Coordinate bell ringing and chamber mechanics",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q11_last_ringing_obj_03",
        "label": "Survive the collapse sequence",
        "type": "choice",
        "targetId": "survive_the_collapse_sequence",
        "targetName": "Survive the collapse sequence",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q11_last_ringing_obj_04",
        "label": "Enter the Wyrm’s Bed with Bell-Tuned buff",
        "type": "choice",
        "targetId": "enter_the_wyrm_s_bed_with_bell_tuned_buff",
        "targetName": "Enter the Wyrm’s Bed with Bell-Tuned buff",
        "district": "Bellward Halls",
        "authoredWaypoint": [
          486,
          -14,
          -151
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 1800,
      "silver": 1500,
      "items": [
        "bellward_robe_cosmetic"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "final_path_confirmation",
        "bell_tuned_boss_buff"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "1500 silver, final-path flag, Bellward Robe, Bell-Tuned +10% all stats for boss."
    },
    "dialogue": {
      "offer": "Aldren and Caldus have argued the whole time you were below. \"Then go and silence her properly. Verena keep you. I will ring the chapel bell-stub at the proper hours until you return.\" If you have changed your mind, change it now. After this, the path is set.",
      "active": "The descent has three small encounters: Compact saboteurs, Bell-Mad townsfolk, and a voice in the corridor wall that knows your name. The Bell Chamber is at the end. Forty feet of dark bronze, suspended on chains thicker than a man. Decide which ringing it gets.",
      "ready": "Rebind: three full ring-cycles, defend the ritual. Slay: three rings rapid, the ending stroke, the floor cracking on the third. Wake: the handbell, once, and stop. In all three the floor opens under you when the work is done.",
      "complete": "The fall is controlled. The chamber below is the size of the town above you, vaulted stone, walls scored with bell-spirals. She lies curled at its centre, two hundred feet of bronze and river-stone gray, wings folded like vellum. Her eyes are still closed. Not for long.",
      "fail": "The party falls back to the Bell Chamber threshold. The bell is still up there, untouched. Nothing is decided that cannot still be unmade. Aldren will be in the chapel when you climb back. He will not ask."
    }
  },
  {
    "id": "bellbound_q12_thaedryn_bellbound",
    "code": "Q12",
    "title": "Thaedryn the Bellbound",
    "category": "main",
    "arc": "main",
    "giverName": "Thaedryn the Bellbound",
    "hidden": true,
    "district": "Wyrm Bed",
    "authoredWaypoint": [
      500,
      -60,
      -160
    ],
    "estimatedMinutes": 45,
    "contentType": "Climactic boss fight",
    "repeatability": "once",
    "phase": "main",
    "premise": "The final encounter resolves Thaedryn by Rebind, Slay, or Wake path and opens the wider continent.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "after",
      "questId": "bellbound_q11_last_ringing"
    },
    "gate": {
      "levelBand": {
        "min": 10,
        "max": 16
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "bellbound_q12_thaedryn_bellbound_obj_01",
        "label": "Enter the Wyrm’s Bed",
        "type": "talk",
        "targetId": "enter_the_wyrm_s_bed",
        "targetName": "Enter the Wyrm’s Bed",
        "district": "Wyrm Bed",
        "authoredWaypoint": [
          500,
          -60,
          -160
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q12_thaedryn_bellbound_obj_02",
        "label": "Survive Thaedryn’s multi-phase encounter",
        "type": "inspect",
        "targetId": "survive_thaedryn_s_multi_phase_encounter",
        "targetName": "Survive Thaedryn’s multi-phase encounter",
        "district": "Wyrm Bed",
        "authoredWaypoint": [
          500,
          -60,
          -160
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q12_thaedryn_bellbound_obj_03",
        "label": "Execute Rebind, Slay, or Wake resolution",
        "type": "choice",
        "targetId": "execute_rebind_slay_or_wake_resolution",
        "targetName": "Execute Rebind, Slay, or Wake resolution",
        "district": "Wyrm Bed",
        "authoredWaypoint": [
          500,
          -60,
          -160
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "bellbound_q12_thaedryn_bellbound_obj_04",
        "label": "Apply path-dependent town and expansion state",
        "type": "choice",
        "targetId": "apply_path_dependent_town_and_expansion_state",
        "targetName": "Apply path-dependent town and expansion state",
        "district": "Wyrm Bed",
        "authoredWaypoint": [
          500,
          -60,
          -160
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 5000,
      "silver": 5000,
      "items": [
        "path_legendary_reward_set"
      ],
      "titles": [
        "Hand That Steadies the Bell OR Wyrmslayer OR She-Who-Was-Greeted"
      ],
      "reputation": {
        "Path Dependent": 500
      },
      "unlocks": [
        "post_main_harthmere_state",
        "other_six_bellwards_available"
      ],
      "permanentBuffs": [
        "path_permanent_town_or_continent_buff"
      ],
      "variable": true,
      "previewText": "Path-dependent final rewards: 3000–7500 silver, legendary/mythic title, gear/mount/pet/perk, and persistent Harthmere state changes."
    },
    "dialogue": {
      "offer": "Thaedryn, low and unhurried, in a voice that is older than the town: \"I have dreamed of this hall for nine hundred years. I dreamed of you in it. Come forward, or stand where you are, and we will see what you brought me.\"",
      "active": "Four phases as the chains break in sequence. Her breath untunes your casting. Her tail is a slow sweep across half the chamber. She has been asleep nine centuries; her aim is not what it was. Do not be reassured by that.",
      "ready": "Three chains broken. The fourth is path-dependent. Rebind: ring the True Bell into her deeper sleep. Slay: burn the last bar of health. Wake: stop attacking, ring the greeting, meet her eyes. Whatever you do here, the town will see it from above.",
      "complete": "Above Harthmere, the sky has changed. Aldren is in the square. Caldus is there. Nessa and Osric and everyone you spoke to. Far away on six horizons, six lights — five calm, one burning. The Bellward Age was nine hundred years. The third age has begun.",
      "fail": "She watches you withdraw and does not pursue. \"Then return when you have decided what you came for. I have learned patience, in nine centuries. You have not yet earned mine.\""
    }
  }
];

export const BIBLE_QUESTS_MAIN: readonly BibleQuestDef[] = Object.freeze(QUESTS);
