// BIBLE_QUESTS_STARTER — generated by
// scripts/harthmere/convert-bible-catalog-to-typed.cjs from the retired
// HARTHMERE_QUEST_CATALOG_JSON, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest and step ids are derived from array index
// (bible_quest_ids.ts), so appending is free and reordering is a migration.
// bible_quest_ids.test.ts fails on any reorder.

import type { BibleQuestDef } from "@/shared/harthmere/bible/bible_quest_schema";

// ANNOTATION PLACEMENT — deliberate, and the two alternatives were tried.
//
// Annotating the DECLARATION gives every element the contextual type
// BibleQuestDef, so tsc checks each row against one known target.
//
//   * `Object.freeze([...])` with no element context infers a UNION of 9 
//     anonymous shapes. Every optional `rewards.reputation` key then appears
//     as `number | undefined` and the module DOES NOT COMPILE. Verified.
//   * `Object.freeze([...] as const)` compiles, but builds a 9 -element tuple
//     of deeply-nested literal types before checking assignability. Measured
//     between 13.3 s and 18.2 s against 13.0-15.4 s for this form — i.e.
//     within run-to-run noise on the machine used, so no speed claim is made
//     for it either way. This form is preferred for being the one that states
//     the intended type once, at the top, where a reader looks for it.
const QUESTS: BibleQuestDef[] = [
  {
    "id": "starter_welcome_to_harthmere",
    "code": "starter_welcome_to_harthmere",
    "title": "Welcome to Harthmere",
    "category": "starter",
    "arc": "starter",
    "giverName": "Sergeant Bram Holt",
    "hidden": false,
    "district": "North Gate",
    "authoredWaypoint": [
      486,
      0,
      -266
    ],
    "estimatedMinutes": 10,
    "contentType": "Onboarding",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Introduce the player to Harthmere, gate law, and the safe-to-danger town identity.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "sergeant_bram_holt"
    },
    "gate": {
      "levelBand": {
        "min": 1,
        "max": 3
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_welcome_to_harthmere_obj_01",
        "label": "Speak with the gate sergeant",
        "type": "talk",
        "targetId": "speak_with_the_gate_sergeant",
        "targetName": "Speak with the gate sergeant",
        "district": "North Gate",
        "authoredWaypoint": [
          486,
          0,
          -266
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_welcome_to_harthmere_obj_02",
        "label": "Visit the market board",
        "type": "inspect",
        "targetId": "visit_the_market_board",
        "targetName": "Visit the market board",
        "district": "North Gate",
        "authoredWaypoint": [
          486,
          0,
          -266
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_welcome_to_harthmere_obj_03",
        "label": "Find the inn marker",
        "type": "choice",
        "targetId": "find_the_inn_marker",
        "targetName": "Find the inn marker",
        "district": "North Gate",
        "authoredWaypoint": [
          486,
          0,
          -266
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_welcome_to_harthmere_obj_04",
        "label": "Return for first orientation reward",
        "type": "choice",
        "targetId": "return_for_first_orientation_reward",
        "targetName": "Return for first orientation reward",
        "district": "North Gate",
        "authoredWaypoint": [
          486,
          0,
          -266
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 80,
      "silver": 5,
      "items": [
        "harthmere_arrival_note"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "town_map_basic"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "5 silver, arrival note, basic town map unlock."
    },
    "dialogue": {
      "offer": "Sergeant Holt at the gate: \"Evening, traveller. I am Sergeant Bramwell Holt; mind your step and I will give you the truth as cleanly as I can. Walk the town. Speak to the market, the inn, the chapel. Come back to me with your boots dirty and your story straight.\"",
      "active": "Three stops: Mara at the market, Elowen at the Kettle, Aldren at the chapel. Each will give you the lay of one corner of Harthmere. Bram will be at the gate when you loop back.",
      "ready": "Bram waves you back to the gate. \"Walked it. Heard the right names. Now you are not a stranger to me. That is most of what a town is — a list of people who have stopped being strangers.\"",
      "complete": "Bram presses a small token into your palm. \"Welcome to Harthmere. Walk safe. Come back to the gate with your boots dirty and your story straight.\"",
      "fail": "Bram: \"Then come back when you have walked the rest. The gate does not close on a stranger. Just on a stranger I do not yet know the shape of.\""
    }
  },
  {
    "id": "starter_apples_for_dawnloaf",
    "code": "starter_apples_for_dawnloaf",
    "title": "Apples for Dawnloaf",
    "category": "starter",
    "arc": "starter",
    "giverName": "Dawn Loaf",
    "hidden": false,
    "district": "Market Square",
    "authoredWaypoint": [
      476,
      0,
      -212
    ],
    "estimatedMinutes": 15,
    "contentType": "Gathering",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Gather apples legally for the bakery and learn owned-resource rules.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "dawn_loaf"
    },
    "gate": {
      "levelBand": {
        "min": 1,
        "max": 4
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_apples_for_dawnloaf_obj_01",
        "label": "Get basket from Dawn Loaf",
        "type": "talk",
        "targetId": "get_basket_from_dawn_loaf",
        "targetName": "Get basket from Dawn Loaf",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_apples_for_dawnloaf_obj_02",
        "label": "Collect legal apples",
        "type": "inspect",
        "targetId": "collect_legal_apples",
        "targetName": "Collect legal apples",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_apples_for_dawnloaf_obj_03",
        "label": "Avoid stealing owned crops",
        "type": "choice",
        "targetId": "avoid_stealing_owned_crops",
        "targetName": "Avoid stealing owned crops",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_apples_for_dawnloaf_obj_04",
        "label": "Return apples for food buff",
        "type": "choice",
        "targetId": "return_apples_for_food_buff",
        "targetName": "Return apples for food buff",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 100,
      "silver": 8,
      "items": [
        "warm_apple_roll"
      ],
      "titles": [],
      "reputation": {
        "Market": 25
      },
      "unlocks": [],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "8 silver, warm apple roll, Market +25."
    },
    "dialogue": {
      "offer": "Brenna at the bakery, flour on her cheekbone: \"I need apples for the morning pies. Six. Not bruised. The orchard rows nearest the chapel are sweeter — go round there. Tell them I sent you and they will not chase you with the long pole.\"",
      "active": "Orchard rows behind the chapel. Six apples, not bruised. The pole is for crows, mostly, but it will reach a stranger too if the orchardman is in a bad humour.",
      "ready": "Brenna inspects each apple like a banker counts coin. Two pass without comment, three with a small nod, and the sixth she rotates in her hand twice before adding it to the bowl.",
      "complete": "Brenna pushes a hot loaf across the counter. \"For the road. Thank the orchardman next time without me. He likes a new face that says please.\"",
      "fail": "Brenna: \"Then bring me what you have, and we will see what we can make of it. A smaller pie. A different pie. The morning queue will eat what is in front of it.\""
    }
  },
  {
    "id": "starter_missing_lockbox",
    "code": "starter_missing_lockbox",
    "title": "Missing Lockbox",
    "category": "starter",
    "arc": "starter",
    "giverName": "Banker Merl Voss",
    "hidden": false,
    "district": "Player Services",
    "authoredWaypoint": [
      556,
      0,
      -224
    ],
    "estimatedMinutes": 20,
    "contentType": "Investigation",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Recover a misplaced lockbox and learn storage/bank service rules.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "banker_merl_voss"
    },
    "gate": {
      "levelBand": {
        "min": 1,
        "max": 4
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_missing_lockbox_obj_01",
        "label": "Speak with banker",
        "type": "talk",
        "targetId": "speak_with_banker",
        "targetName": "Speak with banker",
        "district": "Player Services",
        "authoredWaypoint": [
          556,
          0,
          -224
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_missing_lockbox_obj_02",
        "label": "Trace the misplaced lockbox",
        "type": "inspect",
        "targetId": "trace_the_misplaced_lockbox",
        "targetName": "Trace the misplaced lockbox",
        "district": "Player Services",
        "authoredWaypoint": [
          556,
          0,
          -224
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_missing_lockbox_obj_03",
        "label": "Recover it from wrong counter",
        "type": "choice",
        "targetId": "recover_it_from_wrong_counter",
        "targetName": "Recover it from wrong counter",
        "district": "Player Services",
        "authoredWaypoint": [
          556,
          0,
          -224
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_missing_lockbox_obj_04",
        "label": "Return unopened",
        "type": "choice",
        "targetId": "return_unopened",
        "targetName": "Return unopened",
        "district": "Player Services",
        "authoredWaypoint": [
          556,
          0,
          -224
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 120,
      "silver": 10,
      "items": [
        "storage_voucher_small"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "bank_storage_intro"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "10 silver, small storage voucher, bank intro."
    },
    "dialogue": {
      "offer": "Banker Merl Voss, paler than the ledger: \"A small lockbox is missing from my counting room. Likely a courier mistake. Walk the route from the docks to the bank. If it turns up, return it. If it does not — tell me whose hands you saw on the road.\"",
      "active": "The route is a half-hour at a walk. Three couriers passed it this morning, and one of them is back at the bench. The lockbox is the size of a fist.",
      "ready": "Lockbox in hand, mistake more likely than theft. Walk it back to Merl. He will count twice, then once more, then thank you only on the second.",
      "complete": "Merl: \"Then the books are square again. Take this — modest, but earned. The bank remembers an honest finder. Come back when your purse needs counting space.\"",
      "fail": "Merl: \"Then I will issue a courier reprimand and a finder's note at the gate. Walk the route tomorrow if you are out that way. The lockbox will surface — they always do.\""
    }
  },
  {
    "id": "starter_cold_iron_hot_temper",
    "code": "starter_cold_iron_hot_temper",
    "title": "Cold Iron, Hot Temper",
    "category": "starter",
    "arc": "starter",
    "giverName": "Master Osric Vale",
    "hidden": false,
    "district": "Craftsman Row",
    "authoredWaypoint": [
      530,
      0,
      -232
    ],
    "estimatedMinutes": 20,
    "contentType": "Crafting",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Repair a simple iron fitting and learn durability/repair loops.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "master_osric_vale"
    },
    "gate": {
      "levelBand": {
        "min": 2,
        "max": 5
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_cold_iron_hot_temper_obj_01",
        "label": "Pick up damaged fitting",
        "type": "talk",
        "targetId": "pick_up_damaged_fitting",
        "targetName": "Pick up damaged fitting",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_cold_iron_hot_temper_obj_02",
        "label": "Use repair station",
        "type": "inspect",
        "targetId": "use_repair_station",
        "targetName": "Use repair station",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_cold_iron_hot_temper_obj_03",
        "label": "Meet quality check",
        "type": "choice",
        "targetId": "meet_quality_check",
        "targetName": "Meet quality check",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_cold_iron_hot_temper_obj_04",
        "label": "Return to Osric",
        "type": "choice",
        "targetId": "return_to_osric",
        "targetName": "Return to Osric",
        "district": "Craftsman Row",
        "authoredWaypoint": [
          530,
          0,
          -232
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 140,
      "silver": 12,
      "items": [
        "simple_repair_kit"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "repair_station_intro"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "12 silver, repair kit, repair station intro."
    },
    "dialogue": {
      "offer": "Master Vale, terse: \"Tessen Hark left a Watch blade in the slack tub overnight. The edge is fine, the temper is not. Take it to the Watch yard, tell Walt the edge holds until it does not, and bring me back the truth of what Walt said in answer.\"",
      "active": "Walt is in the yard. The blade in your hand. He will laugh and then he will not. Listen for the part after the laugh.",
      "ready": "Walt's answer is shorter than expected and rougher than Osric will like. Carry it back to the forge anyway. Smiths do not need lies.",
      "complete": "Osric grunts. \"Then we re-temper from cold and Tessen sweeps the floor for a week. Free repair on the next blade you bring me. Tessen will know whose blade I worked on this week, and that is the lesson.\"",
      "fail": "Osric: \"Then leave it on the bench. I will speak to Walt myself in the morning. Go home. The blade is not going anywhere worse than the slack tub.\""
    }
  },
  {
    "id": "starter_fever_tea",
    "code": "starter_fever_tea",
    "title": "Fever Tea",
    "category": "starter",
    "arc": "starter",
    "giverName": "Ysabet Fenlow",
    "hidden": false,
    "district": "Apothecary",
    "authoredWaypoint": [
      476,
      0,
      -212
    ],
    "estimatedMinutes": 20,
    "contentType": "Gathering + crafting",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Gather simple herbs and brew fever tea for a dock worker.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "ysabet_fenlow"
    },
    "gate": {
      "levelBand": {
        "min": 2,
        "max": 5
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_fever_tea_obj_01",
        "label": "Gather feverfew and mint",
        "type": "talk",
        "targetId": "gather_feverfew_and_mint",
        "targetName": "Gather feverfew and mint",
        "district": "Apothecary",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_fever_tea_obj_02",
        "label": "Brew tea at apothecary",
        "type": "inspect",
        "targetId": "brew_tea_at_apothecary",
        "targetName": "Brew tea at apothecary",
        "district": "Apothecary",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_fever_tea_obj_03",
        "label": "Deliver to patient",
        "type": "choice",
        "targetId": "deliver_to_patient",
        "targetName": "Deliver to patient",
        "district": "Apothecary",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_fever_tea_obj_04",
        "label": "Report to Ysabet",
        "type": "choice",
        "targetId": "report_to_ysabet",
        "targetName": "Report to Ysabet",
        "district": "Apothecary",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 130,
      "silver": 10,
      "items": [
        "basic_salves"
      ],
      "titles": [],
      "reputation": {
        "Apothecary Circle": 25
      },
      "unlocks": [],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "10 silver, basic salves, Apothecary +25."
    },
    "dialogue": {
      "offer": "Ysabet: \"Marsh fever tea, three bowls, to be delivered before noon. The list is on the counter. Don't shake the bowls. Don't sip them. Some patients are particular about whose breath has been near the rim.\"",
      "active": "Three doors before noon. One in Mudden, one in market, one on Noble Rise. The Noble Rise door will keep you waiting longest, and they will tip best.",
      "ready": "All three delivered. None spilled. Ysabet does not say thank you — she nods. That is the same thing.",
      "complete": "Ysabet hands you a small pouch. \"A week's free counter. Spend it on something other than fever tea. Most of what I sell is not for the dying.\"",
      "fail": "Ysabet: \"Then I will walk them myself after sundown. Come back when your hands are steadier. Tea is not the hard part — the hard part is the door you have to knock on.\""
    }
  },
  {
    "id": "starter_rumor_has_it",
    "code": "starter_rumor_has_it",
    "title": "Rumor Has It",
    "category": "starter",
    "arc": "starter",
    "giverName": "Elowen Pike",
    "hidden": false,
    "district": "Copper Kettle",
    "authoredWaypoint": [
      552,
      0,
      -194
    ],
    "estimatedMinutes": 15,
    "contentType": "Social",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Learn the rumor board and inn social loop without placeholder dialogue.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "elowen_pike"
    },
    "gate": {
      "levelBand": {
        "min": 1,
        "max": 5
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_rumor_has_it_obj_01",
        "label": "Ask three patrons for grounded rumors",
        "type": "talk",
        "targetId": "ask_three_patrons_for_grounded_rumors",
        "targetName": "Ask three patrons for grounded rumors",
        "district": "Copper Kettle",
        "authoredWaypoint": [
          552,
          0,
          -194
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_rumor_has_it_obj_02",
        "label": "Post one rumor card",
        "type": "inspect",
        "targetId": "post_one_rumor_card",
        "targetName": "Post one rumor card",
        "district": "Copper Kettle",
        "authoredWaypoint": [
          552,
          0,
          -194
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_rumor_has_it_obj_03",
        "label": "Return to Elowen",
        "type": "choice",
        "targetId": "return_to_elowen",
        "targetName": "Return to Elowen",
        "district": "Copper Kettle",
        "authoredWaypoint": [
          552,
          0,
          -194
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_rumor_has_it_obj_04",
        "label": "Unlock rumor board",
        "type": "choice",
        "targetId": "unlock_rumor_board",
        "targetName": "Unlock rumor board",
        "district": "Copper Kettle",
        "authoredWaypoint": [
          552,
          0,
          -194
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 100,
      "silver": 7,
      "items": [],
      "titles": [],
      "reputation": {
        "Copper Kettle": 25
      },
      "unlocks": [
        "rumor_board_intro"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "7 silver, rumor board intro, Copper Kettle +25."
    },
    "dialogue": {
      "offer": "Elowen, leaning across the bar: \"Rumour going round that one of my barrels has a letter inside it, addressed to me, from someone who has been dead five years. I do not want to know if it is true. I do want you to find which barrel before a regular finds it first.\"",
      "active": "Six barrels in the cellar. Tap each. The wrong one will not sound right. The right one will. The letter — if there is one — is your problem first, Elowen's second.",
      "ready": "One barrel sounds wrong. Open it, or close it. Elowen has not asked you to read what is inside. Whether she would have wanted you to is a question only you will know the answer to.",
      "complete": "Elowen pours you a small one, on the house. \"Then we put the barrel back together and the cellar goes quiet again. Bards' rumours are mostly bards' rumours. Mostly. Walk safe.\"",
      "fail": "Elowen: \"Then leave them be for now. A barrel that has waited five years can wait another week. Come back when you have time to listen properly.\""
    }
  },
  {
    "id": "starter_loose_chickens",
    "code": "starter_loose_chickens",
    "title": "Loose Chickens",
    "category": "starter",
    "arc": "starter",
    "giverName": "Dawn Loaf",
    "hidden": false,
    "district": "Market Square",
    "authoredWaypoint": [
      476,
      0,
      -212
    ],
    "estimatedMinutes": 12,
    "contentType": "Light capture",
    "repeatability": "once",
    "phase": "starter",
    "premise": "Catch escaped chickens without harming animals.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": false,
    "start": {
      "kind": "giver",
      "giverId": "dawn_loaf"
    },
    "gate": {
      "levelBand": {
        "min": 1,
        "max": 3
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_loose_chickens_obj_01",
        "label": "Find loose chickens",
        "type": "talk",
        "targetId": "find_loose_chickens",
        "targetName": "Find loose chickens",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_loose_chickens_obj_02",
        "label": "Herd them away from road",
        "type": "inspect",
        "targetId": "herd_them_away_from_road",
        "targetName": "Herd them away from road",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_loose_chickens_obj_03",
        "label": "Return them to pen",
        "type": "choice",
        "targetId": "return_them_to_pen",
        "targetName": "Return them to pen",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_loose_chickens_obj_04",
        "label": "Receive small food reward",
        "type": "choice",
        "targetId": "receive_small_food_reward",
        "targetName": "Receive small food reward",
        "district": "Market Square",
        "authoredWaypoint": [
          476,
          0,
          -212
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 90,
      "silver": 6,
      "items": [
        "fresh_egg_bundle"
      ],
      "titles": [],
      "reputation": {
        "Market": 15
      },
      "unlocks": [],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "6 silver, egg bundle, Market +15."
    },
    "dialogue": {
      "offer": "Brenna, hands on hips: \"Three chickens out the back gate. Again. Bring them back before the bakery cat decides it is a hunter. I will give you a still-warm bun for each one, and a third for the cat if you can be a charitable.\"",
      "active": "Three chickens. They are slower than they look and faster than you. The cat is watching from the windowsill, pretending not to be interested.",
      "ready": "All three back in the coop, the gate latched twice, the cat re-stationed at the front of the bakery where it belongs.",
      "complete": "Brenna passes the buns across the counter. \"Three for the chickens. One for the cat. One for you, because you did not chase them with the broom — they remember a broom for a fortnight.\"",
      "fail": "Brenna: \"Then the cat will deal with it and we will both be sorry. Come back at the next dawn. The chickens are loose more often than the bakery doors are closed.\""
    }
  },
  {
    "id": "starter_whispering_crate",
    "code": "starter_whispering_crate",
    "title": "Whispering Crate",
    "category": "starter",
    "arc": "starter",
    "giverName": "Tovin Reed",
    "hidden": false,
    "district": "River Docks",
    "authoredWaypoint": [
      596,
      0,
      -172
    ],
    "estimatedMinutes": 25,
    "contentType": "Investigation",
    "repeatability": "once",
    "phase": "starter",
    "premise": "A simplified dock crate mystery introduces Bell-Tie ambience before SQ-026.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "giver",
      "giverId": "tovin_reed"
    },
    "gate": {
      "levelBand": {
        "min": 3,
        "max": 6
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_whispering_crate_obj_01",
        "label": "Inspect whispering crate",
        "type": "talk",
        "targetId": "inspect_whispering_crate",
        "targetName": "Inspect whispering crate",
        "district": "River Docks",
        "authoredWaypoint": [
          596,
          0,
          -172
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_whispering_crate_obj_02",
        "label": "Check manifest",
        "type": "inspect",
        "targetId": "check_manifest",
        "targetName": "Check manifest",
        "district": "River Docks",
        "authoredWaypoint": [
          596,
          0,
          -172
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_whispering_crate_obj_03",
        "label": "Decide chapel or dock outcome",
        "type": "choice",
        "targetId": "decide_chapel_or_dock_outcome",
        "targetName": "Decide chapel or dock outcome",
        "district": "River Docks",
        "authoredWaypoint": [
          596,
          0,
          -172
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_whispering_crate_obj_04",
        "label": "Record crate clue",
        "type": "choice",
        "targetId": "record_crate_clue",
        "targetName": "Record crate clue",
        "district": "River Docks",
        "authoredWaypoint": [
          596,
          0,
          -172
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 150,
      "silver": 15,
      "items": [
        "crate_rune_splinter"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "sq026_hint"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "15 silver, crate rune splinter, SQ-026 hint."
    },
    "dialogue": {
      "offer": "Tovin Reed, quieter than usual: \"There is a small crate in the warehouse making noises a small crate should not make. Look at it. Tell me what is inside. I want my warehouse back, and I would rather not pry the lid myself.\"",
      "active": "Smaller than the SQ-026 crate. Less ominous. Probably nothing. Crates whispering at night is usually a rat in the packing straw — usually.",
      "ready": "Inside the crate: a small carved bell, a Mudden Ward child's toy lost on the dock weeks ago. The whispering was the wind through the wooden handle. Return it to Nessa or to Tam.",
      "complete": "Tovin: \"Then the warehouse sleeps again. Take this — modest pay for a modest noise. Come back when there is a louder one. There always is.\"",
      "fail": "Tovin: \"Then I will move the crate to the back row and pretend not to hear it. Come back when you have an evening. The warehouse is patient.\""
    }
  },
  {
    "id": "starter_the_missing_bell",
    "code": "starter_the_missing_bell",
    "title": "The Missing Bell",
    "category": "starter",
    "arc": "starter",
    "giverName": "Father Aldren Mell",
    "hidden": false,
    "district": "Temple Green",
    "authoredWaypoint": [
      480,
      0,
      -137
    ],
    "estimatedMinutes": 25,
    "contentType": "Lore starter",
    "repeatability": "once",
    "phase": "starter",
    "premise": "A local-dev mystery starter introduces the public story that the chapel bell was stolen.",
    "bibleRef": "Bellbound Dragon / Harthmere MMO / Wilds bible",
    "bellTie": true,
    "start": {
      "kind": "giver",
      "giverId": "father_aldren_mell"
    },
    "gate": {
      "levelBand": {
        "min": 4,
        "max": 7
      },
      "timeOfDay": [],
      "activeHours": [],
      "weather": [],
      "requiredFlags": []
    },
    "steps": [
      {
        "id": "starter_the_missing_bell_obj_01",
        "label": "Ask Aldren about the missing bell",
        "type": "talk",
        "targetId": "ask_aldren_about_the_missing_bell",
        "targetName": "Ask Aldren about the missing bell",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 5,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_the_missing_bell_obj_02",
        "label": "Check chapel notice",
        "type": "inspect",
        "targetId": "check_chapel_notice",
        "targetName": "Check chapel notice",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": true,
          "maxDistance": 4,
          "idempotent": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_the_missing_bell_obj_03",
        "label": "Inspect old bell tower marks",
        "type": "choice",
        "targetId": "inspect_old_bell_tower_marks",
        "targetName": "Inspect old bell tower marks",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      },
      {
        "id": "starter_the_missing_bell_obj_04",
        "label": "Receive warning not to dig further yet",
        "type": "choice",
        "targetId": "receive_warning_not_to_dig_further_yet",
        "targetName": "Receive warning not to dig further yet",
        "district": "Temple Green",
        "authoredWaypoint": [
          480,
          0,
          -137
        ],
        "count": 1,
        "validation": {
          "serverAuthority": true,
          "requiresLineOfSight": false,
          "maxDistance": 8,
          "idempotent": true,
          "requiresChoiceRevalidation": true
        },
        "failureCases": [
          "player_too_far",
          "wrong_phase",
          "duplicate_submission"
        ]
      }
    ],
    "choices": [
      {
        "id": "standard_resolution",
        "label": "Resolve according to quest evidence",
        "consequence": "World state, reputation, and reward grants are applied by server authority."
      }
    ],
    "rewards": {
      "xp": 180,
      "silver": 20,
      "items": [
        "chapel_bell_notice_copy"
      ],
      "titles": [],
      "reputation": {},
      "unlocks": [
        "bell_mystery_starter_flag"
      ],
      "permanentBuffs": [],
      "variable": false,
      "previewText": "20 silver, chapel bell notice copy, Bell mystery starter flag."
    },
    "dialogue": {
      "offer": "A boy from the Mudden Ward — Tam — tugs your sleeve at the market: \"Father Aldren says the chapel bell is stolen. Father Aldren is a kind man but he is lying. I know because I can still hear it. Will you find it? Don't tell anyone I asked. They think I'm too little.\"",
      "active": "Tam is too little to be heard. He is not too little to be right. Ask around the Ward and the chapel — gently. Whoever first claimed the bell was stolen is the door you want, not the bell.",
      "ready": "The Ward and the chapel say two different versions of the same story, and the seam between them is exactly where the bell sits. Tam will not need details — only the promise that you have looked, and that you believed him.",
      "complete": "Tam, very seriously, places his carved wooden bell in your palm. \"For the road. It doesn't ring. It only listens. That's how the real one used to be too, before they changed it.\" He will not say which adult told him that. He may not remember.",
      "fail": "Tam shrugs and pockets his hands. \"Come back when you've asked the right grown-up. I'll be at the fountain. I'm patient for a small.\""
    }
  }
];

export const BIBLE_QUESTS_STARTER: readonly BibleQuestDef[] = Object.freeze(QUESTS);
