// HARTHMERE_RESOLVER_CONTRACT_V1
//
// Patch 04 contract test. Locks the local/prod agnosticism rules in place:
//
//   1. Glitch-specific endpoints (install validation, save sync, achievements,
//      leaderboards) stay hard-wired and are NOT routed through the resolver.
//      Their paths live under /api/glitch/ and inside harthmere_glitch_bridge.
//
//   2. Mission / quest / snapshot-progress state IS routed through the
//      snapshot_backend_resolver_v80 so production deployments can swap the
//      backing service (Laravel, custom microservice, anything compatible)
//      by setting GLITCH_SNAPSHOT_BACKEND_MODE / _BACKEND_URL at deploy time.
//
//   3. Grove terrain Y is selectable via GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE
//      so future snapshot rebakes do not require a code change.

import {
  resolveSnapshotBackendEnvironmentV80,
  resolveSnapshotGroveGroundYV80,
  resolveSnapshotGroveTerrainModeV80,
  resolveSnapshotHealthEndpointV80,
  resolveSnapshotProgressEndpointV80,
  SNAPSHOT_BACKEND_RESOLVER_VERSION_V80,
  snapshotBackendAllowsRemoteProgressV80,
  snapshotBackendUsesLocalProgressV80,
} from "@/shared/harthmere/snapshot_backend_resolver_v80";

import {
  SNAPSHOT_GROVE_LIVE_MARKER_Y_V83,
  SNAPSHOT_GROVE_LIVE_NPC_FEET_Y_V83,
  SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y_V83,
} from "@/shared/harthmere/snapshot_grove_content_v75";


export const HARTHMERE_RESOLVER_CONTRACT_VERSION_V1 =
  "harthmere-resolver-contract-v1" as const;

// ---------------------------------------------------------------------------
// Glitch endpoints that MUST stay hard-wired (not resolver-routed).
// Patch 04 audit: these paths must appear in their respective modules and
// not be dynamically generated by the snapshot resolver.
// ---------------------------------------------------------------------------
export const GLITCH_HARDWIRED_ENDPOINTS_V1: ReadonlyArray<{
  module: string;
  path: string;
  purpose: string;
}> = [
  {
    module: "src/client/game/glitch/harthmere_glitch_bridge.ts",
    path: "/api/glitch/harthmere",
    purpose: "install-id validation and save / achievement / leaderboard sync",
  },
];

// ---------------------------------------------------------------------------
// Snapshot endpoints that MUST be resolver-routed (not hard-coded).
// These call sites are checked at the source-text level in the CJS check;
// here we assert the resolver returns sane shapes for each operating mode.
// ---------------------------------------------------------------------------
export interface HarthmereResolverContractReportV1 {
  ok: boolean;
  version: typeof HARTHMERE_RESOLVER_CONTRACT_VERSION_V1;
  failures: string[];
}

function check(
  failures: string[],
  cond: boolean,
  message: string,
) {
  if (!cond) failures.push(message);
}

export function validateHarthmereResolverContractV1(): HarthmereResolverContractReportV1 {
  const failures: string[] = [];

  // Mode dispatch ---------------------------------------------------------
  const localEnv = resolveSnapshotBackendEnvironmentV80({});
  check(failures, localEnv.mode === "local",
    `default env (no NODE_ENV) should yield local mode (got ${localEnv.mode})`);
  check(failures, snapshotBackendUsesLocalProgressV80(localEnv),
    "default env should use local progress");
  check(failures, !snapshotBackendAllowsRemoteProgressV80(localEnv),
    "default env should not allow remote progress");
  check(failures, localEnv.progressEndpoint === "/api/glitch/snapshot_progress",
    `default progress endpoint should be local Next API path (got ${localEnv.progressEndpoint})`);

  const prodDefault = resolveSnapshotBackendEnvironmentV80({ NODE_ENV: "production" });
  check(failures, prodDefault.mode === "disabled",
    `production with no backend URL should default to disabled (got ${prodDefault.mode})`);
  check(failures, !snapshotBackendAllowsRemoteProgressV80(prodDefault),
    "production with no backend URL must not allow remote progress");

  const prodWithUrl = resolveSnapshotBackendEnvironmentV80({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://api.example.com",
  });
  check(failures, prodWithUrl.mode === "remote",
    `production + backend URL should resolve to remote (got ${prodWithUrl.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgressV80(prodWithUrl),
    "production + backend URL must allow remote progress");
  check(failures,
    prodWithUrl.progressEndpoint === "https://api.example.com/api/glitch/snapshot_progress",
    `production progress endpoint should join backend URL + default path (got ${prodWithUrl.progressEndpoint})`);

  // Explicit laravel mode --------------------------------------------------
  const laravel = resolveSnapshotBackendEnvironmentV80({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_BACKEND_MODE: "laravel",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://laravel.example.com/",
    GLITCH_SNAPSHOT_PROGRESS_ENDPOINT: "/api/quest_state",
  });
  check(failures, laravel.mode === "laravel", `laravel mode honoured (got ${laravel.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgressV80(laravel),
    "laravel mode must allow remote progress");
  check(failures,
    laravel.progressEndpoint === "https://laravel.example.com/api/quest_state",
    `laravel progress endpoint honours custom path (got ${laravel.progressEndpoint})`);

  // Generic custom mode (Laravel-or-anything-else) ------------------------
  const custom = resolveSnapshotBackendEnvironmentV80({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_BACKEND_MODE: "custom",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://custom.example.com",
  });
  check(failures, custom.mode === "custom",
    `custom mode honoured for future agnostic backends (got ${custom.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgressV80(custom),
    "custom mode must allow remote progress");

  // Endpoint resolver helpers ---------------------------------------------
  check(failures, resolveSnapshotProgressEndpointV80(prodWithUrl).length > 0,
    "resolveSnapshotProgressEndpointV80 returns a non-empty string");
  check(failures, resolveSnapshotHealthEndpointV80(prodWithUrl).length > 0,
    "resolveSnapshotHealthEndpointV80 returns a non-empty string");

  // Grove terrain mode ----------------------------------------------------
  check(failures, resolveSnapshotGroveTerrainModeV80({}) === "live_v83",
    "Grove terrain mode defaults to live_v83 (production snapshot terrain)");
  check(failures,
    resolveSnapshotGroveTerrainModeV80({
      GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "authored_v75",
    }) === "authored_v75",
    "Grove terrain mode honours authored_v75 override");
  check(failures,
    resolveSnapshotGroveTerrainModeV80({
      GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "v83",
    }) === "live_v83",
    "Grove terrain mode short alias 'v83' resolves to live_v83");

  // Grove ground Y --------------------------------------------------------
  const liveY = resolveSnapshotGroveGroundYV80({});
  check(failures, liveY.mode === "live_v83", "default Grove Y mode is live_v83");
  check(failures, liveY.worldGroundY === SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y_V83,
    `live Grove world ground Y follows SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y_V83 (got ${liveY.worldGroundY})`);
  check(failures, liveY.npcFeetY === SNAPSHOT_GROVE_LIVE_NPC_FEET_Y_V83,
    `live Grove NPC feet Y follows SNAPSHOT_GROVE_LIVE_NPC_FEET_Y_V83 (got ${liveY.npcFeetY})`);
  check(failures, liveY.markerY === SNAPSHOT_GROVE_LIVE_MARKER_Y_V83,
    `live Grove marker Y follows SNAPSHOT_GROVE_LIVE_MARKER_Y_V83 (got ${liveY.markerY})`);

  const authoredY = resolveSnapshotGroveGroundYV80({
    GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "authored_v75",
  });
  check(failures, authoredY.worldGroundY === 52,
    `authored Grove world ground Y is 52 (got ${authoredY.worldGroundY})`);
  check(failures, authoredY.npcFeetY === 53,
    `authored Grove NPC feet Y is 53 (got ${authoredY.npcFeetY})`);

  // Version sanity --------------------------------------------------------
  check(failures, SNAPSHOT_BACKEND_RESOLVER_VERSION_V80 === "snapshot-backend-resolver-v80",
    `resolver version constant matches its marker (got ${SNAPSHOT_BACKEND_RESOLVER_VERSION_V80})`);

  return {
    ok: failures.length === 0,
    version: HARTHMERE_RESOLVER_CONTRACT_VERSION_V1,
    failures,
  };
}

declare const describe: unknown;
declare const test: unknown;
declare const expect: unknown;

if (typeof (describe as any) === "function" && typeof (test as any) === "function") {
  (describe as any)("harthmere resolver contract v1", () => {
    const report = validateHarthmereResolverContractV1();

    (test as any)("all resolver contract assertions pass", () => {
      (expect as any)(report.failures).toEqual([]);
      (expect as any)(report.ok).toBe(true);
    });
  });
}
