// HARTHMERE_RESOLVER_CONTRACT
//
// Patch 04 contract test. Locks the local/prod agnosticism rules in place:
//
//   1. Glitch-specific endpoints (install validation, save sync, achievements,
//      leaderboards) stay hard-wired and are NOT routed through the resolver.
//      Their paths live under /api/glitch/ and inside harthmere_glitch_bridge.
//
//   2. Mission / quest / snapshot-progress state IS routed through the
//      snapshot_backend_resolver so production deployments can swap the
//      backing service (Laravel, custom microservice, anything compatible)
//      by setting GLITCH_SNAPSHOT_BACKEND_MODE / _BACKEND_URL at deploy time.
//
//   3. Grove terrain Y is selectable via GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE
//      so future snapshot rebakes do not require a code change.

import {
  resolveSnapshotBackendEnvironment,
  resolveSnapshotGroveGroundY,
  resolveSnapshotGroveTerrainMode,
  resolveSnapshotHealthEndpoint,
  resolveSnapshotProgressEndpoint,
  SNAPSHOT_BACKEND_RESOLVER_VERSION,
  snapshotBackendAllowsRemoteProgress,
  snapshotBackendUsesLocalProgress,
} from "@/shared/harthmere/snapshot_backend_resolver";

import {
  SNAPSHOT_GROVE_LIVE_MARKER_Y,
  SNAPSHOT_GROVE_LIVE_NPC_FEET_Y,
  SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y,
} from "@/shared/harthmere/snapshot_grove_content";


export const HARTHMERE_RESOLVER_CONTRACT_VERSION =
  "harthmere-resolver-contract" as const;

// ---------------------------------------------------------------------------
// Glitch endpoints that MUST stay hard-wired (not resolver-routed).
// Patch 04 audit: these paths must appear in their respective modules and
// not be dynamically generated by the snapshot resolver.
// ---------------------------------------------------------------------------
export const GLITCH_HARDWIRED_ENDPOINTS: ReadonlyArray<{
  module: string;
  path: string;
  purpose: string;
}> = [
  {
    module: "src/client/game/glitch/harthmere_glitch_bridge.ts",
    path: "/api/glitch/harthmere",
    purpose: "install-id validation and save / achievement / leaderboard sync",
  },
];

// ---------------------------------------------------------------------------
// Snapshot endpoints that MUST be resolver-routed (not hard-coded).
// These call sites are checked at the source-text level in the CJS check;
// here we assert the resolver returns sane shapes for each operating mode.
// ---------------------------------------------------------------------------
export interface HarthmereResolverContractReport {
  ok: boolean;
  version: typeof HARTHMERE_RESOLVER_CONTRACT_VERSION;
  failures: string[];
}

function check(
  failures: string[],
  cond: boolean,
  message: string,
) {
  if (!cond) failures.push(message);
}

export function validateHarthmereResolverContract(): HarthmereResolverContractReport {
  const failures: string[] = [];

  // Mode dispatch ---------------------------------------------------------
  const localEnv = resolveSnapshotBackendEnvironment({});
  check(failures, localEnv.mode === "local",
    `default env (no NODE_ENV) should yield local mode (got ${localEnv.mode})`);
  check(failures, snapshotBackendUsesLocalProgress(localEnv),
    "default env should use local progress");
  check(failures, !snapshotBackendAllowsRemoteProgress(localEnv),
    "default env should not allow remote progress");
  check(failures, localEnv.progressEndpoint === "/api/glitch/snapshot_progress",
    `default progress endpoint should be local Next API path (got ${localEnv.progressEndpoint})`);

  const prodDefault = resolveSnapshotBackendEnvironment({ NODE_ENV: "production" });
  check(failures, prodDefault.mode === "disabled",
    `production with no backend URL should default to disabled (got ${prodDefault.mode})`);
  check(failures, !snapshotBackendAllowsRemoteProgress(prodDefault),
    "production with no backend URL must not allow remote progress");

  const prodWithUrl = resolveSnapshotBackendEnvironment({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://api.example.com",
  });
  check(failures, prodWithUrl.mode === "remote",
    `production + backend URL should resolve to remote (got ${prodWithUrl.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgress(prodWithUrl),
    "production + backend URL must allow remote progress");
  check(failures,
    prodWithUrl.progressEndpoint === "https://api.example.com/api/glitch/snapshot_progress",
    `production progress endpoint should join backend URL + default path (got ${prodWithUrl.progressEndpoint})`);

  // Explicit laravel mode --------------------------------------------------
  const laravel = resolveSnapshotBackendEnvironment({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_BACKEND_MODE: "laravel",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://laravel.example.com/",
    GLITCH_SNAPSHOT_PROGRESS_ENDPOINT: "/api/quest_state",
  });
  check(failures, laravel.mode === "laravel", `laravel mode honoured (got ${laravel.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgress(laravel),
    "laravel mode must allow remote progress");
  check(failures,
    laravel.progressEndpoint === "https://laravel.example.com/api/quest_state",
    `laravel progress endpoint honours custom path (got ${laravel.progressEndpoint})`);

  // Generic custom mode (Laravel-or-anything-else) ------------------------
  const custom = resolveSnapshotBackendEnvironment({
    NODE_ENV: "production",
    GLITCH_SNAPSHOT_BACKEND_MODE: "custom",
    GLITCH_SNAPSHOT_PROGRESS_BACKEND_URL: "https://custom.example.com",
  });
  check(failures, custom.mode === "custom",
    `custom mode honoured for future agnostic backends (got ${custom.mode})`);
  check(failures, snapshotBackendAllowsRemoteProgress(custom),
    "custom mode must allow remote progress");

  // Endpoint resolver helpers ---------------------------------------------
  check(failures, resolveSnapshotProgressEndpoint(prodWithUrl).length > 0,
    "resolveSnapshotProgressEndpoint returns a non-empty string");
  check(failures, resolveSnapshotHealthEndpoint(prodWithUrl).length > 0,
    "resolveSnapshotHealthEndpoint returns a non-empty string");

  // Grove terrain mode ----------------------------------------------------
  check(failures, resolveSnapshotGroveTerrainMode({}) === "live",
    "Grove terrain mode defaults to live (production snapshot terrain)");
  check(failures,
    resolveSnapshotGroveTerrainMode({
      GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "authored",
    }) === "authored",
    "Grove terrain mode honours authored override");
  check(failures,
    resolveSnapshotGroveTerrainMode({
      GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "current",
    }) === "live",
    "Grove terrain mode short alias 'current' resolves to live");

  // Grove ground Y --------------------------------------------------------
  const liveY = resolveSnapshotGroveGroundY({});
  check(failures, liveY.mode === "live", "default Grove Y mode is live");
  check(failures, liveY.worldGroundY === SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y,
    `live Grove world ground Y follows SNAPSHOT_GROVE_LIVE_WORLD_GROUND_Y (got ${liveY.worldGroundY})`);
  check(failures, liveY.npcFeetY === SNAPSHOT_GROVE_LIVE_NPC_FEET_Y,
    `live Grove NPC feet Y follows SNAPSHOT_GROVE_LIVE_NPC_FEET_Y (got ${liveY.npcFeetY})`);
  check(failures, liveY.markerY === SNAPSHOT_GROVE_LIVE_MARKER_Y,
    `live Grove marker Y follows SNAPSHOT_GROVE_LIVE_MARKER_Y (got ${liveY.markerY})`);

  const authoredY = resolveSnapshotGroveGroundY({
    GLITCH_SNAPSHOT_GROVE_TERRAIN_MODE: "authored",
  });
  check(failures, authoredY.worldGroundY === 52,
    `authored Grove world ground Y is 52 (got ${authoredY.worldGroundY})`);
  check(failures, authoredY.npcFeetY === 53,
    `authored Grove NPC feet Y is 53 (got ${authoredY.npcFeetY})`);

  // Version sanity --------------------------------------------------------
  check(failures, SNAPSHOT_BACKEND_RESOLVER_VERSION === "snapshot-backend-resolver",
    `resolver version constant matches its marker (got ${SNAPSHOT_BACKEND_RESOLVER_VERSION})`);

  return {
    ok: failures.length === 0,
    version: HARTHMERE_RESOLVER_CONTRACT_VERSION,
    failures,
  };
}

declare const describe: unknown;
declare const test: unknown;
declare const expect: unknown;

if (typeof (describe as any) === "function" && typeof (test as any) === "function") {
  (describe as any)("harthmere resolver contract current", () => {
    const report = validateHarthmereResolverContract();

    (test as any)("all resolver contract assertions pass", () => {
      (expect as any)(report.failures).toEqual([]);
      (expect as any)(report.ok).toBe(true);
    });
  });
}
