load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "anima",
    srcs = [
        "find_surfaces.cpp",
    ],
    hdrs = glob(["*.hpp"]),
    deps = [
        "//voxeloo/common:errors",
        "//voxeloo/common:spatial",
        "//voxeloo/galois:terrain",
        "//voxeloo/tensors",
    ],
)

cc_test(
    name = "find_surfaces_test",
    srcs = ["find_surfaces_test.cpp"],
    defines = ["CATCH_CONFIG_MAIN"],
    deps = [
        ":anima",
        "//voxeloo/tensors",
        "@catch2",
    ],
)
