#!/usr/bin/env bash
set -euo pipefail

# This entrypoint runs inside the production VNet, where the private Redis
# address is reachable. Keep every terrain-heavy operation in its own Node
# process so native voxel memory is returned between phases.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

REDIS_HOST="${REDIS_HOST:-${GLITCH_REDIS_HOST:-${LOCAL_REDIS_HOST:-}}}"
REDIS_PORT="${REDIS_PORT:-${GLITCH_REDIS_PORT:-6379}}"
if [ -z "$REDIS_HOST" ]; then
  echo "ERROR REDIS_HOST is required for production Harthmere reconciliation." >&2
  exit 2
fi

export REDIS_HOST
export GLITCH_REDIS_HOST="${GLITCH_REDIS_HOST:-$REDIS_HOST}"
export LOCAL_REDIS_HOST="${LOCAL_REDIS_HOST:-$REDIS_HOST}"
export REDIS_PORT
export GLITCH_REDIS_PORT="${GLITCH_REDIS_PORT:-$REDIS_PORT}"
export IS_SERVER="${IS_SERVER:-1}"
export APPLY="${APPLY:-1}"
# Maintenance-only TypeScript packages live outside /app so the normal game
# dependency tree remains production-pruned. NODE_PATH exposes them only here.
export NODE_PATH="/opt/harthmere-maintenance/node_modules${NODE_PATH:+:$NODE_PATH}"

log() {
  printf '[harthmere-reconcile] %s\n' "$*"
}

run_node() {
  local label="$1"
  shift
  log "START $label"
  node "$@"
  log "PASS $label"
}

audit_extension_terrain() {
  if [ "${HARTHMERE_SKIP_EXTENSION_TERRAIN_AUDIT:-0}" = "1" ]; then
    log "Skipping additive Harthmere terrain audit by request."
    return
  fi
  # Audit before the authored outpost and connector writers intentionally
  # modify the flat foundation generated by the maintenance revision.
  run_node "additive Harthmere terrain audit" \
    scripts/harthmere/audit-production-extension-terrain.cjs
}

materialize_business_outposts() {
  if [ "${HARTHMERE_SKIP_BUSINESS_OUTPOST_MATERIALIZATION:-0}" = "1" ]; then
    log "Skipping business outpost terrain materialization by request."
    return
  fi

  local mode="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_MODE:-per-outpost}"
  if [ "$mode" = "bulk" ]; then
    log "START all Harthmere business outposts"
    SCAN_COUNT="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_SCAN_COUNT:-5000}" \
      APPLY_SHARD_BATCH_SIZE="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_APPLY_SHARD_BATCH_SIZE:-2}" \
      node scripts/harthmere/materialize-business-outposts-redis.cjs
    log "PASS all Harthmere business outposts"
    return
  fi
  if [ "$mode" != "per-outpost" ]; then
    echo "ERROR unknown business outpost materialization mode: $mode" >&2
    exit 2
  fi

  local outpost_ids outpost_id materialized_count=0
  outpost_ids="$(node -r ts-node/register/transpile-only -r tsconfig-paths/register - <<'NODE'
const { HARTHMERE_BUSINESS_OUTPOSTS } = require("./src/shared/harthmere/business_customer_simulator");
for (const outpost of HARTHMERE_BUSINESS_OUTPOSTS) {
  console.log(outpost.outpostId);
}
NODE
)"
  while IFS= read -r outpost_id; do
    [ -n "$outpost_id" ] || continue
    log "START business outpost $outpost_id"
    OUTPOST_ID="$outpost_id" \
      SCAN_COUNT="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_SCAN_COUNT:-5000}" \
      APPLY_SHARD_BATCH_SIZE="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_APPLY_SHARD_BATCH_SIZE:-2}" \
      node scripts/harthmere/materialize-business-outposts-redis.cjs
    materialized_count=$((materialized_count + 1))
    log "PASS business outpost $outpost_id"
  done <<< "$outpost_ids"

  if [ "$materialized_count" -ne 19 ]; then
    echo "ERROR materialized ${materialized_count}/19 Harthmere business outposts." >&2
    exit 1
  fi
}

materialize_connector_route() {
  if [ "${HARTHMERE_SKIP_CONNECTOR_ROUTE_MATERIALIZATION:-0}" = "1" ]; then
    log "Skipping Grove-to-Harthmere connector route by request."
    return
  fi
  # The connector is the final authored terrain writer so later town work
  # cannot bury or cut the protected player route.
  log "START protected Grove-to-Harthmere connector"
  APPLY=1 \
    SCAN_COUNT="${HARTHMERE_CONNECTOR_ROUTE_SCAN_COUNT:-5000}" \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_CONNECTOR_ROUTE_APPLY_SHARD_BATCH_SIZE:-4}" \
    node scripts/harthmere/materialize-harthmere-connector-route.cjs
  log "PASS protected Grove-to-Harthmere connector"
}

audit_extension_terrain
materialize_business_outposts
run_node "Harthmere ECS and shared-state reconciliation" \
  scripts/harthmere/reconcile-production-world-sync.cjs
materialize_connector_route

if [ "${HARTHMERE_SKIP_GROUNDING_PROBE:-0}" != "1" ]; then
  run_node "deterministic actor and object grounding repair/readback" \
    scripts/harthmere/probe-production-terrain-grounding.cjs
else
  log "Skipping deterministic grounding probe by request."
fi

if [ "${HARTHMERE_SKIP_LIVE_CREATURE_GROUNDING_RECONCILE:-0}" != "1" ]; then
  run_node "live Mucker, Hex, and animal grounding repair/readback" \
    scripts/harthmere/reconcile-production-live-creature-grounding.cjs
else
  log "Skipping live-creature grounding reconciliation by request."
fi

printf 'HARTHMERE_PRODUCTION_RECONCILIATION_READY tag=%s redis=%s:%s\n' \
  "${HARTHMERE_DEPLOY_TAG:-unknown}" "$REDIS_HOST" "$REDIS_PORT"
