#!/usr/bin/env bash
set -euo pipefail

# This entrypoint runs inside the production VNet, where the private Redis
# address is reachable. Keep every terrain-heavy operation in its own Node
# process so native voxel memory is returned between phases.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

REDIS_HOST="${REDIS_HOST:-${GLITCH_REDIS_HOST:-${LOCAL_REDIS_HOST:-}}}"
REDIS_PORT="${REDIS_PORT:-${GLITCH_REDIS_PORT:-6379}}"
if [ -z "$REDIS_HOST" ]; then
  echo "ERROR REDIS_HOST is required for production Harthmere reconciliation." >&2
  exit 2
fi

export REDIS_HOST
export GLITCH_REDIS_HOST="${GLITCH_REDIS_HOST:-$REDIS_HOST}"
export LOCAL_REDIS_HOST="${LOCAL_REDIS_HOST:-$REDIS_HOST}"
export REDIS_PORT
export GLITCH_REDIS_PORT="${GLITCH_REDIS_PORT:-$REDIS_PORT}"
export IS_SERVER="${IS_SERVER:-1}"
export APPLY="${APPLY:-1}"
# Maintenance-only TypeScript packages live outside /app so the normal game
# dependency tree remains production-pruned. NODE_PATH exposes them only here.
export NODE_PATH="/opt/harthmere-maintenance/node_modules${NODE_PATH:+:$NODE_PATH}"

log() {
  printf '[harthmere-reconcile] %s\n' "$*"
}

run_node() {
  local label="$1"
  shift
  log "START $label"
  node "$@"
  log "PASS $label"
}

# HARTHMERE_DEPLOY_TERRAIN_GATE (2026-07-30)
#
# The sunken 32x32 black pits in the wilds shipped release after release, and
# this file is why. The terrain audit ran FIRST and threw on any damage, so a
# deploy that found a pit aborted before it could ever reach a repair — and
# there was no repair phase here to reach. The runbook's fix
# (docs/harthmere/EXTENSION_SURFACE_REPAIR_RUNBOOK.md) existed but was a manual
# in-VNet chore nobody was going to remember.
#
# Now the terrain work is three ordered phases:
#
#   1. report   non-fatal. Describes the damage so it is in the deploy log.
#   2. repair   idempotent and ADD-ONLY. Restores the flat plane, creates any
#               missing surface shard, lifts creatures off pit floors, and
#               clears the forest that grew inside buildings.
#   3. verify   fatal. Runs the same audit with the gate armed. A pit that
#               survives the repair now stops the deploy, which is the only
#               state in which failing is useful.
#
# "Without destroying the terrain" is a property of the repair, not of this
# script: it never emits an air edit, never writes at or below the probed
# surface, refuses the Bellbinder stair mouth and every authored cave, writes to
# shard_seed so Gaia restoration cannot revert it, and yields to any voxel a
# player has edited in shard_diff. All of that is unit-tested in
# src/shared/harthmere/test/extension_surface_repair.test.ts.
report_extension_terrain() {
  if [ "${HARTHMERE_SKIP_EXTENSION_TERRAIN_AUDIT:-0}" = "1" ]; then
    log "Skipping additive Harthmere terrain report by request."
    return
  fi
  # Report before the authored outpost and connector writers intentionally
  # modify the flat foundation generated by the maintenance revision.
  log "START additive Harthmere terrain report (non-fatal)"
  HARTHMERE_TERRAIN_AUDIT_NON_FATAL=1 \
    node scripts/harthmere/audit-production-extension-terrain.cjs
  log "PASS additive Harthmere terrain report"
}

# HARTHMERE_AUTHORED_WATER: cut and fill the Brell.
#
# This runs BEFORE the sunken-surface repair, and the order is load-bearing.
# Production deploys pass HARTHMERE_SKIP_EXTENSION_TERRAIN_SEED=1, and the
# terrain seed is the only writer that can remove ground — the surface repair
# below is add-only. So without this step the river could never be cut, and the
# repair's authored-water exemption would leave those columns sunken forever
# instead of filling them. Materialize first, then let the repair handle
# everything that is genuinely damaged.
#
# Deliberately NOT gated by HARTHMERE_SKIP_EXTENSION_TERRAIN_SEED: skipping the
# broad terrain reseed is a routine, safe choice; skipping the river is not.
materialize_authored_water() {
  if [ "${HARTHMERE_SKIP_AUTHORED_WATER_MATERIALIZE:-0}" = "1" ]; then
    log "Skipping Harthmere authored-water materialization by request."
    return
  fi
  log "START Harthmere authored-water materialization (river, mill race, basins)"
  APPLY=1 timeout "${HARTHMERE_AUTHORED_WATER_TIMEOUT_SECONDS:-300}" \
    node scripts/harthmere/materialize-harthmere-authored-water.cjs
  log "PASS Harthmere authored-water materialization"
}

repair_extension_surface() {
  if [ "${HARTHMERE_SKIP_EXTENSION_SURFACE_REPAIR:-0}" = "1" ]; then
    log "Skipping additive Harthmere surface repair by request."
    return
  fi
  log "START additive Harthmere sunken-surface repair"
  APPLY=1 \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_SURFACE_REPAIR_APPLY_SHARD_BATCH_SIZE:-8}" \
    node scripts/harthmere/repair-harthmere-extension-surface.cjs
  log "PASS additive Harthmere sunken-surface repair"
}

clear_building_interior_vegetation() {
  if [ "${HARTHMERE_SKIP_INTERIOR_VEGETATION_CLEAR:-0}" = "1" ]; then
    log "Skipping Harthmere interior vegetation clear by request."
    return
  fi
  # The seeder gate (harthmere_building_exclusion.ts) stops NEW growth, which
  # covers a fresh reseed. Live Redis still holds shards seeded under the old
  # rule, and nobody reseeds a live world, so the trees already standing in the
  # watermill and the Residential row houses need removing explicitly.
  log "START Harthmere building interior vegetation clear"
  APPLY=1 \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_INTERIOR_CLEAR_APPLY_SHARD_BATCH_SIZE:-8}" \
    timeout --signal=TERM --kill-after=30s \
      "${HARTHMERE_INTERIOR_CLEAR_TIMEOUT_SECONDS:-300}" \
      node scripts/harthmere/clear-harthmere-building-interior-vegetation.cjs
  log "PASS Harthmere building interior vegetation clear"
}

repair_harthmere_town() {
  if [ "${HARTHMERE_SKIP_TOWN_PRODUCTION_REPAIR:-0}" = "1" ]; then
    log "Skipping persisted Harthmere town surface, roof, and NPC repair by request."
    return
  fi
  # Ordinary deploys use additive terrain mode, which correctly preserves
  # existing shards but therefore cannot migrate previously-authored town
  # surfaces, roofs, moved shells, added floors, or the derived street network.
  # This writer reconstructs the ~142 canonical shard seeds those volumes touch
  # (up from 14 before the shell/street pass), preserves all mutable ECS
  # overlays (including shard_diff and shard_water), applies the reviewed
  # town-style overrides, and retires only the audited generic/customer NPC ids.
  #
  # The timeout below is per-run, not per-shard, and a kill leaves the town
  # PARTIALLY repaired: each shard commit is atomic, so nothing corrupts, but
  # some shells would still be at their old coordinates until the next deploy.
  # Budget for the full set rather than the old fourteen.
  log "START persisted Harthmere town surface, roof, and NPC repair"
  APPLY=1 \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_TOWN_REPAIR_APPLY_SHARD_BATCH_SIZE:-4}" \
    timeout --signal=TERM --kill-after=30s \
      "${HARTHMERE_TOWN_REPAIR_TIMEOUT_SECONDS:-900}" \
      node scripts/harthmere/repair-harthmere-town-production.cjs
  log "PASS persisted Harthmere town surface, roof, and NPC repair"
}

verify_extension_terrain() {
  if [ "${HARTHMERE_SKIP_EXTENSION_TERRAIN_AUDIT:-0}" = "1" ]; then
    log "Skipping additive Harthmere terrain verification by request."
    return
  fi
  # Gate armed. This is the phase that can stop a bad deploy.
  run_node "additive Harthmere terrain verification" \
    scripts/harthmere/audit-production-extension-terrain.cjs
}

verify_harthmere_town() {
  if [ "${HARTHMERE_SKIP_TOWN_REPAIR_AUDIT:-0}" = "1" ]; then
    log "Skipping persisted Harthmere town repair verification by request."
    return
  fi
  # Water has its own authored-water deployment gate. Keep this town gate
  # focused on the user-reported surface, building, and population defects.
  log "START persisted Harthmere town surface, roof, and NPC verification"
  HARTHMERE_TOWN_REPAIR_SKIP_WATER=1 \
    timeout --signal=TERM --kill-after=30s \
      "${HARTHMERE_TOWN_REPAIR_AUDIT_TIMEOUT_SECONDS:-300}" \
      node scripts/harthmere/audit-harthmere-town-repair.cjs
  log "PASS persisted Harthmere town surface, roof, and NPC verification"
}

materialize_business_outposts() {
  if [ "${HARTHMERE_SKIP_BUSINESS_OUTPOST_MATERIALIZATION:-0}" = "1" ]; then
    log "Skipping business outpost terrain materialization by request."
    return
  fi

  local mode="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_MODE:-per-outpost}"
  if [ "$mode" = "bulk" ]; then
    log "START all Harthmere business outposts"
    SCAN_COUNT="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_SCAN_COUNT:-5000}" \
      APPLY_SHARD_BATCH_SIZE="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_APPLY_SHARD_BATCH_SIZE:-2}" \
      node scripts/harthmere/materialize-business-outposts-redis.cjs
    log "PASS all Harthmere business outposts"
    return
  fi
  if [ "$mode" != "per-outpost" ]; then
    echo "ERROR unknown business outpost materialization mode: $mode" >&2
    exit 2
  fi

  local outpost_ids outpost_id materialized_count=0
  outpost_ids="$(node -r ts-node/register/transpile-only -r tsconfig-paths/register - <<'NODE'
const { HARTHMERE_BUSINESS_OUTPOSTS } = require("./src/shared/harthmere/business_customer_simulator");
for (const outpost of HARTHMERE_BUSINESS_OUTPOSTS) {
  console.log(outpost.outpostId);
}
NODE
)"
  while IFS= read -r outpost_id; do
    [ -n "$outpost_id" ] || continue
    log "START business outpost $outpost_id"
    OUTPOST_ID="$outpost_id" \
      SCAN_COUNT="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_SCAN_COUNT:-5000}" \
      APPLY_SHARD_BATCH_SIZE="${HARTHMERE_BUSINESS_OUTPOST_MATERIALIZATION_APPLY_SHARD_BATCH_SIZE:-2}" \
      node scripts/harthmere/materialize-business-outposts-redis.cjs
    materialized_count=$((materialized_count + 1))
    log "PASS business outpost $outpost_id"
  done <<< "$outpost_ids"

  if [ "$materialized_count" -ne 19 ]; then
    echo "ERROR materialized ${materialized_count}/19 Harthmere business outposts." >&2
    exit 1
  fi
}

materialize_connector_route() {
  if [ "${HARTHMERE_SKIP_CONNECTOR_ROUTE_MATERIALIZATION:-0}" = "1" ]; then
    log "Skipping Grove-to-Harthmere connector route by request."
    return
  fi
  # The connector is the final authored terrain writer so later town work
  # cannot bury or cut the protected player route.
  log "START protected Grove-to-Harthmere connector"
  APPLY=1 \
    SCAN_COUNT="${HARTHMERE_CONNECTOR_ROUTE_SCAN_COUNT:-5000}" \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_CONNECTOR_ROUTE_APPLY_SHARD_BATCH_SIZE:-4}" \
    node scripts/harthmere/materialize-harthmere-connector-route.cjs
  log "PASS protected Grove-to-Harthmere connector"
}

materialize_chapter1_world_buildings() {
  if [ "${HARTHMERE_SKIP_CH1_WORLD_BUILDING_MATERIALIZATION:-0}" = "1" ]; then
    log "Skipping Chapter 1 Road-House and Watch House materialization by request."
    return
  fi
  log "START Chapter 1 Road-House and Watch House"
  APPLY=1 \
    SCAN_COUNT="${HARTHMERE_CH1_WORLD_BUILDING_SCAN_COUNT:-5000}" \
    APPLY_SHARD_BATCH_SIZE="${HARTHMERE_CH1_WORLD_BUILDING_APPLY_SHARD_BATCH_SIZE:-4}" \
    node scripts/harthmere/materialize-chapter1-world-buildings-redis.cjs
  log "PASS Chapter 1 Road-House and Watch House"
}

if [ "${HARTHMERE_TOWN_REPAIR_ONLY:-0}" = "1" ]; then
  # The river is authored world content, not an outpost/ECS extra, so it is
  # restored in the town-only path too. Skipping the broad reconciliation must
  # not mean skipping the Brell.
  materialize_authored_water
  repair_harthmere_town
  verify_harthmere_town
  printf 'HARTHMERE_PRODUCTION_RECONCILIATION_READY tag=%s redis=%s:%s mode=town-only\n' \
    "${HARTHMERE_DEPLOY_TAG:-unknown}" "$REDIS_HOST" "$REDIS_PORT"
  exit 0
fi

report_extension_terrain
materialize_authored_water
repair_extension_surface
clear_building_interior_vegetation
repair_harthmere_town
materialize_business_outposts
run_node "Harthmere ECS and shared-state reconciliation" \
  scripts/harthmere/reconcile-production-world-sync.cjs
materialize_chapter1_world_buildings
materialize_connector_route

if [ "${HARTHMERE_SKIP_GROUNDING_PROBE:-0}" != "1" ]; then
  run_node "deterministic actor and object grounding repair/readback" \
    scripts/harthmere/probe-production-terrain-grounding.cjs
else
  log "Skipping deterministic grounding probe by request."
fi

if [ "${HARTHMERE_SKIP_LIVE_CREATURE_GROUNDING_RECONCILE:-0}" != "1" ]; then
  run_node "live Mucker, Hex, and animal grounding repair/readback" \
    scripts/harthmere/reconcile-production-live-creature-grounding.cjs
else
  log "Skipping live-creature grounding reconciliation by request."
fi

# The terrain gate runs LAST, after every authored writer has had its turn, so
# it verifies the world the player will actually load rather than an
# intermediate state.
verify_extension_terrain
verify_harthmere_town

printf 'HARTHMERE_PRODUCTION_RECONCILIATION_READY tag=%s redis=%s:%s\n' \
  "${HARTHMERE_DEPLOY_TAG:-unknown}" "$REDIS_HOST" "$REDIS_PORT"
