name: "Cached eslint restore"

description: "Restore the eslint cache from a previous run."

outputs:
  cache-hit:
    description: "Whether the eslint cache was restored from an exact key."
    value: ${{ steps.eslintcache-cache.outputs.cache-hit }}

branding:
  icon: "download"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Restore .eslintcache
      uses: actions/cache/restore@v5
      id: eslintcache-cache
      with:
        path: ./.next/cache/eslint
        key: ${{ runner.os }}-eslintcache-${{ hashFiles('./yarn.lock') }}
        # Start from an older cache if we don't have an exact match.
        restore-keys: |
          ${{ runner.os }}-eslintcache-
