export const HARTHMERE_ATTACK_VARIATION_POLISH_VERSION =
  "harthmere-attack-variation-polish";

export type HarthmereAttackFamily =
  "basic" | "heavy" | "magic" | "rangedRelease" | "shieldBash" | "toolUse";

export type HarthmereAttackVariation = {
  id: string;
  family: HarthmereAttackFamily;
  clip: string;
  frameCount: number;
  fps: 24;
  emoteType: string;
  windupFrame: number;
  impactFrame: number;
  recoveryFrame: number;
  stance: "open" | "closed" | "forward" | "low" | "high";
  leadFoot: "left" | "right" | "balanced";
  attackSide: "right" | "left" | "center";
  arc: string;
  torsoYawDeg: number;
  spineBendDeg: number;
  shoulderYawDeg: number;
  hipYawDeg: number;
  stepForwardMeters: number;
  stepLateralMeters: number;
  weaponTravelArcDeg: number;
  weightShift: "front" | "rear" | "left" | "right" | "center";
  locomotionAllowed: boolean;
  airAllowed: boolean;
  silhouetteTag: string;
  notes: string;
};

const make = (
  family: HarthmereAttackFamily,
  index: number,
  data: Omit<HarthmereAttackVariation, "id" | "family" | "frameCount" | "fps">
): HarthmereAttackVariation => ({
  id: `${family}_${index}`,
  family,
  frameCount: family === "heavy" ? 26 : family === "basic" ? 17 : 24,
  fps: 24,
  ...data,
});

export const HARTHMERE_ATTACK_VARIATIONS_POLISH: Record<
  HarthmereAttackFamily,
  readonly HarthmereAttackVariation[]
> = {
  basic: [
    make("basic", 1, {
      emoteType: "attack1Var1",
      clip: "HarthmereBodyWeaponBasic_Variation1_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "open",
      leadFoot: "left",
      attackSide: "left",
      arc: "horizontal_right_to_left",
      torsoYawDeg: 34,
      spineBendDeg: 8,
      shoulderYawDeg: 42,
      hipYawDeg: 20,
      stepForwardMeters: 0.1,
      stepLateralMeters: 0.02,
      weaponTravelArcDeg: 128,
      weightShift: "front",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "wide_forehand",
      notes:
        "Right-side anticipation into a clean leftward horizontal cut, impact hold, overshoot, and planted recovery.",
    }),
    make("basic", 2, {
      emoteType: "attack1Var2",
      clip: "HarthmereBodyWeaponBasic_Variation2_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "horizontal_left_to_right",
      torsoYawDeg: -34,
      spineBendDeg: 8,
      shoulderYawDeg: -42,
      hipYawDeg: -20,
      stepForwardMeters: 0.08,
      stepLateralMeters: -0.04,
      weaponTravelArcDeg: 128,
      weightShift: "right",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "backhand_return",
      notes:
        "Cross-body anticipation into a mirrored rightward backhand with delayed wrist and weapon recovery.",
    }),
    make("basic", 3, {
      emoteType: "attack1Var3",
      clip: "HarthmereBodyWeaponBasic_Variation3_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "high",
      leadFoot: "left",
      attackSide: "left",
      arc: "high_right_to_low_left",
      torsoYawDeg: 36,
      spineBendDeg: 18,
      shoulderYawDeg: 48,
      hipYawDeg: 20,
      stepForwardMeters: 0.11,
      stepLateralMeters: 0.03,
      weaponTravelArcDeg: 152,
      weightShift: "front",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "descending_cleave",
      notes:
        "High-right load into a low-left diagonal cut with a clearly descending blade path.",
    }),
    make("basic", 4, {
      emoteType: "attack1Var4",
      clip: "HarthmereBodyWeaponBasic_Variation4_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "low",
      leadFoot: "right",
      attackSide: "right",
      arc: "low_left_to_high_right",
      torsoYawDeg: -36,
      spineBendDeg: 18,
      shoulderYawDeg: -48,
      hipYawDeg: -20,
      stepForwardMeters: 0.09,
      stepLateralMeters: -0.03,
      weaponTravelArcDeg: 152,
      weightShift: "right",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "rising_cut",
      notes:
        "Low-left load into a fast rising cut with an open final silhouette and clean combo handoff.",
    }),
  ],
  heavy: [
    make("heavy", 1, {
      emoteType: "attack2Var1",
      clip: "HarthmereBodyWeaponHeavy_Variation1_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "high",
      leadFoot: "left",
      attackSide: "left",
      arc: "vertical_high_to_low",
      torsoYawDeg: 44,
      spineBendDeg: 12,
      shoulderYawDeg: 54,
      hipYawDeg: 28,
      stepForwardMeters: 0.14,
      stepLateralMeters: 0.03,
      weaponTravelArcDeg: 168,
      weightShift: "front",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "overhead_cleave",
      notes:
        "High load into a frame-10 overhead contact, broad overshoot, and compact frame-26 recovery.",
    }),
    make("heavy", 2, {
      emoteType: "attack2Var2",
      clip: "HarthmereBodyWeaponHeavy_Variation2_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "horizontal_left_to_right",
      torsoYawDeg: -44,
      spineBendDeg: 12,
      shoulderYawDeg: -54,
      hipYawDeg: -28,
      stepForwardMeters: 0.12,
      stepLateralMeters: -0.06,
      weaponTravelArcDeg: 168,
      weightShift: "right",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "broad_side_sweep",
      notes:
        "Mirrored heavy backhand with planted weight transfer and delayed weapon settle.",
    }),
    make("heavy", 3, {
      emoteType: "attack2Var3",
      clip: "HarthmereBodyWeaponHeavy_Variation3_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "high",
      leadFoot: "left",
      attackSide: "left",
      arc: "high_left_to_low_right",
      torsoYawDeg: 46,
      spineBendDeg: 24,
      shoulderYawDeg: 60,
      hipYawDeg: 30,
      stepForwardMeters: 0.15,
      stepLateralMeters: 0.04,
      weaponTravelArcDeg: 188,
      weightShift: "front",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "backhand_crusher",
      notes:
        "Committed high-right to low-left cleave with descending tip path and grounded follow-through.",
    }),
    make("heavy", 4, {
      emoteType: "attack2Var4",
      clip: "HarthmereBodyWeaponHeavy_Variation4_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "low",
      leadFoot: "right",
      attackSide: "right",
      arc: "low_right_to_high_left",
      torsoYawDeg: -46,
      spineBendDeg: 24,
      shoulderYawDeg: -60,
      hipYawDeg: -30,
      stepForwardMeters: 0.13,
      stepLateralMeters: -0.04,
      weaponTravelArcDeg: 188,
      weightShift: "right",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "rising_finisher",
      notes:
        "Low committed load into a rising finisher with strong leg drive and a high open follow-through.",
    }),
  ],
  magic: [
    make("magic", 1, {
      emoteType: "magicCastVar1",
      clip: "HarthmereBodyMagicCast_Variation1_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 20,
      stance: "open",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "palm_burst",
      torsoYawDeg: 0,
      spineBendDeg: -2,
      shoulderYawDeg: 10,
      hipYawDeg: 0,
      stepForwardMeters: 0.02,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 22,
      weightShift: "center",
      locomotionAllowed: true,
      airAllowed: true,
      silhouetteTag: "palm_burst",
      notes: "Straight forward palm/burst cast.",
    }),
    make("magic", 2, {
      emoteType: "magicCastVar2",
      clip: "HarthmereBodyMagicCast_Variation2_24",
      windupFrame: 5,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "high",
      leadFoot: "left",
      attackSide: "center",
      arc: "overhead_invocation",
      torsoYawDeg: 14,
      spineBendDeg: -8,
      shoulderYawDeg: 18,
      hipYawDeg: 6,
      stepForwardMeters: 0.04,
      stepLateralMeters: 0.02,
      weaponTravelArcDeg: 86,
      weightShift: "front",
      locomotionAllowed: true,
      airAllowed: true,
      silhouetteTag: "overhead_invocation",
      notes: "Arms lift high then channel downward.",
    }),
    make("magic", 3, {
      emoteType: "magicCastVar3",
      clip: "HarthmereBodyMagicCast_Variation3_24",
      windupFrame: 4,
      impactFrame: 10,
      recoveryFrame: 19,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "sweeping_sigil",
      torsoYawDeg: -22,
      spineBendDeg: 6,
      shoulderYawDeg: -24,
      hipYawDeg: -10,
      stepForwardMeters: 0.0,
      stepLateralMeters: -0.08,
      weaponTravelArcDeg: 110,
      weightShift: "right",
      locomotionAllowed: true,
      airAllowed: true,
      silhouetteTag: "sweeping_sigil",
      notes: "Broad sideways spell sweep.",
    }),
    make("magic", 4, {
      emoteType: "magicCastVar4",
      clip: "HarthmereBodyMagicCast_Variation4_24",
      windupFrame: 6,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "low",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "ground_slam_cast",
      torsoYawDeg: 0,
      spineBendDeg: 12,
      shoulderYawDeg: 14,
      hipYawDeg: 0,
      stepForwardMeters: 0.05,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 74,
      weightShift: "front",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "ground_slam_cast",
      notes: "Crouched ground-focused release.",
    }),
  ],
  rangedRelease: [
    make("rangedRelease", 1, {
      emoteType: "rangedReleaseVar1",
      clip: "HarthmereBodyRangedRelease_Variation1_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "forward",
      leadFoot: "left",
      attackSide: "right",
      arc: "square_release",
      torsoYawDeg: 0,
      spineBendDeg: -3,
      shoulderYawDeg: 12,
      hipYawDeg: 0,
      stepForwardMeters: 0.02,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 10,
      weightShift: "center",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "square_release",
      notes: "Neutral release.",
    }),
    make("rangedRelease", 2, {
      emoteType: "rangedReleaseVar2",
      clip: "HarthmereBodyRangedRelease_Variation2_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "open",
      leadFoot: "balanced",
      attackSide: "right",
      arc: "open_release",
      torsoYawDeg: 16,
      spineBendDeg: -2,
      shoulderYawDeg: 18,
      hipYawDeg: 6,
      stepForwardMeters: 0.03,
      stepLateralMeters: 0.05,
      weaponTravelArcDeg: 18,
      weightShift: "left",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "open_release",
      notes: "Open stance release with obvious body openness.",
    }),
    make("rangedRelease", 3, {
      emoteType: "rangedReleaseVar3",
      clip: "HarthmereBodyRangedRelease_Variation3_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "snap_release",
      torsoYawDeg: -18,
      spineBendDeg: 4,
      shoulderYawDeg: -16,
      hipYawDeg: -8,
      stepForwardMeters: 0.0,
      stepLateralMeters: -0.05,
      weaponTravelArcDeg: 12,
      weightShift: "right",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "snap_release",
      notes: "Short snap release from closed stance.",
    }),
    make("rangedRelease", 4, {
      emoteType: "rangedReleaseVar4",
      clip: "HarthmereBodyRangedRelease_Variation4_24",
      windupFrame: 7,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "high",
      leadFoot: "balanced",
      attackSide: "right",
      arc: "lofted_release",
      torsoYawDeg: 0,
      spineBendDeg: -8,
      shoulderYawDeg: 14,
      hipYawDeg: 0,
      stepForwardMeters: 0.03,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 24,
      weightShift: "center",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "lofted_release",
      notes: "Elevated shot release.",
    }),
  ],
  shieldBash: [
    make("shieldBash", 1, {
      emoteType: "shieldBashVar1",
      clip: "HarthmereBodyShieldBash_Variation1_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "forward",
      leadFoot: "left",
      attackSide: "left",
      arc: "short_jab",
      torsoYawDeg: -10,
      spineBendDeg: -2,
      shoulderYawDeg: -16,
      hipYawDeg: -6,
      stepForwardMeters: 0.08,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 16,
      weightShift: "front",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "short_jab",
      notes: "Compact shield jab.",
    }),
    make("shieldBash", 2, {
      emoteType: "shieldBashVar2",
      clip: "HarthmereBodyShieldBash_Variation2_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "closed",
      leadFoot: "right",
      attackSide: "left",
      arc: "hook_bash",
      torsoYawDeg: -24,
      spineBendDeg: 5,
      shoulderYawDeg: -22,
      hipYawDeg: -12,
      stepForwardMeters: 0.02,
      stepLateralMeters: -0.08,
      weaponTravelArcDeg: 92,
      weightShift: "right",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "hook_bash",
      notes: "Hooking shield bash.",
    }),
    make("shieldBash", 3, {
      emoteType: "shieldBashVar3",
      clip: "HarthmereBodyShieldBash_Variation3_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "low",
      leadFoot: "balanced",
      attackSide: "left",
      arc: "rising_bump",
      torsoYawDeg: -16,
      spineBendDeg: 10,
      shoulderYawDeg: -18,
      hipYawDeg: -6,
      stepForwardMeters: 0.04,
      stepLateralMeters: 0.02,
      weaponTravelArcDeg: 84,
      weightShift: "left",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "rising_bump",
      notes: "Rising upward bump.",
    }),
    make("shieldBash", 4, {
      emoteType: "shieldBashVar4",
      clip: "HarthmereBodyShieldBash_Variation4_24",
      windupFrame: 7,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "high",
      leadFoot: "left",
      attackSide: "left",
      arc: "slam_bash",
      torsoYawDeg: -8,
      spineBendDeg: -6,
      shoulderYawDeg: -12,
      hipYawDeg: -2,
      stepForwardMeters: 0.09,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 118,
      weightShift: "front",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "slam_bash",
      notes: "Downward shield slam.",
    }),
  ],
  toolUse: [
    make("toolUse", 1, {
      emoteType: "toolUseVar1",
      clip: "HarthmereBodyToolUse_Variation1_24",
      windupFrame: 5,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "high",
      leadFoot: "left",
      attackSide: "right",
      arc: "overhead_chop",
      torsoYawDeg: 0,
      spineBendDeg: -10,
      shoulderYawDeg: 18,
      hipYawDeg: 0,
      stepForwardMeters: 0.06,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 132,
      weightShift: "front",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "overhead_chop",
      notes: "Obvious overhead gather hit.",
    }),
    make("toolUse", 2, {
      emoteType: "toolUseVar2",
      clip: "HarthmereBodyToolUse_Variation2_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "open",
      leadFoot: "right",
      attackSide: "right",
      arc: "angled_hack",
      torsoYawDeg: -18,
      spineBendDeg: 4,
      shoulderYawDeg: -16,
      hipYawDeg: -6,
      stepForwardMeters: 0.02,
      stepLateralMeters: -0.06,
      weaponTravelArcDeg: 108,
      weightShift: "right",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "angled_hack",
      notes: "Angled chop for wood/ore.",
    }),
    make("toolUse", 3, {
      emoteType: "toolUseVar3",
      clip: "HarthmereBodyToolUse_Variation3_24",
      windupFrame: 4,
      impactFrame: 10,
      recoveryFrame: 18,
      stance: "closed",
      leadFoot: "left",
      attackSide: "right",
      arc: "cross_body_pick",
      torsoYawDeg: 22,
      spineBendDeg: 8,
      shoulderYawDeg: 20,
      hipYawDeg: 8,
      stepForwardMeters: 0.0,
      stepLateralMeters: 0.08,
      weaponTravelArcDeg: 116,
      weightShift: "left",
      locomotionAllowed: false,
      airAllowed: false,
      silhouetteTag: "cross_body_pick",
      notes: "Cross-body mining hit.",
    }),
    make("toolUse", 4, {
      emoteType: "toolUseVar4",
      clip: "HarthmereBodyToolUse_Variation4_24",
      windupFrame: 6,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "low",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "forward_dig",
      torsoYawDeg: 0,
      spineBendDeg: 14,
      shoulderYawDeg: 10,
      hipYawDeg: 0,
      stepForwardMeters: 0.08,
      stepLateralMeters: 0.0,
      weaponTravelArcDeg: 58,
      weightShift: "front",
      locomotionAllowed: true,
      airAllowed: false,
      silhouetteTag: "forward_dig",
      notes: "Forward dig/poke strike.",
    }),
  ],
} as const;

const __harthmereVariationCycleState: Record<HarthmereAttackFamily, number> = {
  basic: 0,
  heavy: 0,
  magic: 0,
  rangedRelease: 0,
  shieldBash: 0,
  toolUse: 0,
};

export function advanceHarthmereAttackVariationIndex(
  family: HarthmereAttackFamily
): number {
  const variants = HARTHMERE_ATTACK_VARIATIONS_POLISH[family];
  const nextIndex =
    (__harthmereVariationCycleState[family] + 1) % variants.length;
  __harthmereVariationCycleState[family] = nextIndex;
  return nextIndex;
}

export function pickHarthmereAttackVariation(
  family: HarthmereAttackFamily
): HarthmereAttackVariation {
  const variants = HARTHMERE_ATTACK_VARIATIONS_POLISH[family];
  return variants[advanceHarthmereAttackVariationIndex(family)];
}

export function getHarthmereAttackFamilyForAction(
  actionType: string
): HarthmereAttackFamily {
  if (actionType === "attack2") return "heavy";
  if (actionType === "magicCast") return "magic";
  if (actionType === "rangedRelease") return "rangedRelease";
  if (actionType === "shieldBash") return "shieldBash";
  if (actionType === "toolUse") return "toolUse";
  return "basic";
}
