export const HARTHMERE_ATTACK_VARIATION_VERSION = "harthmere-attack-variation";

export type HarthmereAttackFamily =
  "basic" | "heavy" | "magic" | "rangedRelease" | "shieldBash" | "toolUse";

export type HarthmereAttackVariation = {
  id: string;
  family: HarthmereAttackFamily;
  clip: string;
  frameCount: number;
  fps: 24;
  windupFrame: number;
  impactFrame: number;
  recoveryFrame: number;
  stance: "neutral" | "forward" | "low" | "cross" | "open" | "closed";
  leadFoot: "left" | "right" | "balanced";
  attackSide: "left" | "right" | "center";
  arc: string;
  torsoYawDeg: number;
  shoulderYawDeg: number;
  weaponYawBiasDeg: number;
  weaponPitchBiasDeg: number;
  locomotionAllowed: boolean;
  airAllowed: boolean;
  notes: string;
};

const v = (
  family: HarthmereAttackFamily,
  index: number,
  data: Omit<HarthmereAttackVariation, "family" | "id" | "frameCount" | "fps">
): HarthmereAttackVariation => ({
  id: `${family}_${index}`,
  family,
  frameCount: family === "heavy" ? 26 : family === "basic" ? 17 : 24,
  fps: 24,
  ...data,
});

export const HARTHMERE_ATTACK_VARIATIONS: Record<
  HarthmereAttackFamily,
  readonly HarthmereAttackVariation[]
> = {
  basic: [
    v("basic", 1, {
      clip: "HarthmereBodyWeaponBasic_Variation1_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "horizontal_left_to_right",
      torsoYawDeg: -34,
      shoulderYawDeg: -42,
      weaponYawBiasDeg: -28,
      weaponPitchBiasDeg: 0,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Combo step one: left-side load to rightward horizontal contact.",
    }),
    v("basic", 2, {
      clip: "HarthmereBodyWeaponBasic_Variation2_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "open",
      leadFoot: "left",
      attackSide: "left",
      arc: "horizontal_right_to_left",
      torsoYawDeg: 34,
      shoulderYawDeg: 42,
      weaponYawBiasDeg: 28,
      weaponPitchBiasDeg: 0,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Combo step two: right-side load to leftward horizontal contact.",
    }),
    v("basic", 3, {
      clip: "HarthmereBodyWeaponBasic_Variation3_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "open",
      leadFoot: "left",
      attackSide: "left",
      arc: "vertical_overhead_to_low",
      torsoYawDeg: 12,
      shoulderYawDeg: 52,
      weaponYawBiasDeg: 8,
      weaponPitchBiasDeg: 58,
      locomotionAllowed: true,
      airAllowed: false,
      notes:
        "Combo step three: overhead load into a near-vertical downward cut.",
    }),
    v("basic", 4, {
      clip: "HarthmereBodyWeaponBasic_Variation4_24",
      windupFrame: 3,
      impactFrame: 6,
      recoveryFrame: 17,
      stance: "low",
      leadFoot: "right",
      attackSide: "right",
      arc: "diagonal_low_left_to_high_right",
      torsoYawDeg: -36,
      shoulderYawDeg: -48,
      weaponYawBiasDeg: -30,
      weaponPitchBiasDeg: 42,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Rising cut: low-left load to high-right contact.",
    }),
  ],
  heavy: [
    v("heavy", 1, {
      clip: "HarthmereBodyWeaponHeavy_Variation1_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "horizontal_left_to_right",
      torsoYawDeg: -44,
      shoulderYawDeg: -54,
      weaponYawBiasDeg: -36,
      weaponPitchBiasDeg: 0,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Heavy combo step one: committed left-to-right power sweep.",
    }),
    v("heavy", 2, {
      clip: "HarthmereBodyWeaponHeavy_Variation2_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "open",
      leadFoot: "left",
      attackSide: "left",
      arc: "horizontal_right_to_left",
      torsoYawDeg: 44,
      shoulderYawDeg: 54,
      weaponYawBiasDeg: 36,
      weaponPitchBiasDeg: 0,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Heavy combo step two: reversed right-to-left power return.",
    }),
    v("heavy", 3, {
      clip: "HarthmereBodyWeaponHeavy_Variation3_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "open",
      leadFoot: "left",
      attackSide: "left",
      arc: "vertical_overhead_to_low",
      torsoYawDeg: 14,
      shoulderYawDeg: 60,
      weaponYawBiasDeg: 10,
      weaponPitchBiasDeg: 64,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Heavy combo step three: overhead crusher with vertical descent.",
    }),
    v("heavy", 4, {
      clip: "HarthmereBodyWeaponHeavy_Variation4_24",
      windupFrame: 6,
      impactFrame: 10,
      recoveryFrame: 26,
      stance: "low",
      leadFoot: "right",
      attackSide: "right",
      arc: "diagonal_low_right_to_high_left",
      torsoYawDeg: -46,
      shoulderYawDeg: -60,
      weaponYawBiasDeg: -40,
      weaponPitchBiasDeg: 52,
      locomotionAllowed: false,
      airAllowed: false,
      notes:
        "Heavy rising finisher with strong leg drive and open follow-through.",
    }),
  ],
  magic: [
    v("magic", 1, {
      clip: "HarthmereBodyMagicCast_Variation1_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 20,
      stance: "open",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "cast_forward",
      torsoYawDeg: 0,
      shoulderYawDeg: 5,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -4,
      locomotionAllowed: true,
      airAllowed: true,
      notes: "Forward palm/burst cast.",
    }),
    v("magic", 2, {
      clip: "HarthmereBodyMagicCast_Variation2_24",
      windupFrame: 5,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "cross",
      leadFoot: "left",
      attackSide: "right",
      arc: "cast_up",
      torsoYawDeg: 4,
      shoulderYawDeg: 10,
      weaponYawBiasDeg: 6,
      weaponPitchBiasDeg: -12,
      locomotionAllowed: true,
      airAllowed: true,
      notes: "Upward arc cast.",
    }),
    v("magic", 3, {
      clip: "HarthmereBodyMagicCast_Variation3_24",
      windupFrame: 4,
      impactFrame: 10,
      recoveryFrame: 19,
      stance: "neutral",
      leadFoot: "right",
      attackSide: "center",
      arc: "cast_forward",
      torsoYawDeg: -3,
      shoulderYawDeg: 8,
      weaponYawBiasDeg: -8,
      weaponPitchBiasDeg: 2,
      locomotionAllowed: true,
      airAllowed: true,
      notes: "Side-snap cast.",
    }),
    v("magic", 4, {
      clip: "HarthmereBodyMagicCast_Variation4_24",
      windupFrame: 6,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "forward",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "thrust",
      torsoYawDeg: 0,
      shoulderYawDeg: 12,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -6,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Committed burst release.",
    }),
  ],
  rangedRelease: [
    v("rangedRelease", 1, {
      clip: "HarthmereBodyRangedRelease_Variation1_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "forward",
      leadFoot: "left",
      attackSide: "right",
      arc: "cast_forward",
      torsoYawDeg: 0,
      shoulderYawDeg: 8,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -3,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Square release.",
    }),
    v("rangedRelease", 2, {
      clip: "HarthmereBodyRangedRelease_Variation2_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "open",
      leadFoot: "balanced",
      attackSide: "right",
      arc: "cast_forward",
      torsoYawDeg: 5,
      shoulderYawDeg: 10,
      weaponYawBiasDeg: 5,
      weaponPitchBiasDeg: -1,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Open-stance release.",
    }),
    v("rangedRelease", 3, {
      clip: "HarthmereBodyRangedRelease_Variation3_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "closed",
      leadFoot: "right",
      attackSide: "right",
      arc: "cast_forward",
      torsoYawDeg: -5,
      shoulderYawDeg: 11,
      weaponYawBiasDeg: -5,
      weaponPitchBiasDeg: -2,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Closed-stance snap release.",
    }),
    v("rangedRelease", 4, {
      clip: "HarthmereBodyRangedRelease_Variation4_24",
      windupFrame: 7,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "low",
      leadFoot: "balanced",
      attackSide: "right",
      arc: "cast_up",
      torsoYawDeg: 0,
      shoulderYawDeg: 9,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -8,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Elevated/lofted release.",
    }),
  ],
  shieldBash: [
    v("shieldBash", 1, {
      clip: "HarthmereBodyShieldBash_Variation1_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "forward",
      leadFoot: "left",
      attackSide: "left",
      arc: "thrust",
      torsoYawDeg: -4,
      shoulderYawDeg: -10,
      weaponYawBiasDeg: -4,
      weaponPitchBiasDeg: -2,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Short forward shield jab.",
    }),
    v("shieldBash", 2, {
      clip: "HarthmereBodyShieldBash_Variation2_24",
      windupFrame: 6,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "closed",
      leadFoot: "right",
      attackSide: "left",
      arc: "high_left",
      torsoYawDeg: -8,
      shoulderYawDeg: -14,
      weaponYawBiasDeg: -10,
      weaponPitchBiasDeg: -4,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Hooking left bash.",
    }),
    v("shieldBash", 3, {
      clip: "HarthmereBodyShieldBash_Variation3_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "open",
      leadFoot: "balanced",
      attackSide: "left",
      arc: "low_left",
      torsoYawDeg: -5,
      shoulderYawDeg: -12,
      weaponYawBiasDeg: -8,
      weaponPitchBiasDeg: 5,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Rising shield bump.",
    }),
    v("shieldBash", 4, {
      clip: "HarthmereBodyShieldBash_Variation4_24",
      windupFrame: 7,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "forward",
      leadFoot: "left",
      attackSide: "left",
      arc: "overhead",
      torsoYawDeg: -3,
      shoulderYawDeg: -12,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -8,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Downward slam bash.",
    }),
  ],
  toolUse: [
    v("toolUse", 1, {
      clip: "HarthmereBodyToolUse_Variation1_24",
      windupFrame: 5,
      impactFrame: 12,
      recoveryFrame: 20,
      stance: "forward",
      leadFoot: "left",
      attackSide: "right",
      arc: "overhead",
      torsoYawDeg: 0,
      shoulderYawDeg: 13,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: -16,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Direct overhead tool strike.",
    }),
    v("toolUse", 2, {
      clip: "HarthmereBodyToolUse_Variation2_24",
      windupFrame: 5,
      impactFrame: 11,
      recoveryFrame: 19,
      stance: "open",
      leadFoot: "right",
      attackSide: "right",
      arc: "high_right",
      torsoYawDeg: -6,
      shoulderYawDeg: 14,
      weaponYawBiasDeg: -10,
      weaponPitchBiasDeg: -8,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Right-angled tool chop.",
    }),
    v("toolUse", 3, {
      clip: "HarthmereBodyToolUse_Variation3_24",
      windupFrame: 4,
      impactFrame: 10,
      recoveryFrame: 18,
      stance: "closed",
      leadFoot: "left",
      attackSide: "right",
      arc: "high_left",
      torsoYawDeg: 5,
      shoulderYawDeg: 12,
      weaponYawBiasDeg: 10,
      weaponPitchBiasDeg: -8,
      locomotionAllowed: false,
      airAllowed: false,
      notes: "Backhand tool strike.",
    }),
    v("toolUse", 4, {
      clip: "HarthmereBodyToolUse_Variation4_24",
      windupFrame: 6,
      impactFrame: 13,
      recoveryFrame: 21,
      stance: "low",
      leadFoot: "balanced",
      attackSide: "center",
      arc: "thrust",
      torsoYawDeg: 0,
      shoulderYawDeg: 8,
      weaponYawBiasDeg: 0,
      weaponPitchBiasDeg: 4,
      locomotionAllowed: true,
      airAllowed: false,
      notes: "Forward poke/chisel strike.",
    }),
  ],
} as const;

export function pickHarthmereAttackVariation(
  family: HarthmereAttackFamily,
  history: readonly string[],
  preferredSide?: "left" | "right" | "center"
): HarthmereAttackVariation {
  const variants = HARTHMERE_ATTACK_VARIATIONS[family];
  const last = history[history.length - 1];
  const prior = history[history.length - 2];
  const candidates = variants.filter(
    (variant) => variant.id !== last && variant.id !== prior
  );
  const sided = preferredSide
    ? candidates.filter((variant) => variant.attackSide === preferredSide)
    : candidates;
  const pool = sided.length
    ? sided
    : candidates.length
      ? candidates
      : variants.filter((v) => v.id !== last);
  return pool[0] || variants[0];
}

export const HARTHMERE_ATTACK_VARIATION_SEQUENCE_VERSION =
  "harthmere-attack-variation-sequencing";
