// Generated by harthmere-body-weapon-aligned-clips-v8.
// Production contract for body animations that visually sync with held weapons/items.

export const HARTHMERE_BODY_WEAPON_ANIMATION_SYNC_VERSION_V8 = "harthmere-body-weapon-aligned-clips-v8";
export const HARTHMERE_BODY_WEAPON_ALIGNED_FRAME_COUNT_V8 = 30;
export const HARTHMERE_BODY_WEAPON_ALIGNED_FPS_V8 = 30;

export const HARTHMERE_BODY_VARIANT_TYPES_V8 = [
  "average", "slim", "broad", "stocky", "athletic", "soft",
] as const;

export const HARTHMERE_BODY_VARIANT_COLORS_V8 = [
  "earth", "forest", "river", "ember", "royal", "ash",
] as const;

export const HARTHMERE_BODY_WEAPON_ALIGNED_CLIPS_V8 = [
  "HarthmereBodyWeaponIdleDrawn_Aligned_30",
  "HarthmereBodyWeaponBasic_Aligned_30",
  "HarthmereBodyWeaponHeavy_Aligned_30",
  "HarthmereBodyWeaponDraw_Aligned_30",
  "HarthmereBodyWeaponSheathe_Aligned_30",
  "HarthmereBodyWeaponBlock_Aligned_30",
  "HarthmereBodyShieldBash_Aligned_30",
  "HarthmereBodyRangedDraw_Aligned_30",
  "HarthmereBodyRangedRelease_Aligned_30",
  "HarthmereBodyRangedReload_Aligned_30",
  "HarthmereBodyMagicCast_Aligned_30",
  "HarthmereBodyMagicChannel_Aligned_30",
  "HarthmereBodyToolUse_Aligned_30",
  "HarthmereBodyToolHeavyUse_Aligned_30",
  "HarthmereBodyItemUse_Aligned_30"
] as const;

export const HARTHMERE_BODY_WEAPON_PROFILE_CLIPS_V8 = {
  melee: {
    idleDrawn: "HarthmereBodyWeaponIdleDrawn_Aligned_30",
    draw: "HarthmereBodyWeaponDraw_Aligned_30",
    sheathe: "HarthmereBodyWeaponSheathe_Aligned_30",
    basic: "HarthmereBodyWeaponBasic_Aligned_30",
    heavy: "HarthmereBodyWeaponHeavy_Aligned_30",
  },
  ranged: {
    drawAim: "HarthmereBodyRangedDraw_Aligned_30",
    release: "HarthmereBodyRangedRelease_Aligned_30",
    reload: "HarthmereBodyRangedReload_Aligned_30",
  },
  magic: {
    cast: "HarthmereBodyMagicCast_Aligned_30",
    channel: "HarthmereBodyMagicChannel_Aligned_30",
  },
  shield: {
    block: "HarthmereBodyWeaponBlock_Aligned_30",
    bash: "HarthmereBodyShieldBash_Aligned_30",
  },
  tool: {
    use: "HarthmereBodyToolUse_Aligned_30",
    heavyUse: "HarthmereBodyToolHeavyUse_Aligned_30",
  },
  item: {
    use: "HarthmereBodyItemUse_Aligned_30",
  },
} as const;

export const HARTHMERE_GAMEPLAY_ITEM_BODY_PROFILE_V8 = {
  training_dagger: "melee",
  iron_longsword: "melee",
  woodsman_axe: "melee",
  two_handed_sword: "melee",
  wooden_shield: "shield",
  bow: "ranged",
  crossbow_1handed: "ranged",
  crossbow_2handed: "ranged",
  staff: "magic",
  wand: "magic",
  spellbook_open: "magic",
  spellbook_closed: "magic",
  pickaxe: "tool",
  Pickaxe_Bronze: "tool",
  Axe_Bronze: "tool",
  Apple: "item",
  Potion_1: "item",
  ChickenLeg: "item",
} as const;

export const HARTHMERE_BODY_WEAPON_SYNC_EDGE_CASES_V8 = [
  "all body size variants use identical clip names",
  "all body color variants use identical clip names",
  "legacy Attack/HeavyAttack remain fallbacks for non-Harthmere bodies",
  "hips/root translation is locked in aligned clips",
  "chest rotation is subtle to avoid full-body tumble",
  "weapons/items are upper-body overlays while locomotion owns lower body",
  "impactFrame metadata is present for gameplay timing",
  "tools, consumables, ranged, magic, shield, and melee profiles are covered",
] as const;
