import {
  harthmereBossVisualForEntity,
  harthmereBossVisualForLabel,
  type HarthmereBossVisualId,
} from "@/shared/harthmere/boss_visual_assets";
import { getHarthmereProjectileVisual } from "@/shared/harthmere/projectile_visual_manifest";
import type { BehaviorRangedAttackParams } from "@/shared/npc/npc_types";

export const HARTHMERE_BOSS_ATTACK_CATALOG_VERSION =
  "harthmere-boss-attack-catalog-v1" as const;

export const HARTHMERE_BOSS_MINIMUM_TELEGRAPH_SECS = Object.freeze({
  projectile: 0.9,
  beam: 0.85,
  ground_aoe: 1.1,
  self_aoe: 0.9,
  cone: 0.9,
} satisfies Record<NonNullable<BehaviorRangedAttackParams["attackShape"]>, number>);

export interface HarthmereBossAttackDefinition
  extends BehaviorRangedAttackParams {
  displayName: string;
  attackShape: NonNullable<BehaviorRangedAttackParams["attackShape"]>;
  damageType: NonNullable<BehaviorRangedAttackParams["damageType"]>;
  animationClip: NonNullable<BehaviorRangedAttackParams["animationClip"]>;
  lore: string;
}

export interface HarthmereBossNativeCombatTuning {
  bossId: HarthmereBossVisualId;
  level: number;
  maxHp: number;
  attackDamage: number;
  attackDistance: number;
  attackIntervalSecs: number;
  attackStrikeMomentSecs: number;
  attackFovDeg: number;
  aggroTrigger: "proximity" | "onlyIfAttacked";
  aggroDistance: number;
  disengageDistance: number;
  walkSpeed: number;
  runSpeed: number;
  rotateSpeed: number;
  attacks: readonly HarthmereBossAttackDefinition[];
}

type AttackInput = Omit<HarthmereBossAttackDefinition, "projectileVisualId"> & {
  projectileVisualId: string;
};

function attack(input: AttackInput): HarthmereBossAttackDefinition {
  const projectileVisualId =
    getHarthmereProjectileVisual(input.projectileVisualId)?.id ??
    input.projectileVisualId;
  return Object.freeze({
    ...input,
    projectileVisualId,
    castTimeSecs: Math.max(
      input.castTimeSecs,
      HARTHMERE_BOSS_MINIMUM_TELEGRAPH_SECS[input.attackShape]
    ),
  });
}

const catalogs: Readonly<
  Record<HarthmereBossVisualId, HarthmereBossNativeCombatTuning>
> = Object.freeze({
  muck_scarred_helix: {
    bossId: "muck_scarred_helix",
    level: 5,
    maxHp: 1800,
    attackDamage: 140,
    attackDistance: 4.2,
    attackIntervalSecs: 1.8,
    attackStrikeMomentSecs: 0.48,
    attackFovDeg: 170,
    aggroTrigger: "proximity",
    aggroDistance: 20,
    disengageDistance: 44,
    walkSpeed: 2.2,
    runSpeed: 4.6,
    rotateSpeed: 235,
    attacks: [
      attack({
        abilityId: "helix_maul_crush",
        displayName: "Maul Crush",
        lore: "The scar-grown demolition limb pounds the breach floor around the Helix.",
        projectileVisualId: "nova_cannon_bolt",
        attackShape: "self_aoe",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "MaulCrush",
        minimumDistance: 0,
        attackDistance: 5.2,
        attackDamage: 125,
        castTimeSecs: 0.8,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.9,
        hitRadius: 4.3,
      }),
      attack({
        abilityId: "helix_siphon_volley",
        displayName: "Siphon Volley",
        lore: "The radial maw spits stolen breach-energy in a life-draining bolt.",
        projectileVisualId: "life_drain",
        attackShape: "projectile",
        damageType: "dark",
        animationClip: "RangedAttack",
        specialAnimationClip: "SiphonVolley",
        minimumDistance: 4,
        attackDistance: 22,
        attackDamage: 88,
        castTimeSecs: 0.72,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.9,
        hitRadius: 1.35,
      }),
      attack({
        abilityId: "helix_resonance_pulse",
        displayName: "Helix Pulse",
        lore: "The exposed double helix aligns and releases a straight breach-resonance beam.",
        projectileVisualId: "helix_projector_beam",
        attackShape: "beam",
        damageType: "arcane",
        animationClip: "RangedAttack",
        specialAnimationClip: "HelixPulse",
        minimumDistance: 3,
        attackDistance: 24,
        attackDamage: 105,
        castTimeSecs: 0.95,
        cooldownSecs: 11,
        sharedCooldownSecs: 2,
        hitRadius: 1.1,
      }),
      attack({
        abilityId: "helix_spore_cast",
        displayName: "Spore Cast",
        lore: "Its back organs seed the target area with binding, Muck-fed growth.",
        projectileVisualId: "entangling_roots",
        attackShape: "ground_aoe",
        damageType: "nature",
        animationClip: "AreaAttack",
        specialAnimationClip: "SporeCast",
        minimumDistance: 2,
        attackDistance: 20,
        attackDamage: 76,
        castTimeSecs: 1.05,
        cooldownSecs: 12,
        sharedCooldownSecs: 2,
        hitRadius: 3.2,
      }),
      attack({
        abilityId: "helix_breach_rupture",
        displayName: "Breach Rupture",
        lore: "At low health the Helix tears open the scar beneath its prey.",
        projectileVisualId: "meteor",
        attackShape: "ground_aoe",
        damageType: "gravity",
        animationClip: "AreaAttack",
        specialAnimationClip: "Rupture",
        minimumDistance: 2,
        attackDistance: 24,
        attackDamage: 138,
        castTimeSecs: 1.35,
        cooldownSecs: 15,
        sharedCooldownSecs: 2.2,
        hitRadius: 4.1,
        maximumHealthRatio: 0.55,
      }),
    ],
  },
  gilded_bull: {
    bossId: "gilded_bull",
    level: 8,
    maxHp: 420,
    attackDamage: 28,
    attackDistance: 3.6,
    attackIntervalSecs: 1.9,
    attackStrikeMomentSecs: 0.5,
    attackFovDeg: 120,
    aggroTrigger: "proximity",
    aggroDistance: 24,
    disengageDistance: 44,
    walkSpeed: 2.1,
    runSpeed: 5.5,
    rotateSpeed: 220,
    attacks: [
      attack({
        abilityId: "bull_sun_court_charge",
        displayName: "Sun Court Charge",
        lore: "The guardian lowers its breakaway horns and drives down a narrow lane.",
        projectileVisualId: "aimed_shot",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "Charge",
        minimumDistance: 2,
        attackDistance: 15,
        attackDamage: 34,
        castTimeSecs: 0.75,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.7,
        hitRadius: 1,
        coneAngleDeg: 28,
      }),
      attack({
        abilityId: "bull_pillar_crash",
        displayName: "Pillar Crash",
        lore: "A piston kick sends old Sun Court masonry crashing onto the marked point.",
        projectileVisualId: "nova_cannon_bolt",
        attackShape: "ground_aoe",
        damageType: "physical",
        animationClip: "AreaAttack",
        specialAnimationClip: "PillarCrash",
        minimumDistance: 1,
        attackDistance: 17,
        attackDamage: 30,
        castTimeSecs: 1.05,
        cooldownSecs: 10,
        sharedCooldownSecs: 1.8,
        hitRadius: 3.1,
      }),
      attack({
        abilityId: "bull_sun_core_beam",
        displayName: "Sun-Core Beam",
        lore: "The two-hundred-year-old exotic-matter core vents a line of ceremonial sunfire.",
        projectileVisualId: "holy_light",
        attackShape: "beam",
        damageType: "holy",
        animationClip: "RangedAttack",
        specialAnimationClip: "SunCoreBeam",
        minimumDistance: 3,
        attackDistance: 22,
        attackDamage: 29,
        castTimeSecs: 0.9,
        cooldownSecs: 11,
        sharedCooldownSecs: 1.8,
        hitRadius: 1.05,
      }),
      attack({
        abilityId: "bull_hoof_quake",
        displayName: "Hoof Quake",
        lore: "Four bronze hooves strike together and turn the court floor into a shock ring.",
        projectileVisualId: "consecrate",
        attackShape: "self_aoe",
        damageType: "blunt",
        animationClip: "AreaAttack",
        specialAnimationClip: "HoofQuake",
        minimumDistance: 0,
        attackDistance: 6,
        attackDamage: 26,
        castTimeSecs: 0.85,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.8,
        hitRadius: 5.2,
      }),
      attack({
        abilityId: "bull_core_rupture",
        displayName: "Core Rupture",
        lore: "With both horns failing, the exposed core discharges unstable solar weight.",
        projectileVisualId: "meteor",
        attackShape: "ground_aoe",
        damageType: "fire",
        animationClip: "AreaAttack",
        specialAnimationClip: "CoreRupture",
        minimumDistance: 1,
        attackDistance: 20,
        attackDamage: 42,
        castTimeSecs: 1.25,
        cooldownSecs: 14,
        sharedCooldownSecs: 2,
        hitRadius: 4,
        maximumHealthRatio: 0.48,
      }),
    ],
  },
  ninth_winter: {
    bossId: "ninth_winter",
    level: 12,
    maxHp: 560,
    attackDamage: 32,
    attackDistance: 4,
    attackIntervalSecs: 2.1,
    attackStrikeMomentSecs: 0.62,
    attackFovDeg: 210,
    aggroTrigger: "proximity",
    aggroDistance: 28,
    disengageDistance: 52,
    walkSpeed: 1.4,
    runSpeed: 3.3,
    rotateSpeed: 150,
    attacks: [
      attack({
        abilityId: "winter_roofbeam_sweep",
        displayName: "Roofbeam Sweep",
        lore: "The walking hall swings its own frozen rafters through a broad arc.",
        projectileVisualId: "ranged_shot",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "RoofbeamSweep",
        minimumDistance: 0,
        attackDistance: 10,
        attackDamage: 38,
        castTimeSecs: 0.95,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.9,
        hitRadius: 1,
        coneAngleDeg: 95,
      }),
      attack({
        abilityId: "winter_failed_dawn_shard",
        displayName: "Failed-Dawn Shard",
        lore: "One unfinished morning hardens into a blue-white spear of winter magic.",
        projectileVisualId: "spark",
        attackShape: "projectile",
        damageType: "ice",
        animationClip: "RangedAttack",
        minimumDistance: 3,
        attackDistance: 23,
        attackDamage: 31,
        castTimeSecs: 0.8,
        cooldownSecs: 8.5,
        sharedCooldownSecs: 1.9,
        hitRadius: 1.2,
      }),
      attack({
        abilityId: "winter_blizzard",
        displayName: "Blizzard",
        lore: "Ash snow and nine years of stalled weather descend on the chosen ground.",
        projectileVisualId: "curse_of_weakness",
        attackShape: "ground_aoe",
        damageType: "ice",
        animationClip: "AreaAttack",
        specialAnimationClip: "Blizzard",
        minimumDistance: 1,
        attackDistance: 24,
        attackDamage: 29,
        castTimeSecs: 1.15,
        cooldownSecs: 11,
        sharedCooldownSecs: 2,
        hitRadius: 4.2,
      }),
      attack({
        abilityId: "winter_same_day_again",
        displayName: "Same Day Again",
        lore: "The stalled year repeats the target's last instant as a cutting arcane echo.",
        projectileVisualId: "polymorph",
        attackShape: "beam",
        damageType: "arcane",
        animationClip: "RangedAttack",
        specialAnimationClip: "TimeLoop",
        minimumDistance: 2,
        attackDistance: 21,
        attackDamage: 27,
        castTimeSecs: 1.1,
        cooldownSecs: 12,
        sharedCooldownSecs: 2,
        hitRadius: 1.35,
      }),
      attack({
        abilityId: "winter_year_breaks",
        displayName: "The Year Breaks",
        lore: "When the ninth year finally cracks, the whole Ash Hall erupts in killing cold.",
        projectileVisualId: "singularity_lance_beam",
        attackShape: "self_aoe",
        damageType: "ice",
        animationClip: "AreaAttack",
        specialAnimationClip: "YearBreaks",
        minimumDistance: 0,
        attackDistance: 10,
        attackDamage: 49,
        castTimeSecs: 1.45,
        cooldownSecs: 15,
        sharedCooldownSecs: 2.2,
        hitRadius: 9,
        maximumHealthRatio: 0.32,
      }),
    ],
  },
  failed_apprentice: {
    bossId: "failed_apprentice",
    level: 14,
    maxHp: 760,
    attackDamage: 38,
    attackDistance: 3.5,
    attackIntervalSecs: 1.85,
    attackStrikeMomentSecs: 0.5,
    attackFovDeg: 175,
    aggroTrigger: "proximity",
    aggroDistance: 20,
    disengageDistance: 38,
    walkSpeed: 1.8,
    runSpeed: 4.2,
    rotateSpeed: 210,
    attacks: [
      attack({
        abilityId: "apprentice_bell_fist",
        displayName: "Bell-Fist",
        lore: "The broken Apprentice's Bell becomes a bronze striking hand.",
        projectileVisualId: "judgment",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "BellFist",
        minimumDistance: 0,
        attackDistance: 6,
        attackDamage: 44,
        castTimeSecs: 0.7,
        cooldownSecs: 7,
        sharedCooldownSecs: 1.7,
        hitRadius: 1,
        coneAngleDeg: 70,
      }),
      attack({
        abilityId: "apprentice_shard_cast",
        displayName: "Shard Cast",
        lore: "Failed-binding fragments orbit once, then spear toward the intruder.",
        projectileVisualId: "hex_bolt",
        attackShape: "projectile",
        damageType: "arcane",
        animationClip: "RangedAttack",
        specialAnimationClip: "ShardCast",
        minimumDistance: 3,
        attackDistance: 20,
        attackDamage: 36,
        castTimeSecs: 0.65,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.7,
        hitRadius: 1.1,
      }),
      attack({
        abilityId: "apprentice_failed_ward",
        displayName: "Failed Ward",
        lore: "A protection lesson collapses outward as hostile dark magic.",
        projectileVisualId: "curse_of_weakness",
        attackShape: "self_aoe",
        damageType: "dark",
        animationClip: "AreaAttack",
        specialAnimationClip: "FailedWard",
        minimumDistance: 0,
        attackDistance: 6,
        attackDamage: 32,
        castTimeSecs: 0.9,
        cooldownSecs: 10,
        sharedCooldownSecs: 1.8,
        hitRadius: 5.4,
      }),
      attack({
        abilityId: "apprentice_wrong_note",
        displayName: "Wrong Note",
        lore: "The cracked bell rings a note the binding was never meant to contain.",
        projectileVisualId: "mocking_verse",
        attackShape: "ground_aoe",
        damageType: "sonic",
        animationClip: "AreaAttack",
        specialAnimationClip: "WrongNote",
        minimumDistance: 2,
        attackDistance: 22,
        attackDamage: 35,
        castTimeSecs: 1,
        cooldownSecs: 11,
        sharedCooldownSecs: 1.9,
        hitRadius: 3.4,
      }),
      attack({
        abilityId: "apprentice_last_lesson",
        displayName: "Last Lesson",
        lore: "At the end, every unfinished lesson is forced through the bell at once.",
        projectileVisualId: "thaedryn_resonance",
        attackShape: "beam",
        damageType: "arcane",
        animationClip: "RangedAttack",
        specialAnimationClip: "LastLesson",
        minimumDistance: 2,
        attackDistance: 24,
        attackDamage: 55,
        castTimeSecs: 1.2,
        cooldownSecs: 14,
        sharedCooldownSecs: 2.1,
        hitRadius: 1.6,
        maximumHealthRatio: 0.38,
      }),
    ],
  },
  first_choir: {
    bossId: "first_choir",
    level: 15,
    maxHp: 900,
    attackDamage: 36,
    attackDistance: 3.5,
    attackIntervalSecs: 1.9,
    attackStrikeMomentSecs: 0.52,
    attackFovDeg: 220,
    aggroTrigger: "proximity",
    aggroDistance: 22,
    disengageDistance: 42,
    walkSpeed: 1.5,
    runSpeed: 3.8,
    rotateSpeed: 185,
    attacks: [
      attack({
        abilityId: "choir_crone_rebuke",
        displayName: "Crone's Rebuke",
        lore: "The eldest spirit turns a chapel admonition into a wave of dread.",
        projectileVisualId: "fear",
        attackShape: "ground_aoe",
        damageType: "dark",
        animationClip: "RangedAttack",
        specialAnimationClip: "Chant",
        minimumDistance: 2,
        attackDistance: 22,
        attackDamage: 34,
        castTimeSecs: 0.95,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.8,
        hitRadius: 3.2,
      }),
      attack({
        abilityId: "choir_stonemason_toll",
        displayName: "Stonemason's Toll",
        lore: "The mason spirit strikes an invisible foundation bell through the front rank.",
        projectileVisualId: "judgment",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        minimumDistance: 0,
        attackDistance: 8,
        attackDamage: 42,
        castTimeSecs: 0.75,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.8,
        hitRadius: 1,
        coneAngleDeg: 82,
      }),
      attack({
        abilityId: "choir_apprentice_false_note",
        displayName: "Apprentice's False Note",
        lore: "The youngest voice launches a bright, eager note that lands subtly wrong.",
        projectileVisualId: "mocking_verse",
        attackShape: "projectile",
        damageType: "sonic",
        animationClip: "RangedAttack",
        specialAnimationClip: "Chant",
        minimumDistance: 3,
        attackDistance: 21,
        attackDamage: 31,
        castTimeSecs: 0.62,
        cooldownSecs: 7.5,
        sharedCooldownSecs: 1.8,
        hitRadius: 1.15,
      }),
      attack({
        abilityId: "choir_threefold_canon",
        displayName: "Threefold Canon",
        lore: "All three Bellbinders overlap their lines into a spreading magical canon.",
        projectileVisualId: "multi_shot",
        attackShape: "ground_aoe",
        damageType: "sonic",
        animationClip: "Summon",
        specialAnimationClip: "Chant",
        minimumDistance: 1,
        attackDistance: 23,
        attackDamage: 38,
        castTimeSecs: 1.1,
        cooldownSecs: 11,
        sharedCooldownSecs: 2,
        hitRadius: 3.7,
      }),
      attack({
        abilityId: "choir_harmony_break",
        displayName: "Harmony Break",
        lore: "Their shared spectral bell fractures its harmony in every direction.",
        projectileVisualId: "thaedryn_resonance",
        attackShape: "self_aoe",
        damageType: "arcane",
        animationClip: "AreaAttack",
        specialAnimationClip: "HarmonyBreak",
        minimumDistance: 0,
        attackDistance: 9,
        attackDamage: 52,
        castTimeSecs: 1.25,
        cooldownSecs: 14,
        sharedCooldownSecs: 2.1,
        hitRadius: 8,
        maximumHealthRatio: 0.45,
      }),
    ],
  },
  echo_singer: {
    bossId: "echo_singer",
    level: 18,
    maxHp: 1100,
    attackDamage: 44,
    attackDistance: 4,
    attackIntervalSecs: 1.7,
    attackStrikeMomentSecs: 0.45,
    attackFovDeg: 200,
    aggroTrigger: "proximity",
    aggroDistance: 24,
    disengageDistance: 44,
    walkSpeed: 2,
    runSpeed: 4.8,
    rotateSpeed: 240,
    attacks: [
      attack({
        abilityId: "echo_copy_melee",
        displayName: "Copy Melee",
        lore: "The Singer reflects the player's last close strike through mirrored tuning blades.",
        projectileVisualId: "quick_shot",
        attackShape: "cone",
        damageType: "slashing",
        animationClip: "HeavyAttack",
        specialAnimationClip: "CopyMelee",
        minimumDistance: 0,
        attackDistance: 7,
        attackDamage: 47,
        castTimeSecs: 0.55,
        cooldownSecs: 7,
        sharedCooldownSecs: 1.55,
        hitRadius: 1,
        coneAngleDeg: 76,
      }),
      attack({
        abilityId: "echo_copy_ranged",
        displayName: "Copy Ranged",
        lore: "A mirrored mask reproduces the player's projectile with impossible precision.",
        projectileVisualId: "aimed_shot",
        attackShape: "projectile",
        damageType: "piercing",
        animationClip: "RangedAttack",
        specialAnimationClip: "CopyRanged",
        minimumDistance: 3,
        attackDistance: 24,
        attackDamage: 40,
        castTimeSecs: 0.62,
        cooldownSecs: 7.5,
        sharedCooldownSecs: 1.55,
        hitRadius: 0.95,
      }),
      attack({
        abilityId: "echo_copy_magic",
        displayName: "Copy Magic",
        lore: "The third mask samples the strongest nearby spell and returns an arcane imitation.",
        projectileVisualId: "spark",
        attackShape: "beam",
        damageType: "arcane",
        animationClip: "RangedAttack",
        minimumDistance: 2,
        attackDistance: 22,
        attackDamage: 43,
        castTimeSecs: 0.8,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.7,
        hitRadius: 1.15,
      }),
      attack({
        abilityId: "echo_delayed_refrain",
        displayName: "Echo Delay",
        lore: "A copied attack lands again at the place the target occupied a heartbeat earlier.",
        projectileVisualId: "mocking_verse",
        attackShape: "ground_aoe",
        damageType: "sonic",
        animationClip: "AreaAttack",
        specialAnimationClip: "EchoDelay",
        minimumDistance: 1,
        attackDistance: 23,
        attackDamage: 39,
        castTimeSecs: 1.15,
        cooldownSecs: 10,
        sharedCooldownSecs: 1.8,
        hitRadius: 3.1,
      }),
      attack({
        abilityId: "echo_resonance_overload",
        displayName: "Resonance Overload",
        lore: "Every incomplete silhouette snaps into alignment and screams outward.",
        projectileVisualId: "thaedryn_resonance",
        attackShape: "self_aoe",
        damageType: "sonic",
        animationClip: "AreaAttack",
        specialAnimationClip: "ResonanceOverload",
        minimumDistance: 0,
        attackDistance: 9,
        attackDamage: 61,
        castTimeSecs: 1.15,
        cooldownSecs: 14,
        sharedCooldownSecs: 2,
        hitRadius: 8,
        maximumHealthRatio: 0.4,
      }),
    ],
  },
  vyrahel_vein_keeper: {
    bossId: "vyrahel_vein_keeper",
    level: 24,
    maxHp: 1800,
    attackDamage: 56,
    attackDistance: 4.2,
    attackIntervalSecs: 1.55,
    attackStrikeMomentSecs: 0.4,
    attackFovDeg: 180,
    aggroTrigger: "proximity",
    aggroDistance: 25,
    disengageDistance: 48,
    walkSpeed: 2.8,
    runSpeed: 6.2,
    rotateSpeed: 280,
    attacks: [
      attack({
        abilityId: "vyrahel_tail_feint",
        displayName: "Tail Feint",
        lore: "A clever half-turn hides the real mineral-tail strike until the last instant.",
        projectileVisualId: "quick_shot",
        attackShape: "cone",
        damageType: "slashing",
        animationClip: "Attack",
        specialAnimationClip: "TailFeint",
        minimumDistance: 0,
        attackDistance: 7,
        attackDamage: 58,
        castTimeSecs: 0.45,
        cooldownSecs: 6.5,
        sharedCooldownSecs: 1.45,
        hitRadius: 1,
        coneAngleDeg: 88,
      }),
      attack({
        abilityId: "vyrahel_vein_breath",
        displayName: "Vein Breath",
        lore: "The wyrmling exhales the heat and pressure carried in the mountain's living veins.",
        projectileVisualId: "fireball",
        attackShape: "cone",
        damageType: "fire",
        animationClip: "RangedAttack",
        specialAnimationClip: "VeinBreath",
        minimumDistance: 1,
        attackDistance: 15,
        attackDamage: 53,
        castTimeSecs: 0.75,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.55,
        hitRadius: 1,
        coneAngleDeg: 46,
      }),
      attack({
        abilityId: "vyrahel_wing_burst",
        displayName: "Wing Burst",
        lore: "Crystal-edged braking wings release a ring of charged stone dust.",
        projectileVisualId: "lightning_bolt",
        attackShape: "self_aoe",
        damageType: "lightning",
        animationClip: "Jump",
        specialAnimationClip: "WingBurst",
        minimumDistance: 0,
        attackDistance: 7,
        attackDamage: 48,
        castTimeSecs: 0.65,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.6,
        hitRadius: 6.2,
      }),
      attack({
        abilityId: "vyrahel_burrow_rush",
        displayName: "Burrow Rush",
        lore: "Digging claws vanish into the vein floor before erupting beneath the marked ground.",
        projectileVisualId: "entangling_roots",
        attackShape: "ground_aoe",
        damageType: "nature",
        animationClip: "Jump",
        specialAnimationClip: "BurrowRush",
        minimumDistance: 2,
        attackDistance: 21,
        attackDamage: 57,
        castTimeSecs: 0.95,
        cooldownSecs: 10,
        sharedCooldownSecs: 1.7,
        hitRadius: 3.3,
      }),
      attack({
        abilityId: "vyrahel_crystal_guard_shatter",
        displayName: "Crystal Guard Shatter",
        lore: "The shoulder shields flare defensively, then cast their stored force back as shards.",
        projectileVisualId: "judgment",
        attackShape: "beam",
        damageType: "arcane",
        animationClip: "HeavyAttack",
        specialAnimationClip: "CrystalGuard",
        minimumDistance: 2,
        attackDistance: 23,
        attackDamage: 69,
        castTimeSecs: 1.05,
        cooldownSecs: 13,
        sharedCooldownSecs: 1.9,
        hitRadius: 1.45,
        maximumHealthRatio: 0.5,
      }),
    ],
  },
  thaedryn_bellbound: {
    bossId: "thaedryn_bellbound",
    level: 30,
    maxHp: 4000,
    attackDamage: 160,
    attackDistance: 8,
    attackIntervalSecs: 1.8,
    attackStrikeMomentSecs: 0.5,
    attackFovDeg: 220,
    aggroTrigger: "onlyIfAttacked",
    aggroDistance: 0,
    disengageDistance: 64,
    walkSpeed: 0,
    runSpeed: 0,
    rotateSpeed: 210,
    attacks: [
      attack({
        abilityId: "thaedryn_sleeper_sweep",
        displayName: "Sleeper Sweep",
        lore: "Even half-asleep, Thaedryn's river-long tail clears a vast arc of the bed.",
        projectileVisualId: "judgment",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "SleeperSweep",
        minimumDistance: 0,
        attackDistance: 16,
        attackDamage: 145,
        castTimeSecs: 1,
        cooldownSecs: 8,
        sharedCooldownSecs: 2,
        hitRadius: 1,
        coneAngleDeg: 112,
      }),
      attack({
        abilityId: "thaedryn_sound_cloud",
        displayName: "Sound Cloud",
        lore: "Words learned in dreams thicken into a bell-pressure cloud over the chosen ground.",
        projectileVisualId: "mocking_verse",
        attackShape: "ground_aoe",
        damageType: "sonic",
        animationClip: "AreaAttack",
        specialAnimationClip: "SoundCloud",
        minimumDistance: 2,
        attackDistance: 30,
        attackDamage: 112,
        castTimeSecs: 1.15,
        cooldownSecs: 10,
        sharedCooldownSecs: 2,
        hitRadius: 5,
      }),
      attack({
        abilityId: "thaedryn_river_breath",
        displayName: "River-Force Breath",
        lore: "Thaedryn exhales the weight and direction of a buried river through the arena.",
        projectileVisualId: "thaedryn_resonance",
        attackShape: "cone",
        damageType: "arcane",
        animationClip: "RangedAttack",
        specialAnimationClip: "RiverBreath",
        minimumDistance: 1,
        attackDistance: 28,
        attackDamage: 132,
        castTimeSecs: 1.25,
        cooldownSecs: 11,
        sharedCooldownSecs: 2.1,
        hitRadius: 1,
        coneAngleDeg: 58,
      }),
      attack({
        abilityId: "thaedryn_wing_gust",
        displayName: "Cathedral Wing Gust",
        lore: "A folded vellum wing opens just far enough to hammer the chamber with air.",
        projectileVisualId: "lightning_bolt",
        attackShape: "self_aoe",
        damageType: "physical",
        animationClip: "AreaAttack",
        specialAnimationClip: "WingGust",
        minimumDistance: 0,
        attackDistance: 14,
        attackDamage: 118,
        castTimeSecs: 1,
        cooldownSecs: 12,
        sharedCooldownSecs: 2.1,
        hitRadius: 13,
        maximumHealthRatio: 0.76,
      }),
      attack({
        abilityId: "thaedryn_vein_call",
        displayName: "Vein Call",
        lore: "The Bellbound voice wakes the mineral veins beneath a marked quadrant.",
        projectileVisualId: "entangling_roots",
        attackShape: "ground_aoe",
        damageType: "nature",
        animationClip: "Summon",
        specialAnimationClip: "VeinSummon",
        minimumDistance: 2,
        attackDistance: 32,
        attackDamage: 156,
        castTimeSecs: 1.45,
        cooldownSecs: 15,
        sharedCooldownSecs: 2.3,
        hitRadius: 5.5,
        maximumHealthRatio: 0.52,
      }),
    ],
  },
  hex_wraith: {
    bossId: "hex_wraith",
    level: 18,
    maxHp: 1250,
    attackDamage: 52,
    attackDistance: 4.5,
    attackIntervalSecs: 1.75,
    attackStrikeMomentSecs: 0.5,
    attackFovDeg: 220,
    aggroTrigger: "proximity",
    aggroDistance: 27,
    disengageDistance: 52,
    walkSpeed: 2.2,
    runSpeed: 5,
    rotateSpeed: 250,
    attacks: [
      attack({
        abilityId: "hex_wraith_hex_volley",
        displayName: "Hex Volley",
        lore: "The orbiting tablets align and loose a grave-violet sequence of hunting sigils.",
        projectileVisualId: "hex_bolt",
        attackShape: "projectile",
        damageType: "dark",
        animationClip: "RangedAttack",
        specialAnimationClip: "HexVolley",
        minimumDistance: 3,
        attackDistance: 25,
        attackDamage: 49,
        castTimeSecs: 0.72,
        cooldownSecs: 7.5,
        sharedCooldownSecs: 1.65,
        hitRadius: 1.25,
      }),
      attack({
        abilityId: "hex_wraith_grave_violet_beam",
        displayName: "Grave-Violet Beam",
        lore: "Its lantern ribs focus a line of death-song through the nearest living voice.",
        projectileVisualId: "life_drain",
        attackShape: "beam",
        damageType: "dark",
        animationClip: "RangedAttack",
        minimumDistance: 2,
        attackDistance: 23,
        attackDamage: 58,
        castTimeSecs: 0.9,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.7,
        hitRadius: 1.2,
      }),
      attack({
        abilityId: "hex_wraith_lantern_rib_pulse",
        displayName: "Lantern-Rib Pulse",
        lore: "The hollow ribs toll without bells and push a ring of corpse-cold sound outward.",
        projectileVisualId: "mocking_verse",
        attackShape: "self_aoe",
        damageType: "sonic",
        animationClip: "AreaAttack",
        minimumDistance: 0,
        attackDistance: 8,
        attackDamage: 46,
        castTimeSecs: 0.9,
        cooldownSecs: 9.5,
        sharedCooldownSecs: 1.75,
        hitRadius: 7.2,
      }),
      attack({
        abilityId: "hex_wraith_tablet_prison",
        displayName: "Tablet Prison",
        lore: "Four funeral tablets nail a marked patch of ground beneath a closing sigil.",
        projectileVisualId: "curse_of_weakness",
        attackShape: "ground_aoe",
        damageType: "arcane",
        animationClip: "Summon",
        minimumDistance: 2,
        attackDistance: 22,
        attackDamage: 54,
        castTimeSecs: 1.1,
        cooldownSecs: 11,
        sharedCooldownSecs: 1.85,
        hitRadius: 3.5,
      }),
      attack({
        abilityId: "hex_wraith_phase_scythe",
        displayName: "Phase Scythe",
        lore: "The footless revenant vanishes through its target and leaves a crescent of severed song behind.",
        projectileVisualId: "judgment",
        attackShape: "cone",
        damageType: "dark",
        animationClip: "RangedAttack",
        specialAnimationClip: "Teleport",
        minimumDistance: 0,
        attackDistance: 9,
        attackDamage: 66,
        castTimeSecs: 0.9,
        cooldownSecs: 12,
        sharedCooldownSecs: 1.9,
        hitRadius: 1,
        coneAngleDeg: 88,
        maximumHealthRatio: 0.62,
      }),
    ],
  },
  alpha_mucker: {
    bossId: "alpha_mucker",
    level: 24,
    maxHp: 3200,
    attackDamage: 92,
    attackDistance: 9,
    attackIntervalSecs: 2.15,
    attackStrikeMomentSecs: 0.72,
    attackFovDeg: 210,
    aggroTrigger: "proximity",
    aggroDistance: 32,
    disengageDistance: 64,
    walkSpeed: 1.8,
    runSpeed: 3.6,
    rotateSpeed: 115,
    attacks: [
      attack({
        abilityId: "alpha_mucker_branch_slam",
        displayName: "Branch Slam",
        lore: "The Alpha drops both grasping boughs across the road in a crushing fan.",
        projectileVisualId: "nova_cannon_bolt",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        specialAnimationClip: "BranchSlam",
        minimumDistance: 0,
        attackDistance: 13,
        attackDamage: 105,
        castTimeSecs: 1.05,
        cooldownSecs: 8,
        sharedCooldownSecs: 2.05,
        hitRadius: 1,
        coneAngleDeg: 104,
      }),
      attack({
        abilityId: "alpha_mucker_seed_barrage",
        displayName: "Seed Barrage",
        lore: "The storm canopy shakes loose hardened Muck-seeds that hunt distant prey.",
        projectileVisualId: "multi_shot",
        attackShape: "projectile",
        damageType: "nature",
        animationClip: "RangedAttack",
        specialAnimationClip: "SeedBarrage",
        minimumDistance: 6,
        attackDistance: 30,
        attackDamage: 76,
        castTimeSecs: 0.9,
        cooldownSecs: 8.5,
        sharedCooldownSecs: 2.05,
        hitRadius: 1.8,
      }),
      attack({
        abilityId: "alpha_mucker_road_uproot",
        displayName: "Road Uproot",
        lore: "Root columns lever stolen road stone upward beneath the marked ground.",
        projectileVisualId: "meteor",
        attackShape: "ground_aoe",
        damageType: "physical",
        animationClip: "AreaAttack",
        specialAnimationClip: "RoadUproot",
        minimumDistance: 2,
        attackDistance: 27,
        attackDamage: 94,
        castTimeSecs: 1.25,
        cooldownSecs: 10,
        sharedCooldownSecs: 2.1,
        hitRadius: 4.8,
      }),
      attack({
        abilityId: "alpha_mucker_root_cage",
        displayName: "Root Cage",
        lore: "Taproots race beneath the soil and close around a chosen escape route.",
        projectileVisualId: "entangling_roots",
        attackShape: "ground_aoe",
        damageType: "nature",
        animationClip: "Summon",
        specialAnimationClip: "RootCage",
        minimumDistance: 3,
        attackDistance: 28,
        attackDamage: 82,
        castTimeSecs: 1.35,
        cooldownSecs: 12,
        sharedCooldownSecs: 2.15,
        hitRadius: 5.2,
      }),
      attack({
        abilityId: "alpha_mucker_muckheart_pulse",
        displayName: "Muckheart Pulse",
        lore: "The exposed crimson heart drives a black-sap shockwave through every root in reach.",
        projectileVisualId: "life_drain",
        attackShape: "self_aoe",
        damageType: "dark",
        animationClip: "AreaAttack",
        specialAnimationClip: "MuckheartPulse",
        minimumDistance: 0,
        attackDistance: 14,
        attackDamage: 128,
        castTimeSecs: 1.4,
        cooldownSecs: 15,
        sharedCooldownSecs: 2.3,
        hitRadius: 13.5,
        maximumHealthRatio: 0.52,
      }),
    ],
  },
  root_crowned_dead: {
    bossId: "root_crowned_dead",
    level: 26,
    maxHp: 2600,
    attackDamage: 62,
    attackDistance: 4.5,
    attackIntervalSecs: 1.9,
    attackStrikeMomentSecs: 0.55,
    attackFovDeg: 210,
    aggroTrigger: "proximity",
    aggroDistance: 30,
    disengageDistance: 58,
    walkSpeed: 1.6,
    runSpeed: 3.8,
    rotateSpeed: 165,
    attacks: [
      attack({
        abilityId: "root_dead_root_eruption",
        displayName: "Root Eruption",
        lore: "The dead forester's throne sends corrupted roots through the chosen soil.",
        projectileVisualId: "entangling_roots",
        attackShape: "ground_aoe",
        damageType: "nature",
        animationClip: "AreaAttack",
        specialAnimationClip: "RootEruption",
        minimumDistance: 1,
        attackDistance: 24,
        attackDamage: 58,
        castTimeSecs: 1,
        cooldownSecs: 8,
        sharedCooldownSecs: 1.8,
        hitRadius: 4.1,
      }),
      attack({
        abilityId: "root_dead_crown_sweep",
        displayName: "Crown Sweep",
        lore: "Antler-roots and branch arms rake a wide public-event front.",
        projectileVisualId: "ranged_shot",
        attackShape: "cone",
        damageType: "blunt",
        animationClip: "HeavyAttack",
        minimumDistance: 0,
        attackDistance: 10,
        attackDamage: 67,
        castTimeSecs: 0.75,
        cooldownSecs: 7,
        sharedCooldownSecs: 1.8,
        hitRadius: 1,
        coneAngleDeg: 105,
      }),
      attack({
        abilityId: "root_dead_grave_sap",
        displayName: "Grave Sap",
        lore: "The hollow chest draws warmth through the roots and returns it as necrotic sap.",
        projectileVisualId: "life_drain",
        attackShape: "beam",
        damageType: "dark",
        animationClip: "RangedAttack",
        minimumDistance: 3,
        attackDistance: 23,
        attackDamage: 55,
        castTimeSecs: 0.85,
        cooldownSecs: 9,
        sharedCooldownSecs: 1.9,
        hitRadius: 1.25,
      }),
      attack({
        abilityId: "root_dead_seed_barrage",
        displayName: "Crown-Seed Barrage",
        lore: "The root crown throws a hard cluster of blighted seeds at distant players.",
        projectileVisualId: "multi_shot",
        attackShape: "projectile",
        damageType: "nature",
        animationClip: "RangedAttack",
        minimumDistance: 4,
        attackDistance: 26,
        attackDamage: 52,
        castTimeSecs: 0.7,
        cooldownSecs: 8.5,
        sharedCooldownSecs: 1.9,
        hitRadius: 1.4,
      }),
      attack({
        abilityId: "root_dead_rootling_swarm",
        displayName: "Rootling Swarm",
        lore: "The throne shakes loose a ring of hungry rootling spirits around its bearer.",
        projectileVisualId: "curse_of_weakness",
        attackShape: "self_aoe",
        damageType: "nature",
        animationClip: "Summon",
        specialAnimationClip: "SpawnRootlings",
        minimumDistance: 0,
        attackDistance: 12,
        attackDamage: 79,
        castTimeSecs: 1.25,
        cooldownSecs: 14,
        sharedCooldownSecs: 2.1,
        hitRadius: 11,
        maximumHealthRatio: 0.55,
      }),
    ],
  },
});

export const HARTHMERE_FIVE_ATTACK_BOSS_IDS = Object.freeze(
  Object.keys(catalogs) as Array<keyof typeof catalogs>
);

export function harthmereBossNativeCombatTuningForLabel(
  label: string | undefined
): HarthmereBossNativeCombatTuning | undefined {
  const bossId = harthmereBossVisualForLabel(label)?.id;
  return bossId ? catalogs[bossId] : undefined;
}

export function harthmereBossNativeCombatTuningForBossId(
  bossId: HarthmereBossVisualId | undefined
): HarthmereBossNativeCombatTuning | undefined {
  return bossId ? catalogs[bossId] : undefined;
}

export function harthmereBossNativeCombatTuningForEntity(
  label: string | undefined,
  entityId: number | undefined
): HarthmereBossNativeCombatTuning | undefined {
  return harthmereBossNativeCombatTuningForBossId(
    harthmereBossVisualForEntity(label, entityId)?.id
  );
}

export function harthmereBossAttacksForLabel(label: string | undefined) {
  return harthmereBossNativeCombatTuningForLabel(label)?.attacks;
}

export function harthmereBossAttackForAbility(
  label: string | undefined,
  abilityId: string | undefined
) {
  if (!abilityId) return undefined;
  return harthmereBossAttacksForLabel(label)?.find(
    (candidate) => candidate.abilityId === abilityId
  );
}

export function validateHarthmereBossAttackCatalog() {
  const failures: string[] = [];
  const abilityIds = new Set<string>();
  const magicalDamageTypes = new Set([
    "fire",
    "ice",
    "lightning",
    "holy",
    "dark",
    "arcane",
    "nature",
    "sonic",
    "gravity",
  ]);
  for (const tuning of Object.values(catalogs)) {
    if (tuning.attacks.length !== 5) {
      failures.push(`${tuning.bossId} must have exactly five attacks`);
    }
    if (
      !tuning.attacks.some((candidate) =>
        magicalDamageTypes.has(candidate.damageType)
      )
    ) {
      failures.push(`${tuning.bossId} has no magical attack`);
    }
    for (const candidate of tuning.attacks) {
      if (abilityIds.has(candidate.abilityId)) {
        failures.push(`duplicate boss ability id ${candidate.abilityId}`);
      }
      abilityIds.add(candidate.abilityId);
      if (!getHarthmereProjectileVisual(candidate.projectileVisualId)) {
        failures.push(
          `${tuning.bossId}.${candidate.abilityId} has no projectile visual`
        );
      }
      if (
        candidate.attackShape === "cone" &&
        candidate.coneAngleDeg === undefined
      ) {
        failures.push(
          `${tuning.bossId}.${candidate.abilityId} cone is missing coneAngleDeg`
        );
      }
    }
  }
  return { ok: failures.length === 0, failures };
}
