/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Harthmere licensed clothing asset manifest v15.
 *
 * Generated by install-harthmere-clothing-assets-v15.sh.
 *
 * Purpose:
 * - Keep third-party clothing assets separate from procedural fallback clothing.
 * - Preserve license and attribution metadata next to every modelUrl.
 * - Give the v14 modular clothing runtime production asset candidates.
 *
 * Important production note:
 * Quaternius modular parts are enabled by default because they are CC0 and skinned modular glTF assets.
 * Sketchfab CC-BY assets are copied and listed, but disabled by default unless they are split/rigged/validated.
 */

export type HarthmereLicensedClothingLicense = {
  id: string;
  title: string;
  author: string;
  authorUrl: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
  creditRequired: boolean;
  commercialUseAllowed: boolean;
  creditLine: string;
  notes?: string;
};

export type HarthmereLicensedClothingItem = {
  id: string;
  displayName: string;
  slot: string;
  modelUrl: string;
  bindMode: string;
  attachBone?: string;
  hidesBodyZones?: readonly string[];
  faction?: string;
  rarity?: string;
  tags?: readonly string[];
  roles?: readonly string[];
  enabledByDefault?: boolean;
  productionState?: string;
  licenseId: string;
  sourceMeshNames?: readonly string[];
  sourceMaterialNames?: readonly string[];
  notes?: string;
};

export const HARTHMERE_CLOTHING_ASSET_MANIFEST_VERSION = "v15";

const HARTHMERE_CLOTHING_ASSET_LICENSES_INTERNAL = {
  "quaternius_fantasy_standard": {
    "id": "quaternius_fantasy_standard",
    "title": "Modular Character Outfits - Fantasy [Standard]",
    "author": "Quaternius",
    "authorUrl": "https://quaternius.com",
    "sourceUrl": "https://quaternius.com/packs/modularcharacteroutfitsfantasy.html",
    "license": "CC0-1.0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "creditRequired": false,
    "commercialUseAllowed": true,
    "creditLine": "Models by Quaternius, CC0 1.0 Universal.",
    "notes": "Standard free version. Readme says these outfits work with the Universal Base Character kit and only the head of the model is required; full body can clip."
  },
  "red_ilya_peasant_female_045592": {
    "id": "red_ilya_peasant_female_045592",
    "title": "Medieval Peasant Female Outfit Free",
    "author": "Red_Ilya",
    "authorUrl": "https://sketchfab.com/Red_Ilya",
    "sourceUrl": "https://sketchfab.com/3d-models/medieval-peasant-female-outfit-free-045592cd151a48da8ab025f980c6b709",
    "license": "CC-BY-4.0",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "creditRequired": true,
    "commercialUseAllowed": true,
    "creditLine": "This work is based on 'Medieval Peasant Female Outfit Free' by Red_Ilya, licensed under CC-BY-4.0.",
    "notes": "Static/non-skinned Sketchfab scene. Keep disabled by default until split/rigged or validated against Volex body scale."
  },
  "red_ilya_peasant_female_b4fd": {
    "id": "red_ilya_peasant_female_b4fd",
    "title": "Medieval Peasant Female Outfit Free",
    "author": "Red_Ilya",
    "authorUrl": "https://sketchfab.com/Red_Ilya",
    "sourceUrl": "https://sketchfab.com/3d-models/medieval-peasant-female-outfit-free-b4fd5481d71e498aa3fc234e8a2a091f",
    "license": "CC-BY-4.0",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "creditRequired": true,
    "commercialUseAllowed": true,
    "creditLine": "This work is based on 'Medieval Peasant Female Outfit Free' by Red_Ilya, licensed under CC-BY-4.0.",
    "notes": "Static/non-skinned Sketchfab scene. Keep disabled by default until split/rigged or validated against Volex body scale."
  },
  "red_ilya_medieval_clothing_free": {
    "id": "red_ilya_medieval_clothing_free",
    "title": "Medieval clothing Free",
    "author": "Red_Ilya",
    "authorUrl": "https://sketchfab.com/Red_Ilya",
    "sourceUrl": "https://sketchfab.com/3d-models/medieval-clothing-free-4df74f937a074e8daa9b512dc600422e",
    "license": "CC-BY-4.0",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "creditRequired": true,
    "commercialUseAllowed": true,
    "creditLine": "This work is based on 'Medieval clothing Free' by Red_Ilya, licensed under CC-BY-4.0.",
    "notes": "Static/non-skinned Sketchfab scene. Good source for retopology/rigging, not enabled by default."
  },
  "blue_spirit_medieval_armor_set": {
    "id": "blue_spirit_medieval_armor_set",
    "title": "Medieval Armor Set",
    "author": "Blue Spirit",
    "authorUrl": "https://sketchfab.com/Blue-Spirit",
    "sourceUrl": "https://sketchfab.com/3d-models/medieval-armor-set-2ee22efb91424935a633a735884f04a0",
    "license": "CC-BY-4.0",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "creditRequired": true,
    "commercialUseAllowed": true,
    "creditLine": "This work is based on 'Medieval Armor Set' by Blue Spirit, licensed under CC-BY-4.0.",
    "notes": "Static armor scene with separate meshes/materials. Strong candidate for manual splitting into torso, gloves, boots, legs, shoulder armor."
  },
  "calviking_armored_king": {
    "id": "calviking_armored_king",
    "title": "Armored King",
    "author": "Calviking073",
    "authorUrl": "https://sketchfab.com/Calviking073",
    "sourceUrl": "https://sketchfab.com/3d-models/armored-king-e3978fb660cf47278485d44eeba488ef",
    "license": "CC-BY-4.0",
    "licenseUrl": "http://creativecommons.org/licenses/by/4.0/",
    "creditRequired": true,
    "commercialUseAllowed": true,
    "creditLine": "This work is based on 'Armored King' by Calviking073, licensed under CC-BY-4.0.",
    "notes": "Skinned full character with animations. Use as boss/full-character reference or retargeted armor source, not as default modular clothing."
  }
} as const satisfies Record<string, HarthmereLicensedClothingLicense>;

export const HARTHMERE_CLOTHING_ASSET_LICENSES: Record<string, HarthmereLicensedClothingLicense> = HARTHMERE_CLOTHING_ASSET_LICENSES_INTERNAL;

export const HARTHMERE_LICENSED_CLOTHING_ASSETS = [
  {
    "id": "licensed.quaternius.female_peasant_arms",
    "displayName": "Female Peasant Arms",
    "slot": "hands",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Peasant_Arms.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms",
      "lowerArms",
      "hands"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_peasant_body",
    "displayName": "Female Peasant Body",
    "slot": "torsoOuter",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Peasant_Body.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_peasant_feet",
    "displayName": "Female Peasant Feet",
    "slot": "feet",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Peasant_Feet.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_peasant_legs",
    "displayName": "Female Peasant Legs",
    "slot": "legs",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Peasant_Legs.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "pelvis",
      "thighs",
      "calves"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_acc_pauldrons",
    "displayName": "Female Ranger Acc Pauldrons",
    "slot": "shoulders",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Acc_Pauldrons.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms"
    ],
    "faction": "harthmere",
    "rarity": "uncommon",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "ranger",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_arms",
    "displayName": "Female Ranger Arms",
    "slot": "hands",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Arms.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms",
      "lowerArms",
      "hands"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_body",
    "displayName": "Female Ranger Body",
    "slot": "torsoOuter",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Body.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_feet",
    "displayName": "Female Ranger Feet",
    "slot": "feet",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Feet.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_head_hood",
    "displayName": "Female Ranger Head Hood",
    "slot": "head",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Head_Hood.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "hair",
      "scalp"
    ],
    "faction": "harthmere",
    "rarity": "rare",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "hunter",
      "ranger",
      "guard",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger_legs",
    "displayName": "Female Ranger Legs",
    "slot": "legs",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Female_Ranger_Legs.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "pelvis",
      "thighs",
      "calves"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_peasant_arms",
    "displayName": "Male Peasant Arms",
    "slot": "hands",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Peasant_Arms.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms",
      "lowerArms",
      "hands"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_peasant_body",
    "displayName": "Male Peasant Body",
    "slot": "torsoOuter",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Peasant_Body.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_peasant_feet",
    "displayName": "Male Peasant Feet",
    "slot": "feet",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Peasant_Feet.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_peasant_legs",
    "displayName": "Male Peasant Legs",
    "slot": "legs",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Peasant_Legs.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "pelvis",
      "thighs",
      "calves"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "peasant",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_acc_pauldron",
    "displayName": "Male Ranger Acc Pauldron",
    "slot": "shoulders",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Acc_Pauldron.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms"
    ],
    "faction": "harthmere",
    "rarity": "uncommon",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "ranger",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_arms",
    "displayName": "Male Ranger Arms",
    "slot": "hands",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Arms.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperArms",
      "lowerArms",
      "hands"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_body",
    "displayName": "Male Ranger Body",
    "slot": "torsoOuter",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Body.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_feet_boots",
    "displayName": "Male Ranger Feet Boots",
    "slot": "feet",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Feet_Boots.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_head_hood",
    "displayName": "Male Ranger Head Hood",
    "slot": "head",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Head_Hood.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "hair",
      "scalp"
    ],
    "faction": "harthmere",
    "rarity": "rare",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "hunter",
      "ranger",
      "guard",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger_legs",
    "displayName": "Male Ranger Legs",
    "slot": "legs",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/modular_parts/Male_Ranger_Legs.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "pelvis",
      "thighs",
      "calves"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "modular"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": true,
    "productionState": "usable_modular_skinned",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_peasant",
    "displayName": "Female Peasant",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/outfits_reference/Female_Peasant.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "reference",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "peasant",
      "full_outfit",
      "reference_only"
    ],
    "roles": [],
    "enabledByDefault": false,
    "productionState": "reference_only_full_outfit",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.female_ranger",
    "displayName": "Female Ranger",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/outfits_reference/Female_Ranger.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "reference",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "female",
      "ranger",
      "full_outfit",
      "reference_only"
    ],
    "roles": [],
    "enabledByDefault": false,
    "productionState": "reference_only_full_outfit",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_peasant",
    "displayName": "Male Peasant",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/outfits_reference/Male_Peasant.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "reference",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "peasant",
      "full_outfit",
      "reference_only"
    ],
    "roles": [],
    "enabledByDefault": false,
    "productionState": "reference_only_full_outfit",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.quaternius.male_ranger",
    "displayName": "Male Ranger",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/quaternius_fantasy_standard/outfits_reference/Male_Ranger.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "reference",
    "tags": [
      "licensed",
      "cc0",
      "quaternius",
      "fantasy",
      "male",
      "ranger",
      "full_outfit",
      "reference_only"
    ],
    "roles": [],
    "enabledByDefault": false,
    "productionState": "reference_only_full_outfit",
    "licenseId": "quaternius_fantasy_standard"
  },
  {
    "id": "licensed.red.ilya.peasant.female.045592.femalePeasantDress",
    "displayName": "Medieval Peasant Female Outfit Free",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/sketchfab/red_ilya/peasant_female_045592/scene.gltf",
    "bindMode": "root",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc_by_4_0",
      "sketchfab",
      "femalePeasantDress",
      "reference_only_static_scene"
    ],
    "roles": [
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": false,
    "productionState": "reference_only_static_scene",
    "licenseId": "red_ilya_peasant_female_045592",
    "sourceMeshNames": [
      "9_1__0",
      "8_1__0",
      "7_1__0",
      "6_1__0",
      "4_1__0",
      "3_1__0",
      "2_1__0",
      "1_1__0"
    ],
    "sourceMaterialNames": [
      "Scene_-_Root"
    ],
    "notes": "Static/non-skinned Sketchfab scene. Keep disabled by default until split/rigged or validated against Volex body scale."
  },
  {
    "id": "licensed.red.ilya.peasant.female.b4fd.femalePeasantSuit",
    "displayName": "Medieval Peasant Female Outfit Free",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/sketchfab/red_ilya/peasant_female_b4fd/scene.gltf",
    "bindMode": "root",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc_by_4_0",
      "sketchfab",
      "femalePeasantSuit",
      "reference_only_static_scene"
    ],
    "roles": [
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": false,
    "productionState": "reference_only_static_scene",
    "licenseId": "red_ilya_peasant_female_b4fd",
    "sourceMeshNames": [
      "Suit__0"
    ],
    "sourceMaterialNames": [
      "Scene_-_Root"
    ],
    "notes": "Static/non-skinned Sketchfab scene. Keep disabled by default until split/rigged or validated against Volex body scale."
  },
  {
    "id": "licensed.red.ilya.medieval.clothing.free.medievalClothing",
    "displayName": "Medieval clothing Free",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/sketchfab/red_ilya/medieval_clothing_free/scene.gltf",
    "bindMode": "root",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "common",
    "tags": [
      "licensed",
      "cc_by_4_0",
      "sketchfab",
      "medievalClothing",
      "reference_only_static_scene"
    ],
    "roles": [
      "guard",
      "hunter",
      "farmer",
      "merchant",
      "townsperson",
      "player"
    ],
    "enabledByDefault": false,
    "productionState": "reference_only_static_scene",
    "licenseId": "red_ilya_medieval_clothing_free",
    "sourceMeshNames": [
      "1__0"
    ],
    "sourceMaterialNames": [
      "Scene_-_Root"
    ],
    "notes": "Static/non-skinned Sketchfab scene. Good source for retopology/rigging, not enabled by default."
  },
  {
    "id": "licensed.blue.spirit.medieval.armor.set.armorSet",
    "displayName": "Medieval Armor Set",
    "slot": "armorSet",
    "modelUrl": "/models/harthmere/clothing/sketchfab/blue_spirit/medieval_armor_set/scene.gltf",
    "bindMode": "root",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "rare",
    "tags": [
      "licensed",
      "cc_by_4_0",
      "sketchfab",
      "armorSet",
      "source_for_split_modular_armor"
    ],
    "roles": [
      "guard",
      "boss",
      "player"
    ],
    "enabledByDefault": false,
    "productionState": "source_for_split_modular_armor",
    "licenseId": "blue_spirit_medieval_armor_set",
    "sourceMeshNames": [
      "Chest Armor.002_CHest Armor belt_0",
      "Chest Armor.002_Chain Armor_0",
      "Chest Armor.002_Arm Cloths_0",
      "Chest Armor.002_Ticks_0",
      "Chest Armor.002_Gloves Plate_0",
      "Chest Armor.002_Gloves_0",
      "Chest Armor.002_Arm Pltaes_0",
      "Chest Armor.002_Shirt Arm_0",
      "Chest Armor.002_Large Belly Scarf_0",
      "Chest Armor.002_Pants_0",
      "Chest Armor.002_NeckHold_0",
      "Chest Armor.002_Large Belly Belt_0",
      "Chest Armor.002_Boots_0",
      "Chest Armor.002_Leg armor_0",
      "Chest Armor.002_Robe_0",
      "Chest Armor.002_Shoulder Armor_0"
    ],
    "sourceMaterialNames": [
      "CHest_Armor_belt",
      "Chain_Armor",
      "Arm_Cloths",
      "Ticks",
      "Gloves_Plate",
      "Gloves",
      "Arm_Pltaes",
      "Shirt_Arm",
      "Large_Belly_Scarf",
      "Pants",
      "NeckHold",
      "Large_Belly_Belt",
      "Boots",
      "Leg_armor",
      "Robe",
      "Shoulder_Armor"
    ],
    "notes": "Static armor scene with separate meshes/materials. Strong candidate for manual splitting into torso, gloves, boots, legs, shoulder armor."
  },
  {
    "id": "licensed.calviking.armored.king.armoredKing",
    "displayName": "Armored King",
    "slot": "fullOutfit",
    "modelUrl": "/models/harthmere/clothing/sketchfab/calviking073/armored_king/scene.gltf",
    "bindMode": "skinned",
    "hidesBodyZones": [
      "upperTorso",
      "lowerTorso",
      "upperArms",
      "lowerArms",
      "hands",
      "pelvis",
      "thighs",
      "calves",
      "feet"
    ],
    "faction": "harthmere",
    "rarity": "rare",
    "tags": [
      "licensed",
      "cc_by_4_0",
      "sketchfab",
      "armoredKing",
      "reference_only_full_character"
    ],
    "roles": [
      "boss",
      "guard"
    ],
    "enabledByDefault": false,
    "productionState": "reference_only_full_character",
    "licenseId": "calviking_armored_king",
    "sourceMeshNames": [
      "Object_0",
      "Object_1",
      "Object_2",
      "Object_3",
      "Object_4"
    ],
    "sourceMaterialNames": [
      "head",
      "body",
      "cloth",
      "helmet",
      "plume"
    ],
    "notes": "Skinned full character with animations. Use as boss/full-character reference or retargeted armor source, not as default modular clothing."
  }
] as const satisfies readonly HarthmereLicensedClothingItem[];

const HARTHMERE_ROLE_LICENSED_CLOTHING_DEFAULTS_INTERNAL = {
  "player": [
    "licensed.quaternius.female_peasant_arms",
    "licensed.quaternius.female_peasant_body",
    "licensed.quaternius.female_peasant_feet",
    "licensed.quaternius.female_peasant_legs",
    "licensed.quaternius.female_ranger_acc_pauldrons",
    "licensed.quaternius.female_ranger_arms",
    "licensed.quaternius.female_ranger_body",
    "licensed.quaternius.female_ranger_feet",
    "licensed.quaternius.female_ranger_head_hood",
    "licensed.quaternius.female_ranger_legs",
    "licensed.quaternius.male_peasant_arms",
    "licensed.quaternius.male_peasant_body",
    "licensed.quaternius.male_peasant_feet",
    "licensed.quaternius.male_peasant_legs",
    "licensed.quaternius.male_ranger_acc_pauldron",
    "licensed.quaternius.male_ranger_arms",
    "licensed.quaternius.male_ranger_body",
    "licensed.quaternius.male_ranger_feet_boots",
    "licensed.quaternius.male_ranger_head_hood",
    "licensed.quaternius.male_ranger_legs"
  ],
  "townsperson": [
    "licensed.quaternius.female_peasant_arms",
    "licensed.quaternius.female_peasant_body",
    "licensed.quaternius.female_peasant_feet",
    "licensed.quaternius.female_peasant_legs",
    "licensed.quaternius.male_peasant_arms",
    "licensed.quaternius.male_peasant_body",
    "licensed.quaternius.male_peasant_feet",
    "licensed.quaternius.male_peasant_legs"
  ],
  "farmer": [
    "licensed.quaternius.female_peasant_arms",
    "licensed.quaternius.female_peasant_body",
    "licensed.quaternius.female_peasant_feet",
    "licensed.quaternius.female_peasant_legs",
    "licensed.quaternius.male_peasant_arms",
    "licensed.quaternius.male_peasant_body",
    "licensed.quaternius.male_peasant_feet",
    "licensed.quaternius.male_peasant_legs"
  ],
  "merchant": [
    "licensed.quaternius.female_peasant_arms",
    "licensed.quaternius.female_peasant_body",
    "licensed.quaternius.female_peasant_feet",
    "licensed.quaternius.female_peasant_legs",
    "licensed.quaternius.male_peasant_arms",
    "licensed.quaternius.male_peasant_body",
    "licensed.quaternius.male_peasant_feet",
    "licensed.quaternius.male_peasant_legs"
  ],
  "hunter": [
    "licensed.quaternius.female_ranger_acc_pauldrons",
    "licensed.quaternius.female_ranger_arms",
    "licensed.quaternius.female_ranger_body",
    "licensed.quaternius.female_ranger_feet",
    "licensed.quaternius.female_ranger_head_hood",
    "licensed.quaternius.female_ranger_legs",
    "licensed.quaternius.male_ranger_acc_pauldron",
    "licensed.quaternius.male_ranger_arms",
    "licensed.quaternius.male_ranger_body",
    "licensed.quaternius.male_ranger_feet_boots",
    "licensed.quaternius.male_ranger_head_hood",
    "licensed.quaternius.male_ranger_legs"
  ],
  "guard": [
    "licensed.quaternius.female_ranger_acc_pauldrons",
    "licensed.quaternius.female_ranger_arms",
    "licensed.quaternius.female_ranger_body",
    "licensed.quaternius.female_ranger_feet",
    "licensed.quaternius.female_ranger_head_hood",
    "licensed.quaternius.female_ranger_legs",
    "licensed.quaternius.male_ranger_acc_pauldron",
    "licensed.quaternius.male_ranger_arms",
    "licensed.quaternius.male_ranger_body",
    "licensed.quaternius.male_ranger_feet_boots",
    "licensed.quaternius.male_ranger_head_hood",
    "licensed.quaternius.male_ranger_legs"
  ],
  "bandit": [
    "licensed.quaternius.female_ranger_acc_pauldrons",
    "licensed.quaternius.female_ranger_arms",
    "licensed.quaternius.female_ranger_body",
    "licensed.quaternius.female_ranger_feet",
    "licensed.quaternius.female_ranger_head_hood",
    "licensed.quaternius.female_ranger_legs",
    "licensed.quaternius.male_ranger_acc_pauldron",
    "licensed.quaternius.male_ranger_arms",
    "licensed.quaternius.male_ranger_body",
    "licensed.quaternius.male_ranger_feet_boots",
    "licensed.quaternius.male_ranger_head_hood",
    "licensed.quaternius.male_ranger_legs"
  ],
  "boss": []
} as const satisfies Record<string, readonly string[]>;

export const HARTHMERE_ROLE_LICENSED_CLOTHING_DEFAULTS: Record<string, readonly string[]> = HARTHMERE_ROLE_LICENSED_CLOTHING_DEFAULTS_INTERNAL;

export function getHarthmereLicensedClothingById(id: string): HarthmereLicensedClothingItem | undefined {
  return HARTHMERE_LICENSED_CLOTHING_ASSETS.find((item) => item.id === id);
}

export type HarthmereLicensedRoleClothingOptions = {
  gender?: "male" | "female" | "neutral";
  style?: "peasant" | "ranger" | "any";
  includeCreditRequiredAssets?: boolean;
  includeReferenceOnlyAssets?: boolean;
};

export function getHarthmereLicensedClothingForRole(
  role: string,
  options: HarthmereLicensedRoleClothingOptions = {}
): HarthmereLicensedClothingItem[] {
  const normalizedRole = (role || "townsperson").toLowerCase();
  const ids = HARTHMERE_ROLE_LICENSED_CLOTHING_DEFAULTS[normalizedRole] || HARTHMERE_ROLE_LICENSED_CLOTHING_DEFAULTS.townsperson || [];
  const gender = options.gender;
  const style = options.style ?? "any";

  return ids
    .map((id: string) => getHarthmereLicensedClothingById(id))
    .filter((item): item is HarthmereLicensedClothingItem => Boolean(item))
    .filter((item: HarthmereLicensedClothingItem) => item.enabledByDefault || options.includeReferenceOnlyAssets)
    .filter((item: HarthmereLicensedClothingItem) => {
      const license = HARTHMERE_CLOTHING_ASSET_LICENSES[item.licenseId];
      return !license?.creditRequired || options.includeCreditRequiredAssets || item.licenseId === "quaternius_fantasy_standard";
    })
    .filter((item: HarthmereLicensedClothingItem) => !gender || item.tags?.includes(gender) || item.tags?.includes("neutral"))
    .filter((item: HarthmereLicensedClothingItem) => style === "any" || item.tags?.includes(style));
}

export function mergeHarthmereLicensedClothingForRole<T extends { id?: string }>(
  existing: T[] | undefined,
  role: string,
  options: HarthmereLicensedRoleClothingOptions = {}
): Array<T | HarthmereLicensedClothingItem> {
  const base = Array.isArray(existing) ? existing : [];
  const seen = new Set(base.map((item: any) => item?.id).filter(Boolean));
  const additions = getHarthmereLicensedClothingForRole(role, options).filter((item: HarthmereLicensedClothingItem) => !seen.has(item.id));
  return [...base, ...additions];
}

export function getHarthmereClothingCreditLinesForItemIds(itemIds: readonly string[]): string[] {
  const licenseIds = new Set<string>();

  for (const id of itemIds) {
    const item = getHarthmereLicensedClothingById(id);
    if (item) {
      licenseIds.add(item.licenseId);
    }
  }

  return Array.from(licenseIds)
    .map((licenseId) => HARTHMERE_CLOTHING_ASSET_LICENSES[licenseId])
    .filter((license): license is HarthmereLicensedClothingLicense => Boolean(license))
    .filter((license) => license.creditRequired)
    .map((license) => license.creditLine);
}
