// Auto-generated by install-harthmere-runtime-completion-v47.sh
// v47 turns Bellbound story locations into explicit playable, physically placed runtime contracts.

export const HARTHMERE_MAIN_QUEST_SPACES_VERSION_V47 = 47 as const;
export const HARTHMERE_MAIN_QUEST_SPACES_V47_JSON = `[
  {
    "id": "old_bridge_crack_interaction_space_v47",
    "name": "Old Bridge Crack Interaction Space",
    "questIds": [
      "bellbound_q01_cracks_in_bridge"
    ],
    "district": "Old Bridge",
    "surface": true,
    "underground": false,
    "entry": {
      "x": 486,
      "z": -206,
      "yOffset": 0
    },
    "exit": {
      "x": 480,
      "z": -212,
      "yOffset": 0
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "stone bridge deck",
      "walls": "bridge parapets",
      "roof": "open exterior",
      "navmesh": "wide pedestrian lane"
    },
    "interactables": [
      "bridge_crack_inspect",
      "bell_residue_scrape",
      "river_echo_listen"
    ],
    "encounters": [],
    "accessibility": [
      "clear approach from market",
      "map marker at bridge rail",
      "no jump required"
    ],
    "testCases": [
      "inspect crack only when Q1 active",
      "server records bridge evidence once",
      "map hint points to bridge rail"
    ]
  },
  {
    "id": "chapel_cellar_undercroft_v47",
    "name": "Chapel Cellar and Undercroft",
    "questIds": [
      "bellbound_q04_sisters_letters",
      "bellbound_q05_beneath_the_stones"
    ],
    "district": "Temple Green",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 480,
      "z": -132,
      "yOffset": -4
    },
    "exit": {
      "x": 482,
      "z": -139,
      "yOffset": 0
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "solid stone undercroft floor",
      "walls": "block-built chapel foundation",
      "roof": "low stone ceiling",
      "navmesh": "single-file but walkable"
    },
    "interactables": [
      "maelle_letter_cache",
      "old_chapel_lock",
      "foundation_bell_mark"
    ],
    "encounters": [
      "undercroft_rat_swarm",
      "echo_choir_shade"
    ],
    "accessibility": [
      "stairs from chapel",
      "subtitle on whisper cues",
      "safe retreat trigger"
    ],
    "testCases": [
      "letters spawn only after Q4",
      "cellar opens for Q5",
      "retreat exit always stays valid"
    ]
  },
  {
    "id": "hidden_door_encounter_v47",
    "name": "Hidden Door Encounter",
    "questIds": [
      "bellbound_q06_hidden_door"
    ],
    "district": "Old Well / Underways",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 484,
      "z": -151,
      "yOffset": -8
    },
    "exit": {
      "x": 484,
      "z": -151,
      "yOffset": 0
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "wet stone stair landing",
      "walls": "sealed block door",
      "roof": "arched stone tunnel",
      "navmesh": "combat-ready landing"
    },
    "interactables": [
      "sealed_bellbinder_door",
      "four_note_lock",
      "old_harth_mark"
    ],
    "encounters": [
      "bell_locked_guardian",
      "door_echo_trap"
    ],
    "accessibility": [
      "telegraph before door trap",
      "visible runes",
      "clear reset after fail"
    ],
    "testCases": [
      "door requires Q6 active",
      "wrong note sequence fails recoverably",
      "guardian death cannot softlock door"
    ]
  },
  {
    "id": "bellward_halls_dungeon_v47",
    "name": "Bellward Halls Dungeon",
    "questIds": [
      "bellbound_q07_bellward_halls"
    ],
    "district": "Bellward Halls",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 486,
      "z": -318,
      "yOffset": -14
    },
    "exit": {
      "x": 486,
      "z": -151,
      "yOffset": -8
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "stone hall lanes",
      "walls": "bellward masonry",
      "roof": "vaulted ceiling",
      "navmesh": "party path with arena pockets"
    },
    "interactables": [
      "listening_chamber_bell",
      "choir_mural",
      "choir_grave_tablet"
    ],
    "encounters": [
      "first_choir_crone",
      "choir_apprentice",
      "choir_singer"
    ],
    "accessibility": [
      "boss arena reset gate",
      "hearing cue visual ripples",
      "safe runback route"
    ],
    "testCases": [
      "Q7 creates dungeon instance",
      "choir choice changes fight modifier",
      "reward grants once"
    ]
  },
  {
    "id": "old_harth_antechamber_v47",
    "name": "Old Harth's Antechamber",
    "questIds": [
      "bellbound_q08_voices_in_stone"
    ],
    "district": "Old Harth Tomb",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 490,
      "z": -336,
      "yOffset": -24
    },
    "exit": {
      "x": 486,
      "z": -318,
      "yOffset": -14
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "octagonal stone chamber",
      "walls": "sealed tomb blocks",
      "roof": "chain-slung memory stone ceiling",
      "navmesh": "lore-safe circle"
    },
    "interactables": [
      "memory_stone",
      "harth_sarcophagus",
      "three_path_choice_tablet"
    ],
    "encounters": [],
    "accessibility": [
      "long monologue subtitle support",
      "pause-friendly lore playback",
      "quest journal transcript"
    ],
    "testCases": [
      "memory stone cannot be skipped without summary",
      "Q8 path choice is recorded",
      "three-path flag persists"
    ]
  },
  {
    "id": "veins_of_wyrm_group_dungeon_v47",
    "name": "Veins of the Wyrm",
    "questIds": [
      "bellbound_q09_veins_of_wyrm"
    ],
    "district": "Veins of the Wyrm",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 498,
      "z": -356,
      "yOffset": -36
    },
    "exit": {
      "x": 490,
      "z": -336,
      "yOffset": -24
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "dragon-warmed stone veins",
      "walls": "cracked ore and bell-metal seams",
      "roof": "low shimmering cavern ceiling",
      "navmesh": "group dungeon lanes"
    },
    "interactables": [
      "scale_shed_deposit",
      "bell_vein_resonator",
      "heat_vent_valve"
    ],
    "encounters": [
      "vein_beast_pack",
      "bell_sick_miner",
      "scale_shed_elite"
    ],
    "accessibility": [
      "heat hazard visual edge",
      "party regroup pockets",
      "solo-story reduced danger mode"
    ],
    "testCases": [
      "group and solo tuning both exist",
      "class spotlights are testable",
      "resource nodes are server gated"
    ]
  },
  {
    "id": "bellbinders_tomb_group_dungeon_v47",
    "name": "Bellbinder's Tomb",
    "questIds": [
      "bellbound_q10_bellbinders_tomb"
    ],
    "district": "Old Harth Tomb",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 506,
      "z": -372,
      "yOffset": -44
    },
    "exit": {
      "x": 498,
      "z": -356,
      "yOffset": -36
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "sealed tomb stone",
      "walls": "chain relief blocks",
      "roof": "heavy crypt ceiling",
      "navmesh": "boss-key puzzle rooms"
    },
    "interactables": [
      "bellbinder_pin",
      "harth_last_oath",
      "chain_relief_puzzle"
    ],
    "encounters": [
      "tomb_bound_wight",
      "silent_robed_echo",
      "harth_oath_trial"
    ],
    "accessibility": [
      "visual puzzle affordances",
      "failsafe reset lever",
      "journal recap"
    ],
    "testCases": [
      "tomb puzzle resets",
      "relic pickup idempotent",
      "Q10 cannot complete without oath trial"
    ]
  },
  {
    "id": "bellward_chamber_race_sequence_v47",
    "name": "Bellward Chamber Race Sequence",
    "questIds": [
      "bellbound_q11_last_ringing"
    ],
    "district": "Bellward Chamber",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 512,
      "z": -388,
      "yOffset": -52
    },
    "exit": {
      "x": 506,
      "z": -372,
      "yOffset": -44
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "racing stone causeway",
      "walls": "collapsing bellward blocks",
      "roof": "falling dust and chain ceiling",
      "navmesh": "timed but readable route"
    },
    "interactables": [
      "last_bell_rope",
      "falling_chain_warning",
      "collapse_gate"
    ],
    "encounters": [
      "bell_sick_wave",
      "chainfall_hazard"
    ],
    "accessibility": [
      "generous telegraphs",
      "slow mode flag",
      "fail-forward reset"
    ],
    "testCases": [
      "race timer starts after Q11 accept",
      "hazards telegraph before damage",
      "failure can retry"
    ]
  },
  {
    "id": "wyrms_bed_thaedryn_arena_v47",
    "name": "Wyrm's Bed / Thaedryn Arena",
    "questIds": [
      "bellbound_q12_thaedryn_bellbound"
    ],
    "district": "Wyrm Bed",
    "surface": false,
    "underground": true,
    "entry": {
      "x": 520,
      "z": -408,
      "yOffset": -60
    },
    "exit": {
      "x": 512,
      "z": -388,
      "yOffset": -52
    },
    "playableRuntime": true,
    "physicallyPlaced": true,
    "collisionPlan": {
      "floor": "huge circular dragon chamber",
      "walls": "ancient bell-chain anchors",
      "roof": "vast vault with falling bell path",
      "navmesh": "four-chain arena quadrants"
    },
    "interactables": [
      "chain_anchor_north",
      "chain_anchor_south",
      "chain_anchor_east",
      "chain_anchor_west",
      "handbell",
      "fallen_bell"
    ],
    "encounters": [
      "thaedryn_the_bellbound"
    ],
    "accessibility": [
      "path-specific objective markers",
      "large telegraphs",
      "wipe recovery",
      "subtitles for dragon voice"
    ],
    "testCases": [
      "Q12 creates boss arena",
      "four anchors are addressable",
      "slay/rebind/wake paths are mutually exclusive"
    ]
  }
]`;
export const HARTHMERE_MAIN_QUEST_SPACES_V47 = JSON.parse(HARTHMERE_MAIN_QUEST_SPACES_V47_JSON) as any[];

export function getHarthmereMainQuestSpaceByIdV47(id: string) {
  return HARTHMERE_MAIN_QUEST_SPACES_V47.find((space) => space.id === id);
}

export function getHarthmereMainQuestSpacesByQuestIdV47(questId: string) {
  return HARTHMERE_MAIN_QUEST_SPACES_V47.filter((space) => space.questIds.includes(questId));
}

export function getHarthmereDungeonEncounterPlacementsV47() {
  return HARTHMERE_MAIN_QUEST_SPACES_V47.flatMap((space) =>
    (space.encounters ?? []).map((encounter: string, index: number) => ({
      id: `${space.id}:${encounter}:${index}`,
      encounterId: encounter,
      spaceId: space.id,
      district: space.district,
      waypoint: [space.entry.x + index * 2, space.entry.yOffset, space.entry.z - index * 2],
      serverSpawned: true,
      phaseGatedByQuestIds: space.questIds,
    })),
  );
}

export function validateHarthmereMainQuestSpacesV47() {
  const requiredQuestIds = [
    "bellbound_q01_cracks_in_bridge",
    "bellbound_q04_sisters_letters",
    "bellbound_q05_beneath_the_stones",
    "bellbound_q06_hidden_door",
    "bellbound_q07_bellward_halls",
    "bellbound_q08_voices_in_stone",
    "bellbound_q09_veins_of_wyrm",
    "bellbound_q10_bellbinders_tomb",
    "bellbound_q11_last_ringing",
    "bellbound_q12_thaedryn_bellbound",
  ];
  const failures: string[] = [];
  for (const questId of requiredQuestIds) {
    if (!getHarthmereMainQuestSpacesByQuestIdV47(questId).length) failures.push(`missing playable space for ${questId}`);
  }
  for (const space of HARTHMERE_MAIN_QUEST_SPACES_V47) {
    if (!space.playableRuntime) failures.push(`${space.id} not runtime playable`);
    if (!space.physicallyPlaced) failures.push(`${space.id} not physically placed`);
    if (!space.collisionPlan?.floor || !space.collisionPlan?.walls || !space.collisionPlan?.navmesh) failures.push(`${space.id} incomplete collision/navmesh plan`);
    if (!space.interactables?.length) failures.push(`${space.id} missing interactables`);
    if (!space.testCases?.length) failures.push(`${space.id} missing test cases`);
  }
  return { ok: failures.length === 0, failures, spaceCount: HARTHMERE_MAIN_QUEST_SPACES_V47.length };
}
