import {
  getHarthmereCraftingRecipeV1,
  getHarthmereCraftingStationV1,
  getHarthmereCraftingToolV1,
  getHarthmereItemDefinitionV1,
  registerHarthmereCraftingRecipeV1,
  registerHarthmereCraftingStationV1,
  registerHarthmereCraftingToolV1,
  registerHarthmereItemDefinitionV1,
  type HarthmereCraftingRecipeV1,
  type HarthmereCraftingStationDefinitionV1,
  type HarthmereCraftingToolDefinitionV1,
  type HarthmereItemDefinitionV1,
} from "./mmo_inventory_authority_v1";

export const HARTHMERE_CRAFTING_STATIONS_V1 = {
  anglersTable: "65464304897922",
  arcadeMachine: "4537020877769721",
  composter: "3814157132212639",
  dyeOMatic: "8287780998923911",
  handcraft: "1534621126189502",
  kitchen: "1485695172010242",
  seedMill: "1403692516415707",
  tailoringBooth: "7539420629350105",
  thermoblaster: "4537020877769775",
  thermolite: "2443541317223860",
  unknownCraftingStation: "4537020877769778",
  wardrobe: "1534621126189262",
  workbench: "1534621126189448",
} as const;

export const HARTHMERE_CRAFTING_TOOLS_V1 = {
  simpleAxe: "4537020877770177",
  stonePick: "7539420629350249",
  pickaxe: "4537020877770159",
  silverPick: "1534621126189607",
  woodenFencer: "7539420629350252",
  slabber: "7539420629350489",
  fishingRod: "2913506116529081",
  bucket: "4537020877769799",
  wateringCan: "7539420629350045",
  muckBuster: "5354980139910506",
  buildersWand: "7539420629350501",
} as const;

export const HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1 = {
  antiprotonCapsule: "antiproton_capsule",
  positronCapsule: "positron_capsule",
  antineutronCapsule: "antineutron_capsule",
  antihydrogenBlock: "antihydrogen_block",
  antiheliumBlock: "antihelium_block",
  antiboronBlock: "antiboron_block",
  rawExoticMatter: "raw_exotic_matter",
  stabilizedExoticMatter: "stabilized_exotic_matter",
  containmentFilter: "containment_filter",
  spentFilter: "spent_filter",
  coolant: "coolant",
  stabilizingCrystal: "stabilizing_crystal",
  exoticMatterPowerCell: "exotic_matter_power_cell",
  portalFuel: "portal_fuel",
  certifiedPortalFuel: "certified_portal_fuel",
  teleportFuel: "teleport_fuel",
  destinationCrystal: "destination_crystal",
  anchorCore: "anchor_core",
  utilityCore: "utility_core",
  alcubierreDriveCore: "alcubierre_drive_core",
} as const;

export const HARTHMERE_EXOTIC_MATTER_BLOCK_ITEM_IDS_V1 = [
  HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antihydrogenBlock,
  HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiheliumBlock,
  HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiboronBlock,
  HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.rawExoticMatter,
  HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
] as const;

export const HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1 = {
  antihydrogenBlock: "harthmere_exotic_antihydrogen_block",
  antiheliumBlock: "harthmere_exotic_antihelium_block",
  antiboronBlock: "harthmere_exotic_antiboron_block",
  rawExoticMatter: "harthmere_exotic_raw_matter_block",
  stabilizedExoticMatter: "harthmere_exotic_stabilized_matter_block",
  powerCell: "harthmere_exotic_power_cell",
  portalFuel: "harthmere_exotic_portal_fuel_cell",
  certifiedPortalFuel: "harthmere_exotic_certified_portal_fuel",
  teleportFuel: "harthmere_exotic_teleport_fuel",
  anchorCore: "harthmere_exotic_anchor_core",
  utilityCore: "harthmere_exotic_utility_core",
  alcubierreDriveCore: "harthmere_exotic_alcubierre_drive_core",
} as const;

export const HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1 = {
  workbench: "harthmere_station_workbench",
  thermolite: "harthmere_station_thermolite",
  thermoblaster: "harthmere_station_thermoblaster",
  kitchen: "harthmere_station_kitchen",
  tailoringBooth: "harthmere_station_tailoring_booth",
  seedMill: "harthmere_station_seed_mill",
  anglersTable: "harthmere_station_anglers_table",
  composter: "harthmere_station_composter",
  dyeOMatic: "harthmere_station_dye_o_matic",
} as const;

export const HARTHMERE_HOME_DECORATION_ITEM_IDS_V1 = {
  storageCabinet: "home_storage_cabinet",
  hearthLamp: "hearth_lamp",
  gardenPlanterBox: "garden_planter_box",
  businessServiceCounter: "business_service_counter",
} as const;

export const HARTHMERE_HOME_DECORATION_RECIPE_IDS_V1 = {
  storageCabinet: "harthmere_decor_storage_cabinet",
  hearthLamp: "harthmere_decor_hearth_lamp",
  gardenPlanterBox: "harthmere_decor_garden_planter_box",
  businessServiceCounter: "harthmere_decor_business_service_counter",
} as const;

function item(
  itemId: string,
  displayName: string,
  overrides: Partial<HarthmereItemDefinitionV1> = {}
): HarthmereItemDefinitionV1 {
  const isMaterial =
    overrides.isCraftingMaterial ??
    /(ore|ingot|wood|log|plank|hide|leather|cloth|herb|extract|dust|coal|flux|fiber|scrap|crystal|reagent|bronze|trace|seed|flour|lure|kit|shard|block|matter|fuel|filter|coolant|core|capsule|cell)/i.test(
      itemId
    );
  return {
    itemId,
    displayName,
    maxStackSize: isMaterial ? 9999 : 20,
    baseValue: 1,
    binding: "none",
    isQuestItem: false,
    isCurrency: false,
    isConsumable: false,
    isCraftingMaterial: isMaterial,
    isSpellTome: false,
    levelRequirement: 1,
    classRestriction: [],
    stats: {},
    tradeable: true,
    ...overrides,
  };
}

const STATIONS: HarthmereCraftingStationDefinitionV1[] = [
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.anglersTable,
    displayName: "Angler's Table",
    stationType: "general",
    size: "2x2x3",
    buildingRequirements: "none",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.arcadeMachine,
    displayName: "Arcade Machine",
    stationType: "general",
    size: "1x2x1",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.composter,
    displayName: "Composter",
    stationType: "composting",
    size: "1x2x3",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.dyeOMatic,
    displayName: "Dye-O-Matic",
    stationType: "dying",
    size: "3x3x3",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.handcraft,
    displayName: "Handcraft",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.kitchen,
    displayName: "Kitchen",
    stationType: "cooking",
    size: "1x1x4",
    buildingRequirements: "roof",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.seedMill,
    displayName: "Seed Mill",
    stationType: "general",
    size: "1x3x1",
    buildingRequirements: "noRoof",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
    displayName: "Tailoring Booth",
    stationType: "general",
    size: "4x1x3",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    displayName: "Thermoblaster",
    stationType: "general",
    size: "3x3x3",
    buildingRequirements: "none",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
    displayName: "Thermolite",
    stationType: "general",
    size: "1x2x3",
    buildingRequirements: "roof",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.unknownCraftingStation,
    displayName: "Crafting Station",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.wardrobe,
    displayName: "Wardrobe",
    stationType: "dying",
    size: "1x1x3",
  },
  {
    stationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    displayName: "Workbench",
    stationType: "general",
    size: "1x1x3",
    supportsHandcraft: true,
  },
];

const TOOLS: HarthmereCraftingToolDefinitionV1[] = [
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.simpleAxe,
    displayName: "Simple Axe",
    action: "destroy",
    tier: 1,
    durabilityMax: 150000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.pickaxe,
    displayName: "Pickaxe",
    action: "destroy",
    tier: 1,
    durabilityMax: 150000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.stonePick,
    displayName: "Stone Pick",
    action: "destroy",
    tier: 2,
    durabilityMax: 900000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.silverPick,
    displayName: "Silver Pick",
    action: "destroy",
    tier: 3,
    durabilityMax: 3600000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.woodenFencer,
    displayName: "Wooden Fencer",
    action: "shape",
    tier: 1,
    durabilityMax: 225000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.slabber,
    displayName: "Slabber",
    action: "shape",
    tier: 1,
    durabilityMax: 500000000,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.fishingRod,
    displayName: "Fishing Rod",
    action: "fish",
    tier: 1,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.bucket,
    displayName: "Bucket",
    action: "dump",
    tier: 1,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.wateringCan,
    displayName: "Watering Can",
    action: "waterPlant",
    tier: 1,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.muckBuster,
    displayName: "Muck Buster",
    action: "demuckerWand",
    tier: 2,
  },
  {
    itemId: HARTHMERE_CRAFTING_TOOLS_V1.buildersWand,
    displayName: "Builder's Wand",
    action: "wand",
    tier: 5,
  },
];

type ItemObjectMetadataV1 = NonNullable<
  HarthmereItemDefinitionV1["objectMetadata"]
>;

const CRAFTABLE_STATION_ITEM_IDS_V1 = [
  HARTHMERE_CRAFTING_STATIONS_V1.workbench,
  HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
  HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
  HARTHMERE_CRAFTING_STATIONS_V1.kitchen,
  HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
  HARTHMERE_CRAFTING_STATIONS_V1.seedMill,
  HARTHMERE_CRAFTING_STATIONS_V1.anglersTable,
  HARTHMERE_CRAFTING_STATIONS_V1.composter,
  HARTHMERE_CRAFTING_STATIONS_V1.dyeOMatic,
] as const;

function parseStationSizeV1(size?: string) {
  const [width, depth, height] = String(size ?? "1x1x1")
    .split("x")
    .map((part) => Math.max(1, Math.floor(Number(part) || 1)));
  return { width, depth, height };
}

function stationItemDefinitionV1(
  station: HarthmereCraftingStationDefinitionV1
) {
  return item(station.stationId, station.displayName, {
    maxStackSize: 20,
    baseValue: 65,
    isCraftingMaterial: false,
    category: "crafting station",
    objectMetadata: {
      objectKind: "station",
      physicalForm: "crafting_station",
      sizeVoxels: parseStationSizeV1(station.size),
      sizeLabel: station.size ?? "1x1x1",
      craftingRoles: [
        `${station.displayName} recipes`,
        station.supportsHandcraft ? "handcraft support" : "station crafting",
      ],
      businessUse: ["home workshop", "licensed business workshop"],
      handling: ["place on owned home or business property"],
      visualDescription: `${station.displayName} crafting station`,
      procedural: {
        canGenerateWithVoxels: true,
        suggestedShape: "functional crafting station",
        palette: ["warm wood", "dark metal", "tool accents"],
        emission:
          station.stationId === HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster
            ? "contained furnace glow"
            : "none",
      },
    },
  });
}

const STATION_ITEMS: HarthmereItemDefinitionV1[] =
  CRAFTABLE_STATION_ITEM_IDS_V1.map((stationId) =>
    stationItemDefinitionV1(
      STATIONS.find((station) => station.stationId === stationId) ?? {
        stationId,
        displayName: "Crafting Station",
      }
    )
  );

const HOME_DECORATION_ITEMS: HarthmereItemDefinitionV1[] = [
  item(
    HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.storageCabinet,
    "Storage Cabinet",
    {
      maxStackSize: 20,
      baseValue: 45,
      isCraftingMaterial: false,
      category: "home decoration",
      objectMetadata: {
        objectKind: "furniture",
        physicalForm: "storage",
        sizeVoxels: { width: 1, depth: 1, height: 2 },
        sizeLabel: "1x1x2",
        visualDescription: "wood cabinet with reinforced hinges",
        craftingRoles: ["home storage"],
        businessUse: ["back room storage"],
      },
    }
  ),
  item(HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.hearthLamp, "Hearth Lamp", {
    maxStackSize: 20,
    baseValue: 35,
    isCraftingMaterial: false,
    category: "home decoration",
    objectMetadata: {
      objectKind: "fixture",
      physicalForm: "light",
      sizeVoxels: { width: 1, depth: 1, height: 1 },
      sizeLabel: "1x1x1",
      visualDescription: "compact home light with a crystal glow",
      craftingRoles: ["home comfort", "business lighting"],
      businessUse: ["shop lighting"],
    },
  }),
  item(
    HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.gardenPlanterBox,
    "Garden Planter Box",
    {
      maxStackSize: 20,
      baseValue: 30,
      isCraftingMaterial: false,
      category: "home decoration",
      objectMetadata: {
        objectKind: "garden",
        physicalForm: "garden_bed",
        sizeVoxels: { width: 2, depth: 1, height: 1 },
        sizeLabel: "2x1x1",
        visualDescription: "soil-filled planter for a small crop",
        craftingRoles: ["home gardening"],
        businessUse: ["fresh herb display"],
      },
    }
  ),
  item(
    HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.businessServiceCounter,
    "Service Counter",
    {
      maxStackSize: 20,
      baseValue: 60,
      isCraftingMaterial: false,
      category: "home decoration",
      objectMetadata: {
        objectKind: "furniture",
        physicalForm: "counter",
        sizeVoxels: { width: 2, depth: 1, height: 1 },
        sizeLabel: "2x1x1",
        visualDescription: "counter for customer orders and commissions",
        craftingRoles: ["business service"],
        businessUse: ["customer counter", "work order intake"],
      },
    }
  ),
];

const EXOTIC_MATTER_LORE_V1 = {
  discoveredYear: 2042,
  discoveredBy: "Tyrone Smith",
  origin:
    "Created by an accident involving Antihydrogen, Antihelium, and Antiboron in a collider.",
  societyUses: [
    "Biomes and pocket dimensions",
    "city power grids",
    "consumer devices",
    "robots",
    "portal transit",
    "teleportation",
  ],
};

function exoticBlockMetadata(
  input: Omit<
    ItemObjectMetadataV1,
    "objectKind" | "physicalForm" | "sizeVoxels" | "sizeLabel" | "procedural"
  >
): ItemObjectMetadataV1 {
  return {
    objectKind: "material",
    physicalForm: "block",
    sizeVoxels: { width: 1, depth: 1, height: 1 },
    sizeLabel: "1x1x1 voxel crafting block",
    procedural: {
      canGenerateWithVoxels: true,
      suggestedShape: "single block with animated inner glow",
      palette: input.colors ?? [],
      emission: "soft contained pulse",
    },
    ...input,
  };
}

function exoticItemMetadata(
  input: Omit<ItemObjectMetadataV1, "sizeLabel" | "procedural">
): ItemObjectMetadataV1 {
  return {
    sizeLabel: "handheld inventory item",
    procedural: {
      canGenerateWithVoxels: true,
      suggestedShape: input.physicalForm.replace(/_/g, " "),
      palette: input.colors ?? [],
      emission: input.energySource ? "small status glow" : "none",
    },
    ...input,
  };
}

const ITEMS: HarthmereItemDefinitionV1[] = [
  ...STATION_ITEMS,
  ...HOME_DECORATION_ITEMS,
  item("iron_ore", "Iron Ore", { baseValue: 5 }),
  item("coal", "Coal", { baseValue: 3 }),
  item("iron_ingot", "Iron Ingot", { baseValue: 12 }),
  item("iron_sword", "Iron Sword", {
    maxStackSize: 1,
    baseValue: 100,
    isCraftingMaterial: false,
    category: "weapon",
    durabilityMax: 120,
    repairable: true,
    stats: { attack: 10, weight: 5 },
    salvageOutputs: [{ itemId: "iron_ingot", count: 1 }],
  }),
  item("iron_sword_reinforced", "Reinforced Iron Sword", {
    maxStackSize: 1,
    baseValue: 180,
    isCraftingMaterial: false,
    category: "weapon",
    durabilityMax: 160,
    repairable: true,
    stats: { attack: 14, weight: 5 },
    salvageOutputs: [{ itemId: "iron_ingot", count: 2 }],
  }),
  item("wood_log", "Wood Log", { baseValue: 2 }),
  item("wood_plank", "Wood Plank", { baseValue: 4 }),
  item("hunter_bow", "Hunter Bow", {
    maxStackSize: 1,
    baseValue: 75,
    isCraftingMaterial: false,
    category: "weapon",
    durabilityMax: 90,
    repairable: true,
    stats: { rangedAttack: 8, weight: 3 },
    salvageOutputs: [{ itemId: "wood_plank", count: 1 }],
  }),
  item("road_repair_kit", "Road Repair Kit", { baseValue: 35, isCraftingMaterial: false }),
  item("rough_hide", "Rough Hide", { baseValue: 4 }),
  item("boiled_leather", "Boiled Leather", { baseValue: 10 }),
  item("leather_armor", "Leather Armor", {
    maxStackSize: 1,
    baseValue: 120,
    isCraftingMaterial: false,
    category: "armor",
    durabilityMax: 110,
    repairable: true,
    stats: { armor: 8, weight: 4 },
    salvageOutputs: [{ itemId: "boiled_leather", count: 1 }],
  }),
  item("flax_fiber", "Flax Fiber", { baseValue: 2 }),
  item("linen_cloth", "Linen Cloth", { baseValue: 6 }),
  item("travel_cloak", "Travel Cloak", {
    maxStackSize: 1,
    baseValue: 65,
    isCraftingMaterial: false,
    category: "armor",
    durabilityMax: 80,
    repairable: true,
    stats: { warmth: 3, weight: 1 },
  }),
  item("rough_herb", "Rough Herb", { baseValue: 3 }),
  item("herbal_extract", "Herbal Extract", { baseValue: 8 }),
  item("health_potion", "Health Potion", {
    maxStackSize: 20,
    baseValue: 25,
    isCraftingMaterial: false,
    isConsumable: true,
    category: "consumable",
    consumableCooldownCategory: "potion",
    consumableCooldownMs: 30000,
  }),
  item("antidote", "Antidote", {
    maxStackSize: 20,
    baseValue: 30,
    isCraftingMaterial: false,
    isConsumable: true,
    category: "consumable",
    consumableCooldownCategory: "potion",
    consumableCooldownMs: 30000,
  }),
  item("crystal_shard", "Crystal Shard", { baseValue: 14 }),
  item("arcane_dust", "Arcane Dust", { baseValue: 30 }),
  item("warded_iron_sword", "Warded Iron Sword", {
    maxStackSize: 1,
    baseValue: 260,
    isCraftingMaterial: false,
    category: "weapon",
    durabilityMax: 160,
    repairable: true,
    stats: { attack: 14, warding: 4, weight: 5 },
  }),
  item("repair_part", "Repair Part", { baseValue: 10, isCraftingMaterial: true }),
  item("upgrade_crystal", "Upgrade Crystal", { baseValue: 45 }),
  item("bell_metal_fragment", "Bell Metal Fragment", { baseValue: 20, isCraftingMaterial: true }),
  item("meteoric_trace", "Meteoric Trace", { baseValue: 25 }),
  item("tin_ingot", "Tin Ingot", { baseValue: 8 }),
  item("bell_bronze_ingot", "Bell-Bronze Ingot", { baseValue: 80 }),
  item("bellbinders_voice", "Bellbinder's Voice", {
    maxStackSize: 1,
    baseValue: 0,
    binding: "quest",
    isQuestItem: true,
    tradeable: false,
    isCraftingMaterial: false,
    category: "quest",
    durabilityMax: 200,
    qualityFloor: 70,
  }),
  item("river_reed", "River Reed", { baseValue: 3, isCraftingMaterial: true }),
  item("fishing_lure", "Fishing Lure", { baseValue: 12 }),
  item("grain_seed", "Grain Seed", { baseValue: 2 }),
  item("grain_flour", "Grain Flour", { baseValue: 5 }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiprotonCapsule,
    "Antiproton Capsule",
    {
      baseValue: 95,
      category: "particle_component",
      materialTier: 4,
      maxStackSize: 250,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "particle_capsule",
        colors: ["cold violet", "black glass", "warning amber"],
        visualDescription:
          "A palm-sized black containment capsule with violet pinpricks locked behind amber warning bands.",
        materialComposition: [
          "antiprotons",
          "micro containment glass",
          "field latch",
        ],
        craftingRoles: [
          "antihydrogen_block",
          "antihelium_block",
          "antiboron_block",
        ],
        source: [
          "deep earth mining",
          "particle collider salvage",
          "licensed exotic matter stores",
        ],
        businessUse: ["exotic_matter_refinery", "magic_goods"],
        handling: [
          "store under active containment",
          "never open outside a Thermoblaster",
        ],
        hazardClass: "antimatter_component",
        containmentRating: 80,
        bikkieGraphicHints: ["powerCell", "thermoblaster"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.positronCapsule,
    "Positron Capsule",
    {
      baseValue: 85,
      category: "particle_component",
      materialTier: 4,
      maxStackSize: 250,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "particle_capsule",
        colors: ["rose white", "black glass", "warning amber"],
        visualDescription:
          "A compact containment capsule with a pale rose-white core and a narrow amber safety seal.",
        materialComposition: [
          "positrons",
          "micro containment glass",
          "field latch",
        ],
        craftingRoles: [
          "antihydrogen_block",
          "antihelium_block",
          "antiboron_block",
        ],
        source: [
          "deep earth mining",
          "particle collider salvage",
          "licensed exotic matter stores",
        ],
        businessUse: ["exotic_matter_refinery", "magic_goods"],
        handling: [
          "pair only inside containment fields",
          "keep away from loose electron-rich matter",
        ],
        hazardClass: "antimatter_component",
        containmentRating: 75,
        bikkieGraphicHints: ["powerCell", "thermoblaster"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antineutronCapsule,
    "Antineutron Capsule",
    {
      baseValue: 110,
      category: "particle_component",
      materialTier: 5,
      maxStackSize: 250,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "particle_capsule",
        colors: ["deep indigo", "black glass", "silver clamp"],
        visualDescription:
          "A heavier capsule with an indigo shimmer suspended inside a silver-clamped containment shell.",
        materialComposition: [
          "antineutrons",
          "micro containment glass",
          "field latch",
        ],
        craftingRoles: ["antihelium_block", "antiboron_block"],
        source: [
          "deep earth mining",
          "particle collider salvage",
          "licensed exotic matter stores",
        ],
        businessUse: ["exotic_matter_refinery"],
        handling: ["transport in padded field trays", "do not mix by hand"],
        hazardClass: "antimatter_component",
        containmentRating: 85,
        bikkieGraphicHints: ["powerCell", "thermoblaster"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antihydrogenBlock,
    "Antihydrogen Block",
    {
      baseValue: 420,
      category: "block",
      materialTier: 5,
      qualityFloor: 45,
      stats: { containmentRating: 82 },
      objectMetadata: exoticBlockMetadata({
        colors: ["blue white", "violet", "transparent black"],
        visualDescription:
          "A one-voxel block that looks almost empty until blue-white antimatter sparks trace the inside edges.",
        materialComposition: [
          "antiprotons",
          "positrons",
          "containment lattice",
        ],
        craftingRoles: ["raw_exotic_matter"],
        source: [
          "crafted from antiproton and positron capsules",
          "rare deep earth mining find",
        ],
        businessUse: ["exotic_matter_refinery"],
        handling: [
          "requires hazardous material license level 2",
          "craft only in a Thermoblaster",
        ],
        hazardClass: "contained_antimatter_block",
        containmentRating: 82,
        bikkieGraphicHints: ["procedural_voxel_block", "thermoblaster"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiheliumBlock,
    "Antihelium Block",
    {
      baseValue: 760,
      category: "block",
      materialTier: 5,
      qualityFloor: 48,
      stats: { containmentRating: 86 },
      objectMetadata: exoticBlockMetadata({
        colors: ["cyan", "electric purple", "transparent black"],
        visualDescription:
          "A dense one-voxel block with cyan nuclei motes orbiting in slow paired loops.",
        materialComposition: [
          "antiprotons",
          "antineutrons",
          "positrons",
          "containment lattice",
        ],
        craftingRoles: ["raw_exotic_matter"],
        source: [
          "crafted from antimatter particle capsules",
          "rare collider-grade salvage",
        ],
        businessUse: ["exotic_matter_refinery"],
        handling: [
          "requires hazardous material license level 2",
          "never stack near damaged filters",
        ],
        hazardClass: "contained_antimatter_block",
        containmentRating: 86,
        bikkieGraphicHints: ["procedural_voxel_block", "thermoblaster"],
      }),
    }
  ),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiboronBlock, "Antiboron Block", {
    baseValue: 1220,
    category: "block",
    materialTier: 6,
    qualityFloor: 52,
    stats: { containmentRating: 90 },
    objectMetadata: exoticBlockMetadata({
      colors: ["magenta", "void black", "white spark"],
      visualDescription:
        "A theoretical antimatter block with magenta facets and a tiny white spark that seems to fall upward.",
      materialComposition: [
        "antiprotons",
        "antineutrons",
        "positrons",
        "high-density containment lattice",
      ],
      craftingRoles: ["raw_exotic_matter"],
      source: ["advanced refinery synthesis", "theoretical antimatter harvest"],
      businessUse: ["exotic_matter_refinery"],
      handling: [
        "requires senior exotic refining skill",
        "move only in sealed refinery crates",
      ],
      hazardClass: "contained_antimatter_block",
      containmentRating: 90,
      bikkieGraphicHints: ["procedural_voxel_block", "thermoblaster"],
    }),
  }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.rawExoticMatter,
    "Raw Exotic Matter Block",
    {
      baseValue: 2400,
      category: "block",
      materialTier: 6,
      qualityFloor: 58,
      stats: { containmentRating: 60, powerMegawatts: 100400 },
      objectMetadata: exoticBlockMetadata({
        colors: ["void black", "blue white", "gold halo"],
        visualDescription:
          "A floating one-voxel block with a black center, blue-white rim light, and a faint gold halo.",
        materialComposition: [
          "Antihydrogen Block",
          "Antihelium Block",
          "Antiboron Block",
        ],
        craftingRoles: [
          "stabilized_exotic_matter",
          "refinery_stock",
          "biome_power_source",
        ],
        source: [
          "crafted in Exotic Matter Refineries",
          "extremely rare deep earth mining find",
        ],
        businessUse: [
          "exotic_matter_refinery",
          "biome_maintenance_repair",
          "portal_transit_company",
        ],
        handling: [
          "unstable until stabilized",
          "keep inside active containment",
        ],
        hazardClass: "raw_exotic_matter",
        containmentRating: 60,
        powerMegawattsPerUnit: 100400,
        energySource: true,
        lore: EXOTIC_MATTER_LORE_V1,
        bikkieGraphicHints: [
          "procedural_voxel_block",
          "powerCell",
          "thermoblaster",
        ],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
    "Stabilized Exotic Matter Block",
    {
      baseValue: 4100,
      category: "block",
      materialTier: 6,
      qualityFloor: 70,
      stats: { containmentRating: 96, powerMegawatts: 100400 },
      objectMetadata: exoticBlockMetadata({
        colors: ["white core", "teal glow", "silver containment"],
        visualDescription:
          "A sealed one-voxel power block with a white core, teal field bands, and silver stabilizer ribs.",
        materialComposition: [
          "Raw Exotic Matter Block",
          "stabilizing crystal",
          "coolant field",
          "containment filter",
        ],
        craftingRoles: [
          "portal_fuel",
          "teleport_fuel",
          "robot_power",
          "city_grid_power",
          "biome_stabilization",
        ],
        source: ["stabilized in Exotic Matter Refineries"],
        businessUse: [
          "exotic_matter_refinery",
          "biome_maintenance_repair",
          "portal_transit_company",
          "teleport_owner",
          "robotics",
        ],
        handling: [
          "safe for industrial stock after certification",
          "audit containment seals before transit",
        ],
        hazardClass: "stabilized_exotic_matter",
        containmentRating: 96,
        powerMegawattsPerUnit: 100400,
        energySource: true,
        lore: EXOTIC_MATTER_LORE_V1,
        bikkieGraphicHints: [
          "procedural_voxel_block",
          "powerCell",
          "thermoblaster",
        ],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
    "Containment Filter",
    {
      baseValue: 70,
      category: "refinery_component",
      materialTier: 4,
      maxStackSize: 500,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "filter",
        colors: ["ceramic white", "graphite", "teal seal"],
        visualDescription:
          "A replaceable ceramic filter cartridge with graphite fins and a teal intact-seal stripe.",
        materialComposition: ["ceramic matrix", "graphite fins", "field seal"],
        craftingRoles: [
          "antimatter_block_synthesis",
          "exotic_matter_stabilization",
          "fuel_certification",
        ],
        source: ["refinery supplier", "crafted maintenance stock"],
        businessUse: ["exotic_matter_refinery", "portal_transit_company"],
        handling: [
          "replace after stabilization",
          "inspect for seal discoloration",
        ],
        hazardClass: "containment_consumable",
        containmentRating: 70,
        bikkieGraphicHints: ["bucket", "thermoblaster"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.spentFilter,
    "Spent Containment Filter",
    {
      baseValue: 8,
      category: "waste",
      materialTier: 3,
      maxStackSize: 500,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "filter",
        colors: ["ash gray", "dull teal", "scorch black"],
        visualDescription:
          "A used containment cartridge with dim seals and blackened filter fins.",
        materialComposition: [
          "spent ceramic matrix",
          "trace coolant residue",
          "captured field dust",
        ],
        craftingRoles: ["hazard_cleanup", "filter_recycling"],
        source: ["exotic matter stabilization byproduct"],
        businessUse: ["exotic_matter_refinery", "waste_management_recycling"],
        handling: [
          "store as refinery waste",
          "recycle or dispose through licensed cleanup",
        ],
        hazardClass: "spent_refinery_filter",
        containmentRating: 20,
        bikkieGraphicHints: ["muckBuster", "composter"],
      }),
    }
  ),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.coolant, "Containment Coolant", {
    baseValue: 35,
    category: "refinery_component",
    materialTier: 3,
    maxStackSize: 500,
    objectMetadata: exoticItemMetadata({
      objectKind: "component",
      physicalForm: "canister",
      colors: ["frost blue", "steel", "white vapor"],
      visualDescription:
        "A steel-blue coolant canister with a frosted viewport and faint white vapor around the cap.",
      materialComposition: ["cryogenic coolant", "field-safe stabilizer salts"],
      craftingRoles: ["exotic_matter_stabilization", "teleport_fuel_tempering"],
      source: ["industrial supplier", "refinery stores"],
      businessUse: ["exotic_matter_refinery", "teleport_owner"],
      handling: ["keep cold", "do not vent in sealed rooms"],
      hazardClass: "industrial_coolant",
      containmentRating: 45,
      bikkieGraphicHints: ["bucket", "thermolite"],
    }),
  }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizingCrystal,
    "Stabilizing Crystal",
    {
      baseValue: 180,
      category: "refinery_component",
      materialTier: 5,
      qualityFloor: 55,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "crystal",
        colors: ["teal", "clear quartz", "silver glint"],
        visualDescription:
          "A clear-teal crystal tuned to hold a steady field around volatile matter.",
        materialComposition: ["field-tuned crystal", "silver trace lattice"],
        craftingRoles: [
          "exotic_matter_stabilization",
          "utility_core",
          "anchor_core",
        ],
        source: ["deep crystal mining", "magic goods refinement"],
        businessUse: [
          "exotic_matter_refinery",
          "magic_goods",
          "teleport_owner",
        ],
        handling: [
          "avoid cracked crystals",
          "socket point-first into the field frame",
        ],
        hazardClass: "field_reagent",
        containmentRating: 65,
        bikkieGraphicHints: ["homestone", "powerCell"],
      }),
    }
  ),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.exoticMatterPowerCell,
    "Exotic Matter Power Cell",
    {
      baseValue: 1450,
      category: "power_cell",
      materialTier: 6,
      maxStackSize: 200,
      qualityFloor: 65,
      stats: { powerMegawatts: 100400 },
      objectMetadata: exoticItemMetadata({
        objectKind: "fuel",
        physicalForm: "power_cell",
        colors: ["electric blue", "white", "dark casing"],
        visualDescription:
          "A compact dark-cased cell with a white core and electric-blue status bands.",
        materialComposition: [
          "Stabilized Exotic Matter Block",
          "iron casing",
          "crystal regulator",
        ],
        craftingRoles: [
          "device_power",
          "robot_power",
          "portal_fuel",
          "city_grid_power",
        ],
        source: ["Exotic Matter Refinery power-cell assembly"],
        businessUse: [
          "exotic_matter_refinery",
          "robotics",
          "portal_transit_company",
          "teleport_owner",
        ],
        handling: [
          "safe for consumer devices after seal check",
          "do not puncture casing",
        ],
        hazardClass: "sealed_exotic_power",
        containmentRating: 92,
        powerMegawattsPerUnit: 100400,
        energySource: true,
        lore: EXOTIC_MATTER_LORE_V1,
        bikkieGraphicHints: ["powerCell"],
      }),
    }
  ),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.portalFuel, "Portal Fuel Cell", {
    baseValue: 720,
    category: "fuel_cell",
    materialTier: 6,
    maxStackSize: 250,
    qualityFloor: 60,
    objectMetadata: exoticItemMetadata({
      objectKind: "fuel",
      physicalForm: "fuel_cell",
      colors: ["teal", "white", "graphite"],
      visualDescription:
        "A sealed portal fuel cartridge with a teal-lit flow window and graphite safety sleeve.",
      materialComposition: [
        "Exotic Matter Power Cell",
        "coolant jacket",
        "field shunt",
      ],
      craftingRoles: [
        "certified_portal_fuel",
        "teleport_fuel",
        "portal_route_charge",
      ],
      source: ["Exotic Matter Refinery fuel assembly"],
      businessUse: ["exotic_matter_refinery", "portal_transit_company"],
      handling: [
        "certify before public transit use",
        "store upright in portal lockers",
      ],
      hazardClass: "sealed_exotic_fuel",
      containmentRating: 90,
      energySource: true,
      bikkieGraphicHints: ["powerCell", "homestone"],
    }),
  }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.certifiedPortalFuel,
    "Certified Portal Fuel Cell",
    {
      baseValue: 860,
      category: "fuel_cell",
      materialTier: 6,
      maxStackSize: 250,
      qualityFloor: 70,
      objectMetadata: exoticItemMetadata({
        objectKind: "fuel",
        physicalForm: "fuel_cell",
        colors: ["teal", "white", "gold seal"],
        visualDescription:
          "A portal fuel cell with a gold certification seal and a clean teal charge indicator.",
        materialComposition: [
          "Portal Fuel Cell",
          "containment filter audit seal",
        ],
        craftingRoles: [
          "public_portal_transit",
          "route_certification",
          "safe_customer_service",
        ],
        source: ["licensed Exotic Matter Refinery certification"],
        businessUse: ["portal_transit_company", "exotic_matter_refinery"],
        handling: [
          "approved for portal customers",
          "seal must remain unbroken",
        ],
        hazardClass: "certified_exotic_fuel",
        containmentRating: 98,
        energySource: true,
        bikkieGraphicHints: ["powerCell", "recipePaper"],
      }),
    }
  ),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.teleportFuel, "Teleport Fuel Cell", {
    baseValue: 1020,
    category: "fuel_cell",
    materialTier: 6,
    maxStackSize: 250,
    qualityFloor: 72,
    objectMetadata: exoticItemMetadata({
      objectKind: "fuel",
      physicalForm: "fuel_cell",
      colors: ["violet", "teal", "white"],
      visualDescription:
        "A violet-teal fuel cell tuned for teleport pads, with a tiny destination shimmer in its core.",
      materialComposition: [
        "Portal Fuel Cell",
        "Destination Crystal",
        "containment coolant",
      ],
      craftingRoles: [
        "teleport_jump_charge",
        "emergency_return",
        "pad_stabilization",
      ],
      source: ["teleport-grade Exotic Matter Refinery assembly"],
      businessUse: ["teleport_owner", "portal_transit_company"],
      handling: [
        "pair with a destination crystal",
        "never use in uncertified pads",
      ],
      hazardClass: "teleport_exotic_fuel",
      containmentRating: 96,
      energySource: true,
      bikkieGraphicHints: ["powerCell", "homestone"],
    }),
  }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.destinationCrystal,
    "Destination Crystal",
    {
      baseValue: 360,
      category: "routing_component",
      materialTier: 5,
      qualityFloor: 58,
      objectMetadata: exoticItemMetadata({
        objectKind: "component",
        physicalForm: "crystal",
        colors: ["violet", "clear blue", "white glint"],
        visualDescription:
          "A clear violet routing crystal that holds a destination lock as a thin blue internal line.",
        materialComposition: [
          "routing crystal",
          "coordinate etching",
          "field memory",
        ],
        craftingRoles: [
          "portal_route",
          "teleport_fuel",
          "alcubierre_drive_core",
        ],
        source: ["magic goods refinement", "portal office calibration"],
        businessUse: [
          "portal_transit_company",
          "teleport_owner",
          "magic_goods",
        ],
        handling: [
          "avoid scrambling the etched route",
          "calibrate before each route batch",
        ],
        hazardClass: "routing_crystal",
        containmentRating: 40,
        bikkieGraphicHints: ["homestone", "powerCell"],
      }),
    }
  ),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.anchorCore, "Portal Anchor Core", {
    baseValue: 1280,
    category: "core",
    materialTier: 6,
    maxStackSize: 100,
    qualityFloor: 68,
    objectMetadata: exoticItemMetadata({
      objectKind: "device",
      physicalForm: "core",
      colors: ["silver", "teal", "dark graphite"],
      visualDescription:
        "A dense silver-and-graphite core that locks a portal endpoint to a stable local frame.",
      materialComposition: [
        "Stabilized Exotic Matter Block",
        "Exotic Matter Power Cell",
        "iron frame",
        "crystal regulator",
      ],
      craftingRoles: [
        "portal_endpoint",
        "biome_anchor",
        "alcubierre_drive_core",
      ],
      source: ["refinery core assembly", "portal transit maintenance"],
      businessUse: ["portal_transit_company", "biome_maintenance_repair"],
      handling: [
        "install only on certified endpoints",
        "do not power without destination lock",
      ],
      hazardClass: "powered_anchor_core",
      containmentRating: 94,
      energySource: true,
      bikkieGraphicHints: ["powerCell", "homestone"],
    }),
  }),
  item(HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.utilityCore, "Utility Core", {
    baseValue: 980,
    category: "core",
    materialTier: 6,
    maxStackSize: 100,
    qualityFloor: 62,
    objectMetadata: exoticItemMetadata({
      objectKind: "device",
      physicalForm: "core",
      colors: ["steel", "white", "teal"],
      visualDescription:
        "A compact city-service core with teal bus lines wrapped around a white exotic matter regulator.",
      materialComposition: [
        "Stabilized Exotic Matter Block",
        "iron housing",
        "arcane dust regulator",
      ],
      craftingRoles: [
        "city_grid_power",
        "property_utility_hookup",
        "robot_power",
      ],
      source: ["industrial utility assembly"],
      businessUse: [
        "custom_home_property_development",
        "robotics",
        "biome_maintenance_repair",
      ],
      handling: [
        "mount in grounded utility frames",
        "inspect regulator before installation",
      ],
      hazardClass: "sealed_utility_core",
      containmentRating: 88,
      energySource: true,
      bikkieGraphicHints: ["powerCell", "workbench"],
    }),
  }),
  item(
    HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.alcubierreDriveCore,
    "Alcubierre Drive Core",
    {
      baseValue: 5200,
      category: "drive_core",
      materialTier: 7,
      maxStackSize: 20,
      qualityFloor: 80,
      objectMetadata: exoticItemMetadata({
        objectKind: "device",
        physicalForm: "device",
        colors: ["white", "violet", "teal", "gold"],
        visualDescription:
          "A high-end drive core with nested teal and violet rings around a white Exotic Matter heart.",
        materialComposition: [
          "Portal Anchor Core",
          "Utility Core",
          "Stabilized Exotic Matter Block",
          "Destination Crystal",
        ],
        craftingRoles: [
          "pocket_dimension_power",
          "teleportation",
          "wormhole_field_drive",
        ],
        source: ["master Exotic Matter Refinery assembly"],
        businessUse: [
          "exotic_matter_refinery",
          "portal_transit_company",
          "teleport_owner",
        ],
        handling: [
          "masterwork-only assembly",
          "requires route and containment audits before activation",
        ],
        hazardClass: "alcubierre_drive_component",
        containmentRating: 99,
        powerMegawattsPerUnit: 100400,
        energySource: true,
        lore: EXOTIC_MATTER_LORE_V1,
        bikkieGraphicHints: ["powerCell", "homestone", "thermoblaster"],
      }),
    }
  ),
];

const RECIPES: HarthmereCraftingRecipeV1[] = [
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.workbench,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 4 },
      { itemId: "iron_ingot", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    craftingTimeMs: 2500,
    xpReward: 20,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.thermolite,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 3 },
      { itemId: "iron_ingot", count: 2 },
      { itemId: "coal", count: 2 },
    ],
    requiredLevel: 2,
    requiredSkillId: "blacksmithing",
    requiredSkillLevel: 1,
    professionId: "blacksmithing",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 3500,
    xpReward: 30,
    recipeTier: 2,
    materialTier: 2,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.thermoblaster,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    outputCount: 1,
    inputs: [
      { itemId: "iron_ingot", count: 6 },
      { itemId: "crystal_shard", count: 2 },
      { itemId: "arcane_dust", count: 1 },
    ],
    requiredLevel: 4,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 2,
    professionId: "exotic_refining",
    requiredProfessionLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 6000,
    xpReward: 70,
    recipeTier: 4,
    materialTier: 4,
    qualityFloor: 50,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.kitchen,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.kitchen,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 3 },
      { itemId: "iron_ingot", count: 1 },
      { itemId: "coal", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2600,
    xpReward: 18,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.tailoringBooth,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 3 },
      { itemId: "linen_cloth", count: 2 },
    ],
    requiredLevel: 1,
    requiredSkillId: "tailoring",
    requiredSkillLevel: 1,
    professionId: "tailoring",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2800,
    xpReward: 20,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.seedMill,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.seedMill,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 3 },
      { itemId: "iron_ingot", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2400,
    xpReward: 16,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.anglersTable,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.anglersTable,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 2 },
      { itemId: "river_reed", count: 2 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2200,
    xpReward: 14,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.composter,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.composter,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 2 },
      { itemId: "rough_herb", count: 2 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2200,
    xpReward: 14,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_CRAFTING_STATION_RECIPE_IDS_V1.dyeOMatic,
    outputItemId: HARTHMERE_CRAFTING_STATIONS_V1.dyeOMatic,
    outputCount: 1,
    inputs: [
      { itemId: "iron_ingot", count: 2 },
      { itemId: "crystal_shard", count: 1 },
      { itemId: "arcane_dust", count: 1 },
    ],
    requiredLevel: 2,
    requiredSkillId: "alchemy",
    requiredSkillLevel: 1,
    professionId: "alchemy",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 3200,
    xpReward: 26,
    recipeTier: 2,
    materialTier: 2,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "crafting station setup",
  },
  {
    recipeId: HARTHMERE_HOME_DECORATION_RECIPE_IDS_V1.storageCabinet,
    outputItemId: HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.storageCabinet,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 4 },
      { itemId: "iron_ingot", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2200,
    xpReward: 16,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "home decoration",
  },
  {
    recipeId: HARTHMERE_HOME_DECORATION_RECIPE_IDS_V1.hearthLamp,
    outputItemId: HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.hearthLamp,
    outputCount: 1,
    inputs: [
      { itemId: "iron_ingot", count: 1 },
      { itemId: "crystal_shard", count: 1 },
      { itemId: "arcane_dust", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "enchanting",
    requiredSkillLevel: 1,
    professionId: "enchanting",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2200,
    xpReward: 18,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "home decoration",
  },
  {
    recipeId: HARTHMERE_HOME_DECORATION_RECIPE_IDS_V1.gardenPlanterBox,
    outputItemId: HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.gardenPlanterBox,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 2 },
      { itemId: "rough_herb", count: 1 },
      { itemId: "grain_seed", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    professionId: "carpentry",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2200,
    xpReward: 16,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "home decoration",
  },
  {
    recipeId: HARTHMERE_HOME_DECORATION_RECIPE_IDS_V1.businessServiceCounter,
    outputItemId: HARTHMERE_HOME_DECORATION_ITEM_IDS_V1.businessServiceCounter,
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 5 },
      { itemId: "linen_cloth", count: 1 },
    ],
    requiredLevel: 2,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 2,
    professionId: "carpentry",
    requiredProfessionLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    craftingTimeMs: 2800,
    xpReward: 24,
    recipeTier: 2,
    materialTier: 1,
    qualityFloor: 45,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "home decoration",
  },
  {
    recipeId: "harthmere_blacksmith_iron_ingot",
    outputItemId: "iron_ingot",
    outputCount: 1,
    inputs: [{ itemId: "iron_ore", count: 3 }],
    fuelInputs: [{ itemId: "coal", count: 1 }],
    requiredLevel: 1,
    requiredSkillId: "smithing",
    requiredSkillLevel: 1,
    professionId: "blacksmithing",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
    requiredToolActions: ["destroy"],
    minToolTier: 1,
    toolDurabilityCost: 1,
    craftingTimeMs: 2500,
    xpReward: 18,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 30,
    businessTypeId: "weapons_tools",
    workOrderTag: "smelting",
  },
  {
    recipeId: "harthmere_blacksmith_iron_sword",
    outputItemId: "iron_sword",
    outputCount: 1,
    inputs: [
      { itemId: "iron_ingot", count: 3 },
      { itemId: "wood_plank", count: 1 },
    ],
    requiredLevel: 2,
    requiredSkillId: "smithing",
    requiredSkillLevel: 2,
    professionId: "blacksmithing",
    requiredProfessionLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    toolDurabilityCost: 2,
    optionalReagents: [
      { itemId: "arcane_dust", count: 1, qualityBonus: 8, successBonus: 0.05 },
    ],
    goldCost: 3,
    successChance: 0.92,
    failureMaterialRefundPercent: 0.25,
    craftingTimeMs: 5000,
    xpReward: 45,
    recipeTier: 1,
    materialTier: 1,
    qualityFloor: 35,
    durabilityMax: 120,
    businessTypeId: "weapons_tools",
    workOrderTag: "weapon_commission",
  },
  {
    recipeId: "harthmere_blacksmith_repair_iron_sword",
    outputItemId: "iron_sword",
    outputCount: 0,
    inputs: [{ itemId: "repair_part", count: 1 }],
    requiredLevel: 1,
    requiredSkillId: "smithing",
    requiredSkillLevel: 1,
    professionId: "blacksmithing",
    requiredProfessionLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    targetItemIds: ["iron_sword", "iron_sword_reinforced", "warded_iron_sword"],
    workflowKind: "repair",
    goldCost: 2,
    craftingTimeMs: 1500,
    xpReward: 12,
    businessTypeId: "weapons_tools",
    workOrderTag: "repair_queue",
  },
  {
    recipeId: "harthmere_blacksmith_upgrade_iron_sword",
    outputItemId: "iron_sword_reinforced",
    outputCount: 1,
    inputs: [
      { itemId: "iron_ingot", count: 2 },
      { itemId: "upgrade_crystal", count: 1 },
    ],
    requiredLevel: 3,
    requiredSkillId: "smithing",
    requiredSkillLevel: 3,
    professionId: "blacksmithing",
    requiredProfessionLevel: 3,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    targetItemIds: ["iron_sword"],
    consumeTargetOnSuccess: true,
    workflowKind: "upgrade",
    successChance: 0.85,
    failureMaterialRefundPercent: 0.1,
    craftingTimeMs: 6500,
    xpReward: 75,
    recipeTier: 2,
    materialTier: 2,
    businessTypeId: "weapons_tools",
    workOrderTag: "item_upgrade",
  },
  {
    recipeId: "harthmere_blacksmith_salvage_iron_sword",
    outputItemId: "iron_ingot",
    outputCount: 1,
    inputs: [],
    requiredLevel: 1,
    requiredSkillId: "smithing",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    targetItemIds: ["iron_sword", "iron_sword_reinforced"],
    consumeTargetOnSuccess: true,
    workflowKind: "salvage",
    craftingTimeMs: 1200,
    xpReward: 8,
    businessTypeId: "weapons_tools",
    workOrderTag: "salvage",
  },
  {
    recipeId: "harthmere_carpentry_wood_plank",
    outputItemId: "wood_plank",
    outputCount: 3,
    inputs: [{ itemId: "wood_log", count: 2 }],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["destroy"],
    craftingTimeMs: 1500,
    xpReward: 12,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "lumber",
  },
  {
    recipeId: "harthmere_carpentry_hunter_bow",
    outputItemId: "hunter_bow",
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 3 },
      { itemId: "flax_fiber", count: 2 },
    ],
    requiredLevel: 2,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolActions: ["shape"],
    successChance: 0.9,
    craftingTimeMs: 4500,
    xpReward: 38,
    durabilityMax: 90,
    businessTypeId: "weapons_tools",
    workOrderTag: "bow_commission",
  },
  {
    recipeId: "harthmere_carpentry_road_repair_kit",
    outputItemId: "road_repair_kit",
    outputCount: 1,
    inputs: [
      { itemId: "wood_plank", count: 2 },
      { itemId: "iron_ingot", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "carpentry",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    craftingTimeMs: 3000,
    xpReward: 24,
    teachesRecipesOnSuccess: ["harthmere_carpentry_hunter_bow"],
    businessTypeId: "custom_home_property_development",
    workOrderTag: "town_repair",
  },
  {
    recipeId: "harthmere_leatherworking_boiled_leather",
    outputItemId: "boiled_leather",
    outputCount: 1,
    inputs: [{ itemId: "rough_hide", count: 2 }],
    fuelInputs: [{ itemId: "coal", count: 1 }],
    requiredLevel: 1,
    requiredSkillId: "leatherworking",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    craftingTimeMs: 2400,
    xpReward: 16,
    businessTypeId: "general_trader",
    workOrderTag: "hide_processing",
  },
  {
    recipeId: "harthmere_leatherworking_armor",
    outputItemId: "leather_armor",
    outputCount: 1,
    inputs: [
      { itemId: "boiled_leather", count: 4 },
      { itemId: "linen_cloth", count: 1 },
    ],
    requiredLevel: 2,
    requiredSkillId: "leatherworking",
    requiredSkillLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
    requiredToolActions: ["shape"],
    successChance: 0.9,
    craftingTimeMs: 5200,
    xpReward: 48,
    durabilityMax: 110,
    businessTypeId: "general_trader",
    workOrderTag: "armor_commission",
  },
  {
    recipeId: "harthmere_tailoring_linen_cloth",
    outputItemId: "linen_cloth",
    outputCount: 2,
    inputs: [{ itemId: "flax_fiber", count: 3 }],
    requiredLevel: 1,
    requiredSkillId: "tailoring",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
    craftingTimeMs: 1800,
    xpReward: 14,
    businessTypeId: "general_trader",
    workOrderTag: "textiles",
  },
  {
    recipeId: "harthmere_tailoring_travel_cloak",
    outputItemId: "travel_cloak",
    outputCount: 1,
    inputs: [{ itemId: "linen_cloth", count: 4 }],
    optionalReagents: [{ itemId: "arcane_dust", count: 1, qualityBonus: 10 }],
    requiredLevel: 2,
    requiredSkillId: "tailoring",
    requiredSkillLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.tailoringBooth,
    successChance: 0.95,
    craftingTimeMs: 4200,
    xpReward: 38,
    durabilityMax: 80,
    businessTypeId: "general_trader",
    workOrderTag: "clothing_commission",
  },
  {
    recipeId: "harthmere_alchemy_herbal_extract",
    outputItemId: "herbal_extract",
    outputCount: 1,
    inputs: [{ itemId: "rough_herb", count: 5 }],
    requiredLevel: 1,
    requiredSkillId: "alchemy",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.workbench,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    craftingTimeMs: 1800,
    xpReward: 14,
    businessTypeId: "magic_goods",
    workOrderTag: "herbalism",
  },
  {
    recipeId: "harthmere_alchemy_health_potion",
    outputItemId: "health_potion",
    outputCount: 2,
    inputs: [
      { itemId: "herbal_extract", count: 1 },
      { itemId: "river_reed", count: 1 },
    ],
    optionalReagents: [
      { itemId: "arcane_dust", count: 1, qualityBonus: 8, successBonus: 0.03 },
    ],
    requiredLevel: 1,
    requiredSkillId: "alchemy",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.kitchen,
    successChance: 0.93,
    craftingTimeMs: 2600,
    xpReward: 26,
    businessTypeId: "magic_goods",
    workOrderTag: "potion_batch",
  },
  {
    recipeId: "harthmere_alchemy_antidote",
    outputItemId: "antidote",
    outputCount: 2,
    inputs: [
      { itemId: "herbal_extract", count: 1 },
      { itemId: "rough_herb", count: 2 },
    ],
    requiredLevel: 2,
    requiredSkillId: "alchemy",
    requiredSkillLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.kitchen,
    successChance: 0.9,
    craftingTimeMs: 3000,
    xpReward: 32,
    businessTypeId: "magic_goods",
    workOrderTag: "medicine",
  },
  {
    recipeId: "harthmere_enchant_warded_iron_sword",
    outputItemId: "warded_iron_sword",
    outputCount: 1,
    inputs: [
      { itemId: "arcane_dust", count: 2 },
      { itemId: "crystal_shard", count: 1 },
    ],
    requiredLevel: 4,
    requiredSkillId: "enchanting",
    requiredSkillLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    targetItemIds: ["iron_sword_reinforced"],
    consumeTargetOnSuccess: true,
    workflowKind: "enchant",
    successChance: 0.78,
    failureMaterialRefundPercent: 0.2,
    craftingTimeMs: 8000,
    xpReward: 90,
    recipeTier: 3,
    materialTier: 3,
    businessTypeId: "magic_goods",
    workOrderTag: "enchanting",
  },
  {
    recipeId: "harthmere_bell_bronze_ingot",
    outputItemId: "bell_bronze_ingot",
    outputCount: 1,
    inputs: [
      { itemId: "bell_metal_fragment", count: 2 },
      { itemId: "tin_ingot", count: 1 },
    ],
    optionalReagents: [
      {
        itemId: "meteoric_trace",
        count: 1,
        qualityBonus: 15,
        successBonus: 0.08,
      },
    ],
    requiredLevel: 3,
    requiredSkillId: "bell_forging",
    requiredSkillLevel: 2,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
    requiredToolActions: ["shape"],
    successChance: 0.88,
    craftingTimeMs: 5500,
    xpReward: 64,
    recipeTier: 2,
    materialTier: 2,
    businessTypeId: "weapons_tools",
    workOrderTag: "bell_forging",
  },
  {
    recipeId: "harthmere_bellbinders_voice",
    outputItemId: "bellbinders_voice",
    outputCount: 1,
    inputs: [
      { itemId: "bell_bronze_ingot", count: 1 },
      { itemId: "meteoric_trace", count: 1 },
    ],
    requiredLevel: 5,
    requiredSkillId: "bell_forging",
    requiredSkillLevel: 3,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermolite,
    requiredToolActions: ["shape"],
    workflowKind: "quest_forge",
    questId: "bellbound_q5",
    questStepIds: [
      "smelt_meteoric_trace",
      "match_alloy_ratio",
      "strike_rhythm",
      "tune_bell",
    ],
    successChance: 1,
    qualityFloor: 70,
    outputBinding: "quest",
    craftingTimeMs: 10000,
    xpReward: 125,
    teachesRecipesOnSuccess: ["harthmere_bell_bronze_ingot"],
    recipeTier: 3,
    materialTier: 3,
    workOrderTag: "bellbound_q5",
  },
  {
    recipeId: "harthmere_angler_fishing_lure",
    outputItemId: "fishing_lure",
    outputCount: 3,
    inputs: [
      { itemId: "river_reed", count: 2 },
      { itemId: "arcane_dust", count: 1 },
    ],
    requiredLevel: 1,
    requiredSkillId: "fishing",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.anglersTable,
    requiredToolActions: ["fish"],
    craftingTimeMs: 1800,
    xpReward: 16,
    businessTypeId: "hunter_wild_meat",
    workOrderTag: "fishing_supply",
  },
  {
    recipeId: "harthmere_seed_mill_grain_flour",
    outputItemId: "grain_flour",
    outputCount: 2,
    inputs: [{ itemId: "grain_seed", count: 4 }],
    requiredLevel: 1,
    requiredSkillId: "cooking",
    requiredSkillLevel: 1,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.seedMill,
    craftingTimeMs: 1700,
    xpReward: 12,
    businessTypeId: "food_service_restaurant",
    workOrderTag: "milling",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.antihydrogenBlock,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antihydrogenBlock,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiprotonCapsule,
        count: 1,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.positronCapsule, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 1,
      },
    ],
    requiredLevel: 4,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 3,
    professionId: "exotic_refining",
    requiredProfessionLevel: 3,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 1,
    successChance: 0.94,
    failureMaterialRefundPercent: 0.25,
    craftingTimeMs: 7000,
    xpReward: 85,
    recipeTier: 4,
    materialTier: 5,
    qualityFloor: 45,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "antimatter_block_synthesis",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.antiheliumBlock,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiheliumBlock,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiprotonCapsule,
        count: 2,
      },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antineutronCapsule,
        count: 2,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.positronCapsule, count: 2 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 1,
      },
    ],
    requiredLevel: 5,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 4,
    professionId: "exotic_refining",
    requiredProfessionLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 1,
    successChance: 0.9,
    failureMaterialRefundPercent: 0.25,
    craftingTimeMs: 9000,
    xpReward: 120,
    recipeTier: 5,
    materialTier: 5,
    qualityFloor: 48,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "antimatter_block_synthesis",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.antiboronBlock,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiboronBlock,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiprotonCapsule,
        count: 5,
      },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antineutronCapsule,
        count: 6,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.positronCapsule, count: 5 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 2,
      },
    ],
    optionalReagents: [
      {
        itemId: "arcane_dust",
        count: 1,
        qualityBonus: 10,
        successBonus: 0.04,
      },
    ],
    requiredLevel: 6,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 5,
    professionId: "exotic_refining",
    requiredProfessionLevel: 5,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 2,
    successChance: 0.84,
    failureMaterialRefundPercent: 0.2,
    craftingTimeMs: 12000,
    xpReward: 170,
    recipeTier: 6,
    materialTier: 6,
    qualityFloor: 52,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "antimatter_block_synthesis",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.rawExoticMatter,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.rawExoticMatter,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antihydrogenBlock,
        count: 1,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiheliumBlock, count: 1 },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.antiboronBlock, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 2,
      },
    ],
    optionalReagents: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizingCrystal,
        count: 1,
        qualityBonus: 12,
        successBonus: 0.05,
      },
    ],
    requiredLevel: 6,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 5,
    professionId: "exotic_refining",
    requiredProfessionLevel: 5,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 2,
    goldCost: 15,
    successChance: 0.88,
    failureMaterialRefundPercent: 0.2,
    craftingTimeMs: 15000,
    xpReward: 220,
    recipeTier: 6,
    materialTier: 6,
    qualityFloor: 58,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "raw_exotic_matter_synthesis",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.stabilizedExoticMatter,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
    outputCount: 1,
    inputs: [
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.rawExoticMatter, count: 2 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizingCrystal,
        count: 1,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.coolant, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 1,
      },
    ],
    requiredLevel: 6,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 5,
    professionId: "exotic_refining",
    requiredProfessionLevel: 5,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 2,
    goldCost: 10,
    successChance: 0.93,
    failureMaterialRefundPercent: 0.3,
    craftingTimeMs: 13000,
    xpReward: 240,
    recipeTier: 6,
    materialTier: 6,
    qualityFloor: 70,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "stabilization",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.powerCell,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.exoticMatterPowerCell,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
        count: 1,
      },
      { itemId: "iron_ingot", count: 1 },
      { itemId: "crystal_shard", count: 1 },
    ],
    requiredLevel: 5,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 4,
    professionId: "exotic_refining",
    requiredProfessionLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolActions: ["shape"],
    toolDurabilityCost: 1,
    successChance: 0.95,
    craftingTimeMs: 8000,
    xpReward: 115,
    recipeTier: 5,
    materialTier: 6,
    qualityFloor: 65,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "power_cell_assembly",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.portalFuel,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.portalFuel,
    outputCount: 2,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.exoticMatterPowerCell,
        count: 1,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.coolant, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 1,
      },
    ],
    requiredLevel: 5,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 4,
    professionId: "exotic_refining",
    requiredProfessionLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 1,
    successChance: 0.96,
    craftingTimeMs: 7000,
    xpReward: 105,
    recipeTier: 5,
    materialTier: 6,
    qualityFloor: 60,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "portal_fuel_assembly",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.certifiedPortalFuel,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.certifiedPortalFuel,
    outputCount: 1,
    inputs: [
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.portalFuel, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.containmentFilter,
        count: 1,
      },
    ],
    requiredLevel: 5,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 4,
    professionId: "exotic_refining",
    requiredProfessionLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    successChance: 0.98,
    goldCost: 5,
    craftingTimeMs: 4500,
    xpReward: 65,
    recipeTier: 5,
    materialTier: 6,
    qualityFloor: 70,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "fuel_certification",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.teleportFuel,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.teleportFuel,
    outputCount: 1,
    inputs: [
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.portalFuel, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.destinationCrystal,
        count: 1,
      },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.coolant, count: 1 },
    ],
    requiredLevel: 6,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 5,
    professionId: "exotic_refining",
    requiredProfessionLevel: 5,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolIds: [HARTHMERE_CRAFTING_TOOLS_V1.bucket],
    toolDurabilityCost: 1,
    successChance: 0.94,
    craftingTimeMs: 7500,
    xpReward: 125,
    recipeTier: 6,
    materialTier: 6,
    qualityFloor: 72,
    businessTypeId: "teleport_owner",
    workOrderTag: "teleport_fuel_assembly",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.anchorCore,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.anchorCore,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
        count: 1,
      },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.exoticMatterPowerCell,
        count: 1,
      },
      { itemId: "iron_ingot", count: 2 },
      { itemId: "crystal_shard", count: 1 },
    ],
    requiredLevel: 6,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 5,
    professionId: "exotic_refining",
    requiredProfessionLevel: 5,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolActions: ["shape"],
    toolDurabilityCost: 2,
    successChance: 0.91,
    failureMaterialRefundPercent: 0.15,
    craftingTimeMs: 14000,
    xpReward: 190,
    recipeTier: 6,
    materialTier: 6,
    qualityFloor: 68,
    businessTypeId: "portal_transit_company",
    workOrderTag: "portal_anchor_core",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.utilityCore,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.utilityCore,
    outputCount: 1,
    inputs: [
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
        count: 1,
      },
      { itemId: "iron_ingot", count: 2 },
      { itemId: "arcane_dust", count: 1 },
    ],
    requiredLevel: 5,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 4,
    professionId: "exotic_refining",
    requiredProfessionLevel: 4,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolActions: ["shape"],
    toolDurabilityCost: 1,
    successChance: 0.94,
    craftingTimeMs: 9000,
    xpReward: 125,
    recipeTier: 5,
    materialTier: 6,
    qualityFloor: 62,
    businessTypeId: "custom_home_property_development",
    workOrderTag: "utility_core",
  },
  {
    recipeId: HARTHMERE_EXOTIC_MATTER_RECIPE_IDS_V1.alcubierreDriveCore,
    outputItemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.alcubierreDriveCore,
    outputCount: 1,
    inputs: [
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.anchorCore, count: 1 },
      { itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.utilityCore, count: 1 },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.stabilizedExoticMatter,
        count: 2,
      },
      {
        itemId: HARTHMERE_EXOTIC_MATTER_ITEM_IDS_V1.destinationCrystal,
        count: 1,
      },
    ],
    optionalReagents: [
      {
        itemId: "arcane_dust",
        count: 2,
        qualityBonus: 14,
        successBonus: 0.05,
      },
    ],
    requiredLevel: 9,
    requiredSkillId: "exotic_refining",
    requiredSkillLevel: 7,
    professionId: "exotic_refining",
    requiredProfessionLevel: 7,
    requiredStationId: HARTHMERE_CRAFTING_STATIONS_V1.thermoblaster,
    requiredToolActions: ["shape"],
    toolDurabilityCost: 3,
    goldCost: 50,
    successChance: 0.86,
    failureMaterialRefundPercent: 0.15,
    craftingTimeMs: 24000,
    xpReward: 420,
    recipeTier: 7,
    materialTier: 7,
    qualityFloor: 80,
    businessTypeId: "exotic_matter_refinery",
    workOrderTag: "alcubierre_drive_core",
  },
];

let registered = false;

export function ensureHarthmereProductionCraftingCatalogueV1() {
  if (registered) return;
  registered = true;
  for (const station of STATIONS) {
    if (!getHarthmereCraftingStationV1(station.stationId)) {
      registerHarthmereCraftingStationV1(station);
    }
  }
  for (const tool of TOOLS) {
    if (!getHarthmereCraftingToolV1(tool.itemId)) {
      registerHarthmereCraftingToolV1(tool);
    }
    if (!getHarthmereItemDefinitionV1(tool.itemId)) {
      registerHarthmereItemDefinitionV1(
        item(tool.itemId, tool.displayName, {
          maxStackSize: 1,
          baseValue: Math.max(1, tool.tier ?? 1) * 20,
          isCraftingMaterial: false,
          category: "tool",
          durabilityMax: tool.durabilityMax,
          stats: { toolTier: tool.tier ?? 1 },
        })
      );
    }
  }
  for (const def of ITEMS) {
    if (!getHarthmereItemDefinitionV1(def.itemId)) {
      registerHarthmereItemDefinitionV1(def);
    }
  }
  for (const recipe of RECIPES) {
    if (!getHarthmereCraftingRecipeV1(recipe.recipeId)) {
      registerHarthmereCraftingRecipeV1(recipe);
    }
  }
}

export function harthmereProductionCraftingRecipeIdsV1() {
  ensureHarthmereProductionCraftingCatalogueV1();
  return RECIPES.map((recipe) => recipe.recipeId);
}
