// HARTHMERE_NPC_DIALOGUE_EXPRESSION_PLAN
//
// Authoring-only expression assignments for non-quest Harthmere dialogue and
// Grove quests. Runtime code consumes the generated hashed-text catalog so the
// client does not have to bundle the full NPC compendium just to look up an
// expression for the currently visible line.

import type { HarthmereCinematicExpression } from "@/shared/cutscene/cinematic_expressions";

export type HarthmereCompendiumDialogueExpressionTuple = readonly [
  greeting: HarthmereCinematicExpression,
  service: HarthmereCinematicExpression,
  rumor: HarthmereCinematicExpression,
  farewell: HarthmereCinematicExpression
];

export type HarthmereThreeLineDialogueExpressionTuple = readonly [
  first: HarthmereCinematicExpression | undefined,
  second: HarthmereCinematicExpression | undefined,
  third: HarthmereCinematicExpression | undefined
];

export const HARTHMERE_COMPENDIUM_DIALOGUE_EXPRESSION_PLAN = {
  sergeant_bram_holt: ["guard", "determined", "thinking", "salute"],
  walt_ormsby: ["guard", "determined", "thinking", "salute"],
  mara_thistle: ["curiosity", "thinking", "nervousness", "thumbsUp"],
  edrik_vane: ["salute", "thinking", "uncertainty", "salute"],
  reeve_caldus_merrow: ["guard", "determined", "nervousness", "salute"],
  master_osric_vale: ["curiosity", "checkingEquipment", "thinking", "thumbsUp"],
  apprentice_luth: [
    "nervousness",
    "checkingEquipment",
    "uncertainty",
    "salute",
  ],
  master_garrik_fen: [
    "curiosity",
    "checkingEquipment",
    "uncertainty",
    "salute",
  ],
  helna_voss: ["determined", "checkingEquipment", "thinking", "thumbsUp"],
  selka_doryn: ["salute", "checkingEquipment", "nervousness", "salute"],
  ysabet_fenlow: ["determined", "thinking", "uncertainty", "gratitude"],
  old_jory_brann: ["curiosity", "checkingEquipment", "uncertainty", "salute"],
  dawn_loaf: ["curiosity", "determined", "nervousness", "salute"],
  tovin_reed: ["salute", "checkingEquipment", "uncertainty", "salute"],
  lina_reed: ["shyness", "curiosity", "nervousness", "salute"],
  sora_reed: ["curiosity", "ready", "thinking", "thumbsUp"],
  father_aldren_mell: ["curiosity", "thinking", "uncertainty", "bow"],
  sister_maelle_frenn: ["salute", "gratitude", "nervousness", "bow"],
  brother_vance_holt: ["determined", "thinking", "uncertainty", "bow"],
  brother_halpen_wren: ["curiosity", "thinking", "uncertainty", "bow"],
  elowen_pike: ["curiosity", "beckon", "thinking", "thumbsUp"],
  tisa_pike: ["annoyance", "curiosity", "nervousness", "ready"],
  cellan_bow: ["determined", "rally", "thinking", "salute"],
  nessa_crowe: ["determined", "guard", "uncertainty", "salute"],
  old_tam_crowe: ["curiosity", "thinking", "nervousness", "salute"],
  boy_tam: ["nervousness", "curiosity", "fear", "determined"],
  banker_merl_voss: ["salute", "checkingEquipment", "thinking", "salute"],
  courier_anwen_mell: [
    "curiosity",
    "checkingEquipment",
    "uncertainty",
    "salute",
  ],
  auction_pell_marsten: ["curiosity", "determined", "thinking", "salute"],
  erena_voss: ["determined", "checkingEquipment", "nervousness", "salute"],
  lady_henrietta_merrow: ["curiosity", "thinking", "uncertainty", "bow"],
  lila_merrow: ["salute", "thinking", "nervousness", "thumbsUp"],
  ren_skell: ["annoyance", "checkingEquipment", "uncertainty", "salute"],
  lord_wrethan_pell: ["determined", "thinking", "nervousness", "bow"],
  henrick_brell: ["curiosity", "checkingEquipment", "thinking", "salute"],
  veska_reed: ["salute", "guard", "uncertainty", "ready"],
  edda_wren: ["salute", "guard", "nervousness", "salute"],
  merrit_bracken: ["salute", "checkingEquipment", "uncertainty", "salute"],
  sella_reedfoot: ["determined", "guard", "thinking", "salute"],
  tamsin_vale: ["determined", "ready", "nervousness", "thumbsUp"],
  brother_cael_marsen: ["curiosity", "sadness", "nervousness", "bow"],
  rusk_hallowhand: ["salute", "guard", "uncertainty", "salute"],
  veneth_moss_woman: ["curiosity", "thinking", "uncertainty", "bow"],
  tessen_hark: ["determined", "uncertainty", "nervousness", "salute"],
  yenna_holt: ["curiosity", "sadness", "nervousness", "thumbsUp"],
  bree_thistle: ["sadness", "depression", "uncertainty", "relief"],
  corvin_bree_friend: ["annoyance", "curiosity", "nervousness", "salute"],
  harlo_grain_merchant: ["curiosity", "thinking", "nervousness", "salute"],
  rinna_fishmonger: [
    "curiosity",
    "checkingEquipment",
    "uncertainty",
    "thumbsUp",
  ],
  drathmar_envoy: ["salute", "thinking", "nervousness", "bow"],
  crown_auditor_selwyn: [
    "annoyance",
    "checkingEquipment",
    "nervousness",
    "determined",
  ],
  noble_widow_avelina: ["curiosity", "sadness", "uncertainty", "salute"],
  barge_captain_orren: [
    "determined",
    "checkingEquipment",
    "nervousness",
    "salute",
  ],
  merrit_apprentice_pell: ["salute", "exhaustion", "nervousness", "thumbsUp"],
  veska_brother_alen: ["curiosity", "sadness", "uncertainty", "salute"],
  evicted_couple_hobb: ["nervousness", "sadness", "nervousness", "gratitude"],
  vera_harth: ["determined", "sadness", "confusion", "salute"],
  old_harth: ["curiosity", "sadness", "nervousness", "bow"],
  outside_gate_father: ["determined", "guard", "uncertainty", "salute"],
  outside_gate_mother: ["annoyance", "fear", "nervousness", "salute"],
  outside_gate_child: ["shyness", "nervousness", "uncertainty", "thumbsUp"],
  north_gate_day_guard: ["salute", "guard", "thinking", "salute"],
  north_gate_night_guard: ["determined", "guard", "thinking", "salute"],
  toll_clerk: ["salute", "checkingEquipment", "nervousness", "salute"],
  gate_peddler: ["salute", "thinking", "uncertainty", "salute"],
  gate_farmer: ["annoyance", "checkingEquipment", "nervousness", "determined"],
  caravan_hand: ["salute", "checkingEquipment", "thinking", "salute"],
  beggar_child_gate: ["shyness", "nervousness", "nervousness", "gratitude"],
  food_seller: ["curiosity", "thinking", "thinking", "thumbsUp"],
  cloth_trader: ["annoyance", "checkingEquipment", "nervousness", "thumbsUp"],
  spice_trader: ["curiosity", "thinking", "uncertainty", "salute"],
  market_clerk: ["curiosity", "checkingEquipment", "thinking", "salute"],
  gossip_elder: ["curiosity", "thinking", "uncertainty", "salute"],
  fountain_child: ["determined", "curiosity", "nervousness", "salute"],
  market_performer: ["annoyance", "beckon", "uncertainty", "ready"],
  stock_keeper: ["annoyance", "checkingEquipment", "nervousness", "thumbsUp"],
  inn_cook: ["determined", "checkingEquipment", "thinking", "thumbsUp"],
  room_attendant: ["annoyance", "checkingEquipment", "uncertainty", "thumbsUp"],
  traveler_patron: ["curiosity", "thinking", "uncertainty", "salute"],
  roleplay_patron: ["annoyance", "thinking", "nervousness", "thumbsUp"],
  mail_runner: ["determined", "ready", "thinking", "salute"],
  forge_apprentice: ["curiosity", "checkingEquipment", "nervousness", "ready"],
  carpenter_apprentice: [
    "curiosity",
    "checkingEquipment",
    "thinking",
    "salute",
  ],
  porter: ["determined", "checkingEquipment", "uncertainty", "salute"],
  tanner: ["curiosity", "checkingEquipment", "thinking", "salute"],
  alchemy_runner: ["curiosity", "checkingEquipment", "uncertainty", "thumbsUp"],
  chapel_pilgrim: ["curiosity", "gratitude", "thinking", "bow"],
  mourner: ["sadness", "depression", "uncertainty", "gratitude"],
  candle_server: ["curiosity", "gratitude", "nervousness", "ready"],
  charity_worker: ["curiosity", "gratitude", "uncertainty", "salute"],
  noble_clerk: ["determined", "checkingEquipment", "uncertainty", "bow"],
  house_servant: ["determined", "checkingEquipment", "uncertainty", "salute"],
  debt_shaken_debtor: ["nervousness", "shame", "fear", "relief"],
  private_guard: ["curiosity", "guard", "nervousness", "salute"],
  docker: ["curiosity", "checkingEquipment", "thinking", "salute"],
  ferryman: ["curiosity", "checkingEquipment", "thinking", "salute"],
  fishmonger: ["salute", "checkingEquipment", "thinking", "salute"],
  bargeman: ["curiosity", "checkingEquipment", "nervousness", "salute"],
  dock_inspector: ["annoyance", "checkingEquipment", "nervousness", "thumbsUp"],
  mudden_laborer: ["curiosity", "checkingEquipment", "nervousness", "thumbsUp"],
  mudden_widow: ["determined", "sadness", "uncertainty", "gratitude"],
  mudden_child: ["curiosity", "nervousness", "thinking", "thumbsUp"],
  rat_catcher: ["salute", "checkingEquipment", "thinking", "salute"],
  informal_trader: ["curiosity", "thinking", "nervousness", "ready"],
  mudden_lookout: ["curiosity", "guard", "nervousness", "ready"],
  old_well_scavenger: ["determined", "guard", "fear", "retreat"],
  secretive_figure: ["curiosity", "uncertainty", "nervousness", "retreat"],
  last_watch_tired_guard_a: ["salute", "guard", "nervousness", "salute"],
  last_watch_tired_guard_b: ["salute", "guard", "uncertainty", "salute"],
  miller: ["annoyance", "checkingEquipment", "nervousness", "thumbsUp"],
  orchard_worker: ["salute", "checkingEquipment", "uncertainty", "salute"],
  shepherd: ["curiosity", "guard", "nervousness", "thumbsUp"],
  woodcutter: ["salute", "checkingEquipment", "uncertainty", "salute"],
  hunter_marker_keeper: ["curiosity", "guard", "uncertainty", "salute"],
  quarry_miner: ["determined", "checkingEquipment", "thinking", "salute"],
} as const satisfies Record<string, HarthmereCompendiumDialogueExpressionTuple>;

export const HARTHMERE_ADDITIVE_TOWN_DIALOGUE_EXPRESSION_PLAN = {
  1: ["beckon", "gratitude", "determined"],
  2: [undefined, undefined, undefined],
  3: ["checkingEquipment", "determined", "guard"],
  4: [undefined, undefined, undefined],
  5: ["ready", "love", "nervousness"],
  6: ["salute", "thinking", "uncertainty"],
  7: ["guard", "checkingEquipment", "determined"],
  8: ["comeHere", "sadness", "determined"],
  9: ["curiosity", "thinking", "uncertainty"],
  10: ["annoyance", "thumbsUp", "guard"],
  11: ["beckon", "thinking", "guard"],
  12: ["guard", "nervousness", "uncertainty"],
  13: ["beckon", "thinking", "uncertainty"],
  14: ["taunt", "curiosity", "thinking"],
  15: ["curiosity", "thinking", "uncertainty"],
  16: ["taunt", "thinking", "rally"],
  17: ["ready", "determined", "guard"],
  18: ["determined", "thinking", "stop"],
  19: ["ready", "thinking", "checkingEquipment"],
  20: ["comeHere", "gratitude", "sadness"],
  21: ["ready", "curiosity", "nervousness"],
  22: ["ready", "thinking", "uncertainty"],
  23: ["beckon", "love", "relief"],
  24: ["curiosity", "thinking", "guard"],
  25: ["curiosity", "thumbsUp", "guard"],
  26: ["ready", "checkingEquipment", "determined"],
  27: ["guard", "sadness", "determined"],
  28: ["annoyance", "love", "thinking"],
  29: ["checkingEquipment", "sadness", "guard"],
  30: ["beckon", "love", "thinking"],
  31: ["beckon", "shame", "pray"],
  32: ["determined", "uncertainty", "thinking"],
  33: ["guard", "anger", "guard"],
  34: ["guard", "uncertainty", "nervousness"],
  35: ["curiosity", "thinking", "uncertainty"],
  36: ["salute", "thinking", "uncertainty"],
  37: ["curiosity", "thinking", "uncertainty"],
  38: ["guard", "nervousness", "stop"],
  39: ["annoyance", "frustration", "thinking"],
  40: ["uncertainty", "determined", "guard"],
  42: ["rally", "thinking", "uncertainty"],
  43: ["ready", "determined", "nervousness"],
  44: ["guard", "sadness", "determined"],
  45: ["checkingEquipment", "thinking", "guard"],
  46: ["comeHere", "sadness", "gratitude"],
  47: ["checkingEquipment", "uncertainty", "thinking"],
  48: ["curiosity", "uncertainty", "guard"],
  49: ["checkingEquipment", "thinking", "uncertainty"],
  50: ["curiosity", "thinking", "uncertainty"],
  51: ["guard", "determined", "uncertainty"],
  52: ["shyness", "nervousness", "guard"],
  53: ["curiosity", "sadness", "frustration"],
  54: ["facepalm", "frustration", "impatience"],
  55: ["determined", "uncertainty", "nervousness"],
  56: ["checkingEquipment", "frustration", "guard"],
  57: ["beckon", "curiosity", "nervousness"],
  58: ["beckon", "thumbsUp", "gratitude"],
  59: ["checkingEquipment", "thinking", "uncertainty"],
  60: ["annoyance", "curiosity", "thinking"],
  61: ["taunt", "curiosity", "guard"],
  62: ["shock", "fear", "stop"],
  63: ["curiosity", "uncertainty", "guard"],
  64: ["checkingEquipment", "thinking", "gratitude"],
  65: ["uncertainty", "determined", "guard"],
  66: ["shyness", "fear", "curiosity"],
  67: ["nervousness", "confusion", "determined"],
  68: ["embarrassment", "determined", "nervousness"],
  69: ["guard", "determined", "stop"],
} as const satisfies Record<number, HarthmereThreeLineDialogueExpressionTuple>;

export const SNAPSHOT_GROVE_AMBIENT_DIALOGUE_EXPRESSION_PLAN = {
  jackie: ["thinking", "determined", "sighing"],
  billy: ["confusion", "determined", "embarrassment"],
  ranger_jane: ["guard", "thinking", "determined"],
  luis: ["curiosity", "checkingEquipment", "facepalm"],
  taye: ["checkingEquipment", "thinking", "curiosity"],
  alexis: ["checkingEquipment", "gratitude", "determined"],
  sil: ["curiosity", "rally", "thinking"],
  dimmi: ["confusion", "checkingEquipment", "thinking"],
  doc: ["thinking", "determined", "frustration"],
  old_coop: ["thinking", "determined", "curiosity"],
  buddy: [undefined, undefined, undefined],
  mucked_robot: [undefined, undefined, undefined],
  rosalyn: ["checkingEquipment", "confusion", "determined"],
  guild_clerk_nia: ["thinking", "determined", "stop"],
  grove_banker_merl: ["nervousness", "checkingEquipment", "determined"],
  mira_grove_land_steward: ["stop", "determined", "thinking"],
  gus_the_baker: ["determined", "thumbsUp", "gratitude"],
  fern_the_grower: ["gratitude", "checkingEquipment", "thinking"],
  kit_the_courier: ["thinking", "determined", "frustration"],
  mel_the_handyman: ["frustration", "stop", "relief"],
  rin_the_forager: ["guard", "determined", "gratitude"],
  carlo_the_cook: ["determined", "thumbsUp", "gratitude"],
} as const satisfies Record<string, HarthmereThreeLineDialogueExpressionTuple>;

export const SNAPSHOT_GROVE_QUEST_DIALOGUE_EXPRESSION_PLAN = {
  fountain_buttons_first: "checkingEquipment",
  painted_path_language: "curiosity",
  road_ready_bag_check: "checkingEquipment",
  tools_before_treasure: "checkingEquipment",
  safe_sparring_not_pvp: "guard",
  ready_check_at_fountain: "rally",
  lost_found_and_mail: "checkingEquipment",
  fountain_chat_channels: "stop",
  fountain_food_keeps_you_moving: "determined",
  fountain_first_aid_before_road: "determined",
  fountain_hotbar_and_dropping: "ready",
  fountain_first_recipe_torch: "determined",
  fountain_trade_table_promises: "handshake",
  grove_road_graduation: "rally",
  intro_alexis_lovely_locks: "checkingEquipment",
  intro_luis_crossroads_cart: "facepalm",
  intro_jane_mosslawn_edge: "guard",
  "read-the-jobs-board": "beckon",
  building_system_intro_talk_to_mira: "determined",
  road_signs_and_small_lies: "annoyance",
  build_repair_claim_lesson: "checkingEquipment",
  guilds_are_promises: "handshake",
  color_that_still_points_home: "thinking",
  cart_that_forgot_its_wheel: "facepalm",
  road_ready_not_fancy: "checkingEquipment",
  moss_that_went_quiet: "guard",
  songline_under_the_lawn: "curiosity",
  sticky_medicine: "disgust",
  cove_keeps_pictures: "curiosity",
  coops_key_hen: "thinking",
  tower_with_a_headache: undefined,
  letter_for_the_north_gate: "nervousness",
  antlers_for_the_watch: "taunt",
  toll_ledger_problem: "frustration",
  samples_for_the_chapel: "thinking",
  tone_beneath_the_road: "curiosity",
  econ_billys_lost_lunch_pail: "annoyance",
  econ_billys_roof_patch_run: "determined",
  econ_billys_map_pin_run: "stop",
  econ_merls_coin_sorting: "checkingEquipment",
  econ_merls_vault_inventory: "determined",
  econ_gus_fresh_loaves_to_fountain: "impatience",
  econ_gus_grain_run: "determined",
  econ_fern_water_the_sprout_beds: "annoyance",
  econ_fern_berry_patch_harvest: "determined",
  econ_kit_letters_around_fountain: "checkingEquipment",
  econ_kit_heavy_parcel_to_crossroads: "determined",
  econ_mel_bench_repair: "checkingEquipment",
  econ_mel_broken_hinge_hunt: "frustration",
  econ_rin_mushroom_pickup: "stop",
  econ_carlo_festival_skewers: "impatience",
} as const satisfies Record<string, HarthmereCinematicExpression | undefined>;
