// Auto-generated by install-harthmere-runtime-completion.sh
// current implements the missing playable quest runtime contract: accept/active/complete,
// objective progress, reward grants, failure/abandon/retry, dialogue links, journal,
// map/compass hints, telemetry, and server-authoritative validation.

import {
  HARTHMERE_QUEST_CATALOG,
  getHarthmereQuestById,
  validateHarthmereQuestActivation,
} from "@/shared/harthmere/quest_compendium";
import { shiftHarthmereAuthoredPositionToWorld } from "@/shared/harthmere/coordinate_transform";
import { normalizeHarthmereExtensionQuestWorldPosition } from "@/shared/harthmere/world_extension";
import {
  resolveHarthmereQuestObjectivePlacement,
  type HarthmereProductionPlacementPurpose,
} from "@/shared/harthmere/production_terrain_placement_map";

export const HARTHMERE_QUEST_RUNTIME_VERSION = 47 as const;

export type HarthmereQuestState =
  | "locked"
  | "available"
  | "active"
  | "ready_to_complete"
  | "completed"
  | "failed"
  | "abandoned";

export type HarthmereQuestObjectiveEventType =
  | "talk"
  | "inspect"
  | "collect"
  | "combat"
  | "escort"
  | "craft"
  | "choice"
  | "read";

export interface HarthmereQuestRuntimeObjectiveProgress {
  current: number;
  target: number;
  completed: boolean;
  lastEventId?: string;
}

export interface HarthmereQuestRuntimeRecord {
  questId: string;
  state: HarthmereQuestState;
  acceptedAtTick?: number;
  completedAtTick?: number;
  failedAtTick?: number;
  abandonedAtTick?: number;
  rewardGrantId?: string;
  failureReason?: string;
  objectiveProgress: Record<string, HarthmereQuestRuntimeObjectiveProgress>;
  chosenPath?: string;
}

export interface HarthmereQuestRuntimeContext {
  playerId: string;
  playerLevel: number;
  hour: number;
  timeOfDay: string;
  weather: string;
  tick: number;
  flags: string[];
  completedQuestIds: string[];
  inventoryFreeSlots: number;
  questStates: Record<string, HarthmereQuestState>;
  runtimeRecords: Record<string, HarthmereQuestRuntimeRecord>;
  grantedRewardIds: string[];
  authority: "server" | "client";
}

export interface HarthmereQuestRuntimeEvent {
  eventId: string;
  questId: string;
  objectiveId?: string;
  type:
    | HarthmereQuestObjectiveEventType
    | "accept"
    | "complete"
    | "fail"
    | "abandon"
    | "retry";
  actorId: string;
  targetId?: string;
  count?: number;
  chosenPath?: string;
  reason?: string;
  authority: "server" | "client";
  tick: number;
  // Position of the acting player at event time (world coords). Used to enforce
  // maxDistance / near-location rules per the state map.
  actorPosition?: [number, number, number];
  // True iff line-of-sight was checked and passed by the caller for talk/inspect.
  lineOfSight?: boolean;
  // For choice objectives: server-revalidated choice value, must match an
  // authorized option for the objective.
  revalidatedChoice?: string;
  // For combat objectives: distinguishes a kill / "encounter cleared" from a
  // mere damage tick or a practice-dummy hit.
  combatResult?: "damage" | "kill" | "encounter_cleared" | "practice_hit";
  // For collect/item_grant/item_use/craft/carry: confirms the inventory or
  // evidence state changed. The runtime will not advance the objective on
  // damage alone or on an unverified inventory event.
  inventoryStateChanged?: boolean;
  // For party-scoped quests: optional party id. When set, the runtime should be
  // called once per party member (with their own context) using the same eventId
  // suffix so per-member rewards remain idempotent.
  partyId?: string;
}

export interface HarthmereQuestRuntimeResult {
  ok: boolean;
  state?: HarthmereQuestState;
  questId?: string;
  record?: HarthmereQuestRuntimeRecord;
  rewardsGranted?: any;
  mapHint?: HarthmereQuestMapHint;
  journal?: HarthmereQuestJournalEntry;
  telemetry?: HarthmereQuestTelemetryEvent[];
  reasons: string[];
}

export interface HarthmereQuestMapHint {
  questId: string;
  objectiveId?: string;
  district: string;
  waypoint: [number, number, number];
  compassLabel: string;
  hintType: "giver" | "objective" | "turn_in" | "hidden_world_trigger";
}

export interface HarthmereQuestJournalEntry {
  questId: string;
  title: string;
  state: HarthmereQuestState;
  giverName?: string;
  district: string;
  activeObjectives: Array<{
    id: string;
    label: string;
    current: number;
    target: number;
    completed: boolean;
  }>;
  dialogueState: string;
  rewardPreview: any;
  mapHints: HarthmereQuestMapHint[];
}

export interface HarthmereQuestTelemetryEvent {
  kind:
    | "quest_available"
    | "quest_accepted"
    | "objective_progressed"
    | "quest_ready_to_complete"
    | "quest_completed"
    | "quest_failed"
    | "quest_abandoned"
    | "quest_retried"
    | "reward_granted_once";
  questId: string;
  objectiveId?: string;
  tick: number;
  details?: Record<string, unknown>;
}

export const HARTHMERE_QUEST_DIALOGUE_LINKS = {
  sergeant_bram_holt: [
    "starter_welcome_to_harthmere",
    "harthmere_sq_005_patrol_route_seven",
    "repeatable_watch_patrol_routes",
  ],
  father_aldren_mell: [
    "bellbound_q01_cracks_in_bridge",
    "bellbound_q04_sisters_letters",
    "repeatable_chapel_candle_vigils",
  ],
  sister_maelle_frenn: [
    "bellbound_q04_sisters_letters",
    "harthmere_sq_017_sister_maelles_concern",
  ],
  nessa_crowe: [
    "bellbound_q02_5_rat_girl_knows",
    "harthmere_sq_028_rats_with_crowns",
  ],
  lina_reed: ["harthmere_sq_027_linas_promise"],
  tamsin_vale: [
    "harthmere_sq_036_tamsins_trial",
    "repeatable_wilds_resource_route",
  ],
  veneth_moss_woman: [
    "harthmere_sq_037_the_moss_womans_riddle",
    "bellbound_q12_thaedryn_bellbound",
  ],
  thaedryn_bellbound: ["bellbound_q12_thaedryn_bellbound"],
} as const;

export function createHarthmereQuestRuntimeContext(
  overrides: Partial<HarthmereQuestRuntimeContext> = {}
): HarthmereQuestRuntimeContext {
  return {
    playerId: overrides.playerId ?? "local-dev-player",
    playerLevel: overrides.playerLevel ?? 12,
    hour: overrides.hour ?? 12,
    timeOfDay: overrides.timeOfDay ?? "day",
    weather: overrides.weather ?? "clear",
    tick: overrides.tick ?? 1,
    flags: overrides.flags ?? [],
    completedQuestIds: overrides.completedQuestIds ?? [],
    inventoryFreeSlots: overrides.inventoryFreeSlots ?? 20,
    questStates: overrides.questStates ?? {},
    runtimeRecords: overrides.runtimeRecords ?? {},
    grantedRewardIds: overrides.grantedRewardIds ?? [],
    authority: overrides.authority ?? "server",
  };
}

export function getHarthmereQuestRuntimeRecord(
  context: HarthmereQuestRuntimeContext,
  questId: string
): HarthmereQuestRuntimeRecord | undefined {
  return context.runtimeRecords[questId];
}

export function createHarthmereQuestRuntimeRecord(
  quest: any,
  tick = 0
): HarthmereQuestRuntimeRecord {
  const objectiveProgress: Record<
    string,
    HarthmereQuestRuntimeObjectiveProgress
  > = {};
  for (const objective of quest.objectives ?? []) {
    objectiveProgress[objective.id] = {
      current: 0,
      target: objective.count ?? 1,
      completed: false,
    };
  }
  return {
    questId: quest.id,
    state: "active",
    acceptedAtTick: tick,
    objectiveProgress,
  };
}

function distanceBetween(
  a: [number, number, number] | undefined,
  b: [number, number, number] | undefined
): number | undefined {
  if (!a || !b) return undefined;
  const dx = a[0] - b[0];
  const dy = a[1] - b[1];
  const dz = a[2] - b[2];
  return Math.sqrt(dx * dx + dy * dy + dz * dz);
}

function placementPurposeForObjective(
  objective: any
): HarthmereProductionPlacementPurpose {
  switch (objective?.type) {
    case "combat":
      return "monster";
    case "collect":
    case "craft":
    case "read":
      return "quest_item";
    case "talk":
      return "npc";
    case "inspect":
    case "choice":
    case "escort":
      return "interactable";
    default:
      return "quest_marker";
  }
}

export function getHarthmereQuestResolvedWaypoint(
  questId: string,
  objective?: any
): [number, number, number] | undefined {
  const quest = getHarthmereQuestById(questId);
  const source = objective?.location ?? quest?.location;
  if (!quest || !source?.waypoint) {
    return undefined;
  }
  const fallback = normalizeHarthmereExtensionQuestWorldPosition(
    shiftHarthmereAuthoredPositionToWorld(source.waypoint)
  );
  return resolveHarthmereQuestObjectivePlacement({
    questId,
    objectiveId: objective?.id,
    fallback,
    purpose: placementPurposeForObjective(objective),
  }).recommendedPosition as [number, number, number];
}

// Per state-map: talk objectives = max distance 5 with line of sight,
// inspect objectives = max distance 4 with line of sight, near_location
// completes when player is within 8m. Other types default to 6m.
function maxDistanceForObjective(objective: any): number {
  const validationMax = objective?.validation?.maxDistance;
  if (typeof validationMax === "number") return validationMax;
  switch (objective?.type) {
    case "talk":
      return 5;
    case "inspect":
      return 4;
    case "near_location":
      return 8;
    case "choice":
    case "craft":
    case "collect":
    case "combat":
    case "escort":
    case "read":
      return 8;
    default:
      return 8;
  }
}

export function validateHarthmereQuestObjectiveEvent(
  context: HarthmereQuestRuntimeContext,
  event: HarthmereQuestRuntimeEvent,
  quest: any,
  objective: any
): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];
  if (!objective) {
    reasons.push("missing_objective");
    return { ok: false, reasons };
  }

  // Server-side line-of-sight + distance for talk/inspect.
  const requiresLoS = !!objective?.validation?.requiresLineOfSight;
  const maxDistance = maxDistanceForObjective(objective);
  const objectiveWaypoint = getHarthmereQuestResolvedWaypoint(
    quest.id,
    objective
  );
  const dist = distanceBetween(event.actorPosition, objectiveWaypoint);
  if (
    event.actorPosition &&
    objectiveWaypoint &&
    dist !== undefined &&
    dist > maxDistance
  ) {
    reasons.push("player_too_far");
  }
  if (requiresLoS && event.lineOfSight === false) {
    reasons.push("line_of_sight_blocked");
  }

  // Choice objectives must include a server-revalidated choice.
  if (
    objective.type === "choice" &&
    objective?.validation?.requiresChoiceRevalidation
  ) {
    if (!event.revalidatedChoice) reasons.push("choice_not_revalidated");
  }

  // Combat objectives must record an encounter result; damage alone is not
  // enough unless the objective explicitly allows a practice hit.
  if (objective.type === "combat") {
    const allowPractice = !!objective?.validation?.allowPracticeHit;
    if (!event.combatResult) {
      reasons.push("combat_result_required");
    } else if (event.combatResult === "damage" && !allowPractice) {
      reasons.push("damage_only_does_not_complete_combat_objective");
    } else if (event.combatResult === "practice_hit" && !allowPractice) {
      reasons.push("practice_hit_does_not_complete_real_combat_objective");
    }
  }

  // Collect/item_grant/item_use/craft/carry require inventory or evidence
  // state to actually change before the objective can advance.
  // Gate on the OBJECTIVE's contract, not the caller-supplied event type: a talk/inspect
  // objective must not be blocked just because the (client-influenced) event was typed
  // "collect", and a collect objective must require the inventory change regardless.
  if (
    (objective.type === "collect" || objective.type === "craft") &&
    event.inventoryStateChanged === false
  ) {
    reasons.push("inventory_state_unchanged");
  }

  // Active rules: only advance an objective when it's listed in
  // activeDuringStates for the current record state. Defaults to ["active"].
  const record = context.runtimeRecords[event.questId];
  const allowedStates: string[] = objective.activeDuringStates ?? ["active"];
  if (record && !allowedStates.includes(record.state)) {
    reasons.push("objective_inactive_in_current_state");
  }

  // Strict prior-objective ordering: only the first incomplete objective in
  // the catalog order may advance. Per state map: "Only objectives with
  // open_tab/status_check/inventory/craft/chat/trade/choice language should
  // require HUD interaction. Other objectives should be world/NPC events."
  // -- and the universal rule "Future markers may be visible, but their
  // events should not complete until their step is current."
  if (record) {
    for (const candidate of quest.objectives ?? []) {
      if (candidate.id === objective.id) break;
      const prior = record.objectiveProgress[candidate.id];
      if (!prior?.completed) {
        reasons.push("prior_objective_not_complete");
        break;
      }
    }
  }

  return { ok: reasons.length === 0, reasons };
}

export function validateHarthmereQuestRuntimeEvent(
  context: HarthmereQuestRuntimeContext,
  event: HarthmereQuestRuntimeEvent
): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];
  const quest = getHarthmereQuestById(event.questId);
  if (!quest) reasons.push("missing_quest");
  if (event.authority !== "server" || context.authority !== "server")
    reasons.push("client_cannot_advance_or_grant_quest_state");
  if (!event.eventId || !event.eventId.includes(event.questId))
    reasons.push("event_id_must_be_namespaced_to_quest");
  if (event.actorId !== context.playerId) reasons.push("actor_mismatch");
  if (event.tick < context.tick) reasons.push("stale_event_tick");
  if (
    event.type === "complete" &&
    context.grantedRewardIds.includes(`reward:${event.questId}`)
  )
    reasons.push("reward_already_granted");
  if (
    (event.type === "collect" || event.type === "complete") &&
    context.inventoryFreeSlots < 0
  )
    reasons.push("invalid_inventory_state");
  return { ok: reasons.length === 0, reasons };
}

export function acceptHarthmereQuest(
  context: HarthmereQuestRuntimeContext,
  questId: string,
  eventId = `${questId}:accept:${context.tick}`
): HarthmereQuestRuntimeResult {
  const quest = getHarthmereQuestById(questId);
  if (!quest) return { ok: false, questId, reasons: ["missing_quest"] };
  const validation = validateHarthmereQuestActivation(quest, {
    playerLevel: context.playerLevel,
    hour: context.hour,
    timeOfDay: context.timeOfDay,
    weather: context.weather,
    flags: context.flags,
    completedQuestIds: context.completedQuestIds,
    questStates: context.questStates,
  } as any);
  if (!validation.ok)
    return { ok: false, questId, state: "locked", reasons: validation.reasons };
  const existingRecord = context.runtimeRecords[questId];
  if (existingRecord) {
    // Idempotent: a duplicate accept of an in-flight quest must NEVER wipe progress.
    if (
      existingRecord.state === "active" ||
      existingRecord.state === "ready_to_complete"
    ) {
      return {
        ok: true,
        questId,
        state: existingRecord.state,
        record: existingRecord,
        reasons: ["already_active_idempotent"],
      };
    }
    // A non-repeatable quest that is already completed cannot be re-accepted.
    if (
      existingRecord.state === "completed" &&
      (quest.repeatability ?? "once") === "once"
    ) {
      return {
        ok: false,
        questId,
        state: "completed",
        reasons: ["quest_already_completed"],
      };
    }
    // Otherwise (repeatable completed → next cycle, or failed/abandoned → restart) fall
    // through and create a fresh record.
  }
  const event = {
    eventId,
    questId,
    type: "accept" as const,
    actorId: context.playerId,
    authority: "server" as const,
    tick: context.tick,
  };
  const eventValidation = validateHarthmereQuestRuntimeEvent(context, event);
  if (!eventValidation.ok)
    return { ok: false, questId, reasons: eventValidation.reasons };
  const record = createHarthmereQuestRuntimeRecord(quest, context.tick);
  context.runtimeRecords[questId] = record;
  context.questStates[questId] = "active";
  return {
    ok: true,
    questId,
    state: "active",
    record,
    journal: getHarthmereQuestJournalEntry(context, questId),
    mapHint: getHarthmereQuestMapHint(context, questId),
    telemetry: [{ kind: "quest_accepted", questId, tick: context.tick }],
    reasons: [],
  };
}

export function advanceHarthmereQuestObjective(
  context: HarthmereQuestRuntimeContext,
  event: HarthmereQuestRuntimeEvent
): HarthmereQuestRuntimeResult {
  const eventValidation = validateHarthmereQuestRuntimeEvent(context, event);
  if (!eventValidation.ok)
    return {
      ok: false,
      questId: event.questId,
      reasons: eventValidation.reasons,
    };
  const record = context.runtimeRecords[event.questId];
  const quest = getHarthmereQuestById(event.questId);
  if (!record || !quest || record.state !== "active")
    return { ok: false, questId: event.questId, reasons: ["quest_not_active"] };
  const objectiveId = event.objectiveId;
  if (!objectiveId || !record.objectiveProgress[objectiveId])
    return {
      ok: false,
      questId: event.questId,
      reasons: ["missing_objective"],
    };
  const progress = record.objectiveProgress[objectiveId];
  if (progress.lastEventId === event.eventId)
    return {
      ok: true,
      questId: event.questId,
      state: record.state,
      record,
      reasons: ["duplicate_objective_event_idempotent"],
    };
  if (progress.completed) {
    return {
      ok: true,
      questId: event.questId,
      state: record.state,
      record,
      reasons: ["objective_already_completed_idempotent"],
    };
  }
  const objective = (quest.objectives ?? []).find(
    (o: any) => o.id === objectiveId
  );
  const objectiveValidation = validateHarthmereQuestObjectiveEvent(
    context,
    event,
    quest,
    objective
  );
  if (!objectiveValidation.ok) {
    return {
      ok: false,
      questId: event.questId,
      state: record.state,
      record,
      reasons: objectiveValidation.reasons,
    };
  }
  progress.current = Math.min(
    progress.target,
    progress.current + Math.max(1, event.count ?? 1)
  );
  progress.completed = progress.current >= progress.target;
  progress.lastEventId = event.eventId;
  const allComplete = Object.values(record.objectiveProgress).every(
    (item) => item.completed
  );
  if (allComplete) {
    record.state = "ready_to_complete";
    context.questStates[event.questId] = "ready_to_complete";
  }
  return {
    ok: true,
    questId: event.questId,
    state: record.state,
    record,
    journal: getHarthmereQuestJournalEntry(context, event.questId),
    mapHint: getHarthmereQuestMapHint(context, event.questId),
    telemetry: [
      {
        kind: "objective_progressed",
        questId: event.questId,
        objectiveId,
        tick: context.tick,
      },
      ...(allComplete
        ? [
            {
              kind: "quest_ready_to_complete" as const,
              questId: event.questId,
              tick: context.tick,
            },
          ]
        : []),
    ],
    reasons: [],
  };
}

export function completeHarthmereQuest(
  context: HarthmereQuestRuntimeContext,
  questId: string,
  eventId = `${questId}:complete:${context.tick}`
): HarthmereQuestRuntimeResult {
  const event = {
    eventId,
    questId,
    type: "complete" as const,
    actorId: context.playerId,
    authority: "server" as const,
    tick: context.tick,
  };
  const eventValidation = validateHarthmereQuestRuntimeEvent(context, event);
  if (!eventValidation.ok)
    return { ok: false, questId, reasons: eventValidation.reasons };
  const quest = getHarthmereQuestById(questId);
  const record = context.runtimeRecords[questId];
  if (!quest || !record)
    return { ok: false, questId, reasons: ["missing_runtime_record"] };
  if (record.state !== "ready_to_complete")
    return {
      ok: false,
      questId,
      state: record.state,
      reasons: ["objectives_not_ready"],
    };
  // Repeatable (daily/weekly) quests must re-grant their reward each cycle. Keying the
  // grant id on the acceptance tick gives each fresh acceptance a distinct id, while a
  // "once" quest keeps a stable id so it can never be re-granted.
  const rewardGrantId =
    (quest.repeatability ?? "once") === "once"
      ? `reward:${questId}`
      : `reward:${questId}:${record.acceptedAtTick}`;
  if (context.grantedRewardIds.includes(rewardGrantId))
    return {
      ok: true,
      questId,
      state: "completed",
      record,
      reasons: ["reward_already_granted_idempotent"],
    };
  record.state = "completed";
  record.completedAtTick = context.tick;
  record.rewardGrantId = rewardGrantId;
  context.questStates[questId] = "completed";
  if (!context.completedQuestIds.includes(questId))
    context.completedQuestIds.push(questId);
  context.grantedRewardIds.push(rewardGrantId);
  return {
    ok: true,
    questId,
    state: "completed",
    record,
    rewardsGranted: {
      ...quest.rewards,
      rewardGrantId,
      authority: "server",
      idempotent: true,
    },
    telemetry: [
      { kind: "reward_granted_once", questId, tick: context.tick },
      { kind: "quest_completed", questId, tick: context.tick },
    ],
    reasons: [],
  };
}

export function failHarthmereQuest(
  context: HarthmereQuestRuntimeContext,
  questId: string,
  reason: string
): HarthmereQuestRuntimeResult {
  const record = context.runtimeRecords[questId];
  if (!record)
    return { ok: false, questId, reasons: ["missing_runtime_record"] };
  if (record.state !== "active" && record.state !== "ready_to_complete") {
    return {
      ok: false,
      questId,
      state: record.state,
      reasons: ["only_active_quests_can_fail"],
    };
  }
  record.state = "failed";
  record.failedAtTick = context.tick;
  record.failureReason = reason;
  context.questStates[questId] = "failed";
  return {
    ok: true,
    questId,
    state: "failed",
    record,
    telemetry: [
      {
        kind: "quest_failed",
        questId,
        tick: context.tick,
        details: { reason },
      },
    ],
    reasons: [],
  };
}

// Party-scoped progression. Per request: multiple users can do the same quest
// together and pass/fail together. The runtime here is per-player; the caller
// is expected to drive each party member's context with the same event suffix
// (so reward grants stay per-player idempotent) and call this helper to
// coordinate ready/complete/fail across all members.
export interface HarthmereQuestPartyMember {
  memberId: string;
  context: HarthmereQuestRuntimeContext;
}

export function advanceHarthmereQuestObjectiveParty(
  members: HarthmereQuestPartyMember[],
  baseEvent: Omit<HarthmereQuestRuntimeEvent, "actorId" | "eventId"> & {
    eventIdSuffix: string;
  }
): Array<{ memberId: string; result: HarthmereQuestRuntimeResult }> {
  return members.map((member) => {
    const event: HarthmereQuestRuntimeEvent = {
      ...baseEvent,
      actorId: member.context.playerId,
      eventId: `${baseEvent.questId}:${baseEvent.eventIdSuffix}:${member.memberId}`,
    };
    return {
      memberId: member.memberId,
      result: advanceHarthmereQuestObjective(member.context, event),
    };
  });
}

export function failHarthmereQuestParty(
  members: HarthmereQuestPartyMember[],
  questId: string,
  reason: string
): Array<{ memberId: string; result: HarthmereQuestRuntimeResult }> {
  return members.map((member) => ({
    memberId: member.memberId,
    result: failHarthmereQuest(member.context, questId, reason),
  }));
}

export function completeHarthmereQuestParty(
  members: HarthmereQuestPartyMember[],
  questId: string,
  baseTick: number
): Array<{ memberId: string; result: HarthmereQuestRuntimeResult }> {
  // All members must be ready_to_complete; if any is not, no rewards grant.
  const allReady = members.every(
    (m) => m.context.runtimeRecords[questId]?.state === "ready_to_complete"
  );
  if (!allReady) {
    return members.map((member) => ({
      memberId: member.memberId,
      result: {
        ok: false,
        questId,
        state: member.context.runtimeRecords[questId]?.state,
        reasons: ["party_member_not_ready"],
      },
    }));
  }
  return members.map((member) => ({
    memberId: member.memberId,
    result: completeHarthmereQuest(
      member.context,
      questId,
      `${questId}:complete:party:${baseTick}:${member.memberId}`
    ),
  }));
}

export function abandonHarthmereQuest(
  context: HarthmereQuestRuntimeContext,
  questId: string
): HarthmereQuestRuntimeResult {
  const record = context.runtimeRecords[questId];
  if (!record)
    return { ok: false, questId, reasons: ["missing_runtime_record"] };
  // Only in-flight quests can be abandoned. Abandoning a completed/failed quest would
  // corrupt its terminal state (and could re-lock chain prerequisites that read it).
  if (record.state !== "active" && record.state !== "ready_to_complete") {
    return {
      ok: false,
      questId,
      state: record.state,
      reasons: ["only_active_quests_can_abandon"],
    };
  }
  record.state = "abandoned";
  record.abandonedAtTick = context.tick;
  context.questStates[questId] = "abandoned";
  return {
    ok: true,
    questId,
    state: "abandoned",
    record,
    telemetry: [{ kind: "quest_abandoned", questId, tick: context.tick }],
    reasons: [],
  };
}

export function retryHarthmereQuest(
  context: HarthmereQuestRuntimeContext,
  questId: string
): HarthmereQuestRuntimeResult {
  const quest = getHarthmereQuestById(questId);
  if (!quest) return { ok: false, questId, reasons: ["missing_quest"] };
  const previous = context.runtimeRecords[questId];
  if (previous?.state !== "failed" && previous?.state !== "abandoned")
    return {
      ok: false,
      questId,
      reasons: ["retry_requires_failed_or_abandoned_state"],
    };
  const record = createHarthmereQuestRuntimeRecord(quest, context.tick);
  context.runtimeRecords[questId] = record;
  context.questStates[questId] = "active";
  return {
    ok: true,
    questId,
    state: "active",
    record,
    telemetry: [{ kind: "quest_retried", questId, tick: context.tick }],
    reasons: [],
  };
}

export function getHarthmereQuestMapHint(
  context: HarthmereQuestRuntimeContext,
  questId: string
): HarthmereQuestMapHint | undefined {
  const quest = getHarthmereQuestById(questId);
  if (!quest) return undefined;
  const record = context.runtimeRecords[questId];
  const firstOpenObjective = record
    ? quest.objectives.find(
        (objective: any) => !record.objectiveProgress[objective.id]?.completed
      )
    : undefined;
  const source = firstOpenObjective?.location ?? quest.location;
  const waypoint =
    getHarthmereQuestResolvedWaypoint(questId, firstOpenObjective) ??
    normalizeHarthmereExtensionQuestWorldPosition(
      shiftHarthmereAuthoredPositionToWorld(source.waypoint)
    );
  return {
    questId,
    objectiveId: firstOpenObjective?.id,
    district: source.district,
    waypoint,
    compassLabel:
      firstOpenObjective?.label ??
      `Speak with ${quest.giverName ?? "the world trigger"}`,
    hintType:
      record?.state === "ready_to_complete"
        ? "turn_in"
        : firstOpenObjective
        ? "objective"
        : quest.hidden
        ? "hidden_world_trigger"
        : "giver",
  };
}

export function getHarthmereQuestJournalEntry(
  context: HarthmereQuestRuntimeContext,
  questId: string
): HarthmereQuestJournalEntry | undefined {
  const quest = getHarthmereQuestById(questId);
  if (!quest) return undefined;
  const state =
    context.questStates[questId] ??
    quest.activeRules.initialState ??
    "available";
  const record = context.runtimeRecords[questId];
  const activeObjectives = (quest.objectives ?? []).map((objective: any) => {
    const progress = record?.objectiveProgress?.[objective.id] ?? {
      current: 0,
      target: objective.count ?? 1,
      completed: false,
    };
    return {
      id: objective.id,
      label: objective.label,
      current: progress.current,
      target: progress.target,
      completed: progress.completed,
    };
  });
  return {
    questId,
    title: quest.title,
    state,
    giverName: quest.giverName,
    district: quest.location.district,
    activeObjectives,
    dialogueState:
      quest.dialogue?.[
        state === "ready_to_complete"
          ? "ready"
          : state === "completed"
          ? "complete"
          : state === "failed"
          ? "fail"
          : state === "active"
          ? "active"
          : "offer"
      ],
    rewardPreview: quest.rewards,
    mapHints: [getHarthmereQuestMapHint(context, questId)].filter(
      Boolean
    ) as HarthmereQuestMapHint[],
  };
}

export function getHarthmereDialogueQuestOffers(
  npcId: keyof typeof HARTHMERE_QUEST_DIALOGUE_LINKS,
  context: HarthmereQuestRuntimeContext
) {
  const questIds = HARTHMERE_QUEST_DIALOGUE_LINKS[npcId] ?? [];
  return questIds
    .map((questId) => getHarthmereQuestById(questId))
    .filter(Boolean)
    .map((quest: any) => ({
      questId: quest.id,
      title: quest.title,
      state: context.questStates[quest.id] ?? quest.activeRules.initialState,
      offer: quest.dialogue.offer,
    }));
}

export function validateHarthmereQuestRuntimeCoverage() {
  const failures: string[] = [];
  for (const quest of HARTHMERE_QUEST_CATALOG as any[]) {
    if (!quest.objectives?.length)
      failures.push(`${quest.id} has no objectives`);
    if (!quest.rewards?.previewText)
      failures.push(`${quest.id} has no reward preview`);
    if (!quest.testContract?.stateTransitions?.length)
      failures.push(`${quest.id} has no state transitions`);
  }
  return {
    ok: failures.length === 0,
    failures,
    questCount: (HARTHMERE_QUEST_CATALOG as any[]).length,
  };
}
