// Auto-generated by install-harthmere-runtime-completion-v47.sh
// v47 implements the missing playable quest runtime contract: accept/active/complete,
// objective progress, reward grants, failure/abandon/retry, dialogue links, journal,
// map/compass hints, telemetry, and server-authoritative validation.

import {
  HARTHMERE_QUEST_CATALOG_V46,
  getHarthmereQuestByIdV46,
  validateHarthmereQuestActivationV46,
} from "./quest_compendium_v46";
import { shiftHarthmereAuthoredPositionToWorldV71 } from "./coordinate_transform_v71";

export const HARTHMERE_QUEST_RUNTIME_VERSION_V47 = 47 as const;

export type HarthmereQuestStateV47 =
  | "locked"
  | "available"
  | "active"
  | "ready_to_complete"
  | "completed"
  | "failed"
  | "abandoned";

export type HarthmereQuestObjectiveEventTypeV47 =
  | "talk"
  | "inspect"
  | "collect"
  | "combat"
  | "escort"
  | "craft"
  | "choice"
  | "read";

export interface HarthmereQuestRuntimeObjectiveProgressV47 {
  current: number;
  target: number;
  completed: boolean;
  lastEventId?: string;
}

export interface HarthmereQuestRuntimeRecordV47 {
  questId: string;
  state: HarthmereQuestStateV47;
  acceptedAtTick?: number;
  completedAtTick?: number;
  failedAtTick?: number;
  abandonedAtTick?: number;
  rewardGrantId?: string;
  failureReason?: string;
  objectiveProgress: Record<string, HarthmereQuestRuntimeObjectiveProgressV47>;
  chosenPath?: string;
}

export interface HarthmereQuestRuntimeContextV47 {
  playerId: string;
  playerLevel: number;
  hour: number;
  timeOfDay: string;
  weather: string;
  tick: number;
  flags: string[];
  completedQuestIds: string[];
  inventoryFreeSlots: number;
  questStates: Record<string, HarthmereQuestStateV47>;
  runtimeRecords: Record<string, HarthmereQuestRuntimeRecordV47>;
  grantedRewardIds: string[];
  authority: "server" | "client";
}

export interface HarthmereQuestRuntimeEventV47 {
  eventId: string;
  questId: string;
  objectiveId?: string;
  type: HarthmereQuestObjectiveEventTypeV47 | "accept" | "complete" | "fail" | "abandon" | "retry";
  actorId: string;
  targetId?: string;
  count?: number;
  chosenPath?: string;
  reason?: string;
  authority: "server" | "client";
  tick: number;
}

export interface HarthmereQuestRuntimeResultV47 {
  ok: boolean;
  state?: HarthmereQuestStateV47;
  questId?: string;
  record?: HarthmereQuestRuntimeRecordV47;
  rewardsGranted?: any;
  mapHint?: HarthmereQuestMapHintV47;
  journal?: HarthmereQuestJournalEntryV47;
  telemetry?: HarthmereQuestTelemetryEventV47[];
  reasons: string[];
}

export interface HarthmereQuestMapHintV47 {
  questId: string;
  objectiveId?: string;
  district: string;
  waypoint: [number, number, number];
  compassLabel: string;
  hintType: "giver" | "objective" | "turn_in" | "hidden_world_trigger";
}

export interface HarthmereQuestJournalEntryV47 {
  questId: string;
  title: string;
  state: HarthmereQuestStateV47;
  giverName?: string;
  district: string;
  activeObjectives: Array<{ id: string; label: string; current: number; target: number; completed: boolean }>;
  dialogueState: string;
  rewardPreview: any;
  mapHints: HarthmereQuestMapHintV47[];
}

export interface HarthmereQuestTelemetryEventV47 {
  kind:
    | "quest_available"
    | "quest_accepted"
    | "objective_progressed"
    | "quest_ready_to_complete"
    | "quest_completed"
    | "quest_failed"
    | "quest_abandoned"
    | "quest_retried"
    | "reward_granted_once";
  questId: string;
  objectiveId?: string;
  tick: number;
  details?: Record<string, unknown>;
}

export const HARTHMERE_QUEST_DIALOGUE_LINKS_V47 = {
  sergeant_bram_holt: ["starter_welcome_to_harthmere", "harthmere_sq_005_patrol_route_seven", "repeatable_watch_patrol_routes"],
  father_aldren_mell: ["bellbound_q01_cracks_in_bridge", "bellbound_q04_sisters_letters", "repeatable_chapel_candle_vigils"],
  sister_maelle_frenn: ["bellbound_q04_sisters_letters", "harthmere_sq_017_sister_maelles_concern"],
  nessa_crowe: ["bellbound_q02_5_rat_girl_knows", "harthmere_sq_028_rats_with_crowns"],
  lina_reed: ["harthmere_sq_027_linas_promise"],
  tamsin_vale: ["harthmere_sq_036_tamsins_trial", "repeatable_wilds_resource_route"],
  veneth_moss_woman: ["harthmere_sq_037_the_moss_womans_riddle", "bellbound_q12_thaedryn_bellbound"],
  thaedryn_bellbound: ["bellbound_q12_thaedryn_bellbound"],
} as const;

export function createHarthmereQuestRuntimeContextV47(overrides: Partial<HarthmereQuestRuntimeContextV47> = {}): HarthmereQuestRuntimeContextV47 {
  return {
    playerId: overrides.playerId ?? "local-dev-player",
    playerLevel: overrides.playerLevel ?? 12,
    hour: overrides.hour ?? 12,
    timeOfDay: overrides.timeOfDay ?? "day",
    weather: overrides.weather ?? "clear",
    tick: overrides.tick ?? 1,
    flags: overrides.flags ?? [],
    completedQuestIds: overrides.completedQuestIds ?? [],
    inventoryFreeSlots: overrides.inventoryFreeSlots ?? 20,
    questStates: overrides.questStates ?? {},
    runtimeRecords: overrides.runtimeRecords ?? {},
    grantedRewardIds: overrides.grantedRewardIds ?? [],
    authority: overrides.authority ?? "server",
  };
}

export function getHarthmereQuestRuntimeRecordV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
): HarthmereQuestRuntimeRecordV47 | undefined {
  return context.runtimeRecords[questId];
}

export function createHarthmereQuestRuntimeRecordV47(quest: any, tick = 0): HarthmereQuestRuntimeRecordV47 {
  const objectiveProgress: Record<string, HarthmereQuestRuntimeObjectiveProgressV47> = {};
  for (const objective of quest.objectives ?? []) {
    objectiveProgress[objective.id] = { current: 0, target: objective.count ?? 1, completed: false };
  }
  return { questId: quest.id, state: "active", acceptedAtTick: tick, objectiveProgress };
}

export function validateHarthmereQuestRuntimeEventV47(
  context: HarthmereQuestRuntimeContextV47,
  event: HarthmereQuestRuntimeEventV47,
): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];
  const quest = getHarthmereQuestByIdV46(event.questId);
  if (!quest) reasons.push("missing_quest");
  if (event.authority !== "server" || context.authority !== "server") reasons.push("client_cannot_advance_or_grant_quest_state");
  if (!event.eventId || !event.eventId.includes(event.questId)) reasons.push("event_id_must_be_namespaced_to_quest");
  if (event.actorId !== context.playerId) reasons.push("actor_mismatch");
  if (event.tick < context.tick) reasons.push("stale_event_tick");
  if (event.type === "complete" && context.grantedRewardIds.includes(`reward:${event.questId}`)) reasons.push("reward_already_granted");
  if ((event.type === "collect" || event.type === "complete") && context.inventoryFreeSlots < 0) reasons.push("invalid_inventory_state");
  return { ok: reasons.length === 0, reasons };
}

export function acceptHarthmereQuestV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
  eventId = `${questId}:accept:${context.tick}`,
): HarthmereQuestRuntimeResultV47 {
  const quest = getHarthmereQuestByIdV46(questId);
  if (!quest) return { ok: false, questId, reasons: ["missing_quest"] };
  const validation = validateHarthmereQuestActivationV46(quest, {
    playerLevel: context.playerLevel,
    hour: context.hour,
    timeOfDay: context.timeOfDay,
    weather: context.weather,
    flags: context.flags,
    completedQuestIds: context.completedQuestIds,
    questStates: context.questStates,
  } as any);
  if (!validation.ok) return { ok: false, questId, state: "locked", reasons: validation.reasons };
  if (context.runtimeRecords[questId]?.state === "active") {
    return { ok: true, questId, state: "active", record: context.runtimeRecords[questId], reasons: ["already_active_idempotent"] };
  }
  const event = { eventId, questId, type: "accept" as const, actorId: context.playerId, authority: "server" as const, tick: context.tick };
  const eventValidation = validateHarthmereQuestRuntimeEventV47(context, event);
  if (!eventValidation.ok) return { ok: false, questId, reasons: eventValidation.reasons };
  const record = createHarthmereQuestRuntimeRecordV47(quest, context.tick);
  context.runtimeRecords[questId] = record;
  context.questStates[questId] = "active";
  return {
    ok: true,
    questId,
    state: "active",
    record,
    journal: getHarthmereQuestJournalEntryV47(context, questId),
    mapHint: getHarthmereQuestMapHintV47(context, questId),
    telemetry: [{ kind: "quest_accepted", questId, tick: context.tick }],
    reasons: [],
  };
}

export function advanceHarthmereQuestObjectiveV47(
  context: HarthmereQuestRuntimeContextV47,
  event: HarthmereQuestRuntimeEventV47,
): HarthmereQuestRuntimeResultV47 {
  const eventValidation = validateHarthmereQuestRuntimeEventV47(context, event);
  if (!eventValidation.ok) return { ok: false, questId: event.questId, reasons: eventValidation.reasons };
  const record = context.runtimeRecords[event.questId];
  const quest = getHarthmereQuestByIdV46(event.questId);
  if (!record || !quest || record.state !== "active") return { ok: false, questId: event.questId, reasons: ["quest_not_active"] };
  const objectiveId = event.objectiveId;
  if (!objectiveId || !record.objectiveProgress[objectiveId]) return { ok: false, questId: event.questId, reasons: ["missing_objective"] };
  const progress = record.objectiveProgress[objectiveId];
  if (progress.lastEventId === event.eventId) return { ok: true, questId: event.questId, state: record.state, record, reasons: ["duplicate_objective_event_idempotent"] };
  progress.current = Math.min(progress.target, progress.current + Math.max(1, event.count ?? 1));
  progress.completed = progress.current >= progress.target;
  progress.lastEventId = event.eventId;
  const allComplete = Object.values(record.objectiveProgress).every((item) => item.completed);
  if (allComplete) {
    record.state = "ready_to_complete";
    context.questStates[event.questId] = "ready_to_complete";
  }
  return {
    ok: true,
    questId: event.questId,
    state: record.state,
    record,
    journal: getHarthmereQuestJournalEntryV47(context, event.questId),
    mapHint: getHarthmereQuestMapHintV47(context, event.questId),
    telemetry: [
      { kind: "objective_progressed", questId: event.questId, objectiveId, tick: context.tick },
      ...(allComplete ? [{ kind: "quest_ready_to_complete" as const, questId: event.questId, tick: context.tick }] : []),
    ],
    reasons: [],
  };
}

export function completeHarthmereQuestV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
  eventId = `${questId}:complete:${context.tick}`,
): HarthmereQuestRuntimeResultV47 {
  const event = { eventId, questId, type: "complete" as const, actorId: context.playerId, authority: "server" as const, tick: context.tick };
  const eventValidation = validateHarthmereQuestRuntimeEventV47(context, event);
  if (!eventValidation.ok) return { ok: false, questId, reasons: eventValidation.reasons };
  const quest = getHarthmereQuestByIdV46(questId);
  const record = context.runtimeRecords[questId];
  if (!quest || !record) return { ok: false, questId, reasons: ["missing_runtime_record"] };
  if (record.state !== "ready_to_complete") return { ok: false, questId, state: record.state, reasons: ["objectives_not_ready"] };
  const rewardGrantId = `reward:${questId}`;
  if (context.grantedRewardIds.includes(rewardGrantId)) return { ok: true, questId, state: "completed", record, reasons: ["reward_already_granted_idempotent"] };
  record.state = "completed";
  record.completedAtTick = context.tick;
  record.rewardGrantId = rewardGrantId;
  context.questStates[questId] = "completed";
  context.completedQuestIds.push(questId);
  context.grantedRewardIds.push(rewardGrantId);
  return {
    ok: true,
    questId,
    state: "completed",
    record,
    rewardsGranted: { ...quest.rewards, rewardGrantId, authority: "server", idempotent: true },
    telemetry: [{ kind: "reward_granted_once", questId, tick: context.tick }, { kind: "quest_completed", questId, tick: context.tick }],
    reasons: [],
  };
}

export function failHarthmereQuestV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
  reason: string,
): HarthmereQuestRuntimeResultV47 {
  const record = context.runtimeRecords[questId];
  if (!record) return { ok: false, questId, reasons: ["missing_runtime_record"] };
  record.state = "failed";
  record.failedAtTick = context.tick;
  record.failureReason = reason;
  context.questStates[questId] = "failed";
  return { ok: true, questId, state: "failed", record, telemetry: [{ kind: "quest_failed", questId, tick: context.tick, details: { reason } }], reasons: [] };
}

export function abandonHarthmereQuestV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
): HarthmereQuestRuntimeResultV47 {
  const record = context.runtimeRecords[questId];
  if (!record) return { ok: false, questId, reasons: ["missing_runtime_record"] };
  record.state = "abandoned";
  record.abandonedAtTick = context.tick;
  context.questStates[questId] = "abandoned";
  return { ok: true, questId, state: "abandoned", record, telemetry: [{ kind: "quest_abandoned", questId, tick: context.tick }], reasons: [] };
}

export function retryHarthmereQuestV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
): HarthmereQuestRuntimeResultV47 {
  const quest = getHarthmereQuestByIdV46(questId);
  if (!quest) return { ok: false, questId, reasons: ["missing_quest"] };
  const previous = context.runtimeRecords[questId];
  if (previous?.state !== "failed" && previous?.state !== "abandoned") return { ok: false, questId, reasons: ["retry_requires_failed_or_abandoned_state"] };
  const record = createHarthmereQuestRuntimeRecordV47(quest, context.tick);
  context.runtimeRecords[questId] = record;
  context.questStates[questId] = "active";
  return { ok: true, questId, state: "active", record, telemetry: [{ kind: "quest_retried", questId, tick: context.tick }], reasons: [] };
}

export function getHarthmereQuestMapHintV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
): HarthmereQuestMapHintV47 | undefined {
  const quest = getHarthmereQuestByIdV46(questId);
  if (!quest) return undefined;
  const record = context.runtimeRecords[questId];
  const firstOpenObjective = record
    ? quest.objectives.find((objective: any) => !record.objectiveProgress[objective.id]?.completed)
    : undefined;
  const source = firstOpenObjective?.location ?? quest.location;
  const waypoint = shiftHarthmereAuthoredPositionToWorldV71(source.waypoint);
  return {
    questId,
    objectiveId: firstOpenObjective?.id,
    district: source.district,
    waypoint,
    compassLabel: firstOpenObjective?.label ?? `Speak with ${quest.giverName ?? "the world trigger"}`,
    hintType: record?.state === "ready_to_complete" ? "turn_in" : firstOpenObjective ? "objective" : quest.hidden ? "hidden_world_trigger" : "giver",
  };
}

export function getHarthmereQuestJournalEntryV47(
  context: HarthmereQuestRuntimeContextV47,
  questId: string,
): HarthmereQuestJournalEntryV47 | undefined {
  const quest = getHarthmereQuestByIdV46(questId);
  if (!quest) return undefined;
  const state = context.questStates[questId] ?? quest.activeRules.initialState ?? "available";
  const record = context.runtimeRecords[questId];
  const activeObjectives = (quest.objectives ?? []).map((objective: any) => {
    const progress = record?.objectiveProgress?.[objective.id] ?? { current: 0, target: objective.count ?? 1, completed: false };
    return { id: objective.id, label: objective.label, current: progress.current, target: progress.target, completed: progress.completed };
  });
  return {
    questId,
    title: quest.title,
    state,
    giverName: quest.giverName,
    district: quest.location.district,
    activeObjectives,
    dialogueState: quest.dialogue?.[state === "ready_to_complete" ? "ready" : state === "completed" ? "complete" : state === "failed" ? "fail" : state === "active" ? "active" : "offer"],
    rewardPreview: quest.rewards,
    mapHints: [getHarthmereQuestMapHintV47(context, questId)].filter(Boolean) as HarthmereQuestMapHintV47[],
  };
}

export function getHarthmereDialogueQuestOffersV47(npcId: keyof typeof HARTHMERE_QUEST_DIALOGUE_LINKS_V47, context: HarthmereQuestRuntimeContextV47) {
  const questIds = HARTHMERE_QUEST_DIALOGUE_LINKS_V47[npcId] ?? [];
  return questIds
    .map((questId) => getHarthmereQuestByIdV46(questId))
    .filter(Boolean)
    .map((quest: any) => ({ questId: quest.id, title: quest.title, state: context.questStates[quest.id] ?? quest.activeRules.initialState, offer: quest.dialogue.offer }));
}

export function validateHarthmereQuestRuntimeCoverageV47() {
  const failures: string[] = [];
  for (const quest of HARTHMERE_QUEST_CATALOG_V46 as any[]) {
    if (!quest.objectives?.length) failures.push(`${quest.id} has no objectives`);
    if (!quest.rewards?.previewText) failures.push(`${quest.id} has no reward preview`);
    if (!quest.testContract?.stateTransitions?.length) failures.push(`${quest.id} has no state transitions`);
  }
  return { ok: failures.length === 0, failures, questCount: (HARTHMERE_QUEST_CATALOG_V46 as any[]).length };
}
