// Auto-generated by install-harthmere-runtime-completion-v47.sh
// v47 implements the Thaedryn final boss runtime contract: phases, path logic,
// solo/group tuning, rewards, town phasing, cinematics, and telemetry.

export const HARTHMERE_THAEDRYN_BOSS_VERSION_V47 = 47 as const;
export const HARTHMERE_THAEDRYN_PHASES_V47_JSON = `[
  {
    "id": "phase_1_sleeper",
    "name": "The Sleeper",
    "chainRange": [
      4,
      3
    ],
    "healthPctRange": [
      100,
      76
    ],
    "requiredTelegraphSeconds": 1.6,
    "mechanics": [
      "slow_tail_sweep",
      "sound_cloud_interrupt",
      "chain_anchor_vulnerability"
    ],
    "failures": [
      "standing_in_sound_cloud",
      "ignoring_chain_anchor"
    ]
  },
  {
    "id": "phase_2_half_waking",
    "name": "The Half-Waking",
    "chainRange": [
      2,
      2
    ],
    "healthPctRange": [
      75,
      51
    ],
    "requiredTelegraphSeconds": 1.8,
    "mechanics": [
      "faster_head_sweep",
      "river_force_breath_cone",
      "anchor_reposition"
    ],
    "failures": [
      "stacking_in_cone",
      "breaking_wrong_chain_order"
    ]
  },
  {
    "id": "phase_3_bellbound",
    "name": "The Bellbound",
    "chainRange": [
      1,
      1
    ],
    "healthPctRange": [
      50,
      21
    ],
    "requiredTelegraphSeconds": 2.0,
    "mechanics": [
      "wing_gust",
      "vein_beast_adds",
      "arena_quadrant_pressure"
    ],
    "failures": [
      "party_blown_into_anchor",
      "adds_not_controlled"
    ]
  },
  {
    "id": "phase_4_path_dependent",
    "name": "Path-Dependent Resolution",
    "chainRange": [
      0,
      0
    ],
    "healthPctRange": [
      20,
      0
    ],
    "requiredTelegraphSeconds": 2.2,
    "mechanics": [
      "rebind_bell_cycle",
      "slay_burn_phase",
      "wake_hold_fire_and_negotiate"
    ],
    "failures": [
      "wake_path_attack_threshold_crossed",
      "rebind_missed_ring_cycle",
      "party_wipe"
    ]
  }
]`;
export const HARTHMERE_THAEDRYN_PATHS_V47_JSON = `[
  {
    "id": "rebind",
    "label": "Rebind Thaedryn",
    "requires": [
      "fallen_bell_positioned",
      "ring_cycle_completed",
      "do_not_kill_dragon"
    ],
    "phase4Objective": "Survive peak strength while coordinating the bell ring cycle.",
    "townPhase": "bell_sings_continuously_chapel_relief",
    "rewards": {
      "xp": 900,
      "silver": 500,
      "items": [
        "Bellbinder's Pin"
      ],
      "titles": [
        "Bell Warden"
      ],
      "unlocks": [
        "Pellmarra courier hook",
        "Underways affix rebind"
      ]
    },
    "cinematic": "Thaedryn sleeps again, Aldren weeps with relief, and the Listening Council hears the news."
  },
  {
    "id": "slay",
    "label": "Slay Thaedryn",
    "requires": [
      "dragon_health_zero",
      "no_wake_hold_fire",
      "no_rebind_cycle"
    ],
    "phase4Objective": "Defeat Thaedryn at peak aggression and accept the moral cost.",
    "townPhase": "town_safe_but_lattice_weakened",
    "rewards": {
      "xp": 1200,
      "silver": 650,
      "items": [
        "Thaedryn's Tooth",
        "Bronze-Scale Trophy"
      ],
      "titles": [
        "Wyrm-Slayer"
      ],
      "unlocks": [
        "Murvath omen",
        "dragon_tooth_crafting"
      ]
    },
    "cinematic": "Thaedryn dies mid-sentence, the chamber falls silent, and the world becomes poorer for it."
  },
  {
    "id": "wake",
    "label": "Wake Thaedryn",
    "requires": [
      "hold_fire_after_third_chain",
      "handbell_greeting",
      "compassion_history_threshold"
    ],
    "phase4Objective": "Stop attacking, ring the greeting, and negotiate with the dragon.",
    "townPhase": "bell_breaks_dragon_leaves_north",
    "rewards": {
      "xp": 1000,
      "silver": 450,
      "items": [
        "Old Tongue Handbell"
      ],
      "titles": [
        "Dragon's Witness"
      ],
      "unlocks": [
        "Veneth expansion hook",
        "Thaedryn ally rumor"
      ]
    },
    "cinematic": "Thaedryn thanks the player, breaks free, and rises through the town into the sky."
  }
]`;
export const HARTHMERE_THAEDRYN_PHASES_V47 = JSON.parse(HARTHMERE_THAEDRYN_PHASES_V47_JSON) as any[];
export const HARTHMERE_THAEDRYN_PATHS_V47 = JSON.parse(HARTHMERE_THAEDRYN_PATHS_V47_JSON) as any[];

export type HarthmereThaedrynPathV47 = "rebind" | "slay" | "wake";

export interface HarthmereThaedrynBossStateV47 {
  questId: "bellbound_q12_thaedryn_bellbound";
  active: boolean;
  mode: "solo_story" | "group";
  phaseId: string;
  healthPct: number;
  chainsRemaining: number;
  chosenPath?: HarthmereThaedrynPathV47;
  wakeAttackThreshold: number;
  wakeAttacksAfterThirdChain: number;
  rebindRingCyclesCompleted: number;
  partyWipes: number;
  completed: boolean;
  townPhase?: string;
}

export function createThaedrynBossStateV47(mode: "solo_story" | "group" = "group"): HarthmereThaedrynBossStateV47 {
  return {
    questId: "bellbound_q12_thaedryn_bellbound",
    active: true,
    mode,
    phaseId: "phase_1_sleeper",
    healthPct: 100,
    chainsRemaining: 4,
    wakeAttackThreshold: mode === "solo_story" ? 2 : 1,
    wakeAttacksAfterThirdChain: 0,
    rebindRingCyclesCompleted: 0,
    partyWipes: 0,
    completed: false,
  };
}

export function getThaedrynPhaseForStateV47(state: HarthmereThaedrynBossStateV47) {
  if (state.chainsRemaining <= 0 || state.healthPct <= 20) return HARTHMERE_THAEDRYN_PHASES_V47.find((phase) => phase.id === "phase_4_path_dependent");
  if (state.chainsRemaining === 1 || state.healthPct <= 50) return HARTHMERE_THAEDRYN_PHASES_V47.find((phase) => phase.id === "phase_3_bellbound");
  if (state.chainsRemaining === 2 || state.healthPct <= 75) return HARTHMERE_THAEDRYN_PHASES_V47.find((phase) => phase.id === "phase_2_half_waking");
  return HARTHMERE_THAEDRYN_PHASES_V47.find((phase) => phase.id === "phase_1_sleeper");
}

export function applyThaedrynBossEventV47(
  state: HarthmereThaedrynBossStateV47,
  event: { type: string; amount?: number; path?: HarthmereThaedrynPathV47 },
): HarthmereThaedrynBossStateV47 {
  const next = { ...state };
  if (!next.active || next.completed) return next;
  if (event.type === "damage") next.healthPct = Math.max(0, next.healthPct - Math.max(0, event.amount ?? 0));
  if (event.type === "break_chain") next.chainsRemaining = Math.max(0, next.chainsRemaining - 1);
  if (event.type === "attack_after_third_chain" && next.chainsRemaining <= 1) next.wakeAttacksAfterThirdChain += 1;
  if (event.type === "rebind_ring_cycle") next.rebindRingCyclesCompleted += 1;
  if (event.type === "party_wipe") next.partyWipes += 1;
  if (event.type === "choose_path" && event.path) next.chosenPath = event.path;
  const phase = getThaedrynPhaseForStateV47(next);
  next.phaseId = phase?.id ?? next.phaseId;
  return next;
}

export function resolveThaedrynPathV47(state: HarthmereThaedrynBossStateV47): { ok: boolean; path?: any; reasons: string[]; rewards?: any; townPhase?: string } {
  const reasons: string[] = [];
  const pathId = state.chosenPath;
  const path = HARTHMERE_THAEDRYN_PATHS_V47.find((item) => item.id === pathId);
  if (!path) return { ok: false, reasons: ["missing_path_choice"] };
  if (pathId === "wake") {
    if (state.chainsRemaining > 1) reasons.push("wake_requires_three_chains_broken");
    if (state.wakeAttacksAfterThirdChain > state.wakeAttackThreshold) reasons.push("wake_collapsed_into_slay_by_attack_threshold");
  }
  if (pathId === "rebind") {
    if (state.rebindRingCyclesCompleted < 3) reasons.push("rebind_requires_three_ring_cycles");
    if (state.healthPct <= 0) reasons.push("dragon_dead_cannot_rebind");
  }
  if (pathId === "slay" && state.healthPct > 0) reasons.push("slay_requires_zero_health");
  return { ok: reasons.length === 0, path, reasons, rewards: path.rewards, townPhase: path.townPhase };
}

export function completeThaedrynBossV47(state: HarthmereThaedrynBossStateV47) {
  const resolution = resolveThaedrynPathV47(state);
  if (!resolution.ok) return { ...resolution, state };
  return {
    ok: true,
    state: { ...state, completed: true, active: false, townPhase: resolution.townPhase },
    path: resolution.path,
    rewards: resolution.rewards,
    townPhase: resolution.townPhase,
    telemetry: [
      { kind: "q12_path_selected", path: resolution.path.id },
      { kind: "q12_completed", path: resolution.path.id, partyWipes: state.partyWipes, mode: state.mode },
    ],
    reasons: [],
  };
}

export function previewThaedrynRewardsV47(pathId: HarthmereThaedrynPathV47) {
  return HARTHMERE_THAEDRYN_PATHS_V47.find((path) => path.id === pathId)?.rewards;
}

export function validateThaedrynBossContractV47() {
  const failures: string[] = [];
  if (HARTHMERE_THAEDRYN_PHASES_V47.length !== 4) failures.push("Thaedryn must have exactly four phases");
  for (const id of ["rebind", "slay", "wake"]) {
    const path = HARTHMERE_THAEDRYN_PATHS_V47.find((item) => item.id === id);
    if (!path) failures.push(`missing path ${id}`);
    if (!path?.rewards?.items?.length) failures.push(`path ${id} missing item rewards`);
    if (!path?.townPhase) failures.push(`path ${id} missing post-fight town phase`);
    if (!path?.cinematic) failures.push(`path ${id} missing cinematic`);
  }
  if (!HARTHMERE_THAEDRYN_PHASES_V47.every((phase) => phase.requiredTelegraphSeconds >= 1.5)) failures.push("boss telegraphs too short");
  return { ok: failures.length === 0, failures };
}
