// Auto-generated by install-harthmere-runtime-completion-v47.sh
// v47 implements the missing Wilds gameplay loops: gathering/hunting/combat,
// resource ownership, overharvest consequences, public events, and town feedback.

export const HARTHMERE_WILDS_GAMEPLAY_LOOPS_VERSION_V47 = 47 as const;
export const HARTHMERE_WILDS_LOOP_SYSTEMS_V47_JSON = `[
  {
    "id": "gate_fields_starter_loop_v47",
    "name": "Gate Fields Starter Loop",
    "regions": [
      "Gate Fields",
      "Last Watch Post"
    ],
    "dangerRing": 1,
    "coreActivities": [
      "gather_food",
      "guard_warning",
      "light_combat",
      "return_to_market"
    ],
    "resources": [
      "apples",
      "grain",
      "small_game",
      "fieldstone"
    ],
    "threats": [
      "loose_chickens",
      "angry_goose",
      "road_wolf_after_dusk"
    ],
    "townEffects": [
      "bakery_stock",
      "market_food_price",
      "guard_warning_dialogue"
    ],
    "lawRules": [
      "owned_farm_goods_require_permission",
      "theft_flags_watch_reputation"
    ],
    "publicEvents": [
      "lost_lamb",
      "wolf_after_dusk"
    ],
    "testCases": [
      "safe road readable",
      "owned food theft triggers law",
      "return loop updates town food stock"
    ]
  },
  {
    "id": "mill_road_orchard_lane_events_v47",
    "name": "Mill Road and Orchard Lane Events",
    "regions": [
      "Mill Road",
      "Orchard Lane",
      "Miller's Rest"
    ],
    "dangerRing": 2,
    "coreActivities": [
      "escort_cart",
      "defend_orchard",
      "harvest_apples",
      "track_bandits"
    ],
    "resources": [
      "apples",
      "flour",
      "wagon_parts",
      "cider_herbs"
    ],
    "threats": [
      "bandit_scout",
      "wolf_pack",
      "harvest_beast_rare"
    ],
    "townEffects": [
      "bakery_goods",
      "inn_cider_stock",
      "road_price_discount"
    ],
    "lawRules": [
      "orchard_crates_are_owned",
      "defense_rewards_require_contribution"
    ],
    "publicEvents": [
      "orchard_bandit_raid",
      "rare_harvest_beast"
    ],
    "testCases": [
      "night increases wolves",
      "clearing bandits lowers cargo price",
      "harvest beast has elite public event state"
    ]
  },
  {
    "id": "greenmere_gathering_hunting_loop_v47",
    "name": "Greenmere Gathering and Hunting Loop",
    "regions": [
      "Greenmere Edge",
      "Old Hunter Track",
      "Charcoal Burners' Camp"
    ],
    "dangerRing": 3,
    "coreActivities": [
      "hunt_deer",
      "collect_herbs",
      "woodcut",
      "protect_charcoal_burners"
    ],
    "resources": [
      "timber",
      "herbs",
      "hides",
      "charcoal",
      "resin"
    ],
    "threats": [
      "boar",
      "black_bear",
      "dire_wolf",
      "missing_woodcutter"
    ],
    "townEffects": [
      "smithy_charcoal_supply",
      "apothecary_herb_stock",
      "repair_cost_modifier"
    ],
    "lawRules": [
      "overharvest_marks_forest_pressure",
      "hunting_near_road_scales_watch_warning"
    ],
    "publicEvents": [
      "missing_woodcutters",
      "charcoal_camp_defense"
    ],
    "testCases": [
      "resource nodes deplete and recover",
      "overharvest raises danger",
      "wood return repairs town props"
    ]
  },
  {
    "id": "briarfen_wetland_danger_loop_v47",
    "name": "Briarfen Wetland Danger Loop",
    "regions": [
      "Briarfen",
      "Witchlight Pool"
    ],
    "dangerRing": 4,
    "coreActivities": [
      "gather_reeds",
      "follow_witchlights",
      "fight_lurkers",
      "recover_lost_traveler"
    ],
    "resources": [
      "reeds",
      "clay",
      "river_herbs",
      "witchlight_essence"
    ],
    "threats": [
      "water_snake",
      "river_lurker",
      "drowned_corpse",
      "witchlight_trap"
    ],
    "townEffects": [
      "dock_goods_price",
      "apothecary_wetland_stock",
      "chapel_tension"
    ],
    "lawRules": [
      "smuggled_reeds_create_river_knots_suspicion",
      "failing_river_events_raises_prices"
    ],
    "publicEvents": [
      "witchlight_rescue",
      "flooded_supply_cache"
    ],
    "testCases": [
      "fog/night changes danger",
      "traveler rescue has fail state",
      "failed river event raises dock prices"
    ]
  },
  {
    "id": "watchtower_ridge_bandit_loop_v47",
    "name": "Ruined Watchtower Ridge Bandit Loop",
    "regions": [
      "Watchtower Ridge",
      "Broken Toll Road"
    ],
    "dangerRing": 4,
    "coreActivities": [
      "clear_bandit_camp",
      "disarm_snares",
      "recover_tax_chest",
      "choose_mercy_or_law"
    ],
    "resources": [
      "ore_scrap",
      "bandit_supplies",
      "old_toll_records"
    ],
    "threats": [
      "hedge_archer",
      "wagon_raider",
      "outlaw_brute",
      "former_guard_captain"
    ],
    "townEffects": [
      "road_prices_fall",
      "watch_reputation",
      "merchant_suspicion"
    ],
    "lawRules": [
      "captured_bandits_can_be_turned_in",
      "looting_watch_property_has_legal_risk"
    ],
    "publicEvents": [
      "road_ambush",
      "watchtower_signal_fire"
    ],
    "testCases": [
      "bandits have family roles",
      "clearing camp updates road safety",
      "mercy path changes reputation"
    ]
  },
  {
    "id": "gravewood_undead_loop_v47",
    "name": "Gravewood Undead Loop",
    "regions": [
      "Gravewood",
      "Outer Cemetery"
    ],
    "dangerRing": 5,
    "coreActivities": [
      "cleanse_graves",
      "fight_wights",
      "recover_names",
      "protect_pilgrim"
    ],
    "resources": [
      "grave_moss",
      "spirit_residue",
      "old_bones",
      "cursed_relic"
    ],
    "threats": [
      "fresh_risen",
      "bell_woken_dead",
      "mourning_wraith",
      "old_soldier_wight"
    ],
    "townEffects": [
      "chapel_grave_quests",
      "resurrection_service_tension",
      "night_bell_rumors"
    ],
    "lawRules": [
      "grave_goods_are_sacred",
      "chapel_turn_in_prevents_curse"
    ],
    "publicEvents": [
      "grave_rising",
      "pilgrim_path_defense"
    ],
    "testCases": [
      "grave goods theft curses player",
      "undead increase at night",
      "chapel reacts to cleanse progress"
    ]
  },
  {
    "id": "deep_old_wood_supernatural_loop_v47",
    "name": "Deep Old Wood Supernatural Loop",
    "regions": [
      "Deep Old Wood",
      "Split Oak",
      "Old Standing Stones"
    ],
    "dangerRing": 6,
    "coreActivities": [
      "party_gathering",
      "fight_root_dead",
      "collect_rare_fungus",
      "solve_moss_woman_riddle"
    ],
    "resources": [
      "ancient_heartwood",
      "mooncap",
      "bluefire_fungus",
      "mana_crystal",
      "root_crown_shard"
    ],
    "threats": [
      "rootling",
      "witch_crow",
      "hollow_treant",
      "root_crowned_dead"
    ],
    "townEffects": [
      "magic_shop_stock",
      "apothecary_rare_stock",
      "old_wood_rumors"
    ],
    "lawRules": [
      "standing_stone_nodes_are_sacred",
      "public_boss_requires_contribution"
    ],
    "publicEvents": [
      "root_crowned_dead_group_event",
      "old_wood_silence"
    ],
    "testCases": [
      "public boss has anchors",
      "rare nodes require danger ring",
      "Veneth route has noncombat resolution"
    ]
  },
  {
    "id": "resource_ownership_and_theft_law_v47",
    "name": "Resource Ownership and Theft Law",
    "regions": [
      "Town Edge",
      "Farms",
      "Wilds"
    ],
    "dangerRing": 0,
    "coreActivities": [
      "classify_resource",
      "validate_permission",
      "apply_law_consequence",
      "route_to_vendor"
    ],
    "resources": [
      "owned_goods",
      "public_nodes",
      "sacred_relics",
      "smuggled_goods"
    ],
    "threats": [
      "watch_penalty",
      "merchant_blacklist",
      "curse_flag"
    ],
    "townEffects": [
      "law_reputation",
      "vendor_price_modifier",
      "dialogue_reactivity"
    ],
    "lawRules": [
      "owned goods require permission",
      "public wild nodes are legal",
      "sacred/illegal goods require special turn-in"
    ],
    "publicEvents": [],
    "testCases": [
      "owned farm theft flags watch",
      "wild node legal gather",
      "sacred relic needs chapel turn-in"
    ]
  },
  {
    "id": "overharvesting_consequence_loop_v47",
    "name": "Overharvesting Consequence Loop",
    "regions": [
      "Greenmere",
      "Deep Old Wood",
      "Briarfen"
    ],
    "dangerRing": 3,
    "coreActivities": [
      "track_node_pressure",
      "spawn_warning_signs",
      "raise_danger",
      "recover_over_time"
    ],
    "resources": [
      "timber",
      "herbs",
      "fungus",
      "ore"
    ],
    "threats": [
      "corrupted_animals",
      "angry_spirits",
      "scarcity_price_increase"
    ],
    "townEffects": [
      "vendor_scarcity",
      "npc_warning_dialogue",
      "resource_recovery_quests"
    ],
    "lawRules": [
      "guild commissions discourage overharvest",
      "recovery quests reduce pressure"
    ],
    "publicEvents": [
      "forest_backlash",
      "resource_recovery_drive"
    ],
    "testCases": [
      "overharvest creates pressure",
      "pressure spawns corrupted warning",
      "recovery quest lowers pressure"
    ]
  },
  {
    "id": "public_world_events_v47",
    "name": "Public World Events",
    "regions": [
      "All Wilds Rings"
    ],
    "dangerRing": 1,
    "coreActivities": [
      "spawn_event",
      "track_contribution",
      "scale_enemies",
      "grant_public_rewards"
    ],
    "resources": [
      "event_cache",
      "faction_tokens",
      "rare_materials"
    ],
    "threats": [
      "bandit_raid",
      "root_crowned_dead",
      "grave_rising",
      "harvest_beast"
    ],
    "townEffects": [
      "festival_state",
      "road_safety",
      "chapel_tension",
      "market_prices"
    ],
    "lawRules": [
      "contribution_required_for_rewards",
      "safe-zone griefing blocked"
    ],
    "publicEvents": [
      "bandit_raid",
      "grave_rising",
      "root_crowned_dead",
      "harvest_beast"
    ],
    "testCases": [
      "contribution required",
      "event scales by players",
      "town result applies after event"
    ]
  }
]`;
export const HARTHMERE_WILDS_LOOP_SYSTEMS_V47 = JSON.parse(HARTHMERE_WILDS_LOOP_SYSTEMS_V47_JSON) as any[];

export interface HarthmereWildsLoopContextV47 {
  region: string;
  hour: number;
  weather: string;
  playerCount: number;
  resourcePressure: Record<string, number>;
  townStock: Record<string, number>;
  reputation: Record<string, number>;
}

export function getHarthmereWildsLoopByIdV47(id: string) {
  return HARTHMERE_WILDS_LOOP_SYSTEMS_V47.find((loop) => loop.id === id);
}

export function getHarthmereWildsLoopsForRegionV47(region: string) {
  return HARTHMERE_WILDS_LOOP_SYSTEMS_V47.filter((loop) => (loop.regions ?? []).some((item: string) => item.includes(region) || region.includes(item)));
}

export function classifyHarthmereResourceOwnershipV47(resourceKind: "owned_goods" | "public_node" | "sacred_relic" | "illegal_smuggled_goods") {
  if (resourceKind === "owned_goods") return { legal: false, permissionRequired: true, consequence: "watch_reputation_loss" };
  if (resourceKind === "sacred_relic") return { legal: false, permissionRequired: false, consequence: "chapel_turn_in_or_curse" };
  if (resourceKind === "illegal_smuggled_goods") return { legal: false, permissionRequired: false, consequence: "river_knots_or_watch_pressure" };
  return { legal: true, permissionRequired: false, consequence: "none" };
}

export function applyHarthmereWildsGatheringV47(
  context: HarthmereWildsLoopContextV47,
  resource: string,
  amount: number,
) {
  const next = { ...context, resourcePressure: { ...context.resourcePressure }, townStock: { ...context.townStock } };
  next.resourcePressure[resource] = (next.resourcePressure[resource] ?? 0) + amount;
  next.townStock[resource] = (next.townStock[resource] ?? 0) + Math.max(0, amount);
  const overharvested = next.resourcePressure[resource] >= 100;
  return {
    ok: true,
    context: next,
    overharvested,
    consequences: overharvested ? ["corrupted_animals_spawn", "vendor_scarcity_warning", "resource_recovery_quest_available"] : ["town_supply_improved"],
  };
}

export function resolveHarthmereWildsPublicEventV47(
  loopId: string,
  contribution: { damage?: number; healing?: number; objectives?: number; resources?: number },
) {
  const loop = getHarthmereWildsLoopByIdV47(loopId);
  if (!loop) return { ok: false, reasons: ["missing_loop"] };
  const score = (contribution.damage ?? 0) + (contribution.healing ?? 0) + (contribution.objectives ?? 0) * 50 + (contribution.resources ?? 0) * 10;
  const eligible = score >= 50;
  return {
    ok: eligible,
    loopId,
    score,
    scaledThreats: loop.threats,
    townEffects: eligible ? loop.townEffects : [],
    rewardsGranted: eligible ? ["faction_tokens", "coin", "resource_cache"] : [],
    reasons: eligible ? [] : ["insufficient_contribution"],
  };
}

export function computeHarthmereWildsDangerV47(loopId: string, hour: number, pressure = 0) {
  const loop = getHarthmereWildsLoopByIdV47(loopId);
  if (!loop) return undefined;
  const nightBonus = hour >= 20 || hour <= 5 ? 2 : 0;
  const pressureBonus = pressure >= 100 ? 2 : pressure >= 50 ? 1 : 0;
  return { loopId, danger: loop.dangerRing + nightBonus + pressureBonus, nightBonus, pressureBonus };
}

export function validateHarthmereWildsLoopCoverageV47() {
  const required = [
    "gate_fields_starter_loop_v47",
    "mill_road_orchard_lane_events_v47",
    "greenmere_gathering_hunting_loop_v47",
    "briarfen_wetland_danger_loop_v47",
    "watchtower_ridge_bandit_loop_v47",
    "gravewood_undead_loop_v47",
    "deep_old_wood_supernatural_loop_v47",
    "resource_ownership_and_theft_law_v47",
    "overharvesting_consequence_loop_v47",
    "public_world_events_v47",
  ];
  const failures: string[] = [];
  for (const id of required) {
    if (!getHarthmereWildsLoopByIdV47(id)) failures.push(`missing wilds loop ${id}`);
  }
  for (const loop of HARTHMERE_WILDS_LOOP_SYSTEMS_V47) {
    if (!loop.coreActivities?.length) failures.push(`${loop.id} missing activities`);
    if (!loop.resources?.length) failures.push(`${loop.id} missing resources`);
    if (!loop.townEffects?.length) failures.push(`${loop.id} missing town feedback`);
    if (!loop.lawRules?.length) failures.push(`${loop.id} missing law/resource rules`);
    if (!loop.testCases?.length) failures.push(`${loop.id} missing test cases`);
  }
  return { ok: failures.length === 0, failures, loopCount: HARTHMERE_WILDS_LOOP_SYSTEMS_V47.length };
}
