// Generated by install-harthmere-bridge-wilds-audit-v54.sh
// HARTHMERE_WILDS_BIBLE_IMPLEMENTATION_VERSION_V54
// Static implementation contract for the uploaded Harthmere Wilds bible.
// This records the full checklist the renderer, quest loops, NPC compendium,
// and economy/law systems must satisfy.

export const HARTHMERE_WILDS_BIBLE_IMPLEMENTATION_VERSION_V54 = "harthmere-wilds-bible-implementation-v54" as const;

export const HARTHMERE_WILDS_REQUIRED_REGIONS_V54 = [
  "Gate Fields",
  "Mill Road",
  "Orchard Lane",
  "Greenmere Edge",
  "Old Hunter's Track",
  "Briarfen",
  "Watchtower Ridge",
  "Gravewood",
  "Deep Old Wood",
] as const;

export const HARTHMERE_WILDS_REQUIRED_LANDMARKS_V54 = [
  "Last Watch Post",
  "Thornbridge Crossing",
  "Miller's Rest",
  "Charcoal Burners' Camp",
  "Split Oak",
  "Broken Toll Road",
  "Witchlight Pool",
  "Old Quarry Cut",
] as const;

export const HARTHMERE_WILDS_REQUIRED_NPCS_V54 = [
  "Edda Wren",
  "Old Merrit Bracken",
  "Sella Reedfoot",
  "Tamsin Vale",
  "Brother Cael Marsen",
  "Rusk Hallowhand",
  "Veneth of the Green Threshold",
] as const;

export const HARTHMERE_WILDS_REQUIRED_STORY_LINES_V54 = [
  "First Steps Beyond the Gate",
  "Road Trouble Chain",
  "The Orchard That Watches",
  "The Briarfen Lights",
  "The Grave Moss Tithe",
  "The Old Hunter's Debt",
  "The Bell Beneath the Roots",
  "Caravan Under Attack",
  "Flood from the Briarfen",
  "The Harvest Beast",
  "The Root-Crowned Dead",
] as const;

export const HARTHMERE_WILDS_REQUIRED_RESOURCE_GROUPS_V54 = [
  "logging",
  "herbalism",
  "hunting_skinning",
  "mining_stone",
  "fishing_wetland",
  "archaeology_relics",
] as const;

export const HARTHMERE_WILDS_REQUIRED_ENEMY_GROUPS_V54 = [
  "bandits",
  "undead",
  "forest_monsters",
  "smugglers",
  "passive_animals",
  "defensive_animals",
  "predators",
  "corrupted_animals",
] as const;

export const HARTHMERE_WILDS_IMPLEMENTATION_CONTRACT_V54 = {
  version: HARTHMERE_WILDS_BIBLE_IMPLEMENTATION_VERSION_V54,
  designStandard: "Every area must be readable, useful, dangerous in context, and tied back to Harthmere.",
  bridgeRule: "Old Bridge and Thornbridge Crossing are approved bridge/checkpoint exceptions: decks are walkable; parapets block only edges.",
  regions: HARTHMERE_WILDS_REQUIRED_REGIONS_V54,
  landmarks: HARTHMERE_WILDS_REQUIRED_LANDMARKS_V54,
  npcs: HARTHMERE_WILDS_REQUIRED_NPCS_V54,
  storyLines: HARTHMERE_WILDS_REQUIRED_STORY_LINES_V54,
  resourceGroups: HARTHMERE_WILDS_REQUIRED_RESOURCE_GROUPS_V54,
  enemyGroups: HARTHMERE_WILDS_REQUIRED_ENEMY_GROUPS_V54,
  systems: [
    "resource ownership and theft law",
    "overharvest consequence loop",
    "public world events",
    "town supply feedback",
    "time of day and storm danger shifts",
    "safe-to-dangerous visual readability rings",
  ],
} as const;
