// GROVE_QUESTS_NEIGHBOR — generated by
// scripts/harthmere/convert-grove-catalog-to-typed.cjs from the retired
// SNAPSHOT_GROVE_QUESTS, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest ids and step ids are pinned by position
// (grove_quest_id_pins.ts), so appending is free and reordering is a
// migration. grove_quest_ids.test.ts fails on any reorder.
//
// Each step is ONE object. The retired shape stored objectives, triggers and
// markerIds as three positionally-indexed parallel arrays whose lengths were
// kept in sync only by a hand-written test.

import type { GroveQuestDef } from "@/shared/harthmere/grove/grove_quest_schema";

// Annotating the DECLARATION gives every element the contextual type, so tsc
// checks each row against one known target. See the note in
// convert-bible-catalog-to-typed.cjs for why neither `as const` nor a bare
// Object.freeze is used here.
const QUESTS: GroveQuestDef[] = [
  {
    "id": "intro_alexis_lovely_locks",
    "title": "First Mirror Outside the Fountain",
    "arc": "neighbor",
    "category": "road_neighbor",
    "area": "Lovely Locks",
    "hook": "Alexis runs the Lovely Locks fitting room and gives every new road-walker one calm look in the mirror before they go further. A travel kit is a promise the road can read.",
    "start": {
      "kind": "after_accepted",
      "questId": "grove_road_graduation",
      "giverNpcId": "alexis"
    },
    "steps": [
      {
        "id": "intro_alexis_lovely_locks_obj_01",
        "index": 0,
        "label": "Walk to Alexis at the Lovely Locks fitting room.",
        "trigger": "near_location",
        "markerId": "npc_alexis"
      },
      {
        "id": "intro_alexis_lovely_locks_obj_02",
        "index": 1,
        "label": "Stand at the Lovely Locks mirror so Alexis can look you over.",
        "trigger": "interact",
        "markerId": "lovely_locks_mirror"
      },
      {
        "id": "intro_alexis_lovely_locks_obj_03",
        "index": 2,
        "label": "Equip or confirm one travel-ready clothing piece while you are at the mirror.",
        "trigger": "inventory_change",
        "markerId": "lovely_locks_mirror"
      },
      {
        "id": "intro_alexis_lovely_locks_obj_04",
        "index": 3,
        "label": "Pick the road-promise your clothes should make: warm, light, or work-ready.",
        "trigger": "choice",
        "markerId": "lovely_locks_mirror"
      },
      {
        "id": "intro_alexis_lovely_locks_obj_05",
        "index": 4,
        "label": "Tell Alexis which promise you chose.",
        "trigger": "talk_npc",
        "markerId": "npc_alexis"
      }
    ],
    "reward": "55 XP, Lovely Locks discount flag, road outfit habit, Alexis trust opened.",
    "sampleDialogue": "The road takes more from people who arrive at it surprised. Let me see what you are wearing before the road sees it first.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "intro_luis_crossroads_cart",
    "title": "Three Wheels, One Road",
    "arc": "neighbor",
    "category": "road_neighbor",
    "area": "Genesis Crossroads",
    "hook": "Luis's repair cart is the Crossroads' shortest lesson in road problems. Anyone who can talk to Luis once knows where to bring a broken wheel later — and where to find the best gossip about which road is lying this week.",
    "start": {
      "kind": "after_accepted",
      "questId": "grove_road_graduation",
      "giverNpcId": "luis"
    },
    "steps": [
      {
        "id": "intro_luis_crossroads_cart_obj_01",
        "index": 0,
        "label": "Walk to Luis's repair cart at the Crossroads.",
        "trigger": "near_location",
        "markerId": "npc_luis"
      },
      {
        "id": "intro_luis_crossroads_cart_obj_02",
        "index": 1,
        "label": "Inspect Luis's cart and find what broke first.",
        "trigger": "interact",
        "markerId": "luis_cart"
      },
      {
        "id": "intro_luis_crossroads_cart_obj_03",
        "index": 2,
        "label": "Pick the repair Luis should try first: wheel, axle, or load.",
        "trigger": "choice",
        "markerId": "luis_cart"
      },
      {
        "id": "intro_luis_crossroads_cart_obj_04",
        "index": 3,
        "label": "Take a sample road bolt from the cart for your kit.",
        "trigger": "item_grant",
        "markerId": "luis_cart"
      },
      {
        "id": "intro_luis_crossroads_cart_obj_05",
        "index": 4,
        "label": "Tell Luis which lesson stuck with you.",
        "trigger": "talk_npc",
        "markerId": "npc_luis"
      }
    ],
    "reward": "65 XP, Crossroads road-bolt sample, repair habit, Luis merchant-compact intro flag.",
    "sampleDialogue": "I am not the smith. I am the one who keeps the road from eating his customers. Come look at this cart before it has to keep telling its story alone.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "intro_jane_mosslawn_edge",
    "title": "The Path That Listens Back",
    "arc": "neighbor",
    "category": "road_neighbor",
    "area": "Mosslawn Boundary",
    "hook": "Jane teaches new road-walkers to listen to Mosslawn before walking it. Warning moss, animal silence, and the right edge of the safe path are the first three things she shows you.",
    "start": {
      "kind": "after_accepted",
      "questId": "grove_road_graduation",
      "giverNpcId": "ranger_jane"
    },
    "steps": [
      {
        "id": "intro_jane_mosslawn_edge_obj_01",
        "index": 0,
        "label": "Walk to Ranger Jane at the Mosslawn boundary.",
        "trigger": "near_location",
        "markerId": "npc_ranger_jane"
      },
      {
        "id": "intro_jane_mosslawn_edge_obj_02",
        "index": 1,
        "label": "Inspect a warning moss patch with Jane standing next to you.",
        "trigger": "interact",
        "markerId": "mosslawn_warning_moss"
      },
      {
        "id": "intro_jane_mosslawn_edge_obj_03",
        "index": 2,
        "label": "Walk the marked stretch quietly to the song stones without sprinting.",
        "trigger": "near_location",
        "markerId": "mosslawn_song_stones"
      },
      {
        "id": "intro_jane_mosslawn_edge_obj_04",
        "index": 3,
        "label": "Pick a road-sense rule worth carrying: watch animals, watch moss, or watch the wind.",
        "trigger": "choice",
        "markerId": "mosslawn_warning_moss"
      },
      {
        "id": "intro_jane_mosslawn_edge_obj_05",
        "index": 4,
        "label": "Tell Ranger Jane which rule you chose.",
        "trigger": "talk_npc",
        "markerId": "npc_ranger_jane"
      }
    ],
    "reward": "70 XP, Ranger trail badge, Mosslawn safe-edge note, animal-sense flag.",
    "sampleDialogue": "If the road were polite, the animals would tell us. They are not polite. They go quiet. Let me show you which quiet is the helpful kind.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  }
];

export const GROVE_QUESTS_NEIGHBOR: readonly GroveQuestDef[] = Object.freeze(QUESTS);
