// GROVE_QUESTS_GRADUATION — generated by
// scripts/harthmere/convert-grove-catalog-to-typed.cjs from the retired
// SNAPSHOT_GROVE_QUESTS, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest ids and step ids are pinned by position
// (grove_quest_id_pins.ts), so appending is free and reordering is a
// migration. grove_quest_ids.test.ts fails on any reorder.
//
// Each step is ONE object. The retired shape stored objectives, triggers and
// markerIds as three positionally-indexed parallel arrays whose lengths were
// kept in sync only by a hand-written test.

import type { GroveQuestDef } from "@/shared/harthmere/grove/grove_quest_schema";

// Annotating the DECLARATION gives every element the contextual type, so tsc
// checks each row against one known target. See the note in
// convert-bible-catalog-to-typed.cjs for why neither `as const` nor a bare
// Object.freeze is used here.
const QUESTS: GroveQuestDef[] = [
  {
    "id": "grove_road_graduation",
    "title": "Where the Road Asks for You",
    "arc": "graduation",
    "category": "road_graduation",
    "area": "The Grove Fountain · Road Tour",
    "hook": "Jackie has watched you complete enough fountain lessons that the road is the next teacher. Three Grove neighbors live on it. Walk to each of them once so the road learns your boots.",
    "start": {
      "kind": "after_fountain_lessons",
      "minCompleted": 5,
      "giverNpcId": "jackie"
    },
    "steps": [
      {
        "id": "grove_road_graduation_obj_01",
        "index": 0,
        "label": "Tell Jackie you are ready to step beyond the fountain.",
        "trigger": "talk_npc",
        "markerId": "npc_jackie"
      },
      {
        "id": "grove_road_graduation_obj_02",
        "index": 1,
        "label": "Walk west to Lovely Locks and find Alexis at her fitting room.",
        "trigger": "near_location",
        "markerId": "npc_alexis"
      },
      {
        "id": "grove_road_graduation_obj_03",
        "index": 2,
        "label": "Walk south to the Genesis Crossroads and find Luis at his repair cart.",
        "trigger": "near_location",
        "markerId": "npc_luis"
      },
      {
        "id": "grove_road_graduation_obj_04",
        "index": 3,
        "label": "Walk to the Mosslawn boundary and find Ranger Jane on the quiet edge.",
        "trigger": "near_location",
        "markerId": "npc_ranger_jane"
      },
      {
        "id": "grove_road_graduation_obj_05",
        "index": 4,
        "label": "Return to Jackie at the fountain when all three neighbors have been met.",
        "trigger": "talk_npc",
        "markerId": "npc_jackie"
      }
    ],
    "reward": "120 XP, Grove graduation badge, three road-neighbor lessons unlocked, fountain compass habit closed out.",
    "sampleDialogue": "You have done the fountain lessons. The road wants the rest of the work now. Three of our neighbors live on it. Meet each one once and tell me which one made the most sense.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  }
];

export const GROVE_QUESTS_GRADUATION: readonly GroveQuestDef[] = Object.freeze(QUESTS);
