// GROVE_QUESTS_STORY — generated by
// scripts/harthmere/convert-grove-catalog-to-typed.cjs from the retired
// SNAPSHOT_GROVE_QUESTS, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest ids and step ids are pinned by position
// (grove_quest_id_pins.ts), so appending is free and reordering is a
// migration. grove_quest_ids.test.ts fails on any reorder.
//
// Each step is ONE object. The retired shape stored objectives, triggers and
// markerIds as three positionally-indexed parallel arrays whose lengths were
// kept in sync only by a hand-written test.

import type { GroveQuestDef } from "@/shared/harthmere/grove/grove_quest_schema";

// Annotating the DECLARATION gives every element the contextual type, so tsc
// checks each row against one known target. See the note in
// convert-bible-catalog-to-typed.cjs for why neither `as const` nor a bare
// Object.freeze is used here.
const QUESTS: GroveQuestDef[] = [
  {
    id: "read-the-jobs-board",
    title: "Read the Jobs Board",
    arc: "story",
    category: "road_story",
    area: "The Grove · Jobs Board",
    hook: "Find the Jobs Board so new players understand where public work, seeker tasks, and business requests live.",
    start: {
      kind: "giver",
      giverNpcId: "jackie",
    },
    steps: [
      {
        id: "read-the-jobs-board_obj_01",
        index: 0,
        label: "Read the Jobs Board.",
        trigger: "open_jobs_board",
        markerId: "harthmere_market_posting_board",
      },
      {
        id: "read-the-jobs-board_obj_02",
        index: 1,
        label: "Return to Jackie to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_jackie",
      },
    ],
    reward: "Jobs Board unlocked, public work routing, and first-job guidance.",
    sampleDialogue:
      "The board is where Harthmere posts real work. Read it, pick a job in person, and the map will track the task.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "building_system_intro_talk_to_mira",
    title: "Meet Mira, Grove Land Steward",
    arc: "story",
    category: "road_story",
    area: "The Grove · Building System",
    hook: "Mira introduces new players to safe land claims, voxel-only building rules, property permissions, taxes, and why muck land must be claimed before construction.",
    start: {
      kind: "giver",
      giverNpcId: "mira_grove_land_steward",
    },
    steps: [
      {
        id: "building_system_intro_talk_to_mira_obj_01",
        index: 0,
        label:
          "Talk to Mira Thatch in the Grove to learn how to buy safe land and build with voxels.",
        trigger: "talk_npc",
        markerId: "npc_mira_grove_land_steward",
      },
    ],
    reward: "Building System unlocked, Grove land marker, safe-plot guidance.",
    sampleDialogue:
      "Land is not safe because paper says so. It is safe when the muck is cleared, the boundary is marked, and the door opens onto a real path.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "road_signs_and_small_lies",
    title: "Road Signs and Small Lies",
    arc: "story",
    category: "road_story",
    area: "The Grove / Old Grove Road",
    hook: "Jackie admits one road sign is pointing the wrong way, but only because the road has been difficult lately.",
    start: {
      kind: "giver",
      giverNpcId: "jackie",
    },
    steps: [
      {
        id: "road_signs_and_small_lies_obj_01",
        index: 0,
        label: "Talk to Jackie about the bent road sign.",
        trigger: "talk_npc",
        markerId: "npc_jackie",
      },
      {
        id: "road_signs_and_small_lies_obj_02",
        index: 1,
        label: "Reach the Old Grove Road Post.",
        trigger: "near_location",
        markerId: "old_grove_road_post",
      },
      {
        id: "road_signs_and_small_lies_obj_03",
        index: 2,
        label:
          "Inspect and straighten the bent sign, pocketing the loose nail.",
        trigger: "interact",
        markerId: "old_grove_road_post",
      },
      {
        id: "road_signs_and_small_lies_obj_04",
        index: 3,
        label: "Return the nail to Jackie.",
        trigger: "talk_npc",
        markerId: "npc_jackie",
      },
    ],
    reward: "35 XP, 20 bling, Road Ahead map layer unlocked.",
    sampleDialogue:
      "That post has told three travelers to walk into a hedge this week. I am starting to think it has opinions.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "build_repair_claim_lesson",
    title: "Patch, Claim, Build",
    arc: "story",
    category: "road_story",
    area: "Genesis Crossroads / Grove Safe-Zone Edge",
    hook: "Luis turns a broken cart repair into a real building lesson: patch the road, read the claim stakes, and learn why safe-zone land works differently from wild claims.",
    start: {
      kind: "giver",
      giverNpcId: "luis",
    },
    steps: [
      {
        id: "build_repair_claim_lesson_obj_01",
        index: 0,
        label: "Talk to Luis at the Crossroads repair cart.",
        trigger: "talk_npc",
        markerId: "npc_luis",
      },
      {
        id: "build_repair_claim_lesson_obj_02",
        index: 1,
        label: "Inspect the Grove Practice Claim Stakes beside the safe road.",
        trigger: "near_location",
        markerId: "grove_claim_stakes",
      },
      {
        id: "build_repair_claim_lesson_obj_03",
        index: 2,
        label: "Gather or break loose repair material near the practice lot.",
        trigger: "destroy",
        markerId: "muckwad_patch",
      },
      {
        id: "build_repair_claim_lesson_obj_04",
        index: 3,
        label:
          "Place one block inside the marked practice claim so the foundation is visible.",
        trigger: "place_voxel",
        markerId: "building_practice_spot",
      },
      {
        id: "build_repair_claim_lesson_obj_05",
        index: 4,
        label:
          "Repair the broken safe-zone fence post and check that the road stays passable.",
        trigger: "interact",
        markerId: "grove_repair_fence",
      },
      {
        id: "build_repair_claim_lesson_obj_06",
        index: 5,
        label:
          "Read the Practice Land Ledger to compare personal lots, rented stalls, guild halls, and wild claims.",
        trigger: "open_tab",
        markerId: "grove_land_ledger",
      },
      {
        id: "build_repair_claim_lesson_obj_07",
        index: 6,
        label:
          "Choose the safer first claim: protected Grove/Harthmere lot before any non-safe-zone wilderness claim.",
        trigger: "choice",
        markerId: "grove_safe_wild_boundary",
      },
      {
        id: "build_repair_claim_lesson_obj_08",
        index: 7,
        label: "Return to Luis so he can stamp the lesson complete.",
        trigger: "talk_npc",
        markerId: "npc_luis",
      },
    ],
    reward:
      "75 XP, Builder basics flag, safe-zone land note, repair kit recipe hint, and first-lot guidance.",
    sampleDialogue:
      "Inspect the claim stakes, break some rubble, place a block inside the marked claim, repair the fence, and read the land ledger. Each marker step shows exactly what to do.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "guilds_are_promises",
    title: "Guilds Are Promises",
    arc: "story",
    category: "road_story",
    area: "The Grove / Guild Charter Table",
    hook: "Nia uses a fake guild charter to teach what guilds actually do: roles, permissions, banks, dues, projects, halls, and safe-zone law before players risk a real guild.",
    start: {
      kind: "giver",
      giverNpcId: "guild_clerk_nia",
    },
    steps: [
      {
        id: "guilds_are_promises_obj_01",
        index: 0,
        label: "Talk to Nia at the Grove Guild Charter Board.",
        trigger: "talk_npc",
        markerId: "npc_guild_clerk_nia",
      },
      {
        id: "guilds_are_promises_obj_02",
        index: 1,
        label:
          "Read the sample charter and pick a guild focus: crafting, gathering, PvE, PvP, trade, social, or building.",
        trigger: "choice",
        markerId: "guild_charter_board",
      },
      {
        id: "guilds_are_promises_obj_03",
        index: 2,
        label:
          "Assign practice ranks for leader, officer, builder, treasurer, scout, and member.",
        trigger: "choice",
        markerId: "guild_charter_board",
      },
      {
        id: "guilds_are_promises_obj_04",
        index: 3,
        label:
          "Deposit a harmless practice item into the guild bank crate and review who may withdraw it.",
        trigger: "item_grant",
        markerId: "guild_bank_crate",
      },
      {
        id: "guilds_are_promises_obj_05",
        index: 4,
        label:
          "Start a tiny guild project at the project table: repair a sign, fund a bridge plank, or stock a shared kit.",
        trigger: "interact",
        markerId: "guild_project_table",
      },
      {
        id: "guilds_are_promises_obj_06",
        index: 5,
        label:
          "Walk to the safe-zone boundary stones and learn which guild actions are protected in town versus risky in the Wilds.",
        trigger: "near_location",
        markerId: "grove_safe_wild_boundary",
      },
      {
        id: "guilds_are_promises_obj_07",
        index: 6,
        label:
          "Choose a first guild rule that prevents drama: bank limits, build permissions, tax rate, or war permissions.",
        trigger: "choice",
        markerId: "guild_charter_board",
      },
      {
        id: "guilds_are_promises_obj_08",
        index: 7,
        label: "Report back to Nia and receive the charter primer.",
        trigger: "talk_npc",
        markerId: "npc_guild_clerk_nia",
      },
    ],
    reward:
      "80 XP, Guild charter primer, guild-bank caution flag, and safe-zone/wild-claim rules codex.",
    sampleDialogue:
      "Read the sample charter, pick a guild focus, assign practice ranks, deposit a practice item in the guild bank, start a tiny shared project, then return to me. Marker shows each stop.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "color_that_still_points_home",
    title: "Color That Still Points Home",
    arc: "story",
    category: "road_story",
    area: "The Grove",
    hook: "Taye needs fresh paint for road markers, but muck has dulled the warning colors.",
    start: {
      kind: "giver",
      giverNpcId: "taye",
    },
    steps: [
      {
        id: "color_that_still_points_home_obj_01",
        index: 0,
        label: "Collect bright berries near the garden edge.",
        trigger: "collect",
        markerId: "grove_garden_edge_berries",
      },
      {
        id: "color_that_still_points_home_obj_02",
        index: 1,
        label: "Break 2 dull muck-stained clumps for pigment.",
        trigger: "destroy",
        markerId: "muckwad_patch",
        requiredCount: 2,
        targetMarkerIds: [
          "muckwad_pigment_clump_west",
          "muckwad_pigment_clump_east",
        ],
      },
      {
        id: "color_that_still_points_home_obj_03",
        index: 2,
        label: "Use the paint pot at Taye's table.",
        trigger: "interact",
        markerId: "paint_pot",
      },
      {
        id: "color_that_still_points_home_obj_04",
        index: 3,
        label: "Apply the fresh paint at the painted route flags.",
        trigger: "interact",
        markerId: "grove_painted_route_flags",
      },
      {
        id: "color_that_still_points_home_obj_05",
        index: 4,
        label: "Return to Taye to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_taye",
      },
    ],
    reward: "40 XP, Sign Painter reputation, cosmetic marker decal.",
    sampleDialogue:
      "A good sign does not shout. It waits where your eyes already want to go.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "cart_that_forgot_its_wheel",
    title: "The Cart That Forgot Its Wheel",
    arc: "story",
    category: "road_story",
    area: "Genesis Crossroads",
    hook: "Luis's repair cart broke down in the middle of the Crossroads, blocking the tutorial road.",
    start: {
      kind: "giver",
      giverNpcId: "luis",
    },
    steps: [
      {
        id: "cart_that_forgot_its_wheel_obj_01",
        index: 0,
        label: "Find the missing wheel near the hedges.",
        trigger: "near_location",
        markerId: "luis_cart",
      },
      {
        id: "cart_that_forgot_its_wheel_obj_02",
        index: 1,
        label: "Gather 3 wood scraps from the marked basket.",
        trigger: "collect",
        markerId: "grove_resource_basket",
        requiredCount: 3,
      },
      {
        id: "cart_that_forgot_its_wheel_obj_03",
        index: 2,
        label: "Place a block under the axle.",
        trigger: "place_voxel",
        markerId: "building_practice_spot",
      },
      {
        id: "cart_that_forgot_its_wheel_obj_04",
        index: 3,
        label: "Help Luis push the cart clear.",
        trigger: "interact",
        markerId: "luis_cart",
      },
      {
        id: "cart_that_forgot_its_wheel_obj_05",
        index: 4,
        label: "Return to Luis to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_luis",
      },
    ],
    reward: "45 XP, 25 bling, 5 road blocks, Luis friendship flag.",
    sampleDialogue:
      "A cart with three wheels is not broken. It is just very committed to circles.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "road_ready_not_fancy",
    title: "Road-Ready, Not Fancy",
    arc: "story",
    category: "road_story",
    area: "Lovely Locks",
    hook: "Alexis refuses to let the player leave The Grove dressed like someone who expects the road to apologize.",
    start: {
      kind: "giver",
      giverNpcId: "alexis",
    },
    steps: [
      {
        id: "road_ready_not_fancy_obj_01",
        index: 0,
        label: "Talk to Alexis at Lovely Locks and open your inventory.",
        trigger: "open_tab",
        markerId: "npc_alexis",
      },
      {
        id: "road_ready_not_fancy_obj_02",
        index: 1,
        label: "Equip a travel top.",
        trigger: "inventory_change",
        markerId: "lovely_locks_mirror",
      },
      {
        id: "road_ready_not_fancy_obj_03",
        index: 2,
        label: "Equip travel bottoms.",
        trigger: "inventory_change",
        markerId: "lovely_locks_mirror",
      },
      {
        id: "road_ready_not_fancy_obj_04",
        index: 3,
        label: "Take a mirror check at Lovely Locks before stepping out.",
        trigger: "interact",
        markerId: "lovely_locks_mirror",
      },
      {
        id: "road_ready_not_fancy_obj_05",
        index: 4,
        label: "Return to Alexis to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_alexis",
      },
    ],
    reward: "35 XP, starter travel outfit, Lovely Locks discount flag.",
    sampleDialogue:
      "Style is not vanity on the road. It is a warning label you choose for yourself.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "moss_that_went_quiet",
    title: "The Moss That Went Quiet",
    arc: "story",
    category: "road_story",
    area: "Mosslawn",
    hook: "A patch of warning moss has stopped reacting to footsteps.",
    start: {
      kind: "giver",
      giverNpcId: "ranger_jane",
    },
    steps: [
      {
        id: "moss_that_went_quiet_obj_01",
        index: 0,
        label: "Follow Ranger Jane's trail markers into Mosslawn.",
        trigger: "near_location",
        markerId: "mosslawn_warning_moss",
      },
      {
        id: "moss_that_went_quiet_obj_02",
        index: 1,
        label: "Crouch-walk past skittish animals on the path.",
        trigger: "near_location",
        markerId: "mosslawn_warning_moss",
      },
      {
        id: "moss_that_went_quiet_obj_03",
        index: 2,
        label: "Inspect three moss patches and note which has gone silent.",
        trigger: "interact",
        markerId: "mosslawn_warning_moss",
        requiredCount: 3,
        targetMarkerIds: [
          "mosslawn_warning_moss_west",
          "mosslawn_warning_moss_center",
          "mosslawn_warning_moss_east",
        ],
      },
      {
        id: "moss_that_went_quiet_obj_04",
        index: 3,
        label: "Clear a small seedy muckling nest the silent moss was hiding.",
        trigger: "combat",
        markerId: "mosslawn_silent_muckling_nest",
      },
      {
        id: "moss_that_went_quiet_obj_05",
        index: 4,
        label:
          "Return to Ranger Jane to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_ranger_jane",
      },
    ],
    reward: "60 XP, ranger token, Mosslawn danger zone revealed.",
    sampleDialogue:
      "Do not look for the monster first. Look for what stopped behaving normally.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "songline_under_the_lawn",
    title: "Songline Under the Lawn",
    arc: "story",
    category: "road_story",
    area: "Mosslawn",
    hook: "Sil hears a low tone beneath Mosslawn after rain and asks the player to stand on old stones while they sing the route pattern.",
    start: {
      kind: "giver",
      giverNpcId: "sil",
    },
    steps: [
      {
        id: "songline_under_the_lawn_obj_01",
        index: 0,
        label: "Stand at three moss stones in the order Sil sings.",
        trigger: "near_location",
        markerId: "mosslawn_song_stones",
        requiredCount: 3,
        targetMarkerIds: [
          "mosslawn_song_stone_low",
          "mosslawn_song_stone_middle",
          "mosslawn_song_stone_high",
        ],
      },
      {
        id: "songline_under_the_lawn_obj_02",
        index: 1,
        label: "Listen for the low tone beneath the lawn.",
        trigger: "interact",
        markerId: "mosslawn_song_stones",
      },
      {
        id: "songline_under_the_lawn_obj_03",
        index: 2,
        label: "Record the pattern at Sil's song board.",
        trigger: "interact",
        markerId: "mosslawn_sil_tuning_strip",
      },
      {
        id: "songline_under_the_lawn_obj_04",
        index: 3,
        label: "Choose whether it sounds like road, water, or bell.",
        trigger: "choice",
        markerId: "npc_sil",
      },
      {
        id: "songline_under_the_lawn_obj_05",
        index: 4,
        label: "Return to Sil to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_sil",
      },
    ],
    reward:
      "45 XP, lore codex: Mosslawn Songline, unlocks Harthmere bell dialogue branch later.",
    sampleDialogue:
      "The ground remembers. Most people only notice when it screams.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "sticky_medicine",
    title: "Sticky Medicine",
    arc: "story",
    category: "road_story",
    area: "Muck Edges",
    hook: "Doc needs clean and corrupted samples from the same plant to prove muck is a condition, not a creature type.",
    start: {
      kind: "giver",
      giverNpcId: "doc",
    },
    steps: [
      {
        id: "sticky_medicine_obj_01",
        index: 0,
        label: "Collect one clean root sample at the muck edge.",
        trigger: "collect",
        markerId: "doc_field_table",
      },
      {
        id: "sticky_medicine_obj_02",
        index: 1,
        label: "Collect one mucked root sample further in.",
        trigger: "collect",
        markerId: "muckwad_patch",
      },
      {
        id: "sticky_medicine_obj_03",
        index: 2,
        label:
          "Return along the safe edge to Doc's field table without lingering in heavy muck.",
        trigger: "near_location",
        markerId: "muckwad_patch",
      },
      {
        id: "sticky_medicine_obj_04",
        index: 3,
        label: "Bring both samples to Doc's field table.",
        trigger: "interact",
        markerId: "doc_field_table",
        inventory: {
          itemId: "mudroot",
          count: 2,
          consumeOnComplete: true,
        },
      },
      {
        id: "sticky_medicine_obj_05",
        index: 4,
        label: "Return to Doc to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_doc",
      },
    ],
    reward: "55 XP, anti-muck poultice, Doc sample flag.",
    sampleDialogue:
      "Do not lick it. I only say that because someone always thinks science needs enthusiasm.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "cove_keeps_pictures",
    title: "The Cove Keeps Pictures",
    arc: "story",
    category: "road_story",
    area: "Shutter Cove",
    hook: "Dimmi's camera caught a reflection of a stone town where only water should be.",
    start: {
      kind: "giver",
      giverNpcId: "dimmi",
    },
    steps: [
      {
        id: "cove_keeps_pictures_obj_01",
        index: 0,
        label: "Equip the camera Dimmi loans you.",
        trigger: "inventory_change",
        markerId: "npc_dimmi",
      },
      {
        id: "cove_keeps_pictures_obj_02",
        index: 1,
        label: "Switch to selfie or scenic mode at the cove marker.",
        trigger: "open_tab",
        markerId: "shutter_cove_marker",
      },
      {
        id: "cove_keeps_pictures_obj_03",
        index: 2,
        label: "Take a photo at the cove marker.",
        trigger: "photo_post",
        markerId: "shutter_cove_marker",
      },
      {
        id: "cove_keeps_pictures_obj_04",
        index: 3,
        label: "Post or save the photo from the overlook.",
        trigger: "photo_post",
        markerId: "selfie_overlook",
      },
      {
        id: "cove_keeps_pictures_obj_05",
        index: 4,
        label: "Show Dimmi the image.",
        trigger: "talk_npc",
        markerId: "npc_dimmi",
      },
    ],
    reward: "50 XP, cove photo frame, Shutter Cove map note.",
    sampleDialogue:
      "If the water is lying, it is doing it with excellent composition.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "coops_key_hen",
    title: "Coop's Key Hen",
    arc: "story",
    category: "road_story",
    area: "Grove Farm Edge",
    hook: "Old Coop's favorite hen has found a key, swallowed a ribbon, and led three people into the wrong garden.",
    start: {
      kind: "giver",
      giverNpcId: "old_coop",
    },
    steps: [
      {
        id: "coops_key_hen_obj_01",
        index: 0,
        label:
          "Follow the hen's marked trail to the dropped feed without sprinting.",
        trigger: "near_location",
        markerId: "grove_coop_dropped_feed",
      },
      {
        id: "coops_key_hen_obj_02",
        index: 1,
        label: "Collect dropped feed along the chase.",
        trigger: "collect",
        markerId: "grove_coop_dropped_feed",
      },
      {
        id: "coops_key_hen_obj_03",
        index: 2,
        label: "Dig at the scratch mark the hen left.",
        trigger: "interact",
        markerId: "coop_supply_box",
      },
      {
        id: "coops_key_hen_obj_04",
        index: 3,
        label: "Use the recovered key on the old supply box.",
        trigger: "item_use",
        markerId: "coop_supply_box",
      },
      {
        id: "coops_key_hen_obj_05",
        index: 4,
        label:
          "Return to Old Coop to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_old_coop",
      },
    ],
    reward: "40 XP, road snacks, old route clue pointing toward Billy.",
    sampleDialogue: "Never trust a map that has not been approved by poultry.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "tower_with_a_headache",
    title: "Tower With a Headache",
    arc: "story",
    category: "road_story",
    area: "Genesis Crossroads",
    hook: "Buddy's service tower pings every route except the one the player needs.",
    start: {
      kind: "giver",
      giverNpcId: "buddy",
    },
    steps: [
      {
        id: "tower_with_a_headache_obj_01",
        index: 0,
        label: "Climb or reach Buddy's service platform.",
        trigger: "near_location",
        markerId: "service_tower_platform",
      },
      {
        id: "tower_with_a_headache_obj_02",
        index: 1,
        label: "Replace a loose coil on the platform console.",
        trigger: "item_use",
        markerId: "service_tower_platform",
      },
      {
        id: "tower_with_a_headache_obj_03",
        index: 2,
        label: "Clear one mucked cable node beside the tower.",
        trigger: "destroy",
        markerId: "muckwad_patch",
      },
      {
        id: "tower_with_a_headache_obj_04",
        index: 3,
        label: "Ping the Old Grove Road marker from the console.",
        trigger: "interact",
        markerId: "old_grove_road_post",
      },
      {
        id: "tower_with_a_headache_obj_05",
        index: 4,
        label: "Return to Buddy to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_buddy",
      },
    ],
    reward: "55 XP, temporary navigation beam upgrade, Buddy memory fragment.",
    sampleDialogue:
      "I remember helping. I do not remember who asked. This is inefficient but emotionally promising.",
    connectorToHarthmere: false,
    countsAsFountainLesson: false,
  },
  {
    id: "letter_for_the_north_gate",
    title: "Letter for the North Gate",
    arc: "story",
    category: "road_story",
    area: "The Grove -> Harthmere",
    hook: "Jackie sends a sealed note to Sergeant Bram Holt because the road signs are changing faster than Grove locals can repair them.",
    start: {
      kind: "giver",
      giverNpcId: "jackie",
    },
    steps: [
      {
        id: "letter_for_the_north_gate_obj_01",
        index: 0,
        label: "Receive Jackie's sealed letter at the fountain.",
        trigger: "item_grant",
        markerId: "grove_jackie_sealed_letter",
      },
      {
        id: "letter_for_the_north_gate_obj_02",
        index: 1,
        label: "Follow the Harthmere Road Connector.",
        trigger: "near_location",
        markerId: "harthmere_connector",
      },
      {
        id: "letter_for_the_north_gate_obj_03",
        index: 2,
        label: "Speak to Sergeant Bram Holt at the North Gate.",
        trigger: "talk_npc",
        markerId: "sergeant_bram_holt",
      },
      {
        id: "letter_for_the_north_gate_obj_04",
        index: 3,
        label: "Return to Jackie with Bram's stamped pass.",
        trigger: "talk_npc",
        markerId: "npc_jackie",
      },
    ],
    reward: "80 XP, Harthmere access reputation, North Gate fast marker.",
    sampleDialogue:
      "Do not let Bram scare you. He sounds like a locked door because people keep trying to walk through him.",
    connectorToHarthmere: true,
    countsAsFountainLesson: false,
  },
  {
    id: "antlers_for_the_watch",
    title: "Antlers for the Watch",
    arc: "story",
    category: "road_story",
    area: "Mosslawn -> Harthmere Wilds",
    hook: "Jane wants Harthmere's Watch to stop mistaking natural animal panic for bandit movement.",
    start: {
      kind: "giver",
      giverNpcId: "ranger_jane",
    },
    steps: [
      {
        id: "antlers_for_the_watch_obj_01",
        index: 0,
        label: "Collect three track rubbings in Mosslawn.",
        trigger: "interact",
        markerId: "mosslawn_warning_moss",
        requiredCount: 3,
        targetMarkerIds: [
          "mosslawn_track_rubbing_hoof",
          "mosslawn_track_rubbing_antler",
          "mosslawn_track_rubbing_claw",
        ],
      },
      {
        id: "antlers_for_the_watch_obj_02",
        index: 1,
        label: "Travel the Harthmere Road Connector to the North Gate.",
        trigger: "near_location",
        markerId: "harthmere_connector",
      },
      {
        id: "antlers_for_the_watch_obj_03",
        index: 2,
        label: "Deliver the report to Sergeant Bram Holt's Watch table.",
        trigger: "talk_npc",
        markerId: "sergeant_bram_holt",
      },
      {
        id: "antlers_for_the_watch_obj_04",
        index: 3,
        label:
          "Compare one Harthmere Wilds track with Jane's notes and return.",
        trigger: "choice",
        markerId: "npc_ranger_jane",
      },
      {
        id: "antlers_for_the_watch_obj_05",
        index: 4,
        label:
          "Return to Ranger Jane to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_ranger_jane",
      },
    ],
    reward:
      "90 XP, Watch/Ranger bridge reputation, Wilds animal-safe marker unlocked.",
    sampleDialogue:
      "Tell them if a deer wanted to invade a town, it would start with the vegetable stalls.",
    connectorToHarthmere: true,
    countsAsFountainLesson: false,
  },
  {
    id: "toll_ledger_problem",
    title: "The Toll Ledger Problem",
    arc: "story",
    category: "road_story",
    area: "Genesis Crossroads -> Harthmere Market",
    hook: "Luis has a shipment of road bolts stuck behind Harthmere paperwork.",
    start: {
      kind: "giver",
      giverNpcId: "luis",
    },
    steps: [
      {
        id: "toll_ledger_problem_obj_01",
        index: 0,
        label: "Pick up Luis's bolt order from the cart.",
        trigger: "item_grant",
        markerId: "grove_luis_bolt_order",
      },
      {
        id: "toll_ledger_problem_obj_02",
        index: 1,
        label: "Speak with the Harthmere toll clerk at the market office.",
        trigger: "talk_npc",
        markerId: "harthmere_market_office",
      },
      {
        id: "toll_ledger_problem_obj_03",
        index: 2,
        label:
          "Pick up the bolt crates after the clerk finds the missing ledger line.",
        trigger: "collect",
        markerId: "harthmere_market_bolt_materials",
      },
      {
        id: "toll_ledger_problem_obj_04",
        index: 3,
        label: "Carry the bolt crates back to Luis for road repairs.",
        trigger: "near_location",
        markerId: "npc_luis",
        inventory: {
          itemId: "grove_bolt_crate",
          count: 1,
          consumeOnComplete: true,
        },
      },
      {
        id: "toll_ledger_problem_obj_05",
        index: 4,
        label: "Return to Luis to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_luis",
      },
    ],
    reward: "85 XP, road repair kit recipe, Merchant Compact intro flag.",
    sampleDialogue:
      "The difference between a road and a government is that roads occasionally go somewhere.",
    connectorToHarthmere: true,
    countsAsFountainLesson: false,
  },
  {
    id: "samples_for_the_chapel",
    title: "Samples for the Chapel",
    arc: "story",
    category: "road_story",
    area: "Muck Edges -> Harthmere Chapel",
    hook: "Doc sends a sealed muck sample to Harthmere's chapel to test whether muck reacts to bell-resonant stone.",
    start: {
      kind: "giver",
      giverNpcId: "doc",
    },
    steps: [
      {
        id: "samples_for_the_chapel_obj_01",
        index: 0,
        label: "Collect a sealed muck sample at the muck edge.",
        trigger: "collect",
        markerId: "muckwad_patch",
      },
      {
        id: "samples_for_the_chapel_obj_02",
        index: 1,
        label:
          "Bring it to Father Aldren or a chapel NPC at the Harthmere chapel.",
        trigger: "talk_npc",
        markerId: "harthmere_chapel_stone",
      },
      {
        id: "samples_for_the_chapel_obj_03",
        index: 2,
        label: "Place it on the chapel listening stone.",
        trigger: "interact",
        markerId: "harthmere_chapel_stone",
      },
      {
        id: "samples_for_the_chapel_obj_04",
        index: 3,
        label:
          "Record whether it trembles, darkens, or stays still — and return to Doc.",
        trigger: "choice",
        markerId: "npc_doc",
      },
      {
        id: "samples_for_the_chapel_obj_05",
        index: 4,
        label: "Return to Doc to report the result and collect the reward.",
        trigger: "talk_npc",
        markerId: "npc_doc",
      },
    ],
    reward: "95 XP, chapel lore codex, unlocks Bell/Muck theory branch.",
    sampleDialogue:
      "If the priests are right, we learn something. If I am right, we learn something louder.",
    connectorToHarthmere: true,
    countsAsFountainLesson: false,
  },
  {
    id: "tone_beneath_the_road",
    title: "The Tone Beneath the Road",
    arc: "story",
    category: "road_story",
    area: "Mosslawn -> Harthmere Bridge",
    hook: "Sil asks the player to test whether the tone under Mosslawn also lives beneath the Harthmere road.",
    start: {
      kind: "giver",
      giverNpcId: "sil",
    },
    steps: [
      {
        id: "tone_beneath_the_road_obj_01",
        index: 0,
        label: "Take Sil's tuning strip from the song board.",
        trigger: "item_grant",
        markerId: "mosslawn_sil_tuning_strip",
      },
      {
        id: "tone_beneath_the_road_obj_02",
        index: 1,
        label: "Stand at the Harthmere bridge center.",
        trigger: "near_location",
        markerId: "harthmere_bridge_center",
      },
      {
        id: "tone_beneath_the_road_obj_03",
        index: 2,
        label:
          "Ask a Black Anvil crafter to mark the strip with bell-resonant ink.",
        trigger: "talk_npc",
        markerId: "harthmere_bridge_center",
      },
      {
        id: "tone_beneath_the_road_obj_04",
        index: 3,
        label: "Report the marked result to Sil at Mosslawn.",
        trigger: "talk_npc",
        markerId: "npc_sil",
      },
    ],
    reward: "110 XP, Bellbound hint, unlocks future main quest breadcrumb.",
    sampleDialogue:
      "If the same note lives under both roads, we should learn whether it is calling or answering.",
    connectorToHarthmere: true,
    countsAsFountainLesson: false,
  },
];

export const GROVE_QUESTS_STORY: readonly GroveQuestDef[] =
  Object.freeze(QUESTS);
