// GROVE_QUESTS_ECONOMY — generated by
// scripts/harthmere/convert-grove-catalog-to-typed.cjs from the retired
// SNAPSHOT_GROVE_QUESTS, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest ids and step ids are pinned by position
// (grove_quest_id_pins.ts), so appending is free and reordering is a
// migration. grove_quest_ids.test.ts fails on any reorder.
//
// Each step is ONE object. The retired shape stored objectives, triggers and
// markerIds as three positionally-indexed parallel arrays whose lengths were
// kept in sync only by a hand-written test.

import type { GroveQuestDef } from "@/shared/harthmere/grove/grove_quest_schema";

// Annotating the DECLARATION gives every element the contextual type, so tsc
// checks each row against one known target. See the note in
// convert-bible-catalog-to-typed.cjs for why neither `as const` nor a bare
// Object.freeze is used here.
const QUESTS: GroveQuestDef[] = [
  {
    "id": "econ_billys_lost_lunch_pail",
    "title": "Billy's Lost Lunch Pail",
    "arc": "economy",
    "category": "road_story",
    "area": "Old Grove Road",
    "hook": "Billy dropped his lunch pail somewhere along his shortcut and now the muck flies are interested.",
    "start": {
      "kind": "giver",
      "giverNpcId": "billy"
    },
    "steps": [
      {
        "id": "econ_billys_lost_lunch_pail_obj_01",
        "index": 0,
        "label": "Hear Billy out about the missing pail.",
        "trigger": "talk_npc",
        "markerId": "npc_billy"
      },
      {
        "id": "econ_billys_lost_lunch_pail_obj_02",
        "index": 1,
        "label": "Search the Old Grove Road post for the dropped pail.",
        "trigger": "near_location",
        "markerId": "old_grove_road_post"
      },
      {
        "id": "econ_billys_lost_lunch_pail_obj_03",
        "index": 2,
        "label": "Pick up the pail before the flies do.",
        "trigger": "collect",
        "markerId": "econ_billy_lunch_pail"
      },
      {
        "id": "econ_billys_lost_lunch_pail_obj_04",
        "index": 3,
        "label": "Return the pail to Billy.",
        "trigger": "talk_npc",
        "markerId": "npc_billy",
        "inventory": {
          "itemId": "billys_lunch_pail",
          "count": 1,
          "consumeOnComplete": true
        }
      }
    ],
    "reward": "8 bling, light-snack note, Billy friendship +1.",
    "sampleDialogue": "I know I had it at the post. I also know the flies should not have a vote.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_billys_roof_patch_run",
    "title": "Billy's Roof Patch Run",
    "arc": "economy",
    "category": "road_story",
    "area": "Old Grove Road",
    "hook": "Billy needs wood scraps carried from the road kit crate to a leaking shed before the rain returns.",
    "start": {
      "kind": "giver",
      "giverNpcId": "billy"
    },
    "steps": [
      {
        "id": "econ_billys_roof_patch_run_obj_01",
        "index": 0,
        "label": "Take the patch order from Billy.",
        "trigger": "talk_npc",
        "markerId": "npc_billy"
      },
      {
        "id": "econ_billys_roof_patch_run_obj_02",
        "index": 1,
        "label": "Collect scrap wood from the marked materials basket.",
        "trigger": "collect",
        "markerId": "grove_resource_basket"
      },
      {
        "id": "econ_billys_roof_patch_run_obj_03",
        "index": 2,
        "label": "Drop the scraps at Billy's road post.",
        "trigger": "place_voxel",
        "markerId": "econ_grove_billy_post"
      },
      {
        "id": "econ_billys_roof_patch_run_obj_04",
        "index": 3,
        "label": "Tell Billy the patch is ready.",
        "trigger": "talk_npc",
        "markerId": "npc_billy"
      }
    ],
    "reward": "12 bling, rough patch flag, Billy friendship +1.",
    "sampleDialogue": "Two scraps and a careful hand keeps the shed dry through tomorrow.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_billys_map_pin_run",
    "title": "Billy's Map Pin Run to Luis",
    "arc": "economy",
    "category": "road_story",
    "area": "Old Grove Road -> Genesis Crossroads",
    "hook": "Billy wants Luis to know the bent sign is back. He needs a runner who will not get distracted by the cove.",
    "start": {
      "kind": "giver",
      "giverNpcId": "billy"
    },
    "steps": [
      {
        "id": "econ_billys_map_pin_run_obj_01",
        "index": 0,
        "label": "Pick up the map pin from Billy.",
        "trigger": "talk_npc",
        "markerId": "npc_billy"
      },
      {
        "id": "econ_billys_map_pin_run_obj_02",
        "index": 1,
        "label": "Run the Old Grove Road to Luis's repair cart.",
        "trigger": "near_location",
        "markerId": "luis_cart"
      },
      {
        "id": "econ_billys_map_pin_run_obj_03",
        "index": 2,
        "label": "Hand the pin to Luis.",
        "trigger": "talk_npc",
        "markerId": "npc_luis"
      },
      {
        "id": "econ_billys_map_pin_run_obj_04",
        "index": 3,
        "label": "Report back to Billy with Luis's note.",
        "trigger": "talk_npc",
        "markerId": "npc_billy"
      }
    ],
    "reward": "10 bling, road-runner badge, Billy friendship +1.",
    "sampleDialogue": "Straight line. No cove. No selfies. The pin is heavier than it looks.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_merls_coin_sorting",
    "title": "Merl's Coin Sorting Apprenticeship",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Merl needs a careful hand to sort a day's deposits into the bank satchel without dropping a single coin.",
    "start": {
      "kind": "giver",
      "giverNpcId": "grove_banker_merl"
    },
    "steps": [
      {
        "id": "econ_merls_coin_sorting_obj_01",
        "index": 0,
        "label": "Take the deposit slip from Merl.",
        "trigger": "talk_npc",
        "markerId": "npc_grove_banker_merl"
      },
      {
        "id": "econ_merls_coin_sorting_obj_02",
        "index": 1,
        "label": "Open the deposit at the Mail and Bank Satchel.",
        "trigger": "open_tab",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "econ_merls_coin_sorting_obj_03",
        "index": 2,
        "label": "Sort the coins by interacting with the satchel station.",
        "trigger": "interact",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "econ_merls_coin_sorting_obj_04",
        "index": 3,
        "label": "Return the sealed slip to Merl.",
        "trigger": "talk_npc",
        "markerId": "npc_grove_banker_merl"
      }
    ],
    "reward": "15 bling, bank apprentice slip, Merl friendship +1.",
    "sampleDialogue": "A bank trusts you when your hands stop apologising to the coins.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_merls_vault_inventory",
    "title": "Merl's Vault Inventory Day",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Merl needs the lost-and-found stone inventoried before he opens the vault for the morning's depositors.",
    "start": {
      "kind": "giver",
      "giverNpcId": "grove_banker_merl"
    },
    "steps": [
      {
        "id": "econ_merls_vault_inventory_obj_01",
        "index": 0,
        "label": "Hear Merl's inventory plan.",
        "trigger": "talk_npc",
        "markerId": "npc_grove_banker_merl"
      },
      {
        "id": "econ_merls_vault_inventory_obj_02",
        "index": 1,
        "label": "Inspect the Lost-and-Found Stone.",
        "trigger": "interact",
        "markerId": "grove_recovery_stone"
      },
      {
        "id": "econ_merls_vault_inventory_obj_03",
        "index": 2,
        "label": "Verify the bank crate matches the ledger.",
        "trigger": "interact",
        "markerId": "guild_bank_crate"
      },
      {
        "id": "econ_merls_vault_inventory_obj_04",
        "index": 3,
        "label": "Return the count to Merl.",
        "trigger": "talk_npc",
        "markerId": "npc_grove_banker_merl"
      }
    ],
    "reward": "20 bling, vault-day slip, Merl friendship +1.",
    "sampleDialogue": "The ledger is the bank. Everything else is just the building it sits in.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_gus_fresh_loaves_to_fountain",
    "title": "Fresh Loaves to the Fountain",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Gus needs a warm-handed runner to deliver loaves to the fountain before the morning crowd arrives.",
    "start": {
      "kind": "giver",
      "giverNpcId": "gus_the_baker"
    },
    "steps": [
      {
        "id": "econ_gus_fresh_loaves_to_fountain_obj_01",
        "index": 0,
        "label": "Pick up the loaf tray from Gus.",
        "trigger": "talk_npc",
        "markerId": "npc_gus_the_baker"
      },
      {
        "id": "econ_gus_fresh_loaves_to_fountain_obj_02",
        "index": 1,
        "label": "Pick up the warm loaf tray at Gus's oven.",
        "trigger": "collect",
        "markerId": "econ_gus_loaf_tray"
      },
      {
        "id": "econ_gus_fresh_loaves_to_fountain_obj_03",
        "index": 2,
        "label": "Deliver the warm loaves to the Fountain Food Satchel.",
        "trigger": "interact",
        "markerId": "grove_food_satchel",
        "inventory": {
          "itemId": "grove_warm_loaf_tray",
          "count": 1,
          "consumeOnComplete": true
        }
      },
      {
        "id": "econ_gus_fresh_loaves_to_fountain_obj_04",
        "index": 3,
        "label": "Confirm the delivery with Gus.",
        "trigger": "talk_npc",
        "markerId": "npc_gus_the_baker"
      }
    ],
    "reward": "10 bling, warm-loaf badge, Gus friendship +1.",
    "sampleDialogue": "Warm pays full. Lukewarm pays half. Cold and we have to talk about your pace.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_gus_grain_run",
    "title": "Gus's Grain Run from the Field",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Gus is out of grain and Fern's field has a basket waiting. He'll pay anyone who can run a sack back before noon.",
    "start": {
      "kind": "giver",
      "giverNpcId": "gus_the_baker"
    },
    "steps": [
      {
        "id": "econ_gus_grain_run_obj_01",
        "index": 0,
        "label": "Take Gus's empty grain sack.",
        "trigger": "talk_npc",
        "markerId": "npc_gus_the_baker"
      },
      {
        "id": "econ_gus_grain_run_obj_02",
        "index": 1,
        "label": "Collect grain from the marked practice materials.",
        "trigger": "collect",
        "markerId": "grove_resource_basket"
      },
      {
        "id": "econ_gus_grain_run_obj_03",
        "index": 2,
        "label": "Deliver the full grain sack at Gus's oven.",
        "trigger": "interact",
        "markerId": "econ_gus_oven",
        "inventory": {
          "itemId": "field_wheat",
          "count": 1,
          "consumeOnComplete": true
        }
      },
      {
        "id": "econ_gus_grain_run_obj_04",
        "index": 3,
        "label": "Tell Gus the oven is fed.",
        "trigger": "talk_npc",
        "markerId": "npc_gus_the_baker"
      }
    ],
    "reward": "18 bling, grain-runner slip, Gus friendship +1.",
    "sampleDialogue": "Grain in. Bread out. The town runs on this and nobody notices.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_fern_water_the_sprout_beds",
    "title": "Water the Sprout Beds",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Fern's sprout beds are dry and she needs hands at the basket to carry water before the sun finishes the job.",
    "start": {
      "kind": "giver",
      "giverNpcId": "fern_the_grower"
    },
    "steps": [
      {
        "id": "econ_fern_water_the_sprout_beds_obj_01",
        "index": 0,
        "label": "Get the watering plan from Fern.",
        "trigger": "talk_npc",
        "markerId": "npc_fern_the_grower"
      },
      {
        "id": "econ_fern_water_the_sprout_beds_obj_02",
        "index": 1,
        "label": "Reach Fern's sprout beds.",
        "trigger": "near_location",
        "markerId": "econ_fern_garden_plot"
      },
      {
        "id": "econ_fern_water_the_sprout_beds_obj_03",
        "index": 2,
        "label": "Interact with the beds to water the row.",
        "trigger": "interact",
        "markerId": "econ_fern_garden_plot"
      },
      {
        "id": "econ_fern_water_the_sprout_beds_obj_04",
        "index": 3,
        "label": "Report back to Fern.",
        "trigger": "talk_npc",
        "markerId": "npc_fern_the_grower"
      }
    ],
    "reward": "12 bling, gardener's mark, Fern friendship +1.",
    "sampleDialogue": "A watered row pays in stems. A dry row pays in lectures.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_fern_berry_patch_harvest",
    "title": "Fern's Berry Patch Harvest",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "The berry patch ripened overnight and Fern needs them in a basket before the birds find them.",
    "start": {
      "kind": "giver",
      "giverNpcId": "fern_the_grower"
    },
    "steps": [
      {
        "id": "econ_fern_berry_patch_harvest_obj_01",
        "index": 0,
        "label": "Take the basket from Fern.",
        "trigger": "talk_npc",
        "markerId": "npc_fern_the_grower"
      },
      {
        "id": "econ_fern_berry_patch_harvest_obj_02",
        "index": 1,
        "label": "Pick berries at the patch.",
        "trigger": "collect",
        "markerId": "econ_fern_berry_patch"
      },
      {
        "id": "econ_fern_berry_patch_harvest_obj_03",
        "index": 2,
        "label": "Bring the basket back to Fern's beds.",
        "trigger": "near_location",
        "markerId": "econ_fern_garden_plot"
      },
      {
        "id": "econ_fern_berry_patch_harvest_obj_04",
        "index": 3,
        "label": "Hand off the berries.",
        "trigger": "talk_npc",
        "markerId": "npc_fern_the_grower"
      }
    ],
    "reward": "20 bling, berry-basket slip, Fern friendship +1.",
    "sampleDialogue": "Pick the dark ones. The birds get the rest. That's the deal.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_kit_letters_around_fountain",
    "title": "Kit's Letters Around the Fountain",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Kit has three letters that need to go to three fountain workstations and a runner who can keep them in order.",
    "start": {
      "kind": "giver",
      "giverNpcId": "kit_the_courier"
    },
    "steps": [
      {
        "id": "econ_kit_letters_around_fountain_obj_01",
        "index": 0,
        "label": "Take Kit's letter packet.",
        "trigger": "talk_npc",
        "markerId": "npc_kit_the_courier"
      },
      {
        "id": "econ_kit_letters_around_fountain_obj_02",
        "index": 1,
        "label": "Drop the first at the Fountain Lesson Board.",
        "trigger": "interact",
        "markerId": "grove_fountain_lesson_board"
      },
      {
        "id": "econ_kit_letters_around_fountain_obj_03",
        "index": 2,
        "label": "Drop the second at the Charter Trade Desk.",
        "trigger": "interact",
        "markerId": "grove_trade_desk"
      },
      {
        "id": "econ_kit_letters_around_fountain_obj_04",
        "index": 3,
        "label": "Drop the third at the Mail and Bank Satchel.",
        "trigger": "interact",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "econ_kit_letters_around_fountain_obj_05",
        "index": 4,
        "label": "Return to Kit for the wage.",
        "trigger": "talk_npc",
        "markerId": "npc_kit_the_courier"
      }
    ],
    "reward": "10 bling, fountain-round badge, Kit friendship +1.",
    "sampleDialogue": "Three stops. One pace. If the order gets mixed, the wage gets mixed too.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_kit_heavy_parcel_to_crossroads",
    "title": "Kit's Heavy Parcel to the Crossroads",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain -> Genesis Crossroads",
    "hook": "Kit has a heavy parcel for Luis that nobody wants to carry. Whoever does it gets the best wage on the board.",
    "start": {
      "kind": "giver",
      "giverNpcId": "kit_the_courier"
    },
    "steps": [
      {
        "id": "econ_kit_heavy_parcel_to_crossroads_obj_01",
        "index": 0,
        "label": "Hear Kit's parcel terms.",
        "trigger": "talk_npc",
        "markerId": "npc_kit_the_courier"
      },
      {
        "id": "econ_kit_heavy_parcel_to_crossroads_obj_02",
        "index": 1,
        "label": "Pick up the parcel at Kit's mailbag stand.",
        "trigger": "item_grant",
        "markerId": "econ_kit_mailbag"
      },
      {
        "id": "econ_kit_heavy_parcel_to_crossroads_obj_03",
        "index": 2,
        "label": "Carry the parcel down the Old Grove Road to Luis's cart.",
        "trigger": "near_location",
        "markerId": "luis_cart"
      },
      {
        "id": "econ_kit_heavy_parcel_to_crossroads_obj_04",
        "index": 3,
        "label": "Hand the parcel to Luis at his cart.",
        "trigger": "talk_npc",
        "markerId": "npc_luis",
        "inventory": {
          "itemId": "grove_heavy_parcel",
          "count": 1,
          "consumeOnComplete": true
        }
      },
      {
        "id": "econ_kit_heavy_parcel_to_crossroads_obj_05",
        "index": 4,
        "label": "Return the receipt to Kit.",
        "trigger": "talk_npc",
        "markerId": "npc_kit_the_courier"
      }
    ],
    "reward": "25 bling, heavy-parcel slip, Kit friendship +1.",
    "sampleDialogue": "Heavy is honest. Whoever finishes this gets first pick on tomorrow's board.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_mel_bench_repair",
    "title": "Mel's Bench Repair",
    "arc": "economy",
    "category": "road_story",
    "area": "Genesis Crossroads",
    "hook": "Mel has a bench with a wobbly leg and a customer who will not sit on it again. She'll pay for steady hands.",
    "start": {
      "kind": "giver",
      "giverNpcId": "mel_the_handyman"
    },
    "steps": [
      {
        "id": "econ_mel_bench_repair_obj_01",
        "index": 0,
        "label": "Take the repair order from Mel.",
        "trigger": "talk_npc",
        "markerId": "npc_mel_the_handyman"
      },
      {
        "id": "econ_mel_bench_repair_obj_02",
        "index": 1,
        "label": "Pick up the part at Mel's workbench.",
        "trigger": "interact",
        "markerId": "econ_mel_workbench"
      },
      {
        "id": "econ_mel_bench_repair_obj_03",
        "index": 2,
        "label": "Install the part on the broken safe-zone fence.",
        "trigger": "interact",
        "markerId": "grove_repair_fence",
        "inventory": {
          "itemId": "scrap_metal",
          "count": 1,
          "consumeOnComplete": true
        }
      },
      {
        "id": "econ_mel_bench_repair_obj_04",
        "index": 3,
        "label": "Report the fix to Mel.",
        "trigger": "talk_npc",
        "markerId": "npc_mel_the_handyman"
      }
    ],
    "reward": "15 bling, handyman tag, Mel friendship +1.",
    "sampleDialogue": "One leg. Two bolts. Three minutes. I'll watch.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_mel_broken_hinge_hunt",
    "title": "Mel's Broken Hinge Hunt",
    "arc": "economy",
    "category": "road_story",
    "area": "Genesis Crossroads / Old Grove Road",
    "hook": "Three hinges in town are squealing. Mel will pay double if a runner can inspect all three before sunset.",
    "start": {
      "kind": "giver",
      "giverNpcId": "mel_the_handyman"
    },
    "steps": [
      {
        "id": "econ_mel_broken_hinge_hunt_obj_01",
        "index": 0,
        "label": "Get the hinge list from Mel.",
        "trigger": "talk_npc",
        "markerId": "npc_mel_the_handyman"
      },
      {
        "id": "econ_mel_broken_hinge_hunt_obj_02",
        "index": 1,
        "label": "Inspect the Old Grove Road post.",
        "trigger": "interact",
        "markerId": "old_grove_road_post"
      },
      {
        "id": "econ_mel_broken_hinge_hunt_obj_03",
        "index": 2,
        "label": "Inspect the safe-zone fence.",
        "trigger": "interact",
        "markerId": "grove_repair_fence"
      },
      {
        "id": "econ_mel_broken_hinge_hunt_obj_04",
        "index": 3,
        "label": "Inspect Mel's workbench supplies.",
        "trigger": "interact",
        "markerId": "econ_mel_workbench"
      },
      {
        "id": "econ_mel_broken_hinge_hunt_obj_05",
        "index": 4,
        "label": "Report the count to Mel.",
        "trigger": "talk_npc",
        "markerId": "npc_mel_the_handyman"
      }
    ],
    "reward": "30 bling, hinge-hunter slip, Mel friendship +1.",
    "sampleDialogue": "Hinges fail in the same way every time. Find the third one before it makes the door an opinion.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_rin_mushroom_pickup",
    "title": "Rin's Wild Mushroom Pickup",
    "arc": "economy",
    "category": "road_story",
    "area": "Muck Edges",
    "hook": "Rin marked a safe ring of mushrooms by the muck and needs a runner to harvest before the fog moves them.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rin_the_forager"
    },
    "steps": [
      {
        "id": "econ_rin_mushroom_pickup_obj_01",
        "index": 0,
        "label": "Meet Rin at the muck edge.",
        "trigger": "talk_npc",
        "markerId": "npc_rin_the_forager"
      },
      {
        "id": "econ_rin_mushroom_pickup_obj_02",
        "index": 1,
        "label": "Collect mushrooms from her marked basket.",
        "trigger": "collect",
        "markerId": "econ_rin_basket"
      },
      {
        "id": "econ_rin_mushroom_pickup_obj_03",
        "index": 2,
        "label": "Return to Rin's safe edge without lingering in heavy muck.",
        "trigger": "near_location",
        "markerId": "npc_rin_the_forager"
      },
      {
        "id": "econ_rin_mushroom_pickup_obj_04",
        "index": 3,
        "label": "Drop the basket back at Rin.",
        "trigger": "talk_npc",
        "markerId": "npc_rin_the_forager",
        "inventory": {
          "itemId": "forest_mushroom",
          "count": 1,
          "consumeOnComplete": true
        }
      }
    ],
    "reward": "18 bling, safe-harvest note, Rin friendship +1.",
    "sampleDialogue": "The marked basket. Not the unmarked clump. I will only say it once.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  },
  {
    "id": "econ_carlo_festival_skewers",
    "title": "Carlo's Festival Skewers",
    "arc": "economy",
    "category": "road_story",
    "area": "The Grove Fountain",
    "hook": "Carlo has a festival cook order and needs a runner-cook to grill skewers at the fountain workbench. Pays the best wage on the starter board.",
    "start": {
      "kind": "giver",
      "giverNpcId": "carlo_the_cook"
    },
    "steps": [
      {
        "id": "econ_carlo_festival_skewers_obj_01",
        "index": 0,
        "label": "Take Carlo's skewer recipe.",
        "trigger": "talk_npc",
        "markerId": "npc_carlo_the_cook"
      },
      {
        "id": "econ_carlo_festival_skewers_obj_02",
        "index": 1,
        "label": "Gather the ingredients at the marked materials basket.",
        "trigger": "collect",
        "markerId": "grove_resource_basket"
      },
      {
        "id": "econ_carlo_festival_skewers_obj_03",
        "index": 2,
        "label": "Cook the skewers at the Fountain Workbench.",
        "trigger": "craft",
        "markerId": "grove_fountain_workbench",
        "craft": {
          "recipeId": "harthmere_grove_festival_skewer",
          "outputItemId": "grove_festival_skewer"
        }
      },
      {
        "id": "econ_carlo_festival_skewers_obj_04",
        "index": 3,
        "label": "Deliver the cooked skewer to Carlo's cookpot.",
        "trigger": "interact",
        "markerId": "econ_carlo_cookpot",
        "inventory": {
          "itemId": "grove_festival_skewer",
          "count": 1,
          "consumeOnComplete": true
        }
      },
      {
        "id": "econ_carlo_festival_skewers_obj_05",
        "index": 4,
        "label": "Settle the wage with Carlo.",
        "trigger": "talk_npc",
        "markerId": "npc_carlo_the_cook"
      }
    ],
    "reward": "50 bling, festival-skewer recipe, Carlo friendship +1.",
    "sampleDialogue": "Five sticks. Three minutes each. Burn one and we both lose a story I needed.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": false
  }
];

export const GROVE_QUESTS_ECONOMY: readonly GroveQuestDef[] = Object.freeze(QUESTS);
