// GROVE_QUESTS_FOUNTAIN — generated by
// scripts/harthmere/convert-grove-catalog-to-typed.cjs from the retired
// SNAPSHOT_GROVE_QUESTS, then owned as ordinary source.
//
// ORDER IS FROZEN. Native quest ids and step ids are pinned by position
// (grove_quest_id_pins.ts), so appending is free and reordering is a
// migration. grove_quest_ids.test.ts fails on any reorder.
//
// Each step is ONE object. The retired shape stored objectives, triggers and
// markerIds as three positionally-indexed parallel arrays whose lengths were
// kept in sync only by a hand-written test.

import type { GroveQuestDef } from "@/shared/harthmere/grove/grove_quest_schema";

// Annotating the DECLARATION gives every element the contextual type, so tsc
// checks each row against one known target. See the note in
// convert-bible-catalog-to-typed.cjs for why neither `as const` nor a bare
// Object.freeze is used here.
const QUESTS: GroveQuestDef[] = [
  {
    "id": "fountain_buttons_first",
    "title": "Buttons Before the Road",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn makes sure the player can read the Grove tracker, pin a stop, open the map, and find the quest journal before the road starts changing on them.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "fountain_buttons_first_obj_01",
        "index": 0,
        "label": "Talk with Rosalyn by the fountain and accept the first lesson.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "fountain_buttons_first_obj_02",
        "index": 1,
        "label": "Use the Grove tracker to pin the Fountain Lesson Board.",
        "trigger": "interact",
        "markerId": "grove_fountain_lesson_board"
      },
      {
        "id": "fountain_buttons_first_obj_03",
        "index": 2,
        "label": "Open the map and confirm the Grove marker is visible.",
        "trigger": "open_tab",
        "markerId": "the_grove"
      },
      {
        "id": "fountain_buttons_first_obj_04",
        "index": 3,
        "label": "Open the quest journal and read the active objective.",
        "trigger": "open_tab",
        "markerId": "grove_hud_compass_ring"
      },
      {
        "id": "fountain_buttons_first_obj_05",
        "index": 4,
        "label": "Return to Rosalyn so she knows the HUD is helping instead of shouting.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "25 XP, Grove tracker confidence, first map pin habit.",
    "sampleDialogue": "First lesson: learn the HUD. Pin the Fountain Lesson Board, open the map, open the quest journal, then come back to me. The marker moves to each stop as you finish it.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "painted_path_language",
    "title": "Paint Knows Where Eyes Go",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Taye teaches the player how colors, route flags, map markers, and HUD highlights work together so navigation feels like world language instead of menu noise.",
    "start": {
      "kind": "giver",
      "giverNpcId": "taye"
    },
    "steps": [
      {
        "id": "painted_path_language_obj_01",
        "index": 0,
        "label": "Ask Taye why the route flags are painted in different colors.",
        "trigger": "talk_npc",
        "markerId": "npc_taye"
      },
      {
        "id": "painted_path_language_obj_02",
        "index": 1,
        "label": "Inspect Taye's paint pot without standing on the fountain crowd.",
        "trigger": "interact",
        "markerId": "paint_pot"
      },
      {
        "id": "painted_path_language_obj_03",
        "index": 2,
        "label": "Follow the painted route flags to the compass practice ring.",
        "trigger": "near_location",
        "markerId": "grove_painted_route_flags"
      },
      {
        "id": "painted_path_language_obj_04",
        "index": 3,
        "label": "Pin the compass ring and watch the HUD highlight the next stop.",
        "trigger": "open_tab",
        "markerId": "grove_hud_compass_ring"
      },
      {
        "id": "painted_path_language_obj_05",
        "index": 4,
        "label": "Choose what the brightest paint should mean: warning, welcome, or work site.",
        "trigger": "choice",
        "markerId": "grove_painted_route_flags"
      },
      {
        "id": "painted_path_language_obj_06",
        "index": 5,
        "label": "Return to Taye with the answer you would trust on a dark road.",
        "trigger": "talk_npc",
        "markerId": "npc_taye"
      }
    ],
    "reward": "35 XP, route-color note, safer map-reading habit.",
    "sampleDialogue": "Follow the painted flags to the compass ring, pin it, then pick what the brightest paint should mean. Come back to me with your answer.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "road_ready_bag_check",
    "title": "Road-Ready Bag Check",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain / Lovely Locks",
    "hook": "Rosalyn turns the first inventory lesson into a calm fountain check: equipment, clothing, health, stamina, and the bottom HUD all need to be understood before the player leaves the safe crowd.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "road_ready_bag_check_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn and let her look over your road kit.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "road_ready_bag_check_obj_02",
        "index": 1,
        "label": "Open the inventory panel from the HUD.",
        "trigger": "open_tab",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "road_ready_bag_check_obj_03",
        "index": 2,
        "label": "Equip or confirm one road-ready clothing piece.",
        "trigger": "inventory_change",
        "markerId": "lovely_locks_mirror"
      },
      {
        "id": "road_ready_bag_check_obj_04",
        "index": 3,
        "label": "Use the Lovely Locks mirror to check your silhouette from the front.",
        "trigger": "interact",
        "markerId": "lovely_locks_mirror"
      },
      {
        "id": "road_ready_bag_check_obj_05",
        "index": 4,
        "label": "Inspect the HUD compass ring and confirm health, stamina, and quick-action bars are visible.",
        "trigger": "interact",
        "markerId": "grove_hud_compass_ring"
      },
      {
        "id": "road_ready_bag_check_obj_06",
        "index": 5,
        "label": "Return to Rosalyn for one final adjustment.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "35 XP, road-ready outfit habit, quick-bar awareness.",
    "sampleDialogue": "Open Inventory, equip a top, check the mirror, then check your health/stamina/quick-action bars. The lesson watches each panel — open them in order and finish back at me.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "tools_before_treasure",
    "title": "Tools Before Treasure",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn hands out a careful first repair job so players learn legal gathering, marked practice materials, road repair, and why owned things are not free loot.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "tools_before_treasure_obj_01",
        "index": 0,
        "label": "Ask Rosalyn for the fountain road kit.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "tools_before_treasure_obj_02",
        "index": 1,
        "label": "Inspect the Road Kit Crate before touching nearby supplies.",
        "trigger": "interact",
        "markerId": "grove_tool_crate"
      },
      {
        "id": "tools_before_treasure_obj_03",
        "index": 2,
        "label": "Collect only from the marked practice materials basket.",
        "trigger": "collect",
        "markerId": "grove_resource_basket"
      },
      {
        "id": "tools_before_treasure_obj_04",
        "index": 3,
        "label": "Place or use one repair piece on the Fountain Repair Post.",
        "trigger": "place_voxel",
        "markerId": "grove_practice_repair_post"
      },
      {
        "id": "tools_before_treasure_obj_05",
        "index": 4,
        "label": "Inspect the safe-zone boundary stones so you know what belongs to the town.",
        "trigger": "interact",
        "markerId": "grove_safe_wild_boundary"
      },
      {
        "id": "tools_before_treasure_obj_06",
        "index": 5,
        "label": "Choose the rule you will follow: ask, claim, or gather only from marked nodes.",
        "trigger": "choice",
        "markerId": "grove_tool_crate"
      },
      {
        "id": "tools_before_treasure_obj_07",
        "index": 6,
        "label": "Return to Rosalyn with the kit intact.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "45 XP, practice repair credit, legal gathering reminder.",
    "sampleDialogue": "Inspect the Road Kit Crate, collect from the marked practice basket only, place a repair piece on the Fountain Repair Post, then come back. Marker walks you through each step.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "safe_sparring_not_pvp",
    "title": "Sparring Is a Promise",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain / Charter Table",
    "hook": "Nia teaches combat safety, duel consent, safe-zone rules, PvP opt-in language, and the difference between a practice dummy and another player.",
    "start": {
      "kind": "giver",
      "giverNpcId": "guild_clerk_nia"
    },
    "steps": [
      {
        "id": "safe_sparring_not_pvp_obj_01",
        "index": 0,
        "label": "Talk to Nia at the charter table.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      },
      {
        "id": "safe_sparring_not_pvp_obj_02",
        "index": 1,
        "label": "Read the charter board before drawing a weapon near anyone.",
        "trigger": "interact",
        "markerId": "guild_charter_board"
      },
      {
        "id": "safe_sparring_not_pvp_obj_03",
        "index": 2,
        "label": "Step into the consent sparring ring and check that it is clearly marked.",
        "trigger": "near_location",
        "markerId": "grove_sparring_boundary"
      },
      {
        "id": "safe_sparring_not_pvp_obj_04",
        "index": 3,
        "label": "Strike the softwood practice dummy or complete the safe combat prompt.",
        "trigger": "combat",
        "markerId": "grove_combat_practice_dummy"
      },
      {
        "id": "safe_sparring_not_pvp_obj_05",
        "index": 4,
        "label": "Open the group or combat panel and find where duel consent belongs.",
        "trigger": "open_tab",
        "markerId": "grove_party_rope_marker"
      },
      {
        "id": "safe_sparring_not_pvp_obj_06",
        "index": 5,
        "label": "Choose the PvP rule Nia should stamp first: consent, safe zones, or no farming.",
        "trigger": "choice",
        "markerId": "grove_safe_wild_boundary"
      },
      {
        "id": "safe_sparring_not_pvp_obj_07",
        "index": 6,
        "label": "Return to Nia before leaving the ring.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      }
    ],
    "reward": "50 XP, sparring consent flag, PvP safety note.",
    "sampleDialogue": "Read the charter board, step into the consent sparring ring, hit the practice dummy, then choose the PvP rule I should stamp first. Marker moves with you.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "ready_check_at_fountain",
    "title": "Ready Check at the Fountain",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain / Charter Table",
    "hook": "Nia uses a tiny party drill to teach ready checks, group roles, guild storage, and why players should not pull danger while someone is still reading the map.",
    "start": {
      "kind": "giver",
      "giverNpcId": "guild_clerk_nia"
    },
    "steps": [
      {
        "id": "ready_check_at_fountain_obj_01",
        "index": 0,
        "label": "Ask Nia to run the fountain ready check.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      },
      {
        "id": "ready_check_at_fountain_obj_02",
        "index": 1,
        "label": "Stand by the Party Rope Marker where everyone can see you.",
        "trigger": "near_location",
        "markerId": "grove_party_rope_marker"
      },
      {
        "id": "ready_check_at_fountain_obj_03",
        "index": 2,
        "label": "Open the guild or party panel from the HUD.",
        "trigger": "open_tab",
        "markerId": "guild_charter_board"
      },
      {
        "id": "ready_check_at_fountain_obj_04",
        "index": 3,
        "label": "Interact with the firefly ring to mark yourself ready.",
        "trigger": "interact",
        "markerId": "grove_ready_firefly_ring"
      },
      {
        "id": "ready_check_at_fountain_obj_05",
        "index": 4,
        "label": "Inspect the practice guild bank crate without taking everything from it.",
        "trigger": "interact",
        "markerId": "guild_bank_crate"
      },
      {
        "id": "ready_check_at_fountain_obj_06",
        "index": 5,
        "label": "Choose a first group role: scout, builder, fighter, healer, or quartermaster.",
        "trigger": "choice",
        "markerId": "guild_project_table"
      },
      {
        "id": "ready_check_at_fountain_obj_07",
        "index": 6,
        "label": "Return to Nia so she can clear the drill.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      }
    ],
    "reward": "45 XP, group-readiness habit, guild role note.",
    "sampleDialogue": "Stand by the Party Rope Marker, open the guild/party panel, mark yourself ready at the firefly ring, then pick your group role. Return here when the drill is done.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "lost_found_and_mail",
    "title": "Nothing Useful Stays Lost",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain / Lovely Locks",
    "hook": "Rosalyn teaches mail, storage, recovery, and calm inventory habits so a new player knows where important items go when panic makes pockets mysterious.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "lost_found_and_mail_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn about where important items go when your bag is full.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "lost_found_and_mail_obj_02",
        "index": 1,
        "label": "Open the storage, mail, or recovery panel from the HUD.",
        "trigger": "open_tab",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "lost_found_and_mail_obj_03",
        "index": 2,
        "label": "Inspect the Mail and Bank Satchel by the fountain.",
        "trigger": "interact",
        "markerId": "grove_mail_bank_satchel"
      },
      {
        "id": "lost_found_and_mail_obj_04",
        "index": 3,
        "label": "Use the Lost-and-Found Stone to recover or confirm a practice item.",
        "trigger": "item_grant",
        "markerId": "grove_recovery_stone"
      },
      {
        "id": "lost_found_and_mail_obj_05",
        "index": 4,
        "label": "Store or organize one item instead of carrying everything loose.",
        "trigger": "inventory_change",
        "markerId": "guild_bank_crate"
      },
      {
        "id": "lost_found_and_mail_obj_06",
        "index": 5,
        "label": "Return to Rosalyn with your bag less dramatic than before.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "35 XP, storage recovery habit, starter mail note.",
    "sampleDialogue": "Open the storage/mail panel, inspect the Mail and Bank Satchel, use the Lost-and-Found Stone, then store one item. Marker moves through each stop and ends back at me.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_chat_channels",
    "title": "Words Find the Right Ear",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Taye teaches new arrivals that words have channels: say is the room, party is your friends, and whisper is for one ear only — and that picking the wrong one is how strangers learn things they should not.",
    "start": {
      "kind": "giver",
      "giverNpcId": "taye"
    },
    "steps": [
      {
        "id": "fountain_chat_channels_obj_01",
        "index": 0,
        "label": "Talk to Taye at her paint table about who hears your words.",
        "trigger": "talk_npc",
        "markerId": "npc_taye"
      },
      {
        "id": "fountain_chat_channels_obj_02",
        "index": 1,
        "label": "Open the chat panel from the HUD.",
        "trigger": "open_tab",
        "markerId": "grove_chat_practice_board"
      },
      {
        "id": "fountain_chat_channels_obj_03",
        "index": 2,
        "label": "Send a 'say' message inside the fountain square so Taye can read it back to you.",
        "trigger": "interact",
        "markerId": "grove_chat_practice_board"
      },
      {
        "id": "fountain_chat_channels_obj_04",
        "index": 3,
        "label": "Try a quiet whisper directly to Taye.",
        "trigger": "interact",
        "markerId": "npc_taye"
      },
      {
        "id": "fountain_chat_channels_obj_05",
        "index": 4,
        "label": "Choose your default channel: say, party, or whisper.",
        "trigger": "choice",
        "markerId": "grove_chat_practice_board"
      },
      {
        "id": "fountain_chat_channels_obj_06",
        "index": 5,
        "label": "Return to Taye with the channel you picked.",
        "trigger": "talk_npc",
        "markerId": "npc_taye"
      }
    ],
    "reward": "30 XP, chat channel primer, whisper habit flag.",
    "sampleDialogue": "Say is the room, party is your friends, whisper is one ear only. Pick wrong and a stranger hears the wrong part of your day.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_food_keeps_you_moving",
    "title": "Food Keeps You Moving",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn turns the first hunger lesson into a calm fountain drill: stamina, rations, and why nobody walks the Old Grove Road on an empty bag.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "fountain_food_keeps_you_moving_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn about traveler's stamina.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "fountain_food_keeps_you_moving_obj_02",
        "index": 1,
        "label": "Take a starter ration from the fountain food satchel.",
        "trigger": "interact",
        "markerId": "grove_food_satchel"
      },
      {
        "id": "fountain_food_keeps_you_moving_obj_03",
        "index": 2,
        "label": "Eat the ration and watch your stamina settle.",
        "trigger": "item_use",
        "markerId": "grove_food_satchel"
      },
      {
        "id": "fountain_food_keeps_you_moving_obj_04",
        "index": 3,
        "label": "Jog the short fountain loop until your stamina drops once.",
        "trigger": "near_location",
        "markerId": "grove_hud_compass_ring"
      },
      {
        "id": "fountain_food_keeps_you_moving_obj_05",
        "index": 4,
        "label": "Eat one more ration to recover before leaving the safe zone.",
        "trigger": "item_use",
        "markerId": "grove_food_satchel"
      },
      {
        "id": "fountain_food_keeps_you_moving_obj_06",
        "index": 5,
        "label": "Return to Rosalyn so she can pack you a road kit.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "35 XP, two starter rations, calm-stamina habit flag.",
    "sampleDialogue": "A full bag and a tired body still lose the road. Eat first. Walk second. Brag third, if ever.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_first_aid_before_road",
    "title": "First Aid Before the Road",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn teaches the bandage habit before the player meets a fight: out-of-combat heal, when to use it, when to save it, and why a clean bandage is cheaper than a confident sprint.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "fountain_first_aid_before_road_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn about minor road injuries.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "fountain_first_aid_before_road_obj_02",
        "index": 1,
        "label": "Take one practice bandage from the first-aid bin.",
        "trigger": "interact",
        "markerId": "grove_first_aid_bin"
      },
      {
        "id": "fountain_first_aid_before_road_obj_03",
        "index": 2,
        "label": "Walk to the practice scratch post and tap it to simulate a small wound.",
        "trigger": "near_location",
        "markerId": "grove_practice_scratch_post"
      },
      {
        "id": "fountain_first_aid_before_road_obj_04",
        "index": 3,
        "label": "Apply the bandage and watch the health bar tick back up.",
        "trigger": "item_use",
        "markerId": "grove_practice_scratch_post"
      },
      {
        "id": "fountain_first_aid_before_road_obj_05",
        "index": 4,
        "label": "Choose whether you would carry one bandage, three, or a full roll on the road.",
        "trigger": "choice",
        "markerId": "grove_first_aid_bin"
      },
      {
        "id": "fountain_first_aid_before_road_obj_06",
        "index": 5,
        "label": "Return to Rosalyn to confirm the lesson.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "40 XP, two practice bandages, first-aid habit flag.",
    "sampleDialogue": "Bandage first, brag later. A clean strip and a quiet minute save more travelers than every potion I have ever weighed.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_hotbar_and_dropping",
    "title": "Hands That Know the Hotbar",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn shows newcomers how to bind tools to the hotbar, drop a stack on purpose, and pick it back up — so panic never costs them their only torch.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "fountain_hotbar_and_dropping_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn at the fountain about hands-free habits.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "fountain_hotbar_and_dropping_obj_02",
        "index": 1,
        "label": "Open the inventory and drag a practice stone onto the hotbar.",
        "trigger": "open_tab",
        "markerId": "grove_fountain_lesson_board"
      },
      {
        "id": "fountain_hotbar_and_dropping_obj_03",
        "index": 2,
        "label": "Press the bound hotbar slot to hold the practice stone.",
        "trigger": "item_use",
        "markerId": "grove_fountain_lesson_board"
      },
      {
        "id": "fountain_hotbar_and_dropping_obj_04",
        "index": 3,
        "label": "Drop the practice stone stack on the fountain stones on purpose.",
        "trigger": "place_voxel",
        "markerId": "grove_drop_practice_stones"
      },
      {
        "id": "fountain_hotbar_and_dropping_obj_05",
        "index": 4,
        "label": "Pick the stack back up to prove dropped items are not lost.",
        "trigger": "collect",
        "markerId": "grove_drop_practice_stones"
      },
      {
        "id": "fountain_hotbar_and_dropping_obj_06",
        "index": 5,
        "label": "Return to Rosalyn with the stack in your hand.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "35 XP, hotbar habit flag, drop-and-recover note.",
    "sampleDialogue": "Your hands are slower than your panic. Bind the tool you would die without, and trust the rest to your bag.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_first_recipe_torch",
    "title": "Your First Real Recipe",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain",
    "hook": "Rosalyn walks the player through their first real crafted item — a small road torch — so the recipe panel, workbench, and lit-light habit all click before the road goes dark.",
    "start": {
      "kind": "giver",
      "giverNpcId": "rosalyn"
    },
    "steps": [
      {
        "id": "fountain_first_recipe_torch_obj_01",
        "index": 0,
        "label": "Talk to Rosalyn about her tinder kit.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      },
      {
        "id": "fountain_first_recipe_torch_obj_02",
        "index": 1,
        "label": "Gather two practice sticks from the marked basket.",
        "trigger": "collect",
        "markerId": "grove_resource_basket",
        "requiredCount": 2
      },
      {
        "id": "fountain_first_recipe_torch_obj_03",
        "index": 2,
        "label": "Open the recipe panel and find the road torch recipe.",
        "trigger": "open_tab",
        "markerId": "grove_fountain_workbench"
      },
      {
        "id": "fountain_first_recipe_torch_obj_04",
        "index": 3,
        "label": "Craft one road torch at the fountain workbench.",
        "trigger": "craft",
        "markerId": "grove_fountain_workbench",
        "craft": {
          "recipeId": "harthmere_grove_road_torch",
          "outputItemId": "grove_road_torch"
        }
      },
      {
        "id": "fountain_first_recipe_torch_obj_05",
        "index": 4,
        "label": "Light the torch and stand in the dim corner of the courtyard until it catches.",
        "trigger": "interact",
        "markerId": "grove_dim_corner"
      },
      {
        "id": "fountain_first_recipe_torch_obj_06",
        "index": 5,
        "label": "Return to Rosalyn with the lit torch.",
        "trigger": "talk_npc",
        "markerId": "npc_rosalyn"
      }
    ],
    "reward": "50 XP, one road torch, first-recipe flag.",
    "sampleDialogue": "A recipe is a promise to your future self. Make the small thing now while it is safe, so your hands remember the shape when it is not.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  },
  {
    "id": "fountain_trade_table_promises",
    "title": "Trade Is a Promise You Both Sign",
    "arc": "fountain",
    "category": "fountain_lesson",
    "area": "The Grove Fountain / Charter Table",
    "hook": "Nia walks the player through a real trade at the practice table — both sides confirm, both sides accept — so a first trade with a stranger does not become a first scam.",
    "start": {
      "kind": "giver",
      "giverNpcId": "guild_clerk_nia"
    },
    "steps": [
      {
        "id": "fountain_trade_table_promises_obj_01",
        "index": 0,
        "label": "Talk to Nia at the charter table about safe trading.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      },
      {
        "id": "fountain_trade_table_promises_obj_02",
        "index": 1,
        "label": "Open the trade window at the practice trade desk.",
        "trigger": "interact",
        "markerId": "grove_trade_desk"
      },
      {
        "id": "fountain_trade_table_promises_obj_03",
        "index": 2,
        "label": "Place one practice item into your side of the trade slot.",
        "trigger": "item_grant",
        "markerId": "grove_trade_desk"
      },
      {
        "id": "fountain_trade_table_promises_obj_04",
        "index": 3,
        "label": "Inspect the clerk's side of the trade desk before you confirm.",
        "trigger": "interact",
        "markerId": "grove_trade_desk"
      },
      {
        "id": "fountain_trade_table_promises_obj_05",
        "index": 4,
        "label": "Choose the trade rule worth keeping: equal value, confirmed both sides, or no rushed accepts.",
        "trigger": "choice",
        "markerId": "guild_charter_board"
      },
      {
        "id": "fountain_trade_table_promises_obj_06",
        "index": 5,
        "label": "Return to Nia to stamp the trade habit into your charter.",
        "trigger": "talk_npc",
        "markerId": "npc_guild_clerk_nia"
      }
    ],
    "reward": "45 XP, trade-safety flag, first guild charter clause.",
    "sampleDialogue": "A trade is a promise both sides sign. If one side is in a hurry, the other side should not be.",
    "connectorToHarthmere": false,
    "countsAsFountainLesson": true
  }
];

export const GROVE_QUESTS_FOUNTAIN: readonly GroveQuestDef[] = Object.freeze(QUESTS);
