#!/usr/bin/env python3
"""Author the canonical player sword-combat actions in Blender.

The actions are intentionally authored on the stock 16-bone Biomes player
armature.  They keep gameplay translation in the engine, but include planted
footwork, hip/chest counter-rotation, anticipation, a one-frame impact hold,
weapon overshoot, and staggered recovery.  The exported glTF merge preserves
every unrelated animation and all existing animation metadata.

Run with either canonical authoring blend open::

    blender --background character-animations.blend \
      --python scripts/harthmere/blender/author_player_combat_actions.py \
      -- --gltf src/galois/data/animations/character-animations.gltf

The ``_24`` / ``_30`` suffixes are retained as runtime compatibility names.
The clips are intentionally compact enough to chain: light contact lands on
frame 6 and heavy contact lands on frame 10.  Recovery remains visible when a
player stops attacking, while a buffered follow-up can cross-fade immediately
into the next direction without a dead pause.
"""

from __future__ import annotations

import argparse
import copy
import os
import sys

import bpy


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from add_native_movement_actions import (  # noqa: E402
    create_action,
    export_and_merge,
    neutral_rotations,
)


FPS = 24
# Frame-exact clocks.  The gameplay constants use the rounded millisecond
# equivalents so animation, damage, trails, audio, and input buffering all
# agree on the same contact sample.
BASIC_IMPACT = 6.0
BASIC_END = 17.0
HEAVY_IMPACT = 10.0
HEAVY_END = 26.0
BASIC_IMPACT_SECONDS = BASIC_IMPACT / FPS
BASIC_DURATION_SECONDS = BASIC_END / FPS
HEAVY_IMPACT_SECONDS = HEAVY_IMPACT / FPS
HEAVY_DURATION_SECONDS = HEAVY_END / FPS

BASIC_NAMES = tuple(
    f"HarthmereBodyWeaponBasic_Variation{index}_24" for index in range(1, 5)
)
HEAVY_NAMES = tuple(
    f"HarthmereBodyWeaponHeavy_Variation{index}_24" for index in range(1, 5)
)
ALIGNED_NAMES = (
    "HarthmereBodyWeaponBasic_Aligned_30",
    "HarthmereBodyWeaponHeavy_Aligned_30",
)
ACTION_NAMES = BASIC_NAMES + HEAVY_NAMES + ALIGNED_NAMES

BASIC_SPECS = (
    ("backhand", "left_to_right_opener", "horizontal_left_to_right"),
    ("forehand", "right_to_left_return", "horizontal_right_to_left"),
    ("descending", "overhead_cleave", "vertical_overhead_to_low"),
    ("rising", "rising_cut", "diagonal_low_left_to_high_right"),
)
HEAVY_SPECS = (
    ("sweep", "left_to_right_power_sweep", "horizontal_left_to_right"),
    ("reverse_sweep", "right_to_left_power_return", "horizontal_right_to_left"),
    ("overhead", "overhead_crusher", "vertical_overhead_to_low"),
    ("uppercut", "rising_finisher", "diagonal_low_right_to_high_left"),
)
COMBO_ROLES = ("opener", "return", "power", "finisher")
COMBAT_PROFILE = "aaa-voxel-sword-v4-distinct-trajectory-combo"
ANIMATION_POLISH_VERSION = "harthmere-player-combo-animation-polish-v4-trajectories"


def args() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser()
    parser.add_argument("--gltf", help="Optional existing glTF to merge actions into")
    return parser.parse_args(argv)


def force_object_mode() -> None:
    if bpy.context.object and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")


def armature():
    force_object_mode()
    rigs = [obj for obj in bpy.data.objects if obj.type == "ARMATURE"]
    if len(rigs) != 1:
        raise RuntimeError(f"Expected one player armature, found {len(rigs)}")
    rig = rigs[0]
    rig.animation_data_create()
    rig.animation_data.use_nla = False
    if rig.animation_data.use_tweak_mode:
        rig.animation_data.use_tweak_mode = False
    return rig


def additive_pose(base, offsets):
    pose = copy.deepcopy(base)
    for bone, offset in offsets.items():
        value = pose.get(bone, (0.0, 0.0, 0.0))
        pose[bone] = tuple(value[axis] + offset[axis] for axis in range(3))
    return pose


def additive_locations(base, offsets):
    return additive_pose(base, offsets)


def scaled_pose(pose, amount):
    return {
        bone: tuple(component * amount for component in rotation)
        for bone, rotation in pose.items()
    }


def blend_pose(a, b, amount):
    bones = set(a) | set(b)
    return {
        bone: tuple(
            (a.get(bone, (0.0, 0.0, 0.0))[axis] * (1.0 - amount))
            + (b.get(bone, (0.0, 0.0, 0.0))[axis] * amount)
            for axis in range(3)
        )
        for bone in bones
    }


def attack_key_poses(style: str):
    """Return additive windup/contact/follow poses for one readable attack.

    The stock player rig has no IK controls, so the offsets deliberately follow
    a hips -> chest -> shoulder -> elbow -> wrist sequence.  Every style owns a
    different silhouette and blade path; none is generated by simply changing
    playback speed or mirroring a single generic flail.
    """

    poses = {
        "forehand": (
            {
                "Waist": (-0.08, 0.30, -0.04), "Chest": (0.04, -0.38, 0.10), "Head": (-0.05, 0.18, -0.04),
                "R_Arm": (0.0, 0.0, 0.0), "R_Forearm": (0.0, 0.24, -1.16), "R_Hand": (0.0, 0.34, -0.06), "Tool": (1.0, 0.10, -0.24),
                "L_Arm": (0.16, 0.0, -0.12), "L_Forearm": (-0.34, 0.0, 0.0),
                "R_Thigh": (0.02, 0.12, 0.04), "L_Thigh": (0.08, -0.12, -0.08), "L_Leg": (0.10, 0.0, 0.0),
            },
            {
                "Waist": (-0.02, -0.30, 0.02), "Chest": (0.06, 0.68, -0.08), "Head": (-0.02, -0.30, -0.02),
                "R_Arm": (0.68, 0.62, 0.88), "R_Forearm": (0.04, 0.18, -0.02), "R_Hand": (0.04, 0.16, 0.16), "Tool": (0.08, -0.10, 0.26),
                "L_Arm": (0.32, 0.12, -0.30), "L_Forearm": (-0.84, 0.0, 0.0),
                "R_Thigh": (0.18, 0.24, 0.10), "L_Thigh": (-0.08, 0.18, 0.08), "R_Leg": (0.16, 0.0, 0.0),
            },
            {
                "Waist": (-0.02, -0.42, 0.03), "Chest": (-0.02, 0.82, -0.18), "Head": (0.0, -0.38, -0.02),
                "R_Arm": (0.78, 0.56, 1.02), "R_Forearm": (0.02, 0.16, 0.08), "R_Hand": (0.0, 0.10, 0.08), "Tool": (0.14, -0.12, 0.42),
                "L_Arm": (0.42, 0.10, -0.42), "L_Forearm": (-1.02, 0.0, 0.0),
                "R_Thigh": (0.24, 0.28, 0.12), "L_Thigh": (-0.10, 0.24, 0.10), "R_Leg": (0.20, 0.0, 0.0),
            },
        ),
        "backhand": (
            {
                "Waist": (-0.08, -0.12, 0.02), "Chest": (-0.08, 0.42, -0.04), "Head": (0.08, -0.32, -0.05),
                "R_Arm": (-0.12, 0.64, -1.34), "R_Forearm": (0.0, 0.0, -0.58), "R_Hand": (0.0, 0.0, 0.24), "Tool": (-0.10, 0.08, 0.30),
                "L_Arm": (0.62, 0.04, -0.24), "L_Forearm": (-0.72, 0.0, 0.0),
                "R_Thigh": (-0.02, -0.10, -0.06), "L_Thigh": (0.04, 0.12, 0.08),
            },
            {
                "Waist": (-0.06, -0.08, -0.04), "Chest": (0.10, 0.30, -0.04), "Head": (-0.08, -0.16, -0.08),
                "R_Arm": (0.70, 0.60, 0.60), "R_Forearm": (0.06, -0.14, 0.04), "R_Hand": (0.02, -0.10, -0.14), "Tool": (0.18, 0.08, 0.40),
                "L_Arm": (-0.54, 0.34, -0.32), "L_Forearm": (-0.24, 0.0, 0.0),
                "R_Thigh": (0.08, 0.10, 0.04), "L_Thigh": (0.10, -0.18, -0.10), "L_Leg": (0.12, 0.0, 0.0),
            },
            {
                "Waist": (-0.04, -0.18, -0.06), "Chest": (0.14, 0.04, -0.08), "Head": (-0.08, -0.02, -0.10),
                "R_Arm": (0.82, 0.42, 0.82), "R_Forearm": (0.12, -0.20, 0.16), "R_Hand": (0.04, -0.14, -0.18), "Tool": (0.24, 0.10, 0.64),
                "L_Arm": (-0.66, 0.38, -0.42), "L_Forearm": (-0.12, 0.0, 0.0),
                "R_Thigh": (0.12, 0.14, 0.06), "L_Thigh": (0.14, -0.24, -0.12), "L_Leg": (0.16, 0.0, 0.0),
            },
        ),
        "descending": (
            {
                "Waist": (-0.06, 0.18, -0.04), "Chest": (-0.12, -0.20, 0.12), "Head": (0.08, 0.12, -0.04),
                "R_Arm": (-1.02, 0.82, -0.92), "R_Forearm": (-0.18, 0.12, -0.84), "R_Hand": (-0.10, 0.12, 0.18), "Tool": (-0.42, 0.08, -0.20),
                "L_Arm": (0.34, 0.06, -0.18), "L_Forearm": (-0.52, 0.0, 0.0),
                "R_Thigh": (-0.08, 0.08, 0.04), "L_Thigh": (0.10, -0.12, -0.06), "L_Leg": (0.10, 0.0, 0.0),
            },
            {
                "Waist": (0.16, -0.32, 0.08), "Chest": (0.36, 0.56, -0.16), "Head": (-0.20, -0.28, -0.04),
                "R_Arm": (0.66, 0.28, 0.94), "R_Forearm": (0.36, -0.02, 0.52), "R_Hand": (0.24, -0.04, 0.18), "Tool": (0.96, -0.10, 0.52),
                "L_Arm": (-0.10, 0.30, -0.54), "L_Forearm": (-0.90, 0.0, 0.0),
                "R_Thigh": (0.30, 0.20, 0.10), "L_Thigh": (-0.08, 0.16, 0.08), "R_Leg": (0.28, 0.0, 0.0),
            },
            {
                "Waist": (0.22, -0.42, 0.10), "Chest": (0.52, 0.66, -0.24), "Head": (-0.24, -0.34, -0.04),
                "R_Arm": (0.92, 0.18, 1.18), "R_Forearm": (0.48, -0.08, 0.66), "R_Hand": (0.30, -0.08, 0.22), "Tool": (1.20, -0.14, 0.74),
                "L_Arm": (-0.20, 0.38, -0.70), "L_Forearm": (-1.04, 0.0, 0.0),
                "R_Thigh": (0.36, 0.24, 0.12), "L_Thigh": (-0.10, 0.20, 0.10), "R_Leg": (0.32, 0.0, 0.0),
            },
        ),
        "rising": (
            {
                "Waist": (0.10, -0.22, 0.02), "Chest": (0.18, 0.32, -0.10), "Head": (-0.08, -0.18, -0.02),
                "R_Arm": (0.52, -0.32, 0.74), "R_Forearm": (0.18, -0.08, 0.22), "R_Hand": (0.10, -0.06, -0.16), "Tool": (0.46, -0.04, -0.30),
                "L_Arm": (-0.18, 0.24, -0.28), "L_Forearm": (-0.38, 0.0, 0.0),
                "R_Thigh": (0.16, 0.12, 0.06), "L_Thigh": (-0.08, 0.18, 0.10), "R_Leg": (0.18, 0.0, 0.0),
            },
            {
                "Waist": (-0.06, 0.24, -0.04), "Chest": (-0.12, -0.48, 0.12), "Head": (0.08, 0.24, -0.06),
                "R_Arm": (-0.52, 0.62, -0.70), "R_Forearm": (-0.14, 0.14, -0.34), "R_Hand": (-0.10, 0.10, 0.18), "Tool": (-0.48, 0.04, 0.36),
                "L_Arm": (0.38, 0.06, -0.18), "L_Forearm": (-0.62, 0.0, 0.0),
                "R_Thigh": (-0.04, 0.16, 0.08), "L_Thigh": (0.18, -0.16, -0.08), "L_Leg": (0.16, 0.0, 0.0),
            },
            {
                "Waist": (-0.10, 0.34, -0.06), "Chest": (-0.18, -0.62, 0.18), "Head": (0.12, 0.30, -0.08),
                "R_Arm": (-0.72, 0.72, -0.88), "R_Forearm": (-0.20, 0.18, -0.46), "R_Hand": (-0.14, 0.12, 0.22), "Tool": (-0.66, 0.06, 0.52),
                "L_Arm": (0.52, 0.02, -0.26), "L_Forearm": (-0.72, 0.0, 0.0),
                "R_Thigh": (-0.06, 0.20, 0.10), "L_Thigh": (0.22, -0.20, -0.10), "L_Leg": (0.20, 0.0, 0.0),
            },
        ),
    }

    if style in poses:
        return poses[style]

    # Heavy attacks reuse readable fundamentals but amplify commitment and add
    # unique silhouettes rather than slowing the light clips.
    heavy_sources = {
        "overhead": "descending",
        "sweep": "backhand",
        "reverse_sweep": "forehand",
        "uppercut": "rising",
    }
    source = poses[heavy_sources[style]]
    windup, contact, follow = (scaled_pose(pose, 1.18) for pose in source)
    if style == "overhead":
        windup.update({"R_Arm": (-1.28, 0.92, -1.04), "R_Forearm": (-0.30, 0.16, -1.02), "Tool": (-0.64, 0.10, -0.26), "L_Arm": (0.46, 0.10, -0.30)})
        contact.update({"Waist": (0.14, -0.24, 0.04), "Chest": (0.34, 0.34, -0.08), "R_Arm": (0.54, 0.40, 0.54), "R_Forearm": (0.34, 0.02, 0.42), "Tool": (0.82, -0.06, 0.18)})
        follow.update({"Waist": (0.18, -0.34, 0.06), "Chest": (0.46, 0.42, -0.14), "R_Arm": (0.82, 0.28, 0.76), "R_Forearm": (0.42, -0.02, 0.56), "Tool": (1.02, -0.08, 0.28)})
    elif style == "sweep":
        windup.update({"Waist": (-0.12, -0.20, 0.04), "Chest": (-0.18, 0.58, -0.08), "R_Arm": (0.02, 0.72, -1.46), "R_Forearm": (-0.14, 0.02, -0.78), "Tool": (-0.20, 0.12, 0.46)})
        contact.update({"Waist": (-0.08, -0.10, -0.06), "Chest": (0.14, 0.34, -0.06), "Tool": (0.16, 0.10, 0.48)})
        follow.update({"Waist": (-0.06, -0.22, -0.08), "Chest": (0.18, 0.02, -0.10), "Tool": (0.24, 0.12, 0.72)})
    elif style == "reverse_sweep":
        # The second combo step must cross the body in the opposite direction
        # from step one.  Its shoulder, wrist, Tool roll, and planted hip turn
        # all reverse, rather than replaying the same broad sweep mirrored only
        # by metadata.
        windup.update({"Waist": (-0.16, 0.48, -0.10), "Chest": (-0.28, -0.66, 0.18), "R_Arm": (0.0, 0.0, -0.50), "R_Forearm": (0.02, 0.28, -1.26), "R_Hand": (0.02, 0.38, -0.08), "Tool": (1.50, 0.12, -0.46), "L_Arm": (0.22, -0.02, -0.18)})
        contact.update({"Waist": (-0.02, -0.40, 0.04), "Chest": (0.10, 0.82, -0.12), "Head": (-0.04, -0.36, -0.04), "R_Arm": (0.84, 0.70, 1.02), "R_Forearm": (0.08, 0.18, 0.02), "R_Hand": (0.04, 0.14, 0.18), "Tool": (0.12, -0.14, 0.38), "L_Arm": (0.38, 0.16, -0.38), "L_Forearm": (-0.94, 0.0, 0.0)})
        follow.update({"Waist": (-0.02, -0.56, 0.06), "Chest": (-0.02, 0.98, -0.24), "Head": (0.0, -0.46, -0.04), "R_Arm": (1.02, 0.60, 1.22), "R_Forearm": (0.04, 0.18, 0.12), "R_Hand": (0.0, 0.10, 0.10), "Tool": (0.20, -0.18, 0.58), "L_Arm": (0.50, 0.12, -0.50), "L_Forearm": (-1.10, 0.0, 0.0)})
    elif style == "uppercut":
        windup.update({"Waist": (0.16, -0.30, 0.04), "Chest": (0.24, 0.42, -0.14), "R_Arm": (0.72, -0.46, 0.96), "R_Forearm": (0.26, -0.12, 0.34), "Tool": (0.62, -0.04, -0.42)})
        contact.update({"Waist": (-0.10, 0.34, -0.06), "Chest": (-0.18, -0.62, 0.18), "R_Arm": (-0.62, 0.78, -0.88), "R_Forearm": (-0.18, 0.18, -0.42), "R_Hand": (-0.12, 0.12, 0.20), "Tool": (-0.62, 0.06, 0.48)})
        follow.update({"Waist": (-0.16, 0.48, -0.10), "Chest": (-0.26, -0.82, 0.26), "R_Arm": (-0.88, 0.92, -1.12), "R_Forearm": (-0.28, 0.22, -0.58), "R_Hand": (-0.18, 0.16, 0.28), "Tool": (-0.84, 0.08, 0.72)})
    return windup, contact, follow


def attack_locations(style: str, heavy: bool):
    lateral = -1.0 if style in {"backhand", "rising", "sweep", "uppercut"} else 1.0
    forward = 0.08 if heavy else 0.05
    return {
        "windup": {"Chest": (-forward * 0.25, 0.0, -0.06 * lateral), "Waist": (-forward * 0.12, 0.0, 0.03 * lateral)},
        "contact": {"Chest": (forward, 0.0, 0.08 * lateral), "Waist": (forward * 0.45, 0.0, -0.04 * lateral)},
        "follow": {"Chest": (forward * 1.25, 0.0, 0.11 * lateral), "Waist": (forward * 0.60, 0.0, -0.06 * lateral)},
    }


def create_attack(
    rig,
    name,
    style,
    direction,
    weapon_arc,
    heavy,
    combo_step,
    base_pose,
    base_locations,
):
    windup, contact, follow = attack_key_poses(style)
    locations = attack_locations(style, heavy)

    def pose(offsets):
        return additive_pose(base_pose, offsets)

    def location(offsets):
        return additive_locations(base_locations, offsets)

    if heavy:
        frames = [
            (0.0, pose(scaled_pose(windup, 0.10)), location(scaled_pose(locations["windup"], 0.10))),
            (2.0, pose(scaled_pose(windup, 0.30)), location(scaled_pose(locations["windup"], 0.30))),
            (5.5, pose(windup), location(locations["windup"])),
            (7.0, pose(blend_pose(windup, contact, 0.20)), location(blend_pose(locations["windup"], locations["contact"], 0.20))),
            (8.8, pose(blend_pose(windup, contact, 0.70)), location(blend_pose(locations["windup"], locations["contact"], 0.70))),
            (HEAVY_IMPACT, pose(contact), location(locations["contact"])),
            (HEAVY_IMPACT + 0.8, pose(contact), location(locations["contact"])),
            (14.0, pose(follow), location(locations["follow"])),
            (17.0, pose(blend_pose(follow, contact, -0.08)), location(locations["follow"])),
            (21.0, pose(scaled_pose(follow, 0.42)), location(scaled_pose(locations["follow"], 0.42))),
            (24.0, pose(scaled_pose(follow, 0.10)), location(scaled_pose(locations["follow"], 0.10))),
            (HEAVY_END, base_pose, base_locations),
        ]
    else:
        frames = [
            (0.0, pose(scaled_pose(windup, 0.08)), location(scaled_pose(locations["windup"], 0.08))),
            (1.25, pose(scaled_pose(windup, 0.30)), location(scaled_pose(locations["windup"], 0.30))),
            (3.25, pose(windup), location(locations["windup"])),
            (4.15, pose(blend_pose(windup, contact, 0.22)), location(blend_pose(locations["windup"], locations["contact"], 0.22))),
            (5.2, pose(blend_pose(windup, contact, 0.72)), location(blend_pose(locations["windup"], locations["contact"], 0.72))),
            (BASIC_IMPACT, pose(contact), location(locations["contact"])),
            (BASIC_IMPACT + 0.6, pose(contact), location(locations["contact"])),
            (8.5, pose(follow), location(locations["follow"])),
            (10.5, pose(blend_pose(follow, contact, -0.06)), location(locations["follow"])),
            (13.5, pose(scaled_pose(follow, 0.40)), location(scaled_pose(locations["follow"], 0.40))),
            (15.5, pose(scaled_pose(follow, 0.10)), location(scaled_pose(locations["follow"], 0.10))),
            (BASIC_END, base_pose, base_locations),
        ]

    action = create_action(rig, name, frames)
    action["harthmereCombatProfile"] = COMBAT_PROFILE
    action["harthmereAnimationPolishVersion"] = ANIMATION_POLISH_VERSION
    action["comboStep"] = combo_step
    action["comboRole"] = COMBO_ROLES[combo_step - 1]
    action["comboHandoffSeconds"] = (
        HEAVY_IMPACT_SECONDS if heavy else BASIC_IMPACT_SECONDS
    )
    action["impactSeconds"] = HEAVY_IMPACT_SECONDS if heavy else BASIC_IMPACT_SECONDS
    action["durationSeconds"] = HEAVY_DURATION_SECONDS if heavy else BASIC_DURATION_SECONDS
    action["attackStyle"] = style
    action["direction"] = direction
    action["weaponArc"] = weapon_arc
    action["gameplayRootMotion"] = True
    action["authoredFootwork"] = True
    action["weaponArcMotionPathReviewed"] = True
    return action


def action_fcurves(action):
    legacy = getattr(action, "fcurves", None)
    if legacy is not None:
        return list(legacy)
    curves = []
    for layer in getattr(action, "layers", []) or []:
        for strip in getattr(layer, "strips", []) or []:
            for bag in getattr(strip, "channelbags", []) or []:
                curves.extend(bag.fcurves)
    return curves


def polish_curves(action):
    for curve in action_fcurves(action):
        for key in curve.keyframe_points:
            key.interpolation = "BEZIER"
            key.handle_left_type = "AUTO_CLAMPED"
            key.handle_right_type = "AUTO_CLAMPED"


def metadata():
    result = {}
    for heavy, names, specs in ((False, BASIC_NAMES, BASIC_SPECS), (True, HEAVY_NAMES, HEAVY_SPECS)):
        for combo_step, (name, (style, label, arc)) in enumerate(
            zip(names, specs), start=1
        ):
            impact = HEAVY_IMPACT_SECONDS if heavy else BASIC_IMPACT_SECONDS
            duration = HEAVY_DURATION_SECONDS if heavy else BASIC_DURATION_SECONDS
            anticipation_end = (5.5 if heavy else 3.25) / FPS
            impact_end = (HEAVY_IMPACT + 0.8 if heavy else BASIC_IMPACT + 0.6) / FPS
            follow_end = (17.0 if heavy else 10.5) / FPS
            result[name] = {
                "harthmereCombatProfile": COMBAT_PROFILE,
                "harthmereAnimationPolishVersion": ANIMATION_POLISH_VERSION,
                "family": "heavy" if heavy else "basic",
                "comboStep": combo_step,
                "comboRole": COMBO_ROLES[combo_step - 1],
                "comboHandoffSeconds": impact,
                "nextComboStep": combo_step + 1 if combo_step < 4 else None,
                "direction": label,
                "weaponArc": arc,
                "attackStyle": style,
                "impactSeconds": impact,
                "durationSeconds": duration,
                "fps": FPS,
                "gameplayRootMotion": True,
                "authoredFootwork": True,
                "impactHoldFrames": 0.8 if heavy else 0.6,
                "phases": [
                    {"name": "anticipation", "start": 0.0, "end": anticipation_end},
                    {"name": "strike", "start": anticipation_end, "end": impact},
                    {"name": "impact", "start": impact, "end": impact_end},
                    {"name": "followThrough", "start": impact_end, "end": follow_end},
                    {"name": "recovery", "start": follow_end, "end": duration},
                ],
            }
    result[ALIGNED_NAMES[0]] = {**result[BASIC_NAMES[0]], "alignedFallbackOf": BASIC_NAMES[0]}
    result[ALIGNED_NAMES[1]] = {**result[HEAVY_NAMES[0]], "alignedFallbackOf": HEAVY_NAMES[0]}
    return result


def main() -> None:
    options = args()
    rig = armature()
    bpy.context.scene.render.fps = FPS
    bpy.context.scene.frame_start = 0
    bpy.context.scene.frame_end = int(HEAVY_END)

    idle = bpy.data.actions.get("Idle")
    if idle is None:
        raise RuntimeError("Canonical Idle action is required as the combat-ready base pose")
    rig.animation_data.action = idle
    bpy.context.scene.frame_set(0)
    bpy.context.view_layer.update()
    base_pose = {
        bone.name: tuple(bone.rotation_quaternion.to_euler("XYZ"))
        for bone in rig.pose.bones
    }
    base_locations = {bone.name: tuple(bone.location) for bone in rig.pose.bones}

    created = []
    for heavy, names, specs in ((False, BASIC_NAMES, BASIC_SPECS), (True, HEAVY_NAMES, HEAVY_SPECS)):
        for combo_step, (name, (style, direction, weapon_arc)) in enumerate(
            zip(names, specs), start=1
        ):
            action = create_attack(
                rig,
                name,
                style,
                direction,
                weapon_arc,
                heavy,
                combo_step,
                base_pose,
                base_locations,
            )
            polish_curves(action)
            created.append(name)

    # Keep the aligned names as deliberate compatibility fallbacks, but make
    # them authored copies of the new opening attacks rather than stale
    # clones of legacy Attack / Attack2.
    for aligned, source in zip(ALIGNED_NAMES, (BASIC_NAMES[0], HEAVY_NAMES[0])):
        old = bpy.data.actions.get(aligned)
        if old is not None:
            bpy.data.actions.remove(old)
        copied = bpy.data.actions[source].copy()
        copied.name = aligned
        copied.use_fake_user = True
        created.append(aligned)

    force_object_mode()
    bpy.ops.wm.save_as_mainfile(filepath=bpy.data.filepath)
    if options.gltf:
        export_and_merge(os.path.abspath(options.gltf), ACTION_NAMES, metadata())
    print("PLAYER_COMBAT_ACTIONS_UPDATED", os.path.basename(bpy.data.filepath), ",".join(created))


if __name__ == "__main__":
    main()
