#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "../../..");
const targetsPath = path.join(__dirname, "inventory_icon_targets.json");
const outputPath = path.join(
  repo,
  "src/shared/harthmere/generated/harthmere_inventory_icon_manifest.ts"
);
const { targets } = JSON.parse(fs.readFileSync(targetsPath, "utf8"));

const lines = [
  "// Generated by scripts/harthmere/blender/inventory_icon_targets.json.",
  "// Do not hand-edit; regenerate the Blender inventory icon catalogue instead.",
  "",
  'import { safeParseBiomesId } from "@/shared/ids";',
  'import { harthmereNativeItemIdForBiomesId } from "@/shared/harthmere/harthmere_native_item_ids";',
  "",
  "export const HARTHMERE_GENERATED_INVENTORY_ICON_URLS = {",
];
for (const target of targets) {
  lines.push(
    `  ${JSON.stringify(target.id)}: ${JSON.stringify(
      `/assets/harthmere/inventory_icons/generated/${target.file}`
    )},`
  );
}
lines.push(
  "} as const satisfies Readonly<Record<string, string>>;",
  "",
  "export function harthmereGeneratedInventoryIconUrl(",
  "  itemId: string | number | undefined",
  "): string | undefined {",
  "  if (itemId === undefined || itemId === null) return undefined;",
  "  const raw = String(itemId).trim();",
  "  if (!raw) return undefined;",
  '  const normalized = raw.replace(/^b:/, "");',
  "  const direct =",
  "    HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "      raw as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "    ] ??",
  "    HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "      normalized as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "    ] ??",
  "    HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "      `b:${normalized}` as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "    ];",
  "  if (direct) return direct;",
  "",
  "  // Live ECS inventory stacks use numeric Bikkie ids, while the Blender icon",
  "  // catalogue is authored against semantic ids. Resolve both `123` and",
  "  // `b:123` through the exact native identity manifest.",
  "  const nativeId = safeParseBiomesId(normalized);",
  "  if (nativeId === undefined) return undefined;",
  "  const semanticItemId = harthmereNativeItemIdForBiomesId(nativeId);",
  "  return semanticItemId",
  "    ? HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "        semanticItemId as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "      ]",
  "    : undefined;",
  "}",
  ""
);

fs.writeFileSync(outputPath, lines.join("\n"));
console.log(`Wrote ${targets.length} icon routes to ${outputPath}`);
