#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "../../..");
const targetsPath = path.join(__dirname, "inventory_icon_targets.json");
const outputPath = path.join(
  repo,
  "src/shared/harthmere/generated/harthmere_inventory_icon_manifest.ts"
);
const { targets } = JSON.parse(fs.readFileSync(targetsPath, "utf8"));

const lines = [
  "// Generated by scripts/harthmere/blender/inventory_icon_targets.json.",
  "// Do not hand-edit; regenerate the Blender inventory icon catalogue instead.",
  "",
  "export const HARTHMERE_GENERATED_INVENTORY_ICON_URLS = {",
];
for (const target of targets) {
  lines.push(
    `  ${JSON.stringify(target.id)}: ${JSON.stringify(
      `/assets/harthmere/inventory_icons/generated/${target.file}`
    )},`
  );
}
lines.push(
  "} as const satisfies Readonly<Record<string, string>>;",
  "",
  "export function harthmereGeneratedInventoryIconUrl(",
  "  itemId: string | undefined",
  "): string | undefined {",
  "  if (!itemId) return undefined;",
  '  const normalized = itemId.replace(/^b:/, "");',
  "  return (",
  "    HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "      itemId as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "    ] ??",
  "    HARTHMERE_GENERATED_INVENTORY_ICON_URLS[",
  "      normalized as keyof typeof HARTHMERE_GENERATED_INVENTORY_ICON_URLS",
  "    ]",
  "  );",
  "}",
  ""
);

fs.writeFileSync(outputPath, lines.join("\n"));
console.log(`Wrote ${targets.length} icon routes to ${outputPath}`);
