// Auto-generated by install-harthmere-runtime-completion-v47.sh
// A small local-dev bridge so the shared quest runtime can drive UI/debug surfaces without granting rewards client-side.

import React from "react";
import {
  createHarthmereQuestRuntimeContextV47,
  getHarthmereDialogueQuestOffersV47,
  getHarthmereQuestJournalEntryV47,
  getHarthmereQuestMapHintV47,
  acceptHarthmereQuestV47,
  advanceHarthmereQuestObjectiveV47,
  completeHarthmereQuestV47,
  failHarthmereQuestV47,
  abandonHarthmereQuestV47,
  retryHarthmereQuestV47,
} from "../../../shared/harthmere/quest_runtime_v47";

export const HARTHMERE_LOCAL_DEV_QUEST_RUNTIME_BRIDGE_VERSION_V47 = 47 as const;

export function createLocalDevHarthmereQuestRuntimeDebugApiV47() {
  const context = createHarthmereQuestRuntimeContextV47({ authority: "server" });
  return {
    context,
    accept: (questId: string) => acceptHarthmereQuestV47(context, questId),
    progress: (questId: string, objectiveId: string, type: any = "inspect") =>
      advanceHarthmereQuestObjectiveV47(context, {
        eventId: `${questId}:${objectiveId}:debug:${context.tick++}`,
        questId,
        objectiveId,
        type,
        actorId: context.playerId,
        authority: "server",
        tick: context.tick,
      }),
    complete: (questId: string) => completeHarthmereQuestV47(context, questId),
    fail: (questId: string, reason = "debug_failure") => failHarthmereQuestV47(context, questId, reason),
    abandon: (questId: string) => abandonHarthmereQuestV47(context, questId),
    retry: (questId: string) => retryHarthmereQuestV47(context, questId),
    journal: (questId: string) => getHarthmereQuestJournalEntryV47(context, questId),
    mapHint: (questId: string) => getHarthmereQuestMapHintV47(context, questId),
    npcOffers: (npcId: any) => getHarthmereDialogueQuestOffersV47(npcId, context),
  };
}

export const LocalDevHarthmereQuestRuntimePanelV47: React.FunctionComponent<{ questId?: string }> = ({ questId }) => {
  const api = React.useMemo(() => createLocalDevHarthmereQuestRuntimeDebugApiV47(), []);
  const journal = questId ? api.journal(questId) : undefined;
  return (
    <section data-harthmere-quest-runtime-v47="journal-map-compass-server-authority">
      <h3>Harthmere Quest Runtime v47</h3>
      <p>Server-authoritative debug bridge for accept, objective progress, completion, rewards, failure, abandon, retry, journal, and map hints.</p>
      {journal ? <pre>{JSON.stringify(journal, null, 2)}</pre> : null}
    </section>
  );
};
