// Auto-generated by install-harthmere-runtime-completion.sh
// A small local-dev bridge so the shared quest runtime can drive UI/debug surfaces without granting rewards client-side.

import React from "react";
import {
  createHarthmereQuestRuntimeContext,
  getHarthmereDialogueQuestOffers,
  getHarthmereQuestJournalEntry,
  getHarthmereQuestMapHint,
  acceptHarthmereQuest,
  advanceHarthmereQuestObjective,
  completeHarthmereQuest,
  failHarthmereQuest,
  abandonHarthmereQuest,
  retryHarthmereQuest,
} from "../../../shared/harthmere/quest_runtime";

export const HARTHMERE_LOCAL_DEV_QUEST_RUNTIME_BRIDGE_VERSION = 47 as const;

export function createLocalDevHarthmereQuestRuntimeDebugApi() {
  const context = createHarthmereQuestRuntimeContext({ authority: "server" });
  return {
    context,
    accept: (questId: string) => acceptHarthmereQuest(context, questId),
    progress: (questId: string, objectiveId: string, type: any = "inspect") =>
      advanceHarthmereQuestObjective(context, {
        eventId: `${questId}:${objectiveId}:debug:${context.tick++}`,
        questId,
        objectiveId,
        type,
        actorId: context.playerId,
        authority: "server",
        tick: context.tick,
      }),
    complete: (questId: string) => completeHarthmereQuest(context, questId),
    fail: (questId: string, reason = "debug_failure") => failHarthmereQuest(context, questId, reason),
    abandon: (questId: string) => abandonHarthmereQuest(context, questId),
    retry: (questId: string) => retryHarthmereQuest(context, questId),
    journal: (questId: string) => getHarthmereQuestJournalEntry(context, questId),
    mapHint: (questId: string) => getHarthmereQuestMapHint(context, questId),
    npcOffers: (npcId: any) => getHarthmereDialogueQuestOffers(npcId, context),
  };
}

export const LocalDevHarthmereQuestRuntimePanel: React.FunctionComponent<{ questId?: string }> = ({ questId }) => {
  const api = React.useMemo(() => createLocalDevHarthmereQuestRuntimeDebugApi(), []);
  const journal = questId ? api.journal(questId) : undefined;
  return (
    <section data-harthmere-quest-runtime="journal-map-compass-server-authority">
      <h3>Harthmere Quest Runtime</h3>
      <p>Server-authoritative debug bridge for accept, objective progress, completion, rewards, failure, abandon, retry, journal, and map hints.</p>
      {journal ? <pre>{JSON.stringify(journal, null, 2)}</pre> : null}
    </section>
  );
};
