name: Test docs deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Yarn
        run: npm install -g yarn@1

      - name: Configure GitHub Git dependencies
        uses: ./.github/actions/configure-github-git-deps
        with:
          token: ${{ secrets.BIOMES_DEPENDENCY_GITHUB_TOKEN }}

      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Install docs dependencies
        working-directory: ./docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./docs
        run: yarn build
